### ISSUE TITLE
can segamd emulator be supported ?

### ISSUE THREAD

**Issue by feizaimm** [EmulatorJS/EmulatorJS#1]
can segamd emulator be supported?

i tried to download the resource but it didn’t work

**Comment by ethanaobrien** [comment]
@ChineseLabelingSystem

Yes, I have just updated supporting more than 10 additional systems!!
You can find the code example [here](https://github.com/ethanaobrien/emulatorjs#sega-mega-drive)
If there are any problems please let me know!

I am going to wait for you to give me the okay before I close this issue.

Thank you for being the first one to suggest!!

**Comment by feizaimm** [comment]
Thank you very much, it works. 
i know little of web and js ,yesterday i tried to download  wasm://wasm/00c096d6  found in chromeand,but 
I am not familiar with chrome devtools ,it took three hours and I didn’t find the sega-wasm.

**Comment by ethanaobrien** [comment]
Awesome. The best thing to use is the network tab. I am going to close this issue now, thank you
