### ISSUE TITLE
Error after latest update loader.js

### ISSUE THREAD

**Issue by dosboxonline** [EmulatorJS/EmulatorJS#10]
![emulatorjs](https://user-images.githubusercontent.com/10185752/130836513-35c11dc0-5ef3-4e86-9d82-623eee0b5f3e.png)

I uploaded the entire archive to the server from here. If i return "loader.js" file a month ago, then everything works.

**Comment by ethanaobrien** [comment]
@dosboxonline Update loader.js - I just fixed it  Report to me on what happens. If it does not work include the screenshot of the console

**Comment by dosboxonline** [comment]
Now all work. Thanks.
