### ISSUE TITLE
Network Error when trying to implement embed on Google Sites.

### ISSUE THREAD

**Issue by SpiralllLmao** [emulatorjs/emulatorjs#100]
Everything embeds fine, but it gives me a newtork error when it finishes loading. 

The embed HTML code; 
```
<div style="width:640px;height:480px;max-width:100%">
        <div id="game"></div>
      </div>
<script type="text/javascript">
    EJS_player = '#game';
    EJS_biosUrl = '';
    EJS_gameUrl = 'games/emulatorjs/pokemon-ruby.gba';
    EJS_core = 'gba';
</script>
<script src="https://www.emulatorjs.com/loader.js"></script>
```

Im a novice to this, never done this before. Not even sure if you can do it on google sites

**Comment by SpiralllLmao** [comment]
Got it to embed just now, its just a blank screen though. Does this not work on Google Sites?

**Comment by ethanaobrien** [comment]
Are you using the old or new google sites (see #61 )

Also, you're using the emulatorjs.com build. This may already be fixed in this build. You might want to change over. (no ads)

**Comment by SpiralllLmao** [comment]
Looks like new Google sites. I used Allans website to make a link for the embed. That finally allowed me to load into the emulator without a network error, however, i get a blank screen.

**Comment by ethanaobrien** [comment]
Can you send a screenshot?

**Comment by SpiralllLmao** [comment]
https://ibb.co/TkY0gb8

The link itself works, i opened it up in a new tab and it runs perfectly.

**Comment by ethanaobrien** [comment]
Anything in the console?

**Comment by SpiralllLmao** [comment]
Want me to send over the whole thing?

https://ibb.co/8B1zPf5

**Comment by ethanaobrien** [comment]
Can you send me the embed site you are suing? I think it is incredibly outdated

**Comment by SpiralllLmao** [comment]
Used the one on this github: https://allancoding.github.io/emulatorjs/

What should i use instead?

**Comment by ethanaobrien** [comment]
I'd recommend making a branch and putting something like that together yourself

Also, I took a look, it is INSANELY outdated

**Comment by SpiralllLmao** [comment]
Lol yikes, so thats the issue. Would you be able to help me out with this? I literally have no clue where to start

**Comment by ethanaobrien** [comment]
Just clone his repository (https://github.com/allancoding/emulatorjs/tree/main/emulator) and update the emulator files. That should work

**Comment by SpiralllLmao** [comment]
Thanks. Lets see how this goes, ill let you know

**Comment by SpiralllLmao** [comment]
Okay, i cloned everything and now im a little confused on how to update the files. Which files should be replaced in the "emulator'"folder?

**Comment by ethanaobrien** [comment]
Replace everything in the emulator folder with everything in the data folder (data folder from this repository)

**Comment by ethanaobrien** [comment]
Hey, @CynthLol did you ever get this working

**Comment by allancoding** [comment]
@CynthLol @ethanaobrien 
I updated the emulator at https://allancoding.github.io/emulatorjs-maker/

That was originally: 

> https://allancoding.github.io/emulatorjs/
