### ISSUE TITLE
MAME #Network error

### ISSUE THREAD

**Issue by megamandev** [emulatorjs/emulatorjs#101]
i updated today and try run mame and get network error

print
https://ibb.co/NxjCLwq

**Comment by ethanaobrien** [comment]
Do you have `EJS_mameCore` set? (see the readme) I recently made this a requirement.

**Comment by megamandev** [comment]
very ty brother now working with insert coin =D
you have any solution for nintendo 64 stick and c buttons?
cheers!

**Comment by ethanaobrien** [comment]
Not yet, my main priority right now is to #94 . Once I get it working, the emulators will be much faster.

Can I close this

**Comment by megamandev** [comment]
ty again brother close this.
is possible hide arrow mouse same time hide emulator player
because arrow mouse not hide

**Comment by ethanaobrien** [comment]
Nope, thats is an os thing
