### ISSUE TITLE
Control settings menu is a mess.

### ISSUE THREAD

**Issue by InTheMidl** [emulatorjs/emulatorjs#102]
The control settings menu is cut off and looks very wrong.
Picture: <img width="1439" alt="Screenshot 2022-01-27 at 10 42 50 AM" src="https://user-images.githubusercontent.com/91590573/151299463-cee1a268-b33c-4f5f-9df6-634c9bf417c0.png">

**Comment by megamandev** [comment]
home computer or phone?
in home computer browser i not have this issue.

**Comment by ethanaobrien** [comment]
Is it reproducible? Have you modified the css?

**Comment by InTheMidl** [comment]
No, I have not modified the css. Chrome 97.0.4692.99 (Official Build) (arm64)

**Comment by ethanaobrien** [comment]
Is it reproducable?

**Comment by ethanaobrien** [comment]
I can't do anything without any information, assuming this is resolved
