### ISSUE TITLE
its just saying game core ready download game data and its just been stuck here 

### ISSUE THREAD

**Issue by Mikeslimy** [emulatorjs/emulatorjs#108]
Im not sure if its my chromebook or its the site thats doing this im probably not near a valid wifi spot and i should move to a different area but Its just been stuck at game core ready download game data this was working like last week also the other week too

**Comment by ethanaobrien** [comment]
What site? Can you send a screenshot of the console logs?

**Comment by Mikeslimy** [comment]
the emulator site

**Comment by Mikeslimy** [comment]
Usually this is like a file problem i misplaced in my folders but its just stuck Ive been looking at the same text here
![Screenshot 2022-01-31 11 04 51 AM](https://user-images.githubusercontent.com/98171646/151839261-f4a3d47e-a1ff-41a2-ab39-2b32971108aa.png)

**Comment by Mikeslimy** [comment]
its psx im trying to get working btw I tried other roms but there just showing the same thing

**Comment by ethanaobrien** [comment]
Which emulator site? I have absolutely no information, I can't just magically make it work. Can you please send a screenshot/txt of the console log

**Comment by Mikeslimy** [comment]
sorry The emulator site im talking about is emulatorjs you made and I have no idea how to see the console log

**Comment by ethanaobrien** [comment]
The emulator.js site and this project are very different. (read the readme)

Right click (click with 2 fingers on mousepad) and click `inspect`. Then, at the top, click `console` then right click on the console and click the export button and upload (drag and drop) the file here

**Comment by Mikeslimy** [comment]
Im using the demo emulatorjs im using a school pc right now

**Comment by ethanaobrien** [comment]
Your school is probably blocking something. I can do absolutely nothing without a console log. 

Use this: https://github.com/ethanaobrien/emulator-button/
