### ISSUE TITLE
segaMS games are not recognized in client

### ISSUE THREAD

**Issue by dinovich** [emulatorjs/emulatorjs#110]
I added segaMS games, and even inside the config everything looks fine:
`{
  "title": "Sega Master System",
  "root": "segaMS",
  "parent": "main",
  "display_items": 9,
  "defaults": {
    "emulator": "libretro-genesis_plus_gx",
    "bios": "sega.zip",
    "path": "segaMS",
    "rom_extension": ".zip",
    "video_position": "left:11.5vw;top:31.5vh;width:36vw;height:43vh;",
    "type": "game",
    "has_back": false,
    "has_corner": false,
    "has_logo": true,
    "has_video": true,
    "multi_disc": 0
  },
  "items": {
    "20 em 1 (Brazil)": {
      "has_video": false,
      "rom_extension": ".sms"
    },
    "4 PAK All Action (Australia) (Unl)": {
      "has_logo": false,
      "has_video": false,
      "rom_extension": ".sms"
    },
    "94 Super World Cup Soccer (Korea)": {
      "has_logo": false,
      "has_video": false,
      "rom_extension": ".sms"
    },
    "Ace of Aces (Europe)": {
      "rom_extension": ".sms"
    },
    "Action Fighter (Japan, Europe) (Rev 1)": {
      "rom_extension": ".sms"
    },
    "Action Fighter (USA, Europe) (Rev 2)": {
      "rom_extension": ".sms"
    },
    "Addams Family, The (Europe)": {
      "rom_extension": ".sms"
    },
...`

But when I navigate the client to the segaMS system, I get the message: "No items to load, please add some games".
I tried to add the games to config again, but it looks like it's mapped properly and still doesn't recognize any game in the client.

Any ideas?

**Comment by ethanaobrien** [comment]
I think you may be in the wrong place. Are you using https://github.com/linuxserver/emulatorjs/

**Comment by dinovich** [comment]
Gotcha, sorry @ethanaobrien

**Comment by ethanaobrien** [comment]
All good, can I close?

**Comment by dinovich** [comment]
Yes, thank you again @ethanaobrien .

**Comment by ethanaobrien** [comment]
No problem!
