### ISSUE TITLE
decrypt tools, please help decrypt script, I can not

### ISSUE THREAD

**Issue by cyrillpetroff** [emulatorjs/emulatorjs#111]
Greetings. Can you help with the script, I can't decrypt it
[eyJ.zip](https://github.com/ethanaobrien/emulatorjs/files/7982790/eyJ.zip)
.

**Comment by ethanaobrien** [comment]
That js file actually doesnt look obstructed in the way the decrypt tools decrypt it. You just need to clean the js. Look up `js cleaner` or `js formatter` or something like that on google and use the tool to format the javascript
