### ISSUE TITLE
video cassette

### ISSUE THREAD

**Issue by nenge123** [emulatorjs/emulatorjs#112]
This video is very good, how can I get the sound? Suppose I can get the ARRAYBUFF of the sound

**Comment by ethanaobrien** [comment]
What is this issue. What are you asking. I have absolutely no details on what you're trying to do

**Comment by nenge123** [comment]
Translation software cheats goods, 

recording screens ,how to add music

**Comment by ethanaobrien** [comment]
>Translation software cheats goods

So what do you exactly want to do


>recording screens ,how to add music

are you trying to add audio to the record feature?

**Comment by nenge123** [comment]
yes ，
i konw how to get sound arrayBuffer


but in the mdn not have way to try

**Comment by nenge123** [comment]
What else has been added to your warehouse code? I'm going to sort out this emulatorjs with a new one.

**Comment by ethanaobrien** [comment]
>i konw how to get sound arrayBuffer

yeaaa thats not going to help much. It isn't currently supported by the browser
see #47 

>What else has been added to your warehouse code? I'm going to sort out this emulatorjs with a new one.

What exactly are you asking?
