### ISSUE TITLE
#MAME i found 3 games not working

### ISSUE THREAD

**Issue by megamandev** [emulatorjs/emulatorjs#117]
battletoads
captain america and avengers
alien vs predator

my emulatorjs not working this games
this site use same emulatorjs and work fine

3 games here in pastebin incl site with same emulatorjs
https://pastebin.com/m6fkqFgT

very ty and cheers!

**Comment by ethanaobrien** [comment]
I cant help you. There is no link in the right click menu citing your source. I cannot verify this is where you got the code and therefore cannot help you.

Also, the [LICENCE](https://github.com/ethanaobrien/emulatorjs/blob/main/LICENSE) file states you much state changes when re-distributing. Please make this change. I cannot help until you do so.

**Comment by ethanaobrien** [comment]
Oops sorry, I misunderstood

add the line

```
EJS_mameCore = '' // mame core options (example: '4|0')
```
set the mame core value to the mame core number (1 - 6) + `|` + save states supported (0 or 1)
you may have to do some testing to find what core number it uses

**Comment by megamandev** [comment]
ok nice i go try and report to you

**Comment by ethanaobrien** [comment]
@megamandev Did you ever get it working?

**Comment by megamandev** [comment]
@ethanaobrien

only work captain america and avengers with core 2

battletoads, i try core 1, 2,3,4,5,6 not work
i inspect the site working battletoads, load core 4 and bios. =(

site working https://www.retrogames.onl/2021/08/battletoads-arcade.html

**Comment by megamandev** [comment]
i found more 1 game now tekken tag working in this site
https://www.retrogames.cc/arcade-games/tekken-tag-tournament-world-teg2-ver-c1-set-1.html

i try run in my host with same core 6 and not work
this site use emulatorjs mame api for run all mame games
u can add this api for self host

**Comment by ethanaobrien** [comment]
Then try with a different mame core

**Comment by megamandev** [comment]
i try all 6 core not work, need bios and api mame check the 2 sites and inspect F12
you go see

**Comment by megamandev** [comment]
@ethanaobrien

core 2 and 3 work fine
core 4 need add bios game for each game different bios.
i set tekken for correct core 6 and click PLAY NOW and say message decompress core and stop working 99%

print screen
https://ibb.co/4RHRHqc

**Comment by ethanaobrien** [comment]
All the cores are different. Some wont work with certain games, that isnt a bug.

**Comment by megamandev** [comment]
@ethanaobrien
example in this site tekken working fine with core 6
https://www.retrogames.cc/arcade-games/tekken-tag-tournament-world-teg2-ver-c1-set-1.html
i download this same tekken and set my mame to core 6 and not work stop in 99%

other example battletoads working fine in this site with core 4
 https://www.retrogames.onl/2021/08/battletoads-arcade.html

same game not work with my core 4

maybe need more file.
you can inspect this site for maybe solved this bug

**Comment by ethanaobrien** [comment]
Im not going to be doing any troubleshooting on the cores until #109 is merged

As long as it works with one core than thats what matters

**Comment by megamandev** [comment]
@ethanaobrien

I did more tests tonight, I managed to make the battletoads work using core 4 and mame bios. however, core 6 does not load is a bug in the emulator.js. because in emulatorjs with ads the core 6 loads normal and tekken tag works.
very thank you.

**Comment by ethanaobrien** [comment]
What kind of bug is it. I need some info about whats wrong I cant fix it without any info

**Comment by megamandev** [comment]
@ethanaobrien 

mame have six cores.
the bug is: core number 6 not load with your emulator.js
freeze in 99%
print: https://ibb.co/4RHRHqc

however with emulator.js original with ads works.

**Comment by megamandev** [comment]
@ethanaobrien 

i don't know decrypt this original emulator with ads
if I knew could try to solve this bug

**Comment by ethanaobrien** [comment]
We are literally going in a loop. I am locking this conversation because you wont give me any of the info I need to be able to even see what might be wrong and you seem to just act like you know you could fix it. Its not that easy. Please stop this behavior.
