### ISSUE TITLE
is possible add NEO GEO CD?

### ISSUE THREAD

**Issue by megamandev** [emulatorjs/emulatorjs#119]
NEO GEO CD have more option in game
change language, difficult and others...

this video working NEO GEO CD in RETROARCH
https://www.youtube.com/watch?v=269BjH8G0I4

**Comment by ethanaobrien** [comment]
This is possible on the next update, can you send me a link to the github retroarch repository containing this emulator?

**Comment by megamandev** [comment]
maybe this repo

https://github.com/libretro/neocd_libretro
https://github.com/Abdess/retroarch_system/tree/libretro/SNK%20-%20NeoGeo%20CD

**Comment by ethanaobrien** [comment]
Thank you, I will look into this

**Comment by ethanaobrien** [comment]
#151 (I am merging all these system requests into 1 issue)
