### ISSUE TITLE
Save broken

### ISSUE THREAD

**Issue by O-ThePlace** [emulatorjs/emulatorjs#122]
This save is broken 
I saved whilst encountering a wild pokemon.
https://ufile.io/y3g3i1tv
Would you like me to link it else where?

**Comment by ethanaobrien** [comment]
Not sure what I can do about this, sorry.

**Comment by O-ThePlace** [comment]
> Not sure what I can do about this, sorry.

is there anyway I can prevent this in future?

**Comment by ethanaobrien** [comment]
No, I really dont know. Something like this is usually a one time bug thing.

**Comment by O-ThePlace** [comment]
> No, I really dont know. Something like this is usually a one time bug thing.

I think it would likely occur again, saving while transitioning from a cut scene might trigger it again.

**Comment by ethanaobrien** [comment]
It might be resolved by #109
