### ISSUE TITLE
Ps1 Game Not working 

### ISSUE THREAD

**Issue by DarkShadow8700** [emulatorjs/emulatorjs#123]
I'm having an issue with crash team racing on the ps1 and the issue is whenever I try to load it in its gets through the introduction of the game but then just goes to a black screen I've tried to download different ROMs of the game but still had no luck

**Comment by ethanaobrien** [comment]
Possibly resolved by #109

**Comment by megamandev** [comment]
not work too
No Fear Downhill Mountain Biking BUG: start button not work in this game
Formula 1 97, 98, 99, 2000, 2001 BUG: game not start
Skeleton Warrios BUG: no Music in game. only fx sound.

ps: in psx emulator this games working

**Comment by megamandev** [comment]
@DarkShadow8700

i have one ISO crash team race working with this emulator but you need test all game mode
i tested only racing mode

**Comment by megamandev** [comment]
@ethanaobrien
@DarkShadow8700

print crash team racing working
https://ibb.co/jW3wbD1

download link my ISO
https://drive.google.com/file/d/16NtVV1lshioX0TKM-9U_MSdVbvrpXP38

**Comment by DarkShadow8700** [comment]
@megamandev Alright I will be sure to download it
