### ISSUE TITLE
SNES game not working

### ISSUE THREAD

**Issue by megamandev** [emulatorjs/emulatorjs#124]
Dragon Ball Z Hyper Dimension
BUG: Black screen when press start button

**Comment by ethanaobrien** [comment]
Possibly resolved by #109

**Comment by dosboxonline** [comment]
Some problems are solved by adding commands to emulator.js file.
Look at the site for the "docs.libretro.com" in the description of the cores.

Examples for PSX:

Additional game fixes options

-Diablo Music Fix [pcsx_rearmed_idiablofix] (disabled|enabled) -Fix for music randomly cuts out when pressing start or interact with somebody.
-Parasite Eve 2/Vandal Hearts ½ Fix [pcsx_rearmed_pe2_fix] (disabled|enabled) - Enable this to fit Parasite Eve 2 and Vandal Hearts ½.
-InuYasha Sengoku Battle Fix [pcsx_rearmed_inuyasha_fix] (disabled|enabled) - Enable this to fix InuYasha.

Apparently, the "asmjs / wasm" files taken from the emulatorjs site are rather old versions. Compile new ones if possible and preferably in "wasm", asmjs work much slower.

Thanks.

**Comment by ethanaobrien** [comment]
>Apparently, the "asmjs / wasm" files taken from the emulatorjs site are rather old versions. Compile new ones if possible and preferably in "wasm", asmjs work much slower.

Thats -  the entire thing I just saidd - #109 contains the beta code of me updating to the new retroarch cores

**Comment by dosboxonline** [comment]
It is very cool! Thank you.
