### ISSUE TITLE
N64 game not working

### ISSUE THREAD

**Issue by megamandev** [emulatorjs/emulatorjs#125]
zelda ocarina of time BUG: black screen inside the link house, when will start the game
jet force gemini BUG: flashing screen on game
Cruis'n exotica BUG: not working
ogre battle BUG: half black screen, half normal on game
pilot wings BUG: Large black shadow on the peronagem when it goes through the hurricane
internation superstar soccer BUG: Large black shadow on the peronagem

**Comment by ethanaobrien** [comment]
Nothing we can do about this right now

**Comment by ethanaobrien** [comment]
#151 (I am merging all these system requests into 1 issue)
