### ISSUE TITLE
Wrong snes button positioning

### ISSUE THREAD

**Issue by imneckro** [emulatorjs/emulatorjs#126]
Correct order:
![image](https://user-images.githubusercontent.com/42493772/152855746-c8028d54-a3b6-48bf-a54f-ec6cc37044f5.jpeg)

Wrong order:
![image](https://user-images.githubusercontent.com/42493772/152855772-b109f288-b0e2-47d3-b732-0d863aba8cd8.jpeg)

Same with game boy.
Correct order:
![image](https://user-images.githubusercontent.com/42493772/152855954-37efad0c-bdae-4358-8c20-723b317f93d6.jpeg)

**Comment by ethanaobrien** [comment]
Are just the labels switched or are the button inputs also switched?

**Comment by imneckro** [comment]
Button inputs also switched

**Comment by imneckro** [comment]
> Are just the labels switched or are the button inputs also switched?

Also when you plug in controller is same wrong positioning and needs mapping.

We grew up playing fighting games like killer instinct and when I plug controller it's unplayable. It needs remaping

**Comment by ethanaobrien** [comment]
>We grew up playing fighting games like killer instinct and when I plug controller it's unplayable. It needs remaping

This is going to happen, it would be very inefficient and a waste of time to be to program specific controls for every type of controller.
