### ISSUE TITLE
nes game bug

### ISSUE THREAD

**Issue by ethanaobrien** [emulatorjs/emulatorjs#127]
Zelda 2, when you are going one direction and suddenly switch directions you can glitch into/through walls/gates/etc.

**Comment by ethanaobrien** [comment]
Already tested with beta from #109 and it will be fixed by updating nes core

**Comment by megamandev** [comment]
i not have this problem with my zelda 2 nes.

Edited to remove game rom

**Comment by ethanaobrien** [comment]
Well I was. This isnt my point. My point is that it is fixed
