### ISSUE TITLE
Retroarch Emulators

### ISSUE THREAD

**Issue by megamandev** [emulatorjs/emulatorjs#128]
RETROARCH EMULATORS

in the future, it would be great to have sega dreamcast, psp and ps2 in your project.
very thank you!
cheers!

NINTENDO GAMECUBE

https://www.youtube.com/watch?v=yb34Mg7mCEA
https://github.com/Abdess/retroarch_system
https://github.com/Abdess/retroarch_system/tree/libretro/Nintendo%20-%20GameCube

SEGA DREANCAST

https://www.youtube.com/watch?v=SOA3pOcg0So
https://github.com/Abdess/retroarch_system
https://github.com/Abdess/retroarch_system/tree/libretro/Sega%20-%20Dreamcast
https://github.com/libretro/libretro-database/blob/master/rdb/Sega%20-%20Dreamcast.rdb
https://github.com/libretro/libretro-database/blob/master/metadat/redump/Sega%20-%20Dreamcast.dat

PSP (Playstation portable)

https://www.youtube.com/watch?v=HCgrKP99H-4
https://github.com/libretro/RetroArch
https://github.com/Abdess/retroarch_system
https://github.com/Abdess/retroarch_system/tree/libretro/Sony%20-%20PlayStation%20Portable
https://github.com/libretro/RetroArch/blob/master/Makefile.psp1
https://github.com/libretro/RetroArch/blob/master/Makefile.psp1.salamander

Playstation 2

https://www.youtube.com/watch?v=2VyIbW0apHs
https://github.com/libretro/RetroArch
https://github.com/libretro/RetroArch/tree/master/ps2
https://github.com/libretro/libretro-database/blob/master/rdb/Sony%20-%20PlayStation%202.rdb
https://github.com/libretro/RetroArch/blob/master/Makefile.ps2
https://github.com/libretro/RetroArch/blob/master/Makefile.ps2.salamander

**Comment by ethanaobrien** [comment]
I would love it if psp would work

**Comment by ethanaobrien** [comment]
#151 (I am merging all these system requests into 1 issue)
