### ISSUE TITLE
MAME CORE 6 NOT WORK

### ISSUE THREAD

**Issue by MariaZDale** [emulatorjs/emulatorjs#130]
all right very good project.
tekkentag works with core 6 in emulator original with ads.
but in your emulatorjs not work, freeze screen.
i try with others cores but not work too.
i very noob with script you can help to fix this bug.

**Comment by ethanaobrien** [comment]
As I said in #117, I cant do anything without a log of the console

**Comment by MariaZDale** [comment]
where i get the console log for you see.

**Comment by ethanaobrien** [comment]
use google, Im tired of explaining something so simple

**Comment by MariaZDale** [comment]
here print console log
https://ibb.co/sw8V0Fn
freeze screen with 99%

**Comment by ethanaobrien** [comment]
Ca you upload it via github. (click the `attach files by dragging & dropping, selecting or pasting them.` button)

**Comment by MariaZDale** [comment]
here
print screen

![console log error core 6](https://user-images.githubusercontent.com/99551110/153730001-df1d69d9-ae1b-4c36-95b7-ee114f7b5dd5.jpg)

(edited to remove game rom download link)

**Comment by ethanaobrien** [comment]
Please do not share roms. This is a problem with `SharedArrayBuffer`s. Ive seen it before. Are you on an https page?

**Comment by hello-smile6** [comment]
> Please do not share roms. This is a problem with `SharedArrayBuffer`s. Ive seen it before. Are you on an https page?

Make sure to delete the previous edits!

**Comment by MariaZDale** [comment]
after, when i click in (play now) appear this issue. my page is secure with htttps ssl certificate.

**Comment by hello-smile6** [comment]
> after when i click in play now appear this issue

What does https://sharedarraybuffer.9pfs.repl.co/ show?
It should look like this.
![screenshot-optimal](https://image.thum.io/get/https://sharedarraybuffer.9pfs.repl.co/)

**Comment by ethanaobrien** [comment]
This should work. It did for me before

```
When you encounter an issue: Uncaught ReferenceError: SharedArrayBuffer is not defined on Chrome, you'll
need to apply "cross-origin isolation" to continue using SharedArrayBuffer, but as an escape-hatch, you
can request [an origin trial](https://developer.chrome.com/blog/enabling-shared-array-buffer/#origin-trial)
to allowlist your site to continue using SharedArrayBuffer without cross-origin isolation at least until
Chrome 96.
```
[source](https://stackoverflow.com/questions/64650119/react-error-sharedarraybuffer-is-not-defined-in-firefox#:~:text=When%20you%20encounter%20an%20issue,using%20SharedArrayBuffer%20without%20cross%2Dorigin)

**Comment by MariaZDale** [comment]
i follow this tutorial and not work
now appear new error
![new error](https://user-images.githubusercontent.com/99551110/153769031-6466e34b-45a5-4922-8007-f930f41e0d57.jpg)

**Comment by hello-smile6** [comment]
> i follow this tutorial and not work now appear new error ![new error](https://user-images.githubusercontent.com/99551110/153769031-6466e34b-45a5-4922-8007-f930f41e0d57.jpg)

Not sure how to fix

**Comment by ethanaobrien** [comment]
This *should* be fixed by the beta (once I get to mame)

**Comment by ethanaobrien** [comment]
This won’t Ben fixed. Once the beta is completed that should allow those games to work
