### ISSUE TITLE
MAME CHD files along zipped roms

### ISSUE THREAD

**Issue by imneckro** [emulatorjs/emulatorjs#131]
It would be cool if anyone has the skills to implement chd support for mame roms.
As many of you know chd is a disk image that some mame roms depend to in order to run.
Mame supports chd out of the box.
The question is how to implement support for chd mame dependent roms on emulator.js.

**Comment by ethanaobrien** [comment]
@imneckro Does retroarch natively support this?

**Comment by imneckro** [comment]
Hello Ethan. Yes retroarch natively support chd.
In rom folder where for example you have kinst.zip
mame rom you must also have a dir named kinst and inside that dir kinst.chd.
That’s the way in retroarch.
Ask me anything, I’ll be more than happy to help if I can!


Wednesday, 16 March 2022, 04:22 +0200 from ***@***.***  ***@***.***>:
***@***.*** Does retroarch natively support this?

**Comment by ethanaobrien** [comment]
Then this is probably already implemented. Do you just need to zip the files together? Can you try that?

**Comment by imneckro** [comment]
Tried all EJS_core options but game isn't loading with no console log errors whatsoever.
zip structures i tried:
1)
![image](https://user-images.githubusercontent.com/42493772/159114021-26269594-621c-41b1-9ec7-139ebd03676e.png)
2)
![image](https://user-images.githubusercontent.com/42493772/159114041-a51f2a25-df4d-4ff1-b229-75f196a95aee.png)

**Comment by ethanaobrien** [comment]
Use theupdated  `mame2003` core, this should be supported now.

**Comment by imneckro** [comment]
> Use theupdated `mame2003` core, this should be supported now.

Ethan whats the way to use mame2003? 
EJS_core = 'mame' and EJS_mameCore = '4|0' ?

And whats the required structure of the rom zip?
this

![image](https://user-images.githubusercontent.com/42493772/183939543-ff56e99c-fa17-41f2-adbb-22c5af34dfe8.png)

or this
![image](https://user-images.githubusercontent.com/42493772/183939631-53197558-0d71-408a-b2a5-efc3c4cb1a23.png)

**Comment by ethanaobrien** [comment]
I dont know exactly, set the core to `mame2003`. `EJS_mameCore` does not need to be set

**Comment by imneckro** [comment]
setting EJS_core = 'mame2003' loads retroarch ui.

**Comment by ethanaobrien** [comment]
That is only if your rom is invalid

**Comment by imneckro** [comment]
Tried every possible solution to load rom zip along chd. Every time loads retroarch ui.
If anyone manage to find the combination let us know.

**Comment by ethanaobrien** [comment]
Well then sorry, I cannot support it

**Comment by imneckro** [comment]
> Well then sorry, I cannot support it

Hello Ethan. Hope your doing well.
Found that [this ](https://www.retrogames.cc/arcade-games/killer-instinct.html)emulator supports chd alongsize zip and runs it well.
My hope is when you have time, check console with your clever eyes to see if its possible for us to implement it.

**Comment by Suburban-Vampire** [comment]
Well, I'll be ding danged if this isn't actually a working instance of Killer Instinct, running in my Google Chrome browser! Thanks for pointing out the site, I had no idea someone had already done this! Amazing stuff.

The MAME 2003 Plus Reference Set contains 30 games that use CHDs and RetroArch fully works with them, so it seems reasonable to expect this to be possible in EmulatorJS.

I had been wondering if it would be as dumb as simply needing a custom handler for MAME CHD games and then downloading both items to local storage prior to launch, and it seriously does look like that's really all they're doing on the site retrogames.cc, and based on an inspection of the site using developer tools, they're using EmulatorJS 0.5.52 to do this.

If they're already running CHDs, would this be more a matter of simply how the UI side of things handles getting the CHD & ZIP files over to the client?
