### ISSUE TITLE
[beta] update nds core file

### ISSUE THREAD

**Issue by ZackandHack** [emulatorjs/emulatorjs#133]
Ok so basically I Love DS games and I saw that your emulator can play DS games and while I understand it's laggy, I was wondering if its possible for the DS games to run more faster (I play on Chromebook) and an idea I had was to make it were you can make the frames go higher or lower as an option

**Comment by ZackandHack** [comment]
(Also if you could not tell I'm a new User)

**Comment by ethanaobrien** [comment]
Yes, this is in progress #109 will close!

(turn on frame skip in the meantime, its in settings in the bottom right corner)

**Comment by ZackandHack** [comment]
I just saw that you added SNES support and I amazed about that fact you did it that fast but I was wondering do you know how long it will take to add DS support :)

**Comment by ethanaobrien** [comment]
Id like to get the save function working properly. Assuming it works properly I'll compile at home and test to see if it works. If it does I'll add to the beta. Save state may not work though

**Comment by ZackandHack** [comment]
All right well I wish you luck 👍

**Comment by ethanaobrien** [comment]
Im keeping this open until I get it working

**Comment by ethanaobrien** [comment]
#151

**Comment by ethanaobrien** [comment]
@ZackandHack I have updated the nintendo ds core. You can try the beta by using https://github.com/ethanaobrien/emulator-button and checking the `use beta cores` option

**Comment by ZackandHack** [comment]
Does this emulator has any multiplayer to it whatever that being local or online as some games (like pokemon) need you to do connectivity to have the most fun in them

**Comment by ethanaobrien** [comment]
No, this is not possible
