### ISSUE TITLE
Running custom functions when game succesfully started

### ISSUE THREAD

**Issue by imneckro** [emulatorjs/emulatorjs#134]
Whats the best way to run custom functions if game succesfully started?
In other words whats the way to check that game started succesfully?

**Comment by ethanaobrien** [comment]
If the emulator started successfully the following boolean variable will be set to true
```
window.EJS_emulator.started;
```

Can I close?

**Comment by imneckro** [comment]
> window.EJS_emulator.started;

if(window.EJS_emulator.started == true)
gives me Cannot read properties of undefined (reading 'started')

**Comment by ethanaobrien** [comment]
if `window.EJS_emulator` is not defined, then the emulator `loader.js` file never loads in the first place.

**Comment by imneckro** [comment]
the problem is on variable 'started'
read the error: Cannot read properties of undefined (reading 'started')

**Comment by ethanaobrien** [comment]
Ok I'm closing because of your attitude. You read the error

Cannot **read properties** of **undefined** (**reading** 'started')

It cannot read `started` because `window.EJS_emulator` is not defined.

The emulator files arent loading on your page

**Comment by imneckro** [comment]
What attitude?
