### ISSUE TITLE
NDS touch screen does not work on mobile

### ISSUE THREAD

**Issue by LightningBlox** [emulatorjs/emulatorjs#140]
## the NDS touch screen does not work on mobile.
Video: https://user-images.githubusercontent.com/43703390/154040255-240ab086-87a2-49a8-8c2b-e6d7d8dfcdfd.mp4

**Comment by ethanaobrien** [comment]
@LightningBlox Does only the click not work? Can you move the cursor?

**Comment by LightningBlox** [comment]
The cursor can be moved, but the click does not work.

**Comment by ethanaobrien** [comment]
Thank you, Ill look at this, should be a simple fix

**Comment by vuquangtam** [comment]
Hi @ethanaobrien, is this issue fix?

**Comment by ethanaobrien** [comment]
Sorry, I havent found the cause yet

**Comment by SlideMovies** [comment]
Any news?

**Comment by ethanaobrien** [comment]
Sorry, I havent been able to fix this yet

**Comment by ethanaobrien** [comment]
I just realized, I’m not capable of this. There is no click touch event event. I guess ds for mobile isn’t supported

**Comment by hax4dazy** [comment]
@ethanaobrien Are you willing to look into this again? Perhaps a solution is possible right now. This would be a great way to play some of the Professor Layton games on mobile.

**Comment by ethanaobrien** [comment]
@hax4dazy 

This behaviour is left up to the core.

Settings -> Backend Core Options -> touch mode -> Touch

**Comment by hax4dazy** [comment]
Oh thanks! I didn't know that existed.
