### ISSUE TITLE
React

### ISSUE THREAD

**Issue by Avi7x** [emulatorjs/emulatorjs#142]
Hi there,

does anyone know how to do that in a react.js webapp?

thanks 🥰♥️

**Comment by ethanaobrien** [comment]
I do not know much about webapps. Maybe someone else does

**Comment by Avi7x** [comment]
Got it with a little help from a Reactjs-Forum.

[dangerously-set-html-content](https://github.com/christo-pr/dangerously-set-html-content-v1)

With dangerously-set-html-content you can render raw html code including script tags.
