### ISSUE TITLE
Multi disc swapping

### ISSUE THREAD

**Issue by dosboxonline** [emulatorjs/emulatorjs#143]
It turned out to implement the ability to switch to the next disc without losing the game process. But. There are two games (Metal Gear Solid, Heart of Darkness) that require the opening/closing of the virtual tray. I'm trying to find the command that is responsible for this DIP switch. Can you help with this?

**Comment by ethanaobrien** [comment]
This would be a part of updating the retroarch core file

**Comment by ethanaobrien** [comment]
This isnt going to be possible. Sorry

**Comment by adamantike** [comment]
@ethanaobrien, do you think this is still not possible? Any chance to provide some context regarding the technical limitations, and if anything has changed since 2022?

**Comment by ethanaobrien** [comment]
@adamantike Things have definitely changed since 2022. Is this issue pertaining to switching disks or needing a virtual open/close button?
