### ISSUE TITLE
virtual gamepad behaves weird as if you holding the tapped button down infinite.

### ISSUE THREAD

**Issue by imneckro** [emulatorjs/emulatorjs#145]
After updating emu-main.js to last version virtual game pad behaves weird as if you holding the tapped button down infinite.
I recorded video before update and after update.

Before update normal behavior:
https://user-images.githubusercontent.com/42493772/154530614-5e7e0c74-d36e-4885-9f61-c74ade459fb1.MOV

After update weird behavior:
https://user-images.githubusercontent.com/42493772/154530723-12d50f50-5d4a-4b02-815b-69488183a982.MOV

Watch virtual analog stick to understand.

**Comment by ethanaobrien** [comment]
@imneckro Could you update your `emu-main.js` file and tell me if this still occurs

**Comment by imneckro** [comment]
@ethanaobrien yes it behaves correctly now. thank you!

**Comment by ethanaobrien** [comment]
No problem!
