### ISSUE TITLE
Screenshot with shader.

### ISSUE THREAD

**Issue by dosboxonline** [emulatorjs/emulatorjs#149]
Found only this parameter - 'video_gpu_screenshot = true\n'. But it only increases the resolution of the screenshot.
Is it possible to add an option to take a screenshot so that it looks like on the screen with the shader enabled, and not actually in the game itself? Ideally with a higher resolution (800x600 or 640x480).

**Comment by ethanaobrien** [comment]
Search for `_0x378b5c.toggleShader(0x0), _0x840cf4(), _0x378b5c.toggleShader(0x1)`. Just remove the `toggleShader` calls

The screenshot resolution cant be changed.

**Comment by dosboxonline** [comment]
Many thanks!

**Comment by dosboxonline** [comment]
Many thanks!
