### ISSUE TITLE
anyone use this with a framework?

### ISSUE THREAD

**Issue by iamjaime** [emulatorjs/emulatorjs#15]
i'm trying to figure out how to run this properly on a Single Page App.

re-instantiating the emulator doesn't work very well.....

any ideas?

**Comment by ethanaobrien** [comment]
@iamjaime Thanks for opening an issue!

I know nothing about single page apps. Sorry. Although, I think I have something that can help

I recently made [this tool](https://github.com/ethanaobrien/emulatorjs/tree/decrypt) that will decrypt parts of the `emulator.js` file into a human readable string. I am still working on a tool that can replace all occurrences with a string.

Hope this helps!
