### ISSUE TITLE
Browse Server

### ISSUE THREAD

**Issue by MikeCedonis** [emulatorjs/emulatorjs#150]
Is there a way to choose/browse files or directories stored on the host itself instead of from the device connecting to it?

**Comment by ethanaobrien** [comment]
This isnt an issue. I dont understand what youre asking. Could you explain. Im closing this but I will still try to help

**Comment by allancoding** [comment]
Yes can you explain more what you want.

**Comment by MikeCedonis** [comment]
No it's not an issue, it's a question sorry. It's there a way to have "choose file" on the server browse for files on the server itself. When I connect to the server on my phone it looks for a rom file on it and I wanted to know if there was way choose files on the host.

**Comment by ethanaobrien** [comment]
Oh, you're using the demo. No there is no way to browse. I do not and will not supply roms to anyone, you must upload your own

**Comment by MikeCedonis** [comment]
Sorry I'm not asking you to supply roms. I have everything set up and have the files stored in my NAS.
I wanted to know if it was possible to load the roms directly from it instead of having to store and browse my phone. I know you can point to a path but I wanted to know if it was possible to traverse the NAS directory for the file to load.

**Comment by ethanaobrien** [comment]
The readme supplies links to specific examples where you just fill in the blank.

**Comment by MikeCedonis** [comment]
Right I tried the code creator but I didn't see a way to have choose the files from the server itself. Thanks for replying and have a good day!

**Comment by ethanaobrien** [comment]
Yeah the code creator will automatically handle all that stuff for you. If you want to do everything yourself youll have to use the [demo code](https://github.com/ethanaobrien/emulatorjs/blob/main/docs/NES-Famicom.md) and edit that

**Comment by MikeCedonis** [comment]
So if anyone who has an Android device and wants to load games stored in their NAS, you can use CIFS Document Provider from the play store to select files directly from your NAS and play. No root required.
Awesome Emulator!
