### ISSUE TITLE
PSX no sound/unable to load cue files

### ISSUE THREAD

**Issue by Ramaerel** [emulatorjs/emulatorjs#157]
Hi, I am having issues with loading in game sounds and music while playing PSX. I can't load CUE files at all- It loads a black screen. I have tried almost all other formats to no avail either. I'm not sure if I'm missing something but I think the cue and bin files need to be loaded together.

**Comment by ethanaobrien** [comment]
@Ramaerel
can you try loading them all in a zip file?

**Comment by Ramaerel** [comment]
Sorry for late reply- Just got home from vacation. Doing it through a .zip file doesn't seem to work with some games (Digimon World), but works for others (Final Fantasy 8)

**Comment by ethanaobrien** [comment]
This should be fixed now. I updated the playstation core
