### ISSUE TITLE
Code creator doesnt work

### ISSUE THREAD

**Issue by Ohyaboiii** [emulatorjs/emulatorjs#160]
First off, I don't know how to code or really anything about coding. That's why I used the code creator feature on https://emulatorjs.netlify.app. I put in the correct gaming system (NES) and uploaded a super mario bros rom. I downloaded the zip file and opened the index.html in my browser. It starts to run smoothly until it stops and says "download game core". This is probably an easy fix and I'm just being dumb, but i want to embed this code into my unblocked gaming website and I really need this fixed. Could someone please help?

**Comment by ethanaobrien** [comment]
Check the `Make it work without web server` box or you need to host it on a web server

**Comment by Ohyaboiii** [comment]
I checked the "make it work without web server" and opened it in my browser and it worked just fine. Now how do I embed that into a website? When I opened the index folder with notepad and copied the code and tried to embed it into my website it just came up as nothing.

**Comment by ethanaobrien** [comment]
Check the `Pack into single file` option
