### ISSUE TITLE
How to embed code creator code into website

### ISSUE THREAD

**Issue by Ohyaboiii** [emulatorjs/emulatorjs#161]
Sorry but I do not know how to code or really anything about it. I used the code creator from this link: https://emulatorjs.netlify.app/codehelper and I successfully downloaded the code but need to know how to embed it into my website.  After checking the box, Game boy advance, uploading a pokemon fire red rom, checking the box, "make it work without web server", and naming the game "Pokemon Fire Red," I downloaded the out file. What do I do from here to embed this into my website? I tried opening the index file with notepad and copying the code and embedding that, but it just showed up as nothing. Can anyone please help?

**Comment by ethanaobrien** [comment]
What are you using to host your website? With this information I can go more in-detail on what to do

**Comment by Ohyaboiii** [comment]
I am using google sites.

**Comment by ethanaobrien** [comment]
As I mentioned [in #61](https://github.com/ethanaobrien/emulatorjs/issues/61#issuecomment-994716936), you can't embed something like this into google sites. To host a site like this you would need to use something like [netlify](https://app.netlify.com/) where you can use the code creator (do not check the `make it work without a web server` option) and then you can zip all the files (if not already zipped) and upload them. This will allow you to create a site!

**Comment by Ohyaboiii** [comment]
Great! Thanks for the help!

**Comment by ethanaobrien** [comment]
No problem!
