### ISSUE TITLE
Host without webserver

### ISSUE THREAD

**Issue by drewlobel** [emulatorjs/emulatorjs#164]
Is there anyway to host this without a webserver? Thx!

**Comment by ethanaobrien** [comment]
use the [code creator](https://emulatorjs.netlify.app/codehelper) and check the `make it work without a web server` box

**Comment by allancoding** [comment]
Or this one https://emulatorjs.ga/codehelper 
![image](https://user-images.githubusercontent.com/74841470/156210984-d05e8a32-4e0f-4ef6-b8d3-f0cba19706f1.png)
