### ISSUE TITLE
Code helper not working

### ISSUE THREAD

**Issue by drewlobel** [emulatorjs/emulatorjs#165]
I used
https://emulatorjs.netlify.app/codehelper

I put in the the nds file,
checked make work without web server 
put in the game name
SKIPPED COLOR AND AD URL
and it would not produce anything

thx

**Comment by ethanaobrien** [comment]
Did you click the next button?

**Comment by drewlobel** [comment]
![Screenshot 2022-03-01 11 53 57 AM](https://user-images.githubusercontent.com/73802818/156213058-52cca23b-529c-4cb0-848b-36e51a0934dc.png)


didnt see one

**Comment by allancoding** [comment]
The generate out file button

**Comment by ethanaobrien** [comment]
at the bottom. `generate out file`

**Comment by drewlobel** [comment]
when i click that it dosent do anything

**Comment by ethanaobrien** [comment]
Can you please upload a log of the console. I dont want to have to explain it (You should have done it initially) google it

**Comment by drewlobel** [comment]
There is no log

**Comment by ethanaobrien** [comment]
3. Right click and click `inspect`.
4. Select the `console` tab at the top.
5. Right click on the console and click `save console log to file`
6. Upload the file here

If no log of the console is present. I will immediately close the issue without any comment.
Please upload straight to github and not to some other website.

**Comment by drewlobel** [comment]
I can't use inspect



I just tried it again on my phone, it downloaded, but when I open all I got was a blank screen.

**Comment by drewlobel** [comment]
UPDATE: githack is blocked on my computer. Thats why.

**Comment by ethanaobrien** [comment]
That would be a reason, sorry
