### ISSUE TITLE
Add cores from retroarch-web

### ISSUE THREAD

**Issue by RunTheCoins** [emulatorjs/emulatorjs#166]
I found a bunch of cores from retroarch converted to Javascript, and I thought it would be cool if you all would be able to import them into EmulatorJS.

https://github.com/DuccMan99/retroarch-web

By looking into the assets cores it seems to have a core for **Dolphin** but I could be wrong on that

**Comment by RunTheCoins** [comment]
https://github.com/DuccMan99/retroarch-web/tree/main/assets/cores You'll also see 3DS listed also

**Comment by ethanaobrien** [comment]
the `cores/` directory just seems to be roms for the system, not the actual system. I am already working on converting the cores, it is a bit more complicated than you seem to think

progress: https://github.com/ethanaobrien/RetroArch
