### ISSUE TITLE
Hope to have dos emulator

### ISSUE THREAD

**Issue by ghost** [emulatorjs/emulatorjs#167]
I hope this project have dos emulator since this platform have many good old games.

**Comment by ethanaobrien** [comment]
I would like this

**Comment by ethanaobrien** [comment]
https://github.com/libretro/dosbox-libretro

**Comment by ghost** [comment]
> https://github.com/libretro/dosbox-libretro

 I know this, but it doesn't seem to compile a javascript version of the core directly.

**Comment by ethanaobrien** [comment]
Yeah I just sent the link here so I wouldnt lose it. I have started working on this shouldnt be too long until I have it finished

**Comment by Protektor-Desura** [comment]
There is already an emscripten version of DOSBox.

https://github.com/dreamlayers/em-dosbox

Could you just add that code to the list?

**Comment by ethanaobrien** [comment]
Yes, I am aware

**Comment by ethanaobrien** [comment]
@Rosabis I'm very sorry for the delay, I've been trying to do this but it just doesnt seem to be working. A problem with libretro dobox. This might not be possible, sorry about that.

**Comment by ethanaobrien** [comment]
I'm sorry, Im going to close this as not planned since it seems to be broken right now

**Comment by muditjuneja** [comment]
@ethanaobrien  So there is no plan as of now? I can try helping if you feel there is a  little chance it can be added.

**Comment by ethanaobrien** [comment]
No, there's no current plan to add dos, this is because the retroarch version of dos seems to be broken for emscripten. If you can get it to compile and tell me what changes you made to get it to compile (and run) then I should be able to plug it in. Thanks!
