### ISSUE TITLE
Load state not working.

### ISSUE THREAD

**Issue by Turtle-rocket** [emulatorjs/emulatorjs#170]
When I try to load a state file nothing happens. It says "Unable to auto-detect system. Please select the desired system." After I pick the system and load the game Im left on a black screen. Is there any way I can prevent this from happening?

**Comment by Turtle-rocket** [comment]
and If pick Game boy instead of gba it briefly works then gets stuck on a white screen.

**Comment by ethanaobrien** [comment]
You need to load the state once the game is loaded
