### ISSUE TITLE
Can you compile some of the core into asm.js?

### ISSUE THREAD

**Issue by ghost** [emulatorjs/emulatorjs#171]
I want to port retroarch to kaios, but it is written in web assembly and kaios doesn't support it for years, so I would like you to compile some kernel without asm.js version like bluemsx,mame,psx to compile the asm.js version.

**Comment by ethanaobrien** [comment]
I dont quite understand. What are you asking

**Comment by ghost** [comment]
> I dont quite understand. What are you asking

![图片](https://user-images.githubusercontent.com/32984303/156906357-50f76865-0792-49a0-b69b-9c59eb4ddbf2.png)
S1
![图片](https://user-images.githubusercontent.com/32984303/156906434-d812cdf2-731c-4376-a8a2-d5245055d6a3.png)
S2
In this screenshot 1, you can see browser in kaios doesn't support web assembly,but it support asm.js, see screenshot 2.However some cores in this project such as bluemsx doesn't have asm.js version,that means I can't port this project to kaios,so I hope you can compile these core an asm.js version.

**Comment by ethanaobrien** [comment]
Oh ok, Im currently working on this it might be a bit. Im leaving this open until it is completed

**Comment by ethanaobrien** [comment]
you can use the beta option (`EJS_BETA = true;`) to watch for updates, although I haven't started working to compile them to asmjs yet, still trying to get it working

**Comment by ghost** [comment]
> you can use the beta option (`EJS_BETA = true;`) to watch for updates, although I haven't started working to compile them to asmjs yet, still trying to get it working

So which file should I add this to?

**Comment by ethanaobrien** [comment]
The index file (although I havent started this yet)

**Comment by ethanaobrien** [comment]
I've started compiling the new cores to asmjs. Currently only the nintendo cores are available, but more will be added as I compile more systems to the new cores. I'm closing this.
