### ISSUE TITLE
emujs not working on my Weebly site? (chr0m3games.weebly.com/earthbound12349.html)

### ISSUE THREAD

**Issue by snappyshortpie** [emulatorjs/emulatorjs#174]

**Comment by ethanaobrien** [comment]
it looks like this is because of babel pollyfill
```
Uncaught Error: only one instance of babel-polyfill is allowed
```

**Comment by snappyshortpie** [comment]
> it looks like this is because of babel pollyfill
> 
> ```
> Uncaught Error: only one instance of babel-polyfill is allowed
> ```

meaning??? what do I fix exactly???

**Comment by ethanaobrien** [comment]
Im not sure, sorry

**Comment by snappyshortpie** [comment]
> Im not sure, sorry

its ok 👍 
idk if it's a bug or something,
but I can't add anything to my site til it's fixed

**Comment by ethanaobrien** [comment]
sorry about that, ill look at this when I get a chance

**Comment by snappyshortpie** [comment]
alright, thx anyway

**Comment by ethanaobrien** [comment]
@AxelMal71 Can you check this? I think I got it fixed but am not sure

**Comment by ethanaobrien** [comment]
Im pretty sure I got this fixed, if it still does not work let me know
