### ISSUE TITLE
Wii support?

### ISSUE THREAD

**Issue by snappyshortpie** [emulatorjs/emulatorjs#176]
So I think Wii support should go into EmulatorJS because it has a **lot** of good games, such as The Legend of Zelda: Twilight Princess, New Super Mario Bros. Wii, etc. I just got the idea and felt like requesting it. The default controls could be:
Enter = +
Shift = -
Z = A
X = B
1 = 1
2 = 2
Ctrl = Shake (or something like that...)
Mouse = Pointer?
etc. (I'm out of idea for ctrls right now...)

**Comment by ethanaobrien** [comment]
This isnt a retroarch core, and way wayy to heavy for the web browser, sorry

**Comment by snappyshortpie** [comment]
rip
