### ISSUE TITLE
N64 running too fast

### ISSUE THREAD

**Issue by Ramaerel** [emulatorjs/emulatorjs#178]
I've noticed that some N64 games run excessively fast - Notably, Super Mario 64 for me. Other games like Paper Mario seem to run fine. I haven't tested yet, but I think this might be the emulator running PAL games at 60fps instead of 50?

**Comment by ethanaobrien** [comment]
This is because of the not fully translated opengl to webgl. Cannot be fixed at this time.

Closing because part of #151
