### ISSUE TITLE
Misnamed data files

### ISSUE THREAD

**Issue by cheesykyle** [emulatorjs/emulatorjs#179]
Just a heads up, it appears that the mame .data files are misnamed causing a Network Error when loading mame cores.

They are currently named like:
`/mame-1-old-wasm.data`

The file is actually being requested at:
`/mame-old-1-wasm.data`

**Comment by ethanaobrien** [comment]
Thank you, I should be able to fix tomorrow

**Comment by ethanaobrien** [comment]
@cheesykyle Sorry Ive been really busy.
I saw you fixed this in a clone of the repository. Can you open a pull request and I can just merge that?

**Comment by cheesykyle** [comment]
Done

**Comment by ethanaobrien** [comment]
Thank you
