### ISSUE TITLE
Catching (?) Save States for uploading

### ISSUE THREAD

**Issue by Ramaerel** [emulatorjs/emulatorjs#181]
I could just be being dumb again and not able to see it after skimming through the code, but I'm aiming to be upload the savestates kept in browser to my server. As I've said I've skimmed through the code but I'm not great at JS. I'd also like to be able to save state/upload it in a beforeUpload event listener, so having easy access to a function for the save state (and/or documented) and how one would grab the save state (although I should be able to figure this one out myself)

That was a mess of a paragraph so if you need me to clarify at all, please ask. This would be a much appreciated feature 🙂

**Comment by ethanaobrien** [comment]
This wouldnt be too hard to do. Im pretty sure someones asked me about this before, heres a possible solution.

set `EJS_onSaveState` (on page load) to the function you want to be called when state is saved (it will call with one argument containing a screenshot and the save state. This will prevent the default save state function

set `EJS_onLoadState` (also on page load) to the function you want to call when the load state function is pressed. With this function you can fetch the file and (make sure you turn it into a `Uint8Array`) Call the function `EJS_loadState` with the argument containing the save state data

Let me know if you have any questions, Im not too got at explaining things either

**Comment by Ramaerel** [comment]
Thank you, I think I got it 🙂
The onlynother question I have in regards to this is forcing a savestate on beforeUnload, so calling the savestate function?

**Comment by ethanaobrien** [comment]
the function `window._0x378b5c.saveState` will return a uint8array of the save state data. There is not really a way to call teh same save state button unless the user clicks it

**Comment by ethanaobrien** [comment]
@Ramaerel Is there anything else you need?

**Comment by Ramaerel** [comment]
I think I'm okay. Still haven't got it working properly but that's just me learning and being bad at it 😅

**Comment by ethanaobrien** [comment]
Is there anything specific you need help on?

**Comment by Ramaerel** [comment]
@ethanaobrien I didn't see your response, sorry. But yes, after a month of trying to figure it out, I need assistance still sorry.
So I have successfully (?) saved both the savestate and screenshot to the server, I'm now having trouble loading it. The data seems to be loading correctly, but it doesn't seem to be loading. I'm clearly doing something wrong and I lack the skills to figure it out. The code for loading is as follows, outside of the URL's being taken out: 

Edit: Added my save code and what my console is printing the save data as, since it's saving and reading 2 different sizes.

Code:
  ```
EJS_onSaveState = function(save) { 
                        console.log("Saving data...");
                        console.log(save);
                        var nsavestate = new TextDecoder().decode(save["state"]);
                        var nscreenshot = new TextDecoder().decode(save["screenshot"]);
                        jQuery.post("./upsave.php", {screenshot: nscreenshot, savedata: nsavestate, uid: "*UserID", gid: "*GameID" });
}

EJS_onLoadState = function() {
                          console.log("Loading data...");
                          let save = {state:"", screenshot:""};
                          fetch(*Savestate URL*).then(res => res.arrayBuffer()).then(arrayBuffer=> {
                              save["state"] = new Uint8Array(arrayBuffer);
                          });
  
                          fetch(*Screenshot URL*).then(res => res.arrayBuffer()).then(arrayBuffer=> {
                              save["screenshot"] = new Uint8Array(arrayBuffer);
                          });
  
  
                          EJS_loadState(save);
                          console.log(save);
                          
  
}
```

Log:
```
Saving data...

{screenshot: Uint8Array(3001), state: Uint8Array(26678)}

screenshot: Uint8Array(3001) [137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 160, 0, 0, 0, 144, 8, 2, 0, 0, 0, 0, 215, 247, 215, 0, 0, 11, 128, 73, 68, 65, 84, 120, 218, 237, 93, 107, 110, 28, 55, 12, 30, 187, 219, 3, 38, 6, 2, 52, 1, 122, 184, 2, 73, 129, 2, 78, 14, 147, 2, 233, 93, 250, 163, 165, 205, 53, 77, 235, 77, 74, 212, 74, 19, 18, 27, 99, 173, 200, 146, 190, 145, 196, 151, 56, 212, 113, 56, 157, 154, 238, …]

state: Uint8Array(26678) [0, 1, 0, 0, 0, 99, 99, 0, 0, 0, 4, 0, 0, 191, 144, 112, 99, 0, 0, 0, 2, 0, 64, 115, 112, 0, 0, 0, 2, 255, 248, 97, 0, 0, 0, 1, 0, 98, 0, 0, 0, 1, 0, 99, 0, 0, 0, 1, 0, 100, 0, 0, 0, 1, 192, 101, 0, 0, 0, 1, 16, 102, 0, 0, 0, 1, 128, 104, 0, 0, 0, 1, 101, 108, 0, 0, 0, 1, 19, 115, 107, 105, 112, 0, 0, 0, 1, 0, 104, 97, 108, 116, 0, 0, 0, 1, 0, 118, 114, 97, …]

[[Prototype]]: Object

play.php?id=88:81 Loading data...

play.php?id=88:93 

{}

screenshot: Uint8Array(3943) [239, 191, 189, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 239, 191, 189, 0, 0, 0, 239, 191, 189, 8, 2, 0, 0, 0, 0, 239, 191, 189, 239, 191, 189, 239, 191, 189, 0, 0, 8, 81, 73, 68, 65, 84, 120, 239, 191, 189, 239, 191, 189, 93, 221, 142, 239, 191, 189, 38, 16, 239, 191, 189, 239, 191, 189, 239, 191, 189, 125, 239, 191, 189, 100, 239, 191, 189, 239, 191, 189, 68, 239, 191, 189, 239, 191, 189, 85, 74, 42, 85, 239, …]

state: Uint8Array(29189) [0, 1, 0, 0, 0, 99, 99, 0, 0, 0, 4, 0, 0, 239, 191, 189, 72, 112, 99, 0, 0, 0, 2, 0, 64, 115, 112, 0, 0, 0, 2, 239, 191, 189, 239, 191, 189, 97, 0, 0, 0, 1, 0, 98, 0, 0, 0, 1, 15, 99, 0, 0, 0, 1, 0, 100, 0, 0, 0, 1, 239, 191, 189, 101, 0, 0, 0, 1, 16, 102, 0, 0, 0, 1, 239, 191, 189, 104, 0, 0, 0, 1, 97, 108, 0, 0, 0, 1, 42, 115, 107, 105, 112, 0, 0, 0, 1, 0, 104, 97, …]

[[Prototype]]: Object
```

**Comment by ethanaobrien** [comment]
It looks like the php isnt writing the file. Youve tried debugging this right?

**Comment by ethanaobrien** [comment]
I am assuming you got this working, if not, comment and I will re-open
