### ISSUE TITLE
Question: How can I get arcade to auto-detect and load?

### ISSUE THREAD

**Issue by MikeCedonis** [emulatorjs/emulatorjs#182]
I've tried adding the line "Arcade": "arcade", to index.html for the demo and the option to choose arcade shows up on the auto-detect list but the rom (1941.zip) doesn't play after downloading. The rim loads just fine if I do it this way https://github.com/ethanaobrien/emulatorjs/blob/main/docs/Arcade.md

**Comment by ethanaobrien** [comment]
I auto-detect based on the extension. `zip` files can be used by any emulator core and it isnt very fast or efficient to unzip it just to get the name of the file. If you want to do this I would recommend looking into [JSZip](https://stuk.github.io/jszip/). Im not going to do this but you can!

**Comment by MikeCedonis** [comment]
I think there's a misunderstanding.
![Screenshot_20220326-125152_Root Explorer~3](https://user-images.githubusercontent.com/45634750/160249725-c3bb71b3-9bf0-445d-aef0-a7d4ea578142.jpg)
![Screenshot_20220326-125310_Chrome](https://user-images.githubusercontent.com/45634750/160249729-987b6f95-0c6d-479e-8bb0-8e2427040f2b.jpg)
If I add a Core to the list in index.html and select it, it should load and run no problems or do i need to edit anything else aside from the index file?

**Comment by ethanaobrien** [comment]
nope, the auto-detection code is from line [58](https://github.com/ethanaobrien/emulatorjs/blob/main/index.html#L58) to line [70](https://github.com/ethanaobrien/emulatorjs/blob/main/index.html#L70)

**Comment by MikeCedonis** [comment]
Sorry, my daughter jumped on me and closed this...

**Comment by ethanaobrien** [comment]
Its ok, I get it

**Comment by MikeCedonis** [comment]
Ok, what I tried to do was add the arcade core as an option like how
 "PlayStation": "psx"
was in the list and I thought it would work was hoping you could point me in the right direction. 
Or is that because the pax files aren't zipped?

**Comment by ethanaobrien** [comment]
All that does it make it to where if the extension is not defined per a specific system, then that is used to display it in the select core list. The list has nothing to do with auto-detecting the core, its all the code right before that that auto-detects it

**Comment by MikeCedonis** [comment]
I'll figure this out when I have time.
