### ISSUE TITLE
Cheats

### ISSUE THREAD

**Issue by drewlobel** [emulatorjs/emulatorjs#188]
When I put in a cheat it does not disable, even when I uncheck them Thx!

**Comment by ethanaobrien** [comment]
What does this mean, can you explain?

**Comment by drewlobel** [comment]
In the cheats option, I used a cheat that makes all pokemon shiny. Well when I turn it off all pokemon still remain shiny. I have tried clearing cookies and all.

**Comment by ethanaobrien** [comment]
Well clearing the cookies isnt going to do anything unless you refresh the page. I cant guarantee that theres anything I can do but ill look

**Comment by drewlobel** [comment]
I did reload the page.
I think there is some data stored in the .state file that causes this to happen.

**Comment by ethanaobrien** [comment]
When you click the cheats button does it still show the cheat there?

**Comment by drewlobel** [comment]
No

**Comment by ethanaobrien** [comment]
which system are you using?

**Comment by drewlobel** [comment]
NDS

**Comment by ethanaobrien** [comment]
This is possibly a problem with retroarch, can you try the beta core, I may need to convert melonds to work

**Comment by drewlobel** [comment]
How do I get to the beta core?

**Comment by ethanaobrien** [comment]
add the line `EJS_BETA = true;`

**Comment by drewlobel** [comment]
where?

**Comment by ethanaobrien** [comment]
into your html code.

**Comment by drewlobel** [comment]
using inspect?

If so I cannot now.

**Comment by ethanaobrien** [comment]
no using the raw html code are you not hosting it? theres nothing I can do if youre using the demo

**Comment by drewlobel** [comment]
Im using the demo I think.

https://ethanaobrien.github.io/emulatorjs/

**Comment by drewlobel** [comment]
Let me make my own hold on

**Comment by drewlobel** [comment]
Ok I did it. do I need to put it in as a script or something? 
or just copy and paste it anywere?

**Comment by ethanaobrien** [comment]
read the readme, I'm not walking you through this

**Comment by drewlobel** [comment]
All it says is add to code
Which code?

**Comment by ethanaobrien** [comment]
Here because its soooo hard
```
<div style='width:640px;height:480px;max-width:100%'>
    <div id='game'></div>
</div>

<script type='text/javascript'>

    EJS_player = '#game';
    EJS_core = 'nds';

    // URL to Game rom
     
    EJS_gameUrl = '';
    
    /*
     *  Path to the WASM / JS files
     *  HAS TO BE in the same directory.
     */
    
    EJS_pathtodata = 'data/';
    EJS_BETA = true;
</script>

<script src='data/loader.js'></script>
```

**Comment by drewlobel** [comment]
To the html?
It would be great if you said to do this WHERE YOU TOLD ME TO LOOK
you say add to code. Which one?
You're so vague

**Comment by ethanaobrien** [comment]
Dude I said to look in the readme, act grown up and mature and actually look in the files It took hours to write to walk people through like you. Ill figure this out later dont bother

**Comment by ethanaobrien** [comment]
I have not been able to reproduce this issue
