### ISSUE TITLE
Is there a way to make it save on your browser?

### ISSUE THREAD

**Issue by EmulatorOS** [emulatorjs/emulatorjs#193]

**Comment by ethanaobrien** [comment]
Yes, you can change this feature in settings (the button in the bottom right corner)

**Comment by EmulatorOS** [comment]
Thanks

**Comment by EmulatorOS** [comment]
I have another question, Ive seen other people using netplay. How do I activate it to super smash bros in the n64

**Comment by ethanaobrien** [comment]
You can read the netplay instructions in the readme
