### ISSUE TITLE
Screen orientation for mobile device

### ISSUE THREAD

**Issue by duanyu5871** [emulatorjs/emulatorjs#195]
Can screen be locked to landscape for mobile device without change device settings, especially when fullscreen ? It is not convient to turn on and off auto-orientation again and agin in my phone settings. For now, I can rotate screen with css style transform, but it won't work when fullscreen . I think the function can be added into auto script or add in menu for user.

**Comment by Ramaerel** [comment]
Hi, 

Locking the screen orientation in landscape mode should be easy. I haven't tested this myself yet but according to this page (https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation/lock), something similar to this in your Web page would work.

<script type="text/javascript">
    ScreenOrientation.lock("landscape");
</script>

I'll fix formatting and test it when I can get to my computer

**Comment by ethanaobrien** [comment]
Thanks, I'll look into this

**Comment by duanyu5871** [comment]
> 
Thanks
I have tired this script before, but this script seems to only work when screen is already fullscreen. I have no idea about emulatorjs fullscreen function. My solution is to create a self-built buttun to hundle landscape fullscreen problem, it does not work in ios.

**Comment by ethanaobrien** [comment]
done
