### ISSUE TITLE
beta volume slider issues

### ISSUE THREAD

**Issue by Ramaerel** [emulatorjs/emulatorjs#196]
The NDS beta core seems to have issues with the volume slider- It doesn't seem to move at all

**Comment by ethanaobrien** [comment]
This is probably a problem with the emulator UI itself. What OS are you using? are you on mobile? Does it work on the normal core?

**Comment by Ramaerel** [comment]
It works fine on mobile, and on the normal cores. The issue only seems to be on PC, across all browsers and specifically on the beta core.

**Comment by ethanaobrien** [comment]
This is really really strange. Is there anything in the console? When you click the volume slider and use the arrow keys does it move?

**Comment by Ramaerel** [comment]
Nothing in the console, and the arrow keys do nothing either. The circle highlights when it's selected, but it doesn't move. All the other buttons work fine, though. Could it have something to do with the emulator grabbing the mouse?

**Comment by ethanaobrien** [comment]
No I dont think so. It doesnt grab the mouse when you try to slide it does it? This is possibly because its preventing the function from running I think I will be able to look at this tomorrow or Wednesday

**Comment by Ramaerel** [comment]
Sounds good, let me know if you need anything else from me

**Comment by ethanaobrien** [comment]
This seems to be for all beta cores - likely something in the webassembly itself

**Comment by ethanaobrien** [comment]
@allancoding When working on the beta cores, could you look for a mouse event that may be stopping this from working?

**Comment by ethanaobrien** [comment]
Fixed!
