### ISSUE TITLE
Visible "X"

### ISSUE THREAD

**Issue by goddard41** [EmulatorJS/EmulatorJS#2]
Hi,

I added your codes to my page and it works great without ad. But after loading screen, close button of ad is still visible. I checked your example page, but it doesn't appear. How can I solve it?

![image](https://user-images.githubusercontent.com/86106111/122547008-420fa680-d038-11eb-838a-66db388e0928.png)

**Comment by ethanaobrien** [comment]
@goddard41 That seems to happen sometimes, but I can't find a pattern. I need to try to find where the x is formed. Does this repeatedly happen or did it only occur once. (If it was a one time thing, leave this open, I would like to make it a no time thing)
It is better than having an actual ad there (As it slows the webpage down)

**Comment by goddard41** [comment]
It appears everytime when i start a game. But as you said, it's better to see just an X than seen an ad everytime. Thanks for your reply..

**Comment by ethanaobrien** [comment]
@goddard41 Can you download the latest version and notify me of the results. I have attempted to completely remove the ad I frame

**Comment by goddard41** [comment]
Hi @ethanaobrien, I tried it but "X" is still there..

**Comment by ethanaobrien** [comment]
@goddard41 Could you right click the game screen and tell me what version of emulatorjs you are on?

**Comment by ethanaobrien** [comment]
@goddard41 Will you please update and check if it is still there? I have fixed this to my understanding. I will close this is 3 days if there is no response saying it is still showing the `x`.

If it still shows the `x` please tell me what version of emulatorjs you are on. Right click (on the game, once it is loaded) and it will be the bottom button.

**Comment by ethanaobrien** [comment]
Tell me if problem persists (when using the latest version of this code!)
