### ISSUE TITLE
Google indexing

### ISSUE THREAD

**Issue by ildomandatore** [emulatorjs/emulatorjs#200]
I have officially opened the website for more than 4 months, and I have an SEO score of +70, and I have been trying to solve technical problems.

But I still have no traffic today, despite a good site with good text. I don't expect a miracle, but 0 traffic through Google is weird. I have asked for help from many places, but I have not solved it.

Do you have traffic using this project?

**Comment by Ramaerel** [comment]
Just a heads up that this is probably not the place for this as its not related to the project itself.

As an (rather poor) attempt to give you assistance regardless, I'd suggest you add more to your website outside of just this with games if you haven't already. More content will get more traffic flowing through. If paying for advertising is an option, that'd also help a lot. Once you have some traffic flowing through, it'll slowly build through word of mouth

**Comment by ildomandatore** [comment]
I was simply wondering if other users using this project have trouble ranking pages. I have created 4 game pages and 21 pages in the sitemap.

I try to understand where the ranking problems come from because they don't seem to depend on my articles. 

If others are in the same situation as me, it becomes a problem for the project.

**Comment by ethanaobrien** [comment]
Thats really strange. Ive attached a screenshot with the view count over the past few weeks and there are days where it dips but it doesnt ever get to 0. I dont really know what to say.
![Screenshot 2022-04-10 12 10 28 PM](https://user-images.githubusercontent.com/77750390/162631194-5fbd78b9-af7f-4ee4-8c68-ca344c3caafe.png)

**Comment by ildomandatore** [comment]
ok
