### ISSUE TITLE
Missing L2 and R2 buttons on PlayStation.

### ISSUE THREAD

**Issue by LightningBlox** [emulatorjs/emulatorjs#201]
There are no L2 and R2 buttons on the PlayStation emulator.

**Comment by ethanaobrien** [comment]
@LightningBlox
Can you assert that none of the other buttons function as the L2 and R2 buttons should?

**Comment by ethanaobrien** [comment]
@LightningBlox I can’t do anything without the requested information. If the information is not supplied within 48 hours then this issue will be closed

**Comment by ethanaobrien** [comment]
It’s been a bit more than 48 hours
