### ISSUE TITLE
Adjust for mobile phone

### ISSUE THREAD

**Issue by ghost** [emulatorjs/emulatorjs#202]
![Screenshot_2022-04-14-11-23-55-729_org mozilla fenix](https://user-images.githubusercontent.com/32984303/163307597-52cf177c-44d4-45d3-bfdc-9d19d5877d51.png)
I hope you can adjust this for mobile,the icon and screen shows on mobile browser are too small.

**Comment by ethanaobrien** [comment]
Theres nothing I can do to adjust it. It doesnt even look like a game is running in your screenshot

**Comment by ghost** [comment]
> Theres nothing I can do to adjust it. It doesnt even look like a game is running in your screenshot

@ethanaobrien Well, I think you need to make both the bottom and the screen adjustable according to the size of the browser screen,see screenshot, don't you think the bottom and the screen are too small to use?
![图片](https://user-images.githubusercontent.com/32984303/164426513-03d42a06-3fba-442b-a785-27f5942bf214.png)
