### ISSUE TITLE
How do u add this into google sites 

### ISSUE THREAD

**Issue by Darandomcoda** [emulatorjs/emulatorjs#203]
I have tried to import it into google sites but when I import a rom it just shows the background and no game?

**Comment by allancoding** [comment]
You could embed my emulatorjs-maker! https://github.com/allancoding/emulatorjs-maker
But you can't host files in google sites which makes it impossible to host emulatorjs on google sites.

**Comment by allancoding** [comment]
Or you could use the code creator here: https://emulatorjs.ga/codehelper
And use these options: 
![image](https://user-images.githubusercontent.com/74841470/163626137-ac51bb90-e232-47b5-9418-5d46908f957c.png)
then copy the html output file in to google sites.

**Comment by ethanaobrien** [comment]
@allancoding Google sites doesnt support custom html

**Comment by allancoding** [comment]
@ethanaobrien 
You can you just put the custom html in the embed code as I did here: https://sites.google.com/view/emulatorjs/games/snes/secret-of-mana-v2
I used the code creator.

**Comment by Darandomcoda** [comment]
I dont see the html

**Comment by ethanaobrien** [comment]
@allancoding How do you host the files then? I'd like to know because I've tried to do something like that but never been able to do so.

**Comment by allancoding** [comment]
Ok so on this page: https://sites.google.com/view/emulatorjs/games/snes/secret-of-mana
I just embed my emulatorjs maker. With the embed page button and then the url filed.
(So the other tab in the picture)
![image](https://user-images.githubusercontent.com/74841470/165554411-b5a1c748-2757-4e5a-a0ff-a2c25c756524.png)
But on this one: https://sites.google.com/view/emulatorjs/games/snes/secret-of-mana-v2
I use the custom embed code and I pasted the code creator html file.

**Comment by allancoding** [comment]
Depending on the size of the rom 2 or more mega bites you may have to host the rom on a different server like drive to web then you would just specify the url of the rom [https://www.drv.tw/](https://www.drv.tw/) .

**Comment by Darandomcoda** [comment]
it says the google aw snap all the time

**Comment by Darandomcoda** [comment]
"We were unable to discover any public HTML page in your cloud drive account to show. Please upload some and share them so everyone can view. Reload this page when you have done so."

What does this mean

**Comment by allancoding** [comment]
What gave you that error? Screenshot?
