### ISSUE TITLE
Mame Core files

### ISSUE THREAD

**Issue by EmulatorOS** [emulatorjs/emulatorjs#209]
What are the mame cores and how do i know if my from works with that core?

**Comment by ethanaobrien** [comment]
I dont know exactly, just go through and find what number (1-6) works.

**Comment by EmulatorOS** [comment]
ok

**Comment by EmulatorOS** [comment]
what does it mean when it says save states supported

**Comment by ethanaobrien** [comment]
some games do not support save states
