### ISSUE TITLE
I really need a way to "Re-instantiate the class" without reloading the page. Any Ideas?

### ISSUE THREAD

**Issue by iamjaime** [emulatorjs/emulatorjs#21]
I've been reading through the loader script and i'm trying to re-init the class

so far i've got this, however it doesn't work 100% as expected.

container id: #gamecontainer

new EJS("#gamecontainer", { 
	biosUrl: '',
	core: 'arcade',
	gameUrl: 'mygamehere.zip',
	pathtodata: 'data/path/here',
	lightgun: false
})

Any ideas? I think the loader js file contains this logic but i'm having trouble decoding it. Any help would be appreciated.

**Comment by ethanaobrien** [comment]
see the `data/emulator.js` file. I recently decoded it and it is mostly readable. I am still working on making it all readable

**Comment by iamjaime** [comment]
nice job with the decoding! i'm going to see if i can swap my emulator file to this one and then hopefully i can figure out the way of doing a new Instance of this class

**Comment by ethanaobrien** [comment]
@iamjaime 

  search for `style` in the `emulator.js` file. This should pull up where the style changes!

**Comment by iamjaime** [comment]
got it, thanks
