### ISSUE TITLE
virtual gamepad layout

### ISSUE THREAD

**Issue by shay16596** [emulatorjs/emulatorjs#211]
Is there any other layout or design for virtual gamepad on mobile devices? if it is not, please add new virtual gamepad style which is more comfortable to use

**Comment by ethanaobrien** [comment]
"more comfortable" is relative. Theres nothing I can really change to make it "more comfortable" You can do this one

**Comment by shay16596** [comment]
Indeed more comfortable is relative.And it's already comfortable and standard. I mean if we had selection for D-pad style in addition to current analog style it could be even better.
