### ISSUE TITLE
EJS_onGameStart documentation / hook for when rom is loaded

### ISSUE THREAD

**Issue by d3st1nyh4x** [emulatorjs/emulatorjs#213]
```
emu-main.js?v=1.2:6534 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'container')
    at _0x6954aa.value (emu-main.js?v=1.2:6534:52)
    at loader.js:69:59
```

Just trying to get some code set up to enable some stuff when the game is loaded.

Mainly, I'm implementing a twitch plays with this and want to enable the controls for a chat after the game loads. Though I can work around it, I wanted to know if this is just not working or is it something i can use?
```

  EJS_onGameStart =  () => {
      console.log("game started?")
  }
```

Also, big fan of this project. Love to see it still going.

**Comment by ethanaobrien** [comment]
Ive never actually tested the `EJS_onGameStart` function (although I assume it works) I do think its possible. Is it not working for you. 

also see this: https://github.com/ethanaobrien/emulatorjs/blob/8acc4ba939b472f0730c872c0b680916502444c5/data/loader.js#L69

**Comment by ethanaobrien** [comment]
Fixed
