### ISSUE TITLE
I dont know how to use it.

### ISSUE THREAD

**Issue by Poopyhead1231231** [emulatorjs/emulatorjs#216]
So can you just drop the roms in from the index.html? or do you have to put it on a website. Whenever I load it says Network error. Sorry if this is a stupid question lol.

**Comment by sDetective** [comment]
oh that happened to me a few times i think its what it says a network error try next day or if you have the option which i don't think is likely theres the option for cache games if not try other roms

**Comment by ethanaobrien** [comment]
Include a log of the console and maybe I can do something

**Comment by Poopyhead1231231** [comment]
![image](https://user-images.githubusercontent.com/75390951/166562805-c822bec9-1667-4825-b2c2-5daf35878f2c.png)
![Screenshot 2022-05-03 1 44 24 PM](https://user-images.githubusercontent.com/75390951/166562855-c90f8a59-cbdc-4025-9f3e-d418e96440ab.png)

**Comment by ethanaobrien** [comment]
A log of the console is not the same a screenshot. Google it if you do not know how

**Comment by Poopyhead1231231** [comment]
The inspect console?

**Comment by ethanaobrien** [comment]
yes, the inspect console

**Comment by Poopyhead1231231** [comment]
![image](https://user-images.githubusercontent.com/75390951/166588667-b17767ea-0f99-46b4-a8b8-5889653808da.png)

**Comment by ethanaobrien** [comment]
Dude you need to host it on a server. Look it up. google it. Read the readme! I have written everything you need to know you just need to look for it!
