### ISSUE TITLE
Ability to change disk (playstation)

### ISSUE THREAD

**Issue by sDetective** [emulatorjs/emulatorjs#217]
I was thinking that for the playstation roms there could be a disc changer as a option like a load state but discs

**Comment by ethanaobrien** [comment]
This is called reloading the page? Like wdym. provide detail and maybe ill re-open

**Comment by Ramaerel** [comment]
I think he means to change from disc 1 to disc 2 in a game. I think simply creating a download save at the disc swap scene, and then loading the save after loading the disc 2 iso will work

**Comment by dosboxonline** [comment]
It works, but not for all games. Metal Gear Solid and Heart of Darkness - these games require open/close cd tray (I/0 cd tray dip switch).

**Comment by ethanaobrien** [comment]
This would be complicated

**Comment by ethanaobrien** [comment]
Just realized, this is a duplicate of #143
