### ISSUE TITLE
More options in config

### ISSUE THREAD

**Issue by Bastard007** [emulatorjs/emulatorjs#218]
Is it possible to add more options in the configuration: for example, enable / disable the use of cheat codes (EJS_cheats), screen recording?

P.S. sorry for my bad english

**Comment by ethanaobrien** [comment]
Are you asking for a feature to disable certain buttons?

**Comment by Bastard007** [comment]
> Are you asking for a feature to disable certain buttons?

Yes, I'd like to enable/disable buttons in the config

For example: if **EJS_cheats = false**; then the "cheat" button is not shown

**Comment by ethanaobrien** [comment]
Ok, this would be pretty easy

**Comment by ethanaobrien** [comment]
```
EJS_Buttons = {
    playPause: false,
    restart: false,
    mute: false,
    settings: false,
    fullscreen: false,
    saveState: false,
    loadState: false,
    screenRecord: false,
    gamepad: false,
    cheat: false,
    volume: false,
    quickSave: false,
    quickLoad: false,
    screenshot: false,
    cacheManage: false
}
```
