### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by Bastard007** [emulatorjs/emulatorjs#219]
After the last update, when loading the ROM, a CORS Error appears.
Debug enabled, no errors in console
https://skr.sh/sDn91uy5Lmh

P.S. Sorry for my bad english

**Comment by ethanaobrien** [comment]
Please go to the network tab and find the request made to fetch the rom. Click it and send me a screenshot of the headers. If its throwing a cors error I'm not sure how it was working before

**Comment by Bastard007** [comment]
> Please go to the network tab and find the request made to fetch the rom. Click it and send me a screenshot of the headers. If its throwing a cors error I'm not sure how it was working before

You can see for yourself - http://nes.inter-corp.ru/

everything worked in the previous release, the error appeared after today's update.

P.S. I also found a few more errors, can I describe them here?

**Comment by ethanaobrien** [comment]
I'll take a look when I get a chance.

> I also found a few more errors, can I describe them here?

Go ahead

**Comment by Bastard007** [comment]
> Go ahead

1 - Sega Master System games not working (black screen)
2 - Nintendo Entertainment System: There are no turbo buttons configured in the joystick button settings (there are only A and B)
3 - If you press Esc while assigning buttons -  error appears in the console
`Uncaught TypeError: "" is not a function at HTMLBodyElement.<anonymous> (emu-main.js?v=1.2:3419:33)`

**Comment by ethanaobrien** [comment]
>Sega Master System games not working (black screen)

This should be resolved by the beta. I'm still working on this

>Nintendo Entertainment System: There are no turbo buttons configured in the joystick button settings (there are only A and B)

There are no turbo buttons on the actual system. Is there an option in the settings for them?

>If you press Esc while assigning buttons - error appears in the console

Ill get this fixed, thanks

**Comment by Bastard007** [comment]
> There are no turbo buttons on the actual system. Is there an option in the settings for them?

Turbo buttons work, they just cannot be reassigned, the fields are hidden.

I fix this problem in emu-main.js (line 2775 - 2787 )
```
 if ('nes' === _0xa88a13.system) {
                    var _0x48ee51 = {
                        0: 'B',
                        **1: 'Y',** <-- added
                        2: 'SELECT',
                        3: 'START',
                        4: 'UP',
                        5: 'DOWN',
                        6: 'LEFT',
                        7: 'RIGHT',
                        8: 'A',
                        **9: 'X',** <-- added
                        24: _0xa88a13.localization('QUICK SAVE STATE'),
                        25: _0xa88a13.localization('QUICK LOAD STATE'),
                        26: _0xa88a13.localization('CHANGE STATE SLOT')
                    }
```
P.S> sorry for my bad english )

**Comment by ethanaobrien** [comment]
Oh, thank you. I will add this. Is Y just turbo for A or B? I think I should label them as turbo A and turbo B

>P.S> sorry for my bad english )

Its all good its really good not as bad as some I've read really not bad at all

**Comment by Bastard007** [comment]
> I think I should label them as turbo A and turbo B

Yes. Turbo A and Turbo B.


I propose to make buttons by analogy with NES for other consoles. For example, Atari doesn't have that many buttons
https://skr.sh/sDnogfUI9OL

**Comment by ethanaobrien** [comment]
Yeah, would you mind doing that and making a pr?

**Comment by Bastard007** [comment]
> Yeah, would you mind doing that and making a pr?

Yes, I will show the code when I add it. Thanks

**Comment by ethanaobrien** [comment]
Im going to go ahead and close this. I fixed it (it was a problem with the `blob:` protocol)

**Comment by allancoding** [comment]
Hay @ethanaobrien you should update the emulator-button blob protocol because it is throwing that same error.

**Comment by ethanaobrien** [comment]
I did, it might need to cache the new files on your device
