### ISSUE TITLE
GBA game doesnt work

### ISSUE THREAD

**Issue by EmulatorOS** [emulatorjs/emulatorjs#220]
The file is loaded but all I see is a black screen. For some reason, if I use inspect element the game loads

**Comment by EmulatorOS** [comment]
The link is https://emulatoros.github.io/mktournament.html and it happens to all the gba games
This happened once I updated the files

**Comment by ethanaobrien** [comment]
How recently did you update the files?

**Comment by EmulatorOS** [comment]
Like 2 hours ago

**Comment by EmulatorOS** [comment]
I just restored them to the old files

**Comment by EmulatorOS** [comment]
does this work on ur end?

**Comment by ethanaobrien** [comment]
It gives me a `cors error` message which I thought I fixed earlier today. Could you share with me a zip of your site because if its happening for you its probably happening for someone else.

**Comment by EmulatorOS** [comment]
Lemme try and update the files again and if it doesnt work ill give u the zip

**Comment by EmulatorOS** [comment]
Heres a download link since i cant upload large files
https://filetransfer.io/data-package/i5zWHu6b#link
Heres the repo link https://github.com/EmulatorOS/EmulatorOS.github.io

**Comment by EmulatorOS** [comment]
can i return to the old files now?

**Comment by EmulatorOS** [comment]
It worked now

**Comment by ethanaobrien** [comment]
@EmulatorOS Sorry for the late response. Is it working with the old files or did the new ones start working?

**Comment by ethanaobrien** [comment]
I just check with the links you sent me, they all load for me

I also just pushed fixes for some of these problems

**Comment by ethanaobrien** [comment]
Im assuming this is resolved. Comment if it is not
