### ISSUE TITLE
Option to scale emulator to window size

### ISSUE THREAD

**Issue by Ramaerel** [emulatorjs/emulatorjs#224]
An option to stretch the screen to whatever the current window size is would be good. Not really sure how I could clarify on this more, but yeah basically an option to stretch the aspect ratio to the full size of the window instead of having it locked

**Comment by ethanaobrien** [comment]
I dont think I can do this. The aspect ratio is locked within the webassembly and why in the first place would you want everything stretched out?

**Comment by Ramaerel** [comment]
I prefer it, honestly. But it's not a deal breaker, and if it can't be done it can't be done 😅 Thabk you anyway

**Comment by Vimm2** [comment]
Works on modern browsers:
```
<div style="margin: auto; aspect-ratio: 4 / 3">
    <div id="game"></div>
</div>
```

**Comment by Ramaerel** [comment]
Much closer to what I'm looking for, thank you. I'm going to stick to the assumption that it's probably impossible to get  exactly what I'm looking for, but this helps a lot

**Comment by ethanaobrien** [comment]
Yeah, I think thats the closest your going to get. Most of the sizing is changed as shown by @Vimm2 

@Ramaerel Can I close this?

**Comment by Ramaerel** [comment]
Yeah, it's all sorted

**Comment by ethanaobrien** [comment]
Awesome, sorry that there isnt a way to change it in the actual code
