### ISSUE TITLE
Add new Layouts for Virtual Gamepad (Arcade)

### ISSUE THREAD

**Issue by sfz3mix** [emulatorjs/emulatorjs#225]
Please,

Add different layouts to make it feasible to play Arcade games.
Playing Street Fighter on the default Virtual Gamepad is quite complicated, a 6-button layout together would help a lot!

If you could upload a layout file via url it would be ideal because let everyone make their own.

Thanks

**Comment by sfz3mix** [comment]
[](url)

**Comment by ethanaobrien** [comment]
>If you could upload a layout file via url it would be ideal because let everyone make their own.

I actually really like this idea

**Comment by ethanaobrien** [comment]
Now available through [`EJS_VirtualGamepadSettings`](https://emulatorjs.netlify.app/docs/Virutal%20Gamepad%20Settings.html)
