### ISSUE TITLE
No login option for server side saves

### ISSUE THREAD

**Issue by MonotoneCulprit** [emulatorjs/emulatorjs#226]
Set up emulatorjs via the docker container. Added some test profiles, but not seeing the login option to use them.

**Comment by Ramaerel** [comment]
I think you're looking for this repo: https://github.com/linuxserver/docker-emulatorjs
Worked on by a different group of people, I believe

**Comment by ethanaobrien** [comment]
That is correct, everything in this repository is client-side. The docker repository is as mentioned above
