### ISSUE TITLE
How do I change the text color in Game Settings?

### ISSUE THREAD

**Issue by ildomandatore** [emulatorjs/emulatorjs#227]
I try to change the color of the text, but having an important rule, I can't impose the new color. How do I resolve?

```
.ejs--5e71fd80268afbb1d588e40b993508 * {
    color: #bcbcbc !important;
    border: unset;
}
```
https://imgur.com/a/Scs6L8b

**Comment by ethanaobrien** [comment]
`EJS_color = 'hex color code'` example: `#c41818`

**Comment by ildomandatore** [comment]
Not what I was looking for. I can't change the color of the texts, because they have an important rule.

I tried to change the text size to 24px, but the lower Update and Cancel buttons go out of the box. You see the top of the button. I will try to do further experiments, but at the moment I have not found any solutions.

There are elements with Div and classless labels. I don't know how to select the affected items.

https://imgur.com/a/mHLQ0HJ

**Comment by ethanaobrien** [comment]
Im pretty sure those boxes have a set size, the text is just like an overlay I'm pretty sure.

**Comment by ethanaobrien** [comment]
@ildomandatore Would #239 make this easier to change?

**Comment by ethanaobrien** [comment]
I haven’t heard anything back, I’m assuming that separating the styling into a different file made this manageable. Let me know if you have any questions
