### ISSUE TITLE
Where are the saves stored?

### ISSUE THREAD

**Issue by the-lazy-fox** [emulatorjs/emulatorjs#228]
Hi there,

Looking in the files all over but can't find where are my saves made in each games to back them up. I would like to delete some of them and backup some others.
Could you please help to find them?

In addition, I want to share this with friend, can you please confirm that the saves are strongly linked with the connected profile?

Thank you!

**Comment by Ramaerel** [comment]
Hi, I believe you might be on the wrong EmulatorJS for this issue. This one would only have the features you've mentioned if you added them yourself. Try this repo: https://github.com/linuxserver/docker-emulatorjs

**Comment by ethanaobrien** [comment]
This is correct. Wrong repository
