### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by lyarinet** [emulatorjs/emulatorjs#230]
netplay create room
and its  show error

![image](https://user-images.githubusercontent.com/19821/167396153-0d780e97-19a4-46de-a399-500d0993c9ad.png)

**Comment by ethanaobrien** [comment]
This might actually be a bug (maybe), can you click on one of the requests and send a screenshot of the request information (the headers and things like that). Also, are you using the default server of are you hosting using the emuserver?

**Comment by lyarinet** [comment]
yes im useing emuserver

**Comment by ethanaobrien** [comment]
Can you answer my other question so I can actually help you

**Comment by BroJac5246** [comment]
I got a CORS error while running emulatorjs locally, as local files use the file:// protocol.

The console said:
`Access to XMLHttpRequest at 'file:///media/archive/emulatorjs-main.zip/emulatorjs-main/data/v.json?t=1652140606' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.`

Is this related?

**Comment by ethanaobrien** [comment]
yes. Read it

```
Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https
```
