### ISSUE TITLE
how i can load rom with direct link url from other vps

### ISSUE THREAD

**Issue by megamandev** [emulatorjs/emulatorjs#231]
i have two vps

vps 1 with emulatorjs
vps 2 with rom

vps 2 i create direct link url of rom

vps 1 how i can load rom with direct link url from vps 2

i need this because vps 1 is only for apps
and vps 2 is cloud

very thank you

**Comment by ethanaobrien** [comment]
You just put the url of the rom into the path to the rom. If this isnt working something is wrong on your server
