### ISSUE TITLE
Emulatorjs wont load games anymore just a black screen

### ISSUE THREAD

**Issue by TestedGuy** [emulatorjs/emulatorjs#233]
i dont know any of coding Lol but when i try to load a rom on Demo its all just a black screen it was fine yesterday until i tried it now

**Comment by ethanaobrien** [comment]
Well no code has been changed for 3 days so if its broken now it should have been broken for 3 days so idk clear your cache

**Comment by allancoding** [comment]
The games are loading fine but into a black screen! It is only on the new version

https://github.com/ethanaobrien/emulatorjs/discussions/223#discussioncomment-2748711
https://github.com/ethanaobrien/emulatorjs/discussions/223#discussioncomment-2748750
https://github.com/ethanaobrien/emulatorjs/discussions/223#discussioncomment-2748752

@ethanaobrien What do you think could be doing this?
![Screenshot (356)](https://user-images.githubusercontent.com/74841470/168396981-22679041-f5d0-4b65-9da4-9e6dbf5458c1.png)
[emulatorjs.ga-1652480872247.log](https://github.com/ethanaobrien/emulatorjs/files/8691620/emulatorjs.ga-1652480872247.log)

https://user-images.githubusercontent.com/74841470/168397483-a45cba19-89df-41d7-ab05-a51034497584.mp4

**Comment by ethanaobrien** [comment]
Yeah, You guys were right, although [this](https://github.com/ethanaobrien/emulatorjs/commit/88eee827a83a4e3af0f9ef7ed8a89ea90662e5e2) fixed it for me. Could you clear the cache and try again/update the emu-site files?

**Comment by Ramaerel** [comment]
Yep, that seems to have fixed it right up!

**Comment by allancoding** [comment]
Ok I will update the website! Thank you!
