### ISSUE TITLE
CORS policy

### ISSUE THREAD

**Issue by saa938** [emulatorjs/emulatorjs#234]
This is probably not your problem, but I downloaded this and opened index.html. I uploaded a Mario 64 ROM and it said it couldn't do it. It gives me a CORS policy error. This is what it says:

Access to XMLHttpRequest at 'file:///C:/Users/s-sardaa/Downloads/emulatorjs-main/emulatorjs-main/data/v.json?t=1652400135' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome-extension, edge, https, chrome-untrusted.
emu-min.js?v=1.6:1 
       ccode: "ERR_NETWORK"config: {transitional: {…}, transformRequest: Array(1), transformResponse: Array(1), timeout: 0, adapter: ƒ, …}message: "Network Error"name: "AxiosError"request: XMLHttpRequest {data: undefined, onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, …}response: XMLHttpRequest {data: undefined, onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, …}[[Prototype]]: Error
e.exports @ emu-min.js?v=1.6:1
data/v.json?t=1652400135:1 
       Failed to load resource: net::ERR_FAILED

If you can help me fix it, it would be appreciated.

**Comment by ethanaobrien** [comment]
Host it using a web server

I have a simple web server I use for testing. Its really fast and simple.

View: https://github.com/ethanaobrien/C-server

Download: https://raw.githubusercontent.com/ethanaobrien/C-server/main/a.exe
