### ISSUE TITLE
IndexedDB grabbing SRAM saves - Primary key missing name?

### ISSUE THREAD

**Issue by Ramaerel** [emulatorjs/emulatorjs#235]
So I've found the SRAM saves (stored in IndexedDB under /data/saves) and am attempting to read them and replace them using Dexie. The issue is that the primary key doesn't have a name and seems to be impossible to reference? Maybe I'm doing something wrong so I'm going to keep trying, but is it at all possible to give it a name?

I know I tend to do a lot of these sorts of requests, sorry if it gets annoying!

**Comment by ethanaobrien** [comment]
The `/data/saves` indexeddb is cleared when you leave the page

And no, not annoying (You actually ask for information, not say things like "it not load")

**Comment by Ramaerel** [comment]
That isn't the case for me, it's stored the roms for all games I've played on it and it seems to load it when I re-open the game. I might have done something, but I've only started experimenting with this today when I noticed it. I'll attach a screenshot of the /data/saves
![IndexedDB](https://user-images.githubusercontent.com/72925865/168293485-4fdd4bd1-7563-4187-940d-dc69171e87df.png)

**Comment by ethanaobrien** [comment]
oh I see. with the way indexeddb works, you need the key in order to access the data. The key seems to be `'/data/saves/'+filename`

**Comment by Ramaerel** [comment]
Ah, I see, thank you. I'll try again some more and see where I get

**Comment by Ramaerel** [comment]
Okay, so I think I've found either where I'm going wrong or where the issue is. Everything I've found refers to a "Key path", which shows next to the word Key at the top of the second tab. I'll include a picture. In the example I've attached, to reference the key to add/read/change data, I would need to include `id:12345,`. This would be where I include the `/data/saves/`+filename. The issue being that I cannot seem to find the reference point, in this example it is "keyPath: 'id'".
![Capture](https://user-images.githubusercontent.com/72925865/168409832-cda47daf-46c2-4c9f-bfed-70fbf5e5daf5.PNG)

**Comment by ethanaobrien** [comment]
Not sure where youre getting that. Could you tell me where in devtools you got to that. The first screenshot you sent includes all the keys. Here is a simple function that will open the indexeddb and get the data based on the key you give it. It will return undefined if key was not found

```
    function get(key, dbName, storeName) {
        return new Promise(function(resolve, reject) {
            var openRequest = indexedDB.open(dbName, 1); //you might need to change the version number based on what the indexeddb version is set to. You can view this in devtools
            openRequest.onerror = function() {};
            openRequest.onsuccess = function() {
                var db = openRequest.result;
                var transaction = db.transaction([storeName], "readwrite");
                var objectStore = transaction.objectStore(storeName);
                var request = objectStore.get(key);
                request.onsuccess = function(e) {
                    resolve(request.result);
                };
                request.onerror = function() {resolve()};
            };
            openRequest.onupgradeneeded = function() {
                var db = openRequest.result;
                if (! db.objectStoreNames.contains(storeName)) {
                    db.createObjectStore(storeName);
                };
            };
        });
    };
```

to call this function you would use `await get(key, '/data/saves', 'FILE_DATA')`

**Comment by Ramaerel** [comment]
Okay I was 100% doing something wrong or reading something wrong. Sorry. This seems very different to ehat I had and seems to work, thank you for your help

**Comment by ethanaobrien** [comment]
No problem, If you got it resolved could you close?
