### ISSUE TITLE
Stream your gameplay on twitch

### ISSUE THREAD

**Issue by imneckro** [emulatorjs/emulatorjs#236]
It would be great to implement twitch api to let users stream their gameplay directly on twitch by capturing game canvas.
A possible start  https://developer.chrome.com/blog/capture-stream/   ?

**Comment by ethanaobrien** [comment]
We'd basically build this on top of the screen recording feature. Just a matter of embedding the twitch api

**Comment by imneckro** [comment]
found an interesting project here
https://support.glitch.com/t/stream-to-twitch-from-your-browser/27484

**Comment by allancoding** [comment]
That might work but it looks like it runs on a server and is very high running.

**Comment by ethanaobrien** [comment]
I mean technically couldnt you just stream your screen?

**Comment by imneckro** [comment]
@ethanaobrien it is as you say it. but some users dont have the knowledge and stream software to do it. hit and stream support is great plus. but it is an enhacement and nothing core. im afraid though that would hit hard browser's emulator perfomance.

**Comment by ethanaobrien** [comment]
That is very true, maybe we can get this done eventually and it really isnt a bad idea but performance is one thing we need to remember

this may work better on the beta cores, the old cores (even the new ones mentioned in #223) use an insane amount of cpu, while the beta cores use less than half the same amount of cpu (nes uses 1/5th the cpu, snes uses I think 1/3rd the cpu) so this would probably be a feature for the beta cores

**Comment by ethanaobrien** [comment]
For now at least, I am going to close this. You should be able to at least stream your screen to twitch (I assume, I dont use twitch)

Mainly I am closing this because after looking at the project you showed me, we wouldnt have enough resources to run the emulator, maybe in the future
