### ISSUE TITLE
Custom code on emu-main.js not being detected 

### ISSUE THREAD

**Issue by imneckro** [emulatorjs/emulatorjs#237]
After updating and having emu-min.js for the first time on my build, my custom code on emu-main.js is not being detected.
Is emu-main.js being skipped as of latest builds?

**Comment by allancoding** [comment]
Yes I looked at the code and I think the `emu-min.js` is both of the files together and it is the only one being (used I think). If you have custom code I would run index.js in the minify folder using npm which should rebuild the `emu-min.js` from `emulator.js` & `emu-main.js` 
Just look at the code here:
```
const UglifyJS = require("uglify-js");
const fs = require('fs');

if (!String.prototype.replaceAll) {
    String.prototype.replaceAll = function(a, b) {
        return this.split(a).join(b);
    }
}

var a = fs.readFileSync('../emu-main.js', 'utf8').substring(18);
var code = fs.readFileSync('../emulator.js', 'utf8').replaceAll('window.EJS_main', a);

function minify(source){
    var ast = UglifyJS.parse(source); 
    return UglifyJS.minify(ast).code;
}
console.log('minifying')
var min = minify(code);
console.log('done!')

fs.writeFileSync('../emu-min.js', min);
```

**Comment by imneckro** [comment]
npm run-script build creates a fresh emu-min.js minifying emu-main.js.
Still it is as if my custom code inside emu-main.js is being overlooked.

**Comment by ethanaobrien** [comment]
@imneckro 
If you are debugging/adding new features to the code, set `EJS_DEBUG_XX` to true. This will pull the `emu-main.js` and `emulator.js` files separately.

Then to put it in production, enter the `/data/minify/` directory, run `npm i` and then `npm run build`, this will build the new `emu-min.js` file and it should work. Make sure the file isnt being cached!

**Comment by imneckro** [comment]
@ethanaobrien thanks Ethan. emu-min.js was being cached. 
i tried with  "emu-min.js": "data/emu-min.js?v=<?php echo filemtime('/var/www/.../data/emu-min.js'); ?>"
and went smooth.

**Comment by ethanaobrien** [comment]
Ok awesome, can I close

also, just for reference, see [this](https://github.com/ethanaobrien/emulatorjs/blob/ec49ebb263e6111f0e7ad69b15e83652c354be1f/data/loader.js#L35)

**Comment by imneckro** [comment]
@ethanaobrien sure Ethan thanks once again!

**Comment by ethanaobrien** [comment]
No problem!

**Comment by ethanaobrien** [comment]
Hey, one last thing @imneckro . In devtools, if you go to the network tab, there is an option to disable cache. This setting will bypass cache (only when devtools is open).

**Comment by imneckro** [comment]
Holy … didn’t know all this time it even existed… thanks a tone Ethan!



Sent from myMail for iOS


Saturday, 14 May 2022, 22:12 +0300 from ***@***.***  ***@***.***>:
