### ISSUE TITLE
Document Build Instructions

### ISSUE THREAD

**Issue by ethanaobrien** [emulatorjs/emulatorjs#238]
Document build instructions for both building the `emu-min.js` file and for building the cores from source. (see [this](https://github.com/ethanaobrien/RetroArch)). This includes installing dependencies (maybe I should just write a shell script file that will do all this for the user, so the user enters the password and walks away or something).

Building the cores from source can only be done on linux (and Ive only ever gotten it to work on ubuntu) but minifying the emulator files requires npm and nothing else

**Comment by ethanaobrien** [comment]
@ElectronicsArchiver Could you clean up the `/data/readme.md` and `/data/minify/readme.md` files

**Comment by ElectronicsArchiver** [comment]
Sure, in an hour or so I'll have some time~
