### ISSUE TITLE
SAV

### ISSUE THREAD

**Issue by drewlobel** [emulatorjs/emulatorjs#24]
Hello. I was wondering if there was a way to use .sav files for the nds version. thx!

**Comment by ethanaobrien** [comment]
I don't think so. What exactly is a .sav file?

**Comment by xxxdrewwerdxxx** [comment]
It is a type of save file that stores save data. It’s what’s used in like PKHeX or CFW

**Comment by ethanaobrien** [comment]
Not supported. Cannot be implemented
