### ISSUE TITLE
Add contributors to the readme.

### ISSUE THREAD

**Issue by ethanaobrien** [emulatorjs/emulatorjs#240]
@ElectronicsArchiver Could you now officially be the styling guy?

**Comment by ElectronicsArchiver** [comment]
Should I add a Contributors.md file?

**Comment by ethanaobrien** [comment]
Yes actually. Thank you

**Comment by ElectronicsArchiver** [comment]
#242

**Comment by ethanaobrien** [comment]
Thank you @ElectronicsArchiver
