### ISSUE TITLE
[beta] pause/play anything but nes

### ISSUE THREAD

**Issue by imneckro** [emulatorjs/emulatorjs#246]
![image](https://user-images.githubusercontent.com/42493772/169085980-82bae1ff-28dd-48a3-82e5-1f73943aa38a.png)

**Comment by ethanaobrien** [comment]
@imneckro could you also enable `EJS_DEBUG_XX`? I cant really tell what the error is because the variables arent the same with the emulator minified file

**Comment by imneckro** [comment]
@ethanaobrien I [recorded ](https://webm.red/tGEN.webm)the whole situation in console log with EJS_DEBUG_XX = true;.  [here ](https://www.file.io/vM3P/download/3S4n48TDvHd7) are emulator.js and emu-main.js. Custom code can be found by searching "XRISTOSCODE". Thanks a lot Ethan!

**Comment by allancoding** [comment]
This only happens on the snes and not the nes cors it needs to updated in the snes-wasm.data. https://github.com/ethanaobrien/emulatorjs/commit/2fcc7bd47bde6e65e68f7ea5f03301293b3d4a0f

**Comment by ethanaobrien** [comment]
Yes, this is probably the case. I only updated the nes core with the update, sorry. I'm not going to be active as often for a bit at least, @allancoding could you re-compile the beta cores and open a pr?

**Comment by allancoding** [comment]
Can you send me a list of all the cores you want in the emulator. bnes, bsnes, snes9x, etc.

**Comment by ethanaobrien** [comment]
Yeah, see #151. It has the list (at the bottom of the issue). Only compile the checkmarked ones currently (because those are the ones known to work)

**Comment by ethanaobrien** [comment]
I just re-compiled the cores
