### ISSUE TITLE
Web demo bios upload

### ISSUE THREAD

**Issue by ghost** [emulatorjs/emulatorjs#249]
Some emulators need bios to run correctly, but the default home page only has an option to load the game rom, I hope you can fix that.

**Comment by ethanaobrien** [comment]
What exactly do you mean? For example, [the nes readme](https://github.com/ethanaobrien/emulatorjs/blob/main/docs/Systems/NES-Famicom.md) has the option `EJS_biosUrl = '';`. You set this to the location of the bios file and can be set on any system (doesnt mean it would do something for them all), this is how you reference the bios. Is this what youre asking?

**Comment by ghost** [comment]
> What exactly do you mean? For example, [the nes readme](https://github.com/ethanaobrien/emulatorjs/blob/main/docs/Systems/NES-Famicom.md) has the option `EJS_biosUrl = '';`. You set this to the location of the bios file and can be set on any system (doesnt mean it would do something for them all), this is how you reference the bios. Is this what youre asking?

As you know, playing games on the Turbografx-16 CD system requires a bios in order to load the CD games correctly, but index.html does not contain this, only a drag and drop game to load option.
![Screenshot_2022-05-22-10-41-41-906_org mozilla fenix](https://user-images.githubusercontent.com/32984303/169675911-7ce28798-76fc-4945-b465-fa3aaf922885.png)

**Comment by ethanaobrien** [comment]
Ah ok got it, thank you

**Comment by ethanaobrien** [comment]
I've decided to not do this, the demo is supposed to be for people to try it out, not to actively play games on it.
