### ISSUE TITLE
How to load multiple patch files

### ISSUE THREAD

**Issue by jf316318161** [emulatorjs/emulatorjs#251]
Example website：https://www.yikm.net/play?id=9480&n=bXNsdWczYjYuemlwJG1zbHVnMy56aXA=&t=%E5%90%88%E9%87%91%E5%BC%B9%E5%A4%B4%206%20(%E5%90%88%E9%87%91%E5%BC%B9%E5%A4%B4%203%20%E7%9B%97%E7%89%88)&ac=4&l=snk-neo-geo
![image](https://user-images.githubusercontent.com/65067128/169805939-360846f7-6092-454f-a7a0-f73b52b58252.png)
Look at this picture，this game loads four files

**Comment by jf316318161** [comment]
[arcade.zip](https://github.com/ethanaobrien/emulatorjs/files/8754043/arcade.zip)
This is a BIOS file

**Comment by ethanaobrien** [comment]
I was thinking, what exactly are you trying to accomplish @jf316318161 ?

**Comment by jf316318161** [comment]
> I was thinking, what exactly are you trying to accomplish @jf316318161 ?
This version is a modified version. Four files have been loaded. I also want to run this modified version

Four files: one is the main body of the game, and the other three are patch files (my guess)

**Comment by jf316318161** [comment]
This version is a modified version. Four files have been loaded. I also want to run this modified version

Four files: one is the main body of the game, and the other three are patch files (my guess)

**Comment by ethanaobrien** [comment]
I don’t think it’s possible to load three patch files. Isn’t this possible in retroarch?

Make sure you’re setting `EJS_gamePatchUrl` to the patch url

**Comment by jf316318161** [comment]
You load the BIOS file I gave you and run mlug3 zip,Different from the Games loaded on the sample website,I guess he ran the patch file，It has three patch files,If I only load one patch file, an error will be reported.

**Comment by ethanaobrien** [comment]
Is there a way to load more than one patch file in retroarch? It doesn’t seem possible to load more than one. Wouldn’t there be conflicts?

**Comment by jf316318161** [comment]
I saw it on another website.

**Comment by Ramaerel** [comment]
Loading multiple patch files is almost unheard of and definitely isn't included functionality in Retroarch. The screenshot provided in the original post seems to include: 
An emulator zip for some reason (fbneo)
Likely a BIOS contained in a zip, and/or some settings files (neogeo)
The actual game (mslug3)
And the patch file (possibly another rom, as google search seems to show it is a bootleg instead of a romhack) (mslug3b6)

So this isn't loading multiple patch files

**Comment by jf316318161** [comment]
> Loading multiple patch files is almost unheard of and definitely isn't included functionality in Retroarch. The screenshot provided in the original post seems to include: An emulator zip for some reason (fbneo) Likely a BIOS contained in a zip, and/or some settings files (neogeo) The actual game (mslug3) And the patch file (possibly another rom, as google search seems to show it is a bootleg instead of a romhack) (mslug3b6)
> 
> So this isn't loading multiple patch files

Thank you very much for your answer
It may not be a loaded patch file, so how do I run this pirated game
I want to figure it out

**Comment by ethanaobrien** [comment]
If multiple patch files are not possible in retroarch, then I am closing this. If you want this I recommend opening an issue in the retroarch repository

Please do not ask about or support piracy. I don’t want to get all tangled in that because you wanted to play a game
