### ISSUE TITLE
Deleting Ones I dont want to have 

### ISSUE THREAD

**Issue by AdanGonz244** [emulatorjs/emulatorjs#252]
Is it possible to delete one I made because I dont want it

**Comment by ethanaobrien** [comment]
Explain...

**Comment by AdanGonz244** [comment]
So if I made like Kirby and want to delete it like if my friends try to play it it won't work since it was deleted or something like that idk

**Comment by ethanaobrien** [comment]
So you want to magically delete the file if your friend tries to play it?

**Comment by AdanGonz2444** [comment]
Yea I guess

**Comment by ethanaobrien** [comment]
Well then no, that’s not possible.

**Comment by AdanGonz2444** [comment]
Oh Ok Thx tho
