### ISSUE TITLE
How to use websocket to play with friends

### ISSUE THREAD

**Issue by jf316318161** [emulatorjs/emulatorjs#255]
are there any relevant examples,I want to learn it.

**Comment by ethanaobrien** [comment]
the https://github.com/ethanaobrien/emuserver contains the web server for netplay

**Comment by jf316318161** [comment]
> https://github.com/ethanaobrien/emuserver包含网络游戏的网络服务器

Thank you，I'll try

**Comment by jf316318161** [comment]
![image](https://user-images.githubusercontent.com/65067128/170003597-277876d7-a7c6-4428-8845-7a250ab2dc38.png)
How do I use it

**Comment by jf316318161** [comment]
@ethanaobrien

**Comment by ethanaobrien** [comment]
I should have the instructions in either the readme or in the emuserver readme. You have to set EJS_netplayUrl to the URL of the server (choose one of the urls it shows)

**Comment by jf316318161** [comment]
thank you
I found the relevant documents and succeeded on windows. 
An error will appear on the Linux server.
The error is as follows. There is only a Windows solution after I Google
![image](https://user-images.githubusercontent.com/65067128/170225721-7e36e6dc-a5f8-41b7-b290-9250682d4b6e.png)

**Comment by ethanaobrien** [comment]
According to the error you just need to install python3  have you tried this?

**Comment by jf316318161** [comment]
Thank you very much. After installing Python 3, it really works, but when I run "NPM start", I make a new error
![image](https://user-images.githubusercontent.com/65067128/170284311-aafe9232-916b-40f9-a5b4-9c36d83decea.png)

**Comment by ethanaobrien** [comment]
it looks like electron didnt install correctly. Did `npm install` throw any errors?

**Comment by jf316318161** [comment]
![image](https://user-images.githubusercontent.com/65067128/170294883-0ab1cab0-0926-46b3-b6f6-ca2931bed8cc.png)
This is the result of running NPM instal

**Comment by ethanaobrien** [comment]
It looks fine. Is it still not working? This may be something with electron

**Comment by jf316318161** [comment]
> It looks fine. Is it still not working? This may be something with electron

Yes, the operation of 'electron' is wrong. After I reinstall 'electron' and execute `npm start` after `npm i`.

**Comment by jf316318161** [comment]
![image](https://user-images.githubusercontent.com/65067128/170410563-893c32b5-58d2-4d19-a29e-bdfed5b20809.png)
this is logs file

**Comment by ethanaobrien** [comment]
That’s really strange. I can confirm from the log file that it is a problem with electron. There seems to be a missing file. What Linux distro seen you using?

**Comment by jf316318161** [comment]
> That’s really strange. I can confirm from the log file that it is a problem with electron. There seems to be a missing file. What Linux distro seen you using?

Linux VM-0-2-centos 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jf316318161** [comment]
Linux version 3.10.0-862.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC) ) #1 SMP Fri Apr 20 16:44:24 UTC 2018

**Comment by ethanaobrien** [comment]
You are running this in a virtual machine, am I correct?

**Comment by jf316318161** [comment]
> You are running this in a virtual machine, am I correct?

No, it's on EC2(Cloud server)

**Comment by ethanaobrien** [comment]
So yes, cloud servers are vms most of the time (because if they weren’t, then the user could access their entire network). This is probably the reason. 

Correct me if I’m wrong but I assume it does not support the UI. Try using the scripts in the web-server folder instead of the electron folder

**Comment by jf316318161** [comment]
> So yes, cloud servers are vms most of the time (because if they weren’t, then the user could access their entire network). This is probably the reason. Correct me if I’m wrong but I assume it does not support the UI. Try using the scripts in the web-server folder instead of the electron folder

What shall I do?
Are there any documents？

**Comment by ethanaobrien** [comment]
As I said, use the web-server folder, not the electron folder.

I’m closing this assuming that resolves it

**Comment by jf316318161** [comment]
> As I said, use the web-server folder, not the electron folder.
> 
> I’m closing this assuming that resolves it

I'm sorry to bother you again. I still don't know how to operate. I'm not good at JavaScript
I really want to start it on the EC2
I think it's cool to start it on the EC2
![image](https://user-images.githubusercontent.com/65067128/170533140-a2540ff9-35fe-4b23-8a05-79e703c9c256.png)

**Comment by ethanaobrien** [comment]
It looks like you ran npm -i instead of npm i. Could you run npm i and then mom run start again?

**Comment by jf316318161** [comment]
> It looks like you ran npm -i instead of npm i. Could you run npm i and then mom run start again?

Hahaha, I'm so stupid
It is really useful to run `npm i`. before running, you need to run `npm install socket io`
I also want to run it in daemon mode,Are there any relevant command.

**Comment by jf316318161** [comment]
I googled and I found the answer
PM2 needs to be installed to run it in the background

```
npm install -g pm2
pm2 start index.js     
pm2 stop all           
pm2 restart index.js      
pm2 restart all        
pm2 delete  index.js  

```

**Comment by ethanaobrien** [comment]
Awesome, so everything’s working?

**Comment by jf316318161** [comment]
> Awesome, so everything’s working?

Yes, thanks again
