### ISSUE TITLE
Make usable offline

### ISSUE THREAD

**Issue by ElijahS117** [emulatorjs/emulatorjs#26]
Working on an offline thingy, want to add this but cant due to it fetching to other sites.

**Comment by ethanaobrien** [comment]
What other sites does it connect too? Can you include a screenshot of the networking tab?

What do you mean by offline thingy?

The reason I started this repository was originally to have the ability to have everything under one domain.

**Comment by samule** [comment]
Hi. I'm currently having the same issue while trying to self-host this emulator on an offline ipad.

I can start the server with `python3 -m http.server` and the emulator fires up, I can search and choose a game, touch the "Play now" icon and then I get "Network Error" and the emulation freezes. No other messages.

**Comment by ethanaobrien** [comment]
@samule Thats a different issue entirely. Can you include a log of the console?

**Comment by samule** [comment]
It’s the same issue. Can’t be use totally offline (airplane mode) due to some dependencies not included in the downloadable code

The server side has no issue. Do you mean the log of the frontend console? (Chrome)

**Comment by ethanaobrien** [comment]
yes. And no that is not the issue. Send me a log of the console please
