### ISSUE TITLE
please solve mame core problem 

### ISSUE THREAD

**Issue by lyarinet** [emulatorjs/emulatorjs#265]
please solve mame core problem 
mame 4|0 is working but other mame core not work
emulatorjs.com is update mame core

https://www.emulatorjs.com/arcade.html

please add this core to this emulatorjs github

thanks @ethanaobrien

**Comment by ethanaobrien** [comment]
See #223 . The cores will not be being updated.

The game is only supposed to work on one core anyway. I see no problem here

The emulatorjs website basically auto-sets the core to the required number. We cannot do this
