### ISSUE TITLE
mame core not playing more game

### ISSUE THREAD

**Issue by lyarinet** [emulatorjs/emulatorjs#267]
mame core not playing more game like Puzzle & Action: Sando-R

mame 1|0
mame 2|0
mame 3|0
mame 4|0

all mame cores not playing but 
emulatorjs.com mame core mame0.243 is playing

**Comment by ethanaobrien** [comment]
Have you tried cores 5 or 6?

**Comment by lyarinet** [comment]
yes i tried 5 or 6

5 core is page freez 

or core 6 is  stop 99 % loading

**Comment by ethanaobrien** [comment]
6 is known to be broken

Sorry, doesn’t look like there’s anything we can do right now. Wait for the beta to be ready is all

I’m closing this as not planned

**Comment by lyarinet** [comment]
thanks for best emulatorjs source 
and update mame cores also

**Comment by ethanaobrien** [comment]
I already told you. Mame cores will not be being updated. See #223 for the reason why
