### ISSUE TITLE
netplay is work fine but

### ISSUE THREAD

**Issue by lyarinet** [emulatorjs/emulatorjs#269]
netplay is work fine but problem is multi player game show current screen

first player start game and make room name kof and game was start playing and current screen
second player join room kof but game From the first start but not start current screen
i mean game not start first player screen

and first player restart game 2 time than player connect current screen

sorry for bad eng

**Comment by ethanaobrien** [comment]
Sometimes this can be fixed by unpausing.

This is part of #69
