### ISSUE TITLE
Error on githack site 

### ISSUE THREAD

**Issue by NovaKnight24** [emulatorjs/emulatorjs#271]
I've been experiencing some troubles with the emulator button and it keeps showing raw githack is down or I'm offline and I tried clearing my cache and the problem still shows up and I've even tried using the emulator button on different devices but the error still shows up

**Comment by ethanaobrien** [comment]
Please include a log of the console. What version of the button are you on? Is githack down? Can you go to the site and check? The site is raw.githack.com

**Comment by NovaKnight24** [comment]
The version of the button I'm using is 6.6 and I went on the githack site and it says that the site is up

**Comment by ethanaobrien** [comment]
Can you get me a log of the console...

**Comment by ethanaobrien** [comment]
Assuming this is resolved

**Comment by ethanaobrien** [comment]
Could you include a log of the console
