### ISSUE TITLE
SNES Light Gun / Super Scope support

### ISSUE THREAD

**Issue by Ramaerel** [emulatorjs/emulatorjs#272]
Just noticed that there's no way to play SNES games that require a Super Scope. I think most emulators support it similar to the SNES mouse, so hopefully it wouldn't take a lot to implement?

**Comment by ethanaobrien** [comment]
Could you verify that retroarch supports this?

**Comment by Ramaerel** [comment]
Yeah, it's a controller option under the snes9x retroarch core.

**Comment by Ramaerel** [comment]
Yeah, it's a controller option under the snes9x retroarch core.

**Comment by ethanaobrien** [comment]
Awesome, this shouldn’t be too hard

**Comment by ethanaobrien** [comment]
This should be supported now. Open the settings menu (in the bottom right) and there should be an option for both of these

**Comment by Norbtails97** [comment]
how do you use it?
