### ISSUE TITLE
Ability to disable the ukraine pop up message

### ISSUE THREAD

**Issue by hexlocation** [emulatorjs/emulatorjs#273]
I created my own instance of EmulatorJS and played it on a chromebook, which didnt end well. Game is playing fine etc etc, but i cant touch the emulator buttons because of the popup. Theres also no close button for me

**Comment by ethanaobrien** [comment]
It doesn’t sound like your using this version. It sounds like you are using emulatorjs.com which is not the same. The pop ups are disabled by default here

**Comment by ethanaobrien** [comment]
I’m closing this

Edit- I think github is broken because this won’t close

**Comment by hexlocation** [comment]
I confirmed that my install actually came from here.

**Comment by Ramaerel** [comment]
If you got it straight from here, the only ads or pop-ups you would be getting would either be from ads you put in yourself, or possibly ads inserted by your host if your using a cheap/free Web host.

**Comment by ethanaobrien** [comment]
@SamIsOnMC Why dont you include a screenshot of this pop up message
