### ISSUE TITLE
Buttons not working

### ISSUE THREAD

**Issue by Joejoemama** [emulatorjs/emulatorjs#274]
I’m on iOS using https://ethanaobrien.github.io/emulatorjs/
and after I load my rom buttons do nothing and the game keeps running. The joystick works and this issue is on n64, nds and GB (these are the only ones I have tried).

**Comment by ethanaobrien** [comment]
Which buttons... Provide more detail and I'll re-open

**Comment by Joejoemama** [comment]
I load my rom and press play, it decompresses the game core and loads the game. The game runs but none of the input buttons work (L,R,B,A select, start, menu) for GBA, the joystick does work and I can control the game with it but not enough to play properly.

**Comment by ethanaobrien** [comment]
Im pretty sure whats wrong

**Comment by ethanaobrien** [comment]
I think this has been fixed

**Comment by Joejoemama** [comment]
Working, thanks bro
