### ISSUE TITLE
npm start problem "Running as root without --no-sandbox is not supported"

### ISSUE THREAD

**Issue by qunlovehe** [emulatorjs/emulatorjs#276]
Using Ubuntu 20 ， Oracle，ARM architecture
when npm start 
[0623/155112.406477:FATAL:electron_main_delegate.cc(292)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

What should I do?
Unavailable now.

I installed this
https://github.com/ethanaobrien/emuserver

If you use windows 10 to enable the windows version of the server software, the port is also open, but in the network settings of the game side, it will not continue to the next step, it will be stuck in the connection, and then there will be no action.

**Comment by ethanaobrien** [comment]
I'd say most of the time, the fix is in the error. 
```
Running as root without --no-sandbox is not supported
```

It seems like you just didnt run it properly

The windows 10 issue is the same thing - misconfiguration on your side
