### ISSUE TITLE
Mapper 30 NES Maker Issue

### ISSUE THREAD

**Issue by cpgb85** [emulatorjs/emulatorjs#277]
I first though that nes maker games worked on this, that is only half true. I can get the title and music to play, but once progressing past title, it stops.  Any idea why?

**Comment by ethanaobrien** [comment]
Can you try using beta?

**Comment by cpgb85** [comment]
Where do I download beta? I downloaded this GitHub And the only thing I found that says beta is the broken link

**Comment by ethanaobrien** [comment]
Read the readme…

**Comment by cpgb85** [comment]
Derp. sorry.  I got it.  now it just freezes everything up.

**Comment by ethanaobrien** [comment]
Strange. There’s nothing I can do to fix this because the emulator uses retroarch and if there’s a bug there then there’s nothing I could do. You could try in retroarch directly and let me know if it works, if it doesn’t you’d need to open a bug there

**Comment by Ramaerel** [comment]
It looks like the FCEUmm and QuickNES cores have support for mapper 30, but even then I can't seem to find a lot on it. Which core are you using?

**Comment by ethanaobrien** [comment]
Nes uses the fceumm core

**Comment by ethanaobrien** [comment]
Closing as not planned

**Comment by cpgb85** [comment]
This has been closed, but mapper 30 support was added.
