### ISSUE TITLE
Frontend configuration

### ISSUE THREAD

**Issue by jpcapone** [emulatorjs/emulatorjs#279]
I downloaded and added some NES roms but they dont appear in the front end.  I assume there is more setup work to do but I need documentation.  Is that the correct assumption and can anyone point me in the right direction?

**Comment by Ramaerel** [comment]
You're likely looking for the other EmulatorJS (https://github.com/linuxserver/docker-emulatorjs). If you are actually using this project, check out my EmulatorJS Library extension- All you have to do is add the roms you want under the /roms folder, and they'll show up in the included Web page.

**Comment by jpcapone** [comment]
You are absolutely right, thanks!
