### ISSUE TITLE
Sega Saturn not load

### ISSUE THREAD

**Issue by dosboxonline** [emulatorjs/emulatorjs#28]
![saturn](https://user-images.githubusercontent.com/10185752/135839589-ac92c52e-75ce-4b6e-832f-7a89f8daac1e.png)
If run from the site - emulatorjs.com the problem is similar. Maybe you can understand what the problem is. On my part, there are no errors because the BIOS file and zip archive with the game work without problems on a similar emulator from the site - neptunjs.xyz.

**Comment by dosboxonline** [comment]
To check this, links to BIOS and game files are not needed. They don't change the emulator load problem.

**Comment by thelamer** [comment]
Emulator type "segaSaturn" works fine for me and I use the bios. The core thing is most roms are distroed as chd files while the emulator.js only supports bin/iso (in my experience only binmerged bins) files (multi disc does not work on any system). Your best bet is to use chdman to pull out a bin/cue and load the resulting single bin IE: 
```
chdman extractcd -i $GAMENAME.chd -o $GAMENAME.cue
```
That resulting bin file will load and play, though Saturn emulation is basically unplayable as is.

**Comment by dosboxonline** [comment]
I have a site with dozens Sega Saturn games that work through an emulator NeptunJS and all the files are in bin and iso (inside zip). I have never seen on the Internet disk images for this console in the format chd, only bin/cue or iso+wav sound/cue. You can show a screenshot of running Sega Saturn on the EmulatorJS ?
![1634597920053](https://user-images.githubusercontent.com/10185752/137818466-ffe21291-574d-496f-9e68-d2477460e5b5.jpg)

**Comment by dosboxonline** [comment]
To determine if the files are in an unsupported format, the emulator must first download them. But the emulator does not even start this process and does not even download the file saturn-asmjs.data .

**Comment by thelamer** [comment]
Wow that's surprising, neptunejs is the same basic codebase as emulatorjs. so which is the chicken and which is the egg? 
You might want to try binmerge to get a single bin file https://github.com/putnam/binmerge, this is the same thing as a single bin being extracted from a compressed hunks file.

**Comment by thelamer** [comment]
Why don't you post your raw html?

**Comment by dosboxonline** [comment]
I close this issue due to a misunderstanding. I'll try to solve it myself.
