### ISSUE TITLE
Import predefined cheats from custom database

### ISSUE THREAD

**Issue by imneckro** [emulatorjs/emulatorjs#280]
Does anyone know what is the cheat add function and how to modify it so we can populate list with custom data from database?

**Comment by ethanaobrien** [comment]
Sorry for the delay, I’ll get this to you when we can.

**Comment by allancoding** [comment]
I do not think there is a cheat function to add cheats to the list. Cheats is only available on some cores. But this could be implemented in beta.

**Comment by ethanaobrien** [comment]
EJS_cheats will set cheats on emulator load - I just don’t know how to use it

**Comment by Ramaerel** [comment]
Regarding this - I know Retroarch has a massive cheats database, with a separate file for each game. I've tried loading a couple in using EJS_cheats to no avail, and will test more (I've only tried Gameshark and Codebreaker for GBA so far), but it might be worth looking at? I've uploaded the cheat files for the relevant systems here (And left all 3 psx cores, not sure which one you use): https://drive.google.com/file/d/1W5pCSQ_D6jVmKA5V_pyWIVd674lO79EL/view?usp=sharing

**Comment by ethanaobrien** [comment]
Sorry! Just got around to looking into this.

```
EJS_cheats = [
    ["name", "value"],
    ["name2", "value2"]
]
```

If the user has any cheats already programmed or programs any additional cheats, then the `EJS_cheats` variable will be overwritten with the value in localstorage.
