### ISSUE TITLE
Sega GameGear does not work if the file is not in the archive

### ISSUE THREAD

**Issue by Bastard007** [emulatorjs/emulatorjs#281]
If i upload a file with the .gg extension, the game does not start (black screen). 
If this file is archived (zip, 7z) - the game starts perfectly.

UPD: Sega Master System  too.

How to fix it?

P.S. sorry for my bad english

**Comment by ethanaobrien** [comment]
Is there a problem against having the games in an archive? This may be something the emulator requires and I wouldn’t be able to fix

**Comment by Bastard007** [comment]
> Is there a problem against having the games in an archive? This may be something the emulator requires and I wouldn’t be able to fix

Yes, I would like to stop using archives.
Emulatorjs.com plays the games of Sega Game Gear and Sega Matser Systems without archives.

The problem is only with the consoles Sega GameGear and SegaMatser systems. Nintendo and other consoles work fine in your emulator.

P.S> Sorry for my bad english

**Comment by ethanaobrien** [comment]
We are not using emulatorjs.com as the source. See #223 

this may be fixed with the beta cores

there might be another fix. Why would you like to stop using archives? It saves space on the server, on the client (as it caches the file) and speeds up transfer time. Why would you like to stop using archives?

**Comment by Bastard007** [comment]
> We are not using emulatorjs.com as the source. See #223
> 
> this may be fixed with the beta cores
> 
> there might be another fix. Why would you like to stop using archives? It saves space on the server, on the client (as it caches the file) and speeds up transfer time. Why would you like to stop using archives?

Thanks for the answer.
In my project i need to know which file is loaded and exclude loading of unnecessary extensions (archives). I would like to make an free analog https://afterplay.io/

**Comment by ethanaobrien** [comment]
If you rename the zip with the extension you want, does that work?

Also, please be aware it is agains the terms of service to not post the changes and include a link to the original license. You might want to fix that as I could legally charge back

**Comment by Bastard007** [comment]
> If you rename the zip with the extension you want, does that work?

Yes, if I archive the game (zip), and then change the file extension to .gg, the game works. If I upload the same game without archiving and without changing the extension - the game does not work

> Also, please be aware it is agains the terms of service to not post the changes and include a link to the original license. You might want to fix that as I could legally charge back

Yes, I know the terms of the GPL 3 license )

**Comment by ethanaobrien** [comment]
Ok, there’s a temporary solution. Could you use that for now?

**Comment by Bastard007** [comment]
> Ok, there’s a temporary solution. Could you use that for now?

Unfortunately, this temporary solution does not work for my project. You can close this problem, I'm glad that you will keep this problem in mind in the future

**Comment by ethanaobrien** [comment]
Awesome, thank you
