### ISSUE TITLE
Virtual Gamepad on mobile devices clicking once double clicks

### ISSUE THREAD

**Issue by imneckro** [emulatorjs/emulatorjs#284]
virtual gamepad on mobile devices behavior is wrong.
Clicking once a button A/B/Y/X but it double clicks it.
Here is a video:
https://user-images.githubusercontent.com/42493772/177033614-fd8b7073-01d3-4e71-acec-c177cc2eeff6.MOV

**Comment by ethanaobrien** [comment]
fixed

**Comment by imneckro** [comment]
> fixed

@ethanaobrien thanks a lot. i downloaded new files, but stack on loading no console log errors what so ever even with EJS_DEBUG_XX = true;
![image](https://user-images.githubusercontent.com/42493772/177607080-f22550e6-6b05-4897-8352-2600b33b523e.png)

**Comment by imneckro** [comment]
> > fixed
> 
> @ethanaobrien thanks a lot. i downloaded new files, but stack on loading no console log errors what so ever even with EJS_DEBUG_XX = true; ![image](https://user-images.githubusercontent.com/42493772/177607080-f22550e6-6b05-4897-8352-2600b33b523e.png)

@ethanaobrien when you have time can you tell why i am stack on loading now that i have updated? should i rebuild with npm? thanks a lot in advance!

**Comment by ethanaobrien** [comment]
Try playing the rom here - https://ethanaobrien.github.io/emulatorjs/ - if it works, it’s something on your end, if not I might have broken something

**Comment by imneckro** [comment]
> Try playing the rom here - https://ethanaobrien.github.io/emulatorjs/ - if it works, it’s something on your end, if not I might have broken something

@ethanaobrien it's definetely on my end and i cant figure out what... thanks for your help Ethan

**Comment by ethanaobrien** [comment]
No problem, if you have any questions you can ask me and I can try to help

**Comment by imneckro** [comment]
Thanks Ethan!
I’ll try to figure it out and if I can’t I’ll  ask you for help .Maybe when you got time you ll help me out.



Saturday, 9 July 2022, 19:38 +0300 from ***@***.***  ***@***.***>:

**Comment by imneckro** [comment]
> > > fixed
> 
> > 
> 
> > @ethanaobrien thanks a lot. i downloaded new files, but stack on loading no console log errors what so ever even with EJS_DEBUG_XX = true; ![image](https://user-images.githubusercontent.com/42493772/177607080-f22550e6-6b05-4897-8352-2600b33b523e.png)
> 
> 
> 
> @ethanaobrien when you have time can you tell why i am stack on loading now that i have updated? should i rebuild with npm? thanks a lot in advance!

@ethanaobrien hello. Still haven't solve it. Probably issue #289 (on EJS_startOnLoaded = true;)
