### ISSUE TITLE
Rewind & Retroachievements support

### ISSUE THREAD

**Issue by Ramaerel** [emulatorjs/emulatorjs#285]
Just an idea- Since Retroarch supports both of these features, would it be possible to get them here at some point in the future?

**Comment by ethanaobrien** [comment]
Retroachievements are not possible. Maybe rewind

**Comment by ethanaobrien** [comment]
Rewind, while possible, I am not doing. It seems to be very very effective on performance.

See https://github.com/libretro/RetroArch/blob/5253e4be23bec378f83aaac50ab0e80f5bca2ac2/retroarch.cfg#L945
