### ISSUE TITLE
RetroArch Commands and Menus

### ISSUE THREAD

**Issue by davideo7** [emulatorjs/emulatorjs#286]
Is it possible to execute RetroArch commands?  Or access the RetroArch menus?

If not, is this something that could be added?

Thank you!

**Comment by ethanaobrien** [comment]
This is currently possible on the beta cores, but is going to be taken out. The resolution doesn’t work properly within the web browser and that is much too complicated to fix. All the similar settings can be found in settings (not yet for beta)

**Comment by ethanaobrien** [comment]
Maybe I could have an option for it though. Although the mouse doesn’t match and the resolution is all messed up. What do you think?

**Comment by davideo7** [comment]
> Maybe I could have an option for it though. Although the mouse doesn’t match and the resolution is all messed up. What do you think?

I think it could be an option that becomes available when debug is enabled.  Just an idea.  It would be cool to have it available in some way though, as a secret or hidden feature.

_"All the similar settings can be found in settings (not yet for beta)"_

Could you elaborate?

**Comment by ethanaobrien** [comment]
Maybe on that first part.

In game, when you hover over the screen, bottom right corner

**Comment by ethanaobrien** [comment]
I've been thinking. I'm not going to do this to keep the emulator clean looking. You can access all the core options in the settings button in the bottom right corner
