### ISSUE TITLE
[question] screenshots size

### ISSUE THREAD

**Issue by Bastard007** [emulatorjs/emulatorjs#288]
Where can I find the size of screenshots in the code?

Thanks )))

**Comment by ethanaobrien** [comment]
Screenshot size height and width, or screenshot size the size of the file?

**Comment by Bastard007** [comment]
> Screenshot size height and width

height and width

**Comment by allancoding** [comment]
What do you want to do?
Do you want to know the size of screenshots or change them?

**Comment by Bastard007** [comment]
> What do you want to do?

I want to change the width and height of the screenshots. Now the screenshot (nes) width is only 256px . I would like to change the width to 800px

P.S> I'm sorry for my bad english )))

**Comment by allancoding** [comment]
Ok I will look in to this.

**Comment by allancoding** [comment]
Just so you know changing the resolution will not change the resolution of the screenshot, it would just inflate the file size (basically would zoom into the image).

**Comment by ethanaobrien** [comment]
I've done digging, this is not possible, you could always just upscale the image. You wouldnt loose any quality  (The screenshots are taken at full resolution)
