### ISSUE TITLE
2 player playing together on one screen

### ISSUE THREAD

**Issue by Vivek230800** [emulatorjs/emulatorjs#292]
Hey, I appreciate all the creators for making this. Could anyone please guide me if I want to play with my friend from 2 different locations. Can we play like that? I want to play 2 player games with her but I cannot figure out.

**Comment by Vivek230800** [comment]
Feature request: Both players see the same game but have controller 1 & 2 from different locations. That way people can play 2 player games from anywhere around the world. This would result in the best emulator in the world.

**Comment by Ramaerel** [comment]
Depending on what console you want, netplay is supported. It's the little globe icon down the bottom.

I don't think the beta supports them yet, but at the very least the NES and SNES non-beta cores support them. The documentation goes over what you need afaik, but just in case:

You need to set the GameID and you also need to either host your own netplay server or use the old one- The one hosted by Ethan seems to be down last I looked

**Comment by allancoding** [comment]
Let me check the public server because I host it. And yes all Nintendo Consoles work and some others. 
It is set to default server is https://emuserver.emulatorjs.ga. I think it is:
```
EJS_gameID = 1; //change 1 to a random 8 number id.
```

**Comment by allancoding** [comment]
Yes the server is up and running!

**Comment by allancoding** [comment]
@Vivek230800 Just so you know this is already implemented in netplay. Up to 4 players over netplay and 4 players on one computer so in total 16 players. Setting the id is so you can make rooms and have passwords on those room's.
Future addon in beta will be a microphone connection room with video. So a call in a game with video and audio.

**Comment by Vivek230800** [comment]
Hey @allancoding , I am very confused about how netplay works. Could you please🙏 share me a guide or walkthrough of how to do it? I have already hosted my emulatorjs on a 1gb ram vultr vps. But couldn't figure out the way to play with my friend in another city.

**Comment by allancoding** [comment]
Add this code to the html page in the javascript code:
````
EJS_gameID = 77646733;
````
Then have your friend access the page where you play the game (same page as you)
Then you click the world icon:
![image](https://user-images.githubusercontent.com/74841470/179633548-e31dcf00-d956-46e1-afd8-1749438b1dbb.png)
Then set player name:
![image](https://user-images.githubusercontent.com/74841470/179633614-a6cd143c-bef8-4fb6-a18b-bf84f684743d.png)
Then click on Create a room:
![image](https://user-images.githubusercontent.com/74841470/179633703-4b12252f-994f-4283-8cab-2f1f661504ea.png)
Then fill in the information: (enter whatever you want)
![image](https://user-images.githubusercontent.com/74841470/179633781-5a448ef7-ae3e-4eec-a3ac-950cdec92fbe.png)
Then click submit
You should see something like this:
![image](https://user-images.githubusercontent.com/74841470/179633945-80127174-4bcb-4146-9c03-7ec4a8a393cb.png)
Then have your friend go the the same page as you and have him click the world icon.
Then click on the room you created and enter the password and it connects.

**Comment by allancoding** [comment]
This issue has already been solved.
