### ISSUE TITLE
Privacy and iframe security

### ISSUE THREAD

**Issue by ildomandatore** [emulatorjs/emulatorjs#294]
What exactly do I do? Tell me in detail and simply. I partly understand things, but I want to do things right. You have closed the post, but I am available to correct the errors. And I've said this more than once if I was doing something wrong with your instrument. You told me everything is fine.

You told me about the cookie page to be modified and the iframe blocked for security. For the cookie page, I think a backlink will suffice. Instead for the security of the iframe, I did not understand if it is my problem with the security plugin or Cloudflare or if you have blocked me.

Please don't put in spam this thread, I am available to fix my unwanted mistakes.

**Comment by ethanaobrien** [comment]
Fix the mistakes, then open an issue

I looked through every single comment you’ve ever made and in my response I’ve never said what you’re doing has been fine. I just assumed you’ve been following the license but I was wrong
