### ISSUE TITLE
I have created a website with your project and given the credits you deserve.

### ISSUE THREAD

**Issue by losingplayer** [emulatorjs/emulatorjs#296]
I created a website with your project and gave you the credit you deserve. On the oldfreegame website and on the Cookie Policy page, I have entered the credits you deserve. If necessary, I will move the link to another page.

Do I have to do anything else? I have questions to ask and you will probably want me to be in good standing with you.

**Comment by ethanaobrien** [comment]
Your website seems to be down.
You would need to
1. Make sure the source is on every page that contains the emulator plugin

and 2. Make sure to clearly state your changes. I can't really help you without this one (and it is required by the license)
