### ISSUE TITLE
[beta] Issues with mouse capture on all beta cores

### ISSUE THREAD

**Issue by Ramaerel** [emulatorjs/emulatorjs#298]
Not sure if this has been pointed out yet, couldn't find anything on it.

I noticed while testing my library extension that the beta cores seem to take away all other inputs on the site even when not in full screen. After starting the game, the dropdown box and other buttons on the site become unresponsive, and pressing f5 to refresh doesn't always work - Pressing Esc and the F5 immediately after seems to work about 50% of the time. Not sure if this is actually an issue, but thought I'd put it out there.

**Comment by ethanaobrien** [comment]
Thats interesting, chanks for the report

**Comment by ethanaobrien** [comment]
This should be fixed because of #305
