### ISSUE TITLE
GBA RTC how to Make it open?

### ISSUE THREAD

**Issue by nenge123** [EmulatorJS/EmulatorJS#3]
i know the vbanext is support the rtc time .
if i run "Pokémon Emerald" the rtc is open,
but i run "Pokemon Radical Red" is not open.

i use other wasm for vbanext ,fist run the "Pokémon Emerald", not close to change roms data to ""Pokemon Radical Red"", game restart ,then the ""Pokemon Radical Red"" will open the rtc time.

**Comment by ethanaobrien** [comment]
@nenge123 I turned off rtc because of some incompatibilities.
If you would like to attempt to use it, set the game ID

`EJS_gameID = 1; // ID in your website, required for netplay.`
