### ISSUE TITLE
Remove "Play Now" button and start emulation right away.

### ISSUE THREAD

**Issue by GeckoLee** [emulatorjs/emulatorjs#30]
Would it be possible to remove the Play Now button and start the emulation process right away without user interaction?

**Comment by ethanaobrien** [comment]
I think. I can take a look at this later today. Although, most browsers need user interaction for an audio context to start, so there would possibly be no sound. I'll try to look at this later today

**Comment by thelamer** [comment]
I just ran a loop to click it when it renders in: 
```
    var clickplay = setInterval(() => {
      if (typeof document.getElementsByClassName('ejs--73f9b4e94a7a1fe74e11107d5ab2ef')[0] !== 'undefined') {
        clearInterval(clickplay);
        document.getElementsByClassName('ejs--73f9b4e94a7a1fe74e11107d5ab2ef')[0].click();
      }
    }, 100);
```
Also fullscreen when the game is loaded: 
```
    EJS_onGameStart = function() {
      document.querySelectorAll('[data-btn="fullscreen"]')[0].click();
    }
```

**Comment by ethanaobrien** [comment]
I absolutely love that, thank you

**Comment by Scoffins** [comment]
> I absolutely love that, thank you

This should work, but it's so inefficient and dirty. It's okay as a temp hack, but I would seriously advise against implementing this into the main code. A better way would be to isolate the function called when the Play Now button is clicked, and just run that on page load.

**Comment by thelamer** [comment]
It should be a flag optimally, the reason the main dev has this button is because until the user inteacts with the page sound and other stuff (gamepad) will be blocked by the browser and causes issues. I specifically do this with what I am building now, because i know with 100% guarantee that the user has interacted with the page before the game is loaded in, though this is honestly rare.

**Comment by ethanaobrien** [comment]
@GeckoLee @Scoffins @thelamer 
I just pushed changes. Add the following line to the code

```
EJS_startOnLoaded = true;
```
I will add this to the readme when I can
