### ISSUE TITLE
WEN I PUT UPDATE EMULATORJS

### ISSUE THREAD

**Issue by lyarinet** [emulatorjs/emulatorjs#303]
wen i put update emulatorjs 
enable 
EJS_DEBUG_XX = true;
page is blank

**Comment by ethanaobrien** [comment]
Provide a log of the console

**Comment by lyarinet** [comment]
> 

extract7z.js:1 Warning: Enlarging memory arrays, this is not fast! 16777216,67108864
Module.printErr.Module.printErr @ extract7z.js:1
enlargeMemory @ extract7z.js:1
Ze @ extract7z.js:1
Xe @ extract7z.js:1
sr @ extract7z.js:1
W @ extract7z.js:1
_extract @ extract7z.js:1
asm._extract @ extract7z.js:1
eval @ VM5:1
onmessage @ extract7z.js:1
extract7z.js:1 enlarged memory arrays from 16777216 to 67108864, took 26 ms (has ArrayBuffer.transfer? false)
Module.printErr.Module.printErr @ VM4 extract7z.js:1
enlargeMemory @ VM4 extract7z.js:1
Ze @ VM4 extract7z.js:1
Xe @ VM4 extract7z.js:1
sr @ VM4 extract7z.js:1
W @ VM4 extract7z.js:1
_extract @ VM4 extract7z.js:1
asm._extract @ VM4 extract7z.js:1
eval @ VM5:1
onmessage @ VM4 extract7z.js:1
emu-main.js?v=2:1944 [Violation] 'message' handler took 167ms
emu-main.js?v=2:1978 [INFO] RetroArch 1.7.7 (Git e97c35ec2d)
emu-main.js?v=2:1978 [INFO] Redirecting save file to "/data/saves/sandor.srm".
emu-main.js?v=2:1978 [INFO] Redirecting savestate to "/home/web_user/retroarch/userdata/states/sandor.state".
emu-main.js?v=2:1978 [INFO] === Build =======================================
emu-main.js?v=2:1978 [INFO] Capabilities: 
emu-main.js?v=2:1978 [INFO] Built: Apr 21 2021
emu-main.js?v=2:1978 [INFO] Version: 1.7.7
emu-main.js?v=2:1978 [INFO] Git: e97c35ec2d
emu-main.js?v=2:1978 [INFO] =================================================
emu-main.js?v=2:1978 [INFO] [Overrides] no core-specific overrides found at /etc/MAME/MAME.cfg.
emu-main.js?v=2:1978 [INFO] [Overrides] no content-dir-specific overrides found at /etc/MAME/.cfg.
emu-main.js?v=2:1978 [INFO] [Overrides] no game-specific overrides found at /etc/MAME/sandor.cfg.
emu-main.js?v=2:1978 [INFO] [recording] twitch streaming key empty
emu-main.js?v=2:1978 [INFO] Environ SET_VARIABLES.
emu-main.js?v=2:1978 [INFO] [Remaps]: remap directory: /home/web_user/retroarch/userdata/config/remaps
emu-main.js?v=2:1978 [INFO] [Remaps]: no game-specific remap found at /home/web_user/retroarch/userdata/config/remaps/MAME/sandor.rmp.
emu-main.js?v=2:1978 [INFO] [Remaps]: no content-dir-specific remap found at /home/web_user/retroarch/userdata/config/remaps/MAME/׿A.rmp.
emu-main.js?v=2:1978 [INFO] [Remaps]: no core-specific remap found at /home/web_user/retroarch/userdata/config/remaps/MAME/MAME.rmp.
emu-main.js?v=2:1978 [INFO] Redirecting save file to "/data/saves/sandor.srm".
emu-main.js?v=2:1978 [INFO] Redirecting savestate to "/home/web_user/retroarch/userdata/states/sandor.state".
emu-main.js?v=2:1978 [INFO] Environ GET_LOG_INTERFACE.
emu-main.js?v=2:1978 [INFO] Environ SYSTEM_DIRECTORY: "/".
emu-main.js?v=2:1978 [libretro INFO] SYSTEM_DIRECTORY: /
emu-main.js?v=2:1978 [INFO] Environ CORE_ASSETS_DIRECTORY: "/home/web_user/retroarch/userdata/content/downloads".
emu-main.js?v=2:1978 [libretro INFO] CONTENT_DIRECTORY: /home/web_user/retroarch/userdata/content/downloads
emu-main.js?v=2:1978 [libretro INFO] SAVE_DIRECTORY: /data/saves
emu-main.js?v=2:1978 [INFO] Environ SET_PIXEL_FORMAT: XRGB8888.
emu-main.js?v=2:1978 [INFO] Content loading skipped. Implementation will load it on its own.
emu-main.js?v=2:1978 [INFO] Skipping SRAM load..
emu-main.js?v=2:1978 [INFO] Version of libretro API: 1
emu-main.js?v=2:1978 [INFO] Compiled against API: 1
emu-main.js?v=2:1978 [libretro INFO] AV_INFO: width=640 height=480
emu-main.js?v=2:1978 [libretro INFO] AV_INFO: max_width=640 max_height=480
emu-main.js?v=2:1978 [libretro INFO] AV_INFO: aspect_ratio = 1.333333
emu-main.js?v=2:1978 [libretro INFO] AV_INFO: fps = 60.000000 sample_rate = 48000.000000
emu-main.js?v=2:1978 [INFO] [Audio]: Set audio input rate to: 47952.05 Hz.
emu-main.js?v=2:1978 [INFO] [Video]: Video @ 640x480
emu-main.js?v=2:1978 [INFO] [EGL] Falling back to eglGetDisplay
emu-main.js?v=2:1978 [INFO] [EGL]: EGL version: 1.4
emu-main.js?v=2:1978 [INFO] [EGL]: Current context: 0xf234.
emu-main.js?v=2:1978 [INFO] [EMSCRIPTEN/EGL]: Dimensions: 600x450
emu-main.js?v=2:1978 [INFO] [GL]: Found GL context: emscripten
emu-main.js?v=2:1978 [INFO] [GL]: Detecting screen resolution 600x450.
emu-main.js?v=2:1978 [INFO] [GL]: Vendor: WebKit, Renderer: WebKit WebGL.
emu-main.js?v=2:1978 [INFO] [GL]: Version: OpenGL ES 2.0 (WebGL 1.0 (OpenGL ES 2.0 Chromium)).
emu-main.js?v=2:1978 [WARN] [GL]: GLES implementation does not have BGRA8888 extension.
emu-main.js?v=2:1978 32-bit path will require conversion.
emu-main.js?v=2:1978 [INFO] [GL]: Using resolution 600x450
emu-main.js?v=2:1978 [INFO] [GL]: Default shader backend found: glsl.
emu-main.js?v=2:1978 [INFO] [Shaders]: preset directory: /home/web_user/retroarch/bundle/shaders/presets
emu-main.js?v=2:1978 [INFO] [Shader driver]: Using GLSL shader backend.
emu-main.js?v=2:1978 [ERROR] [GL]: Failed to parse GLSL shader.
emu-main.js?v=2:1978 [ERROR] [GL]: Failed to initialize shader, falling back to stock.
emu-main.js?v=2:1978 [INFO] [Shader driver]: Using GLSL shader backend.
emu-main.js?v=2:1978 [WARN] [GL]: Stock GLSL shaders will be used.
emu-main.js?v=2:1978 [INFO] [GLSL]: Found GLSL vertex shader.
emu-main.js?v=2:1978 [INFO] [GLSL]: Found GLSL fragment shader.
emu-main.js?v=2:1978 [INFO] [GLSL]: Linking GLSL program.
emu-main.js?v=2:1978 [INFO] [GLSL]: Found GLSL vertex shader.
emu-main.js?v=2:1978 [INFO] [GLSL]: Found GLSL fragment shader.
emu-main.js?v=2:1978 [INFO] [GLSL]: Linking GLSL program.
emu-main.js?v=2:1978 [INFO] [GLSL]: Found GLSL vertex shader.
emu-main.js?v=2:1978 [INFO] [GLSL]: Found GLSL fragment shader.
emu-main.js?v=2:1978 [INFO] [GLSL]: Linking GLSL program.
emu-main.js?v=2:1978 [INFO] [GL]: Using 4 textures.
emu-main.js?v=2:1978 [INFO] [GL]: Loaded 1 program(s).
emu-main.js?v=2:1978 [INFO] [Joypad]: Found joypad driver: "null".
emu-main.js?v=2:1978 [INFO] [Video]: Found display server: null
emu-main.js?v=2:1978 [INFO] [LED]: LED driver = 'null' 0x362b40
emu-main.js?v=2:1978 [INFO] [MIDI]: Initializing ...
emu-main.js?v=2:1978 [INFO] [MIDI]: Input disabled.
emu-main.js?v=2:1978 [INFO] [MIDI]: Output disabled.
emu-main.js?v=2:1978 [INFO] [MIDI]: Initialized "null" driver.
emu-main.js?v=2:1978 [INFO] Loading history file: [/home/web_user/retroarch/userdata/content_history.lpl].
emu-main.js?v=2:1978 [INFO] Loading history file: [/home/web_user/retroarch/userdata/content_favorites.lpl].
emu-main.js?v=2:1978 [INFO] Loading history file: [/home/web_user/retroarch/userdata/content_music_history.lpl].
emu-main.js?v=2:1978 [ERROR] cannot push NULL or empty core path into the playlist.
emulator.js?v=2:1004 [Violation] 'complete' handler took 370ms
emu-main.js?v=2:1978 [libretro INFO] Starting game:sandor.zip
emu-main.js?v=2:1978 [libretro ERROR] Error parsing system name: sandor.zip
emu-main.js?v=2:1978 [libretro ERROR] Error parsing parent path: sandor.zip
emu-main.js?v=2:1978 [libretro INFO] Game name: sandor, Game description: Puzzle & Action: Sando-R (J 951114 V1.000)
emu-main.js?v=2:1978 [libretro ERROR] System not found: sandor.zip
emu-main.js?v=2:1978 [libretro WARN] Driver sandor.zip not found -1
emu-main.js?v=2:1978 [libretro INFO] Creating frontend for game: sandor
emu-main.js?v=2:1978 [libretro INFO] Softlists: 1

**Comment by ethanaobrien** [comment]
Looks like your zip is invalid
