### ISSUE TITLE
Virtual Gamepad - Location appearance switch (left or right)

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#310]
Hi,

Currently, when playing on mobile, the virtual gamepad nipple appears on the left side of the screen.
I would like to ask if it there is any option for the user to switch the side of the nipple will appearance  - between left or right (for right or left handed).

Thanks in advance.

**Comment by ethanaobrien** [comment]
Now available through [`EJS_VirtualGamepadSettings`](https://emulatorjs.netlify.app/docs/Virutal%20Gamepad%20Settings.html)
