### ISSUE TITLE
Console Requests

### ISSUE THREAD

**Issue by Protektor-Desura** [emulatorjs/emulatorjs#317]
For most Sega consoles.
"Genesis Plus GX has 100% compatibility with Genesis / Mega Drive, Sega/Mega CD, Master System, Game Gear, SG-1000 & Pico released software" You would pick up support for SG-1000 and Pico.

https://github.com/libretro/Genesis-Plus-GX
https://docs.libretro.com/library/genesis_plus_gx/

Fairchild F Channel

https://github.com/libretro/FreeChaF
https://www.libretro.com/index.php/category/freechaf/

**Comment by Protektor-Desura** [comment]
Doom engine

https://github.com/libretro/libretro-prboom
https://docs.libretro.com/library/prboom/

**Comment by Protektor-Desura** [comment]
RetroArch (MAME 2000 (0.37b5))

RetroArch (MAME 2003 (0.78))

So if you are using:

MAME 2000 which is version 0.37.b5 
**or**
MAME 2003 which is version  0.78

then you should have support for these because support was added on 0.246, an older version of MAME:

Atari XEGS ([MAME 0.246](https://emulation.gametechwiki.com/index.php/Atari_8-bit))
Amiga CD32 ([MAME 0.246](http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=cd32))

**Comment by ethanaobrien** [comment]
Mame 2003 is suported

Genesis Plus GX - Error when running (bug in emulator code)
FreeChaF - Not supported by the wrapper, requires modifications that would break other systems
prboom - Emscripten is not supported.


You can comment on a closed issue you know.
