### ISSUE TITLE
Adding mouse support in aim shooting games (similar to SNES EJS_mouse parameter)

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#318]
Hi,

I would like to ask please if there is a possibility to add support for shooting aim games by using the mouse support that available for the snes (EJS_mouse parameter)

For example this games:
Operation Wolf (Arcade)
Virtua Cop (Sega Saturn)
MadDog Mcree (3DO)

**Comment by ethanaobrien** [comment]
Possibly, Do the Arcade, Sega Saturn, and 3DO RetroArch cores support this? If yes then yes this should be possible

**Comment by shaylevary** [comment]
I know that the mame/arcade under retroarch support this feature (it also support lightgun).
Anyway it will be a great feature.

**Comment by ethanaobrien** [comment]
Then I should be able to do this for at least mame and arcade. I'll look into this

**Comment by ethanaobrien** [comment]
I looked into this, I cant do this at least at the moment. Its not yet possible. Maybe later. Closing for now
