### ISSUE TITLE
Freeze on load from mobile

### ISSUE THREAD

**Issue by imneckro** [emulatorjs/emulatorjs#319]
I noticed snes,nes,n64,gb freeze on load from mobile. Here is a video 
https://user-images.githubusercontent.com/42493772/183943219-1d2c3e1c-bff0-4251-8726-2c995ea841c6.MOV

**Comment by ethanaobrien** [comment]
fixed

**Comment by imneckro** [comment]
> fixed

Now gives the following error
![image](https://user-images.githubusercontent.com/42493772/183977959-4c459082-4173-4f85-bdde-6be7a1bc506a.png)

**Comment by ethanaobrien** [comment]
Should be fixed now
