### ISSUE TITLE
Save state to base64 in the middle of game.

### ISSUE THREAD

**Issue by 60013695** [emulatorjs/emulatorjs#32]
ESJ_SaveState does not work!

**Comment by ethanaobrien** [comment]
`ESJ_SaveState` is not a function. You cant save to base64. This would crazily inflate the save file

**Comment by 60013695** [comment]
How could you do auto save?

**Comment by ethanaobrien** [comment]
You cant auto save. There is no way to call the save function because it is wrapped in the emulator.js file. The user must interactively save
