### ISSUE TITLE
[beta] GBA Vertical alignment off

### ISSUE THREAD

**Issue by Ramaerel** [emulatorjs/emulatorjs#320]
The window for GBA games seems to be aligned off vertically. As shown in the screenshot, a portion is cut off the top of the emulator window and there is a black bar on the bottom. Strangely enough, I can only replicate this on another computer, and not any mobile device.
![vertical offset](https://user-images.githubusercontent.com/72925865/184057866-4fe3c2ab-7878-4b3b-b627-892ef123330e.PNG)

**Comment by ethanaobrien** [comment]
That is really strange. Mobile uses the old cores by default because the compatibility is pretty slim for mobile.

**Comment by ethanaobrien** [comment]
I decided to downgrade the gba core until further notice
