### ISSUE TITLE
[beta] "Fail to save" in console

### ISSUE THREAD

**Issue by Ramaerel** [emulatorjs/emulatorjs#321]
The new cores don't seem to save SRAM like the old ones did, and shows a "fail to save" error message in the console when reloading the page. I can't grab a screenshot of it as there's maybe a second where it shows, sorry. It seems to affect all new cores

**Comment by ethanaobrien** [comment]
I see why. Its not actually because its failing to save anything, its because its failing to delete the save file. Not sure why its there. I'll fix this tomorrow.

**Comment by Ramaerel** [comment]
Sounds good. I'm sorry for dumping a bunch of bug reports at once, first time actually checking out any updates in a while

**Comment by ethanaobrien** [comment]
It’s all good! You provide enough information to where I actually know what the problem is and I thank you for that!

**Comment by ethanaobrien** [comment]
fixed
