### ISSUE TITLE
[beta] PSX core not loading roms or bios?

### ISSUE THREAD

**Issue by Ramaerel** [emulatorjs/emulatorjs#322]
The PSX core isn't loading any roms (I have tried multiple roms, both zipped and not, confirmed working on old core and other emulators). It shoots me back to the retroarch menu. I've included the debug log.

Also in regards to the PSX core, the debug log seems to show that the firmware is missing even though I've pointed to a good bios with EJS_biosUrl. 

I've removed the missing menu asset stuff for easier reading

> emu-main.js?v=2.3:2035 [INFO] [EGL]: EGL version: 1.4
emu-main.js?v=2.3:2035 [INFO] [EGL]: Current context: 0xf234.
emu-main.js?v=2.3:2035 [INFO] [EMSCRIPTEN/EGL]: Dimensions: 300x150
emu-main.js?v=2.3:2035 [INFO] [GL]: Found GL context: "egl_emscripten".
emu-main.js?v=2.3:2035 [INFO] [GL]: Detecting screen resolution: 300x150.
emu-main.js?v=2.3:2035 [INFO] [GL]: Vendor: WebKit, Renderer: WebKit WebGL.
emu-main.js?v=2.3:2035 [INFO] [GL]: Version: OpenGL ES 2.0 (WebGL 1.0 (OpenGL ES 2.0 Chromium)).
emu-main.js?v=2.3:2035 [WARN] [GL]: GLES implementation does not have BGRA8888 extension.
emu-main.js?v=2.3:2035 [GL]: 32-bit path will require conversion.
emu-main.js?v=2.3:2035 [INFO] [GL]: Using resolution 300x150.
emu-main.js?v=2.3:2035 [INFO] [GL]: Default shader backend found: glsl.
emu-main.js?v=2.3:2035 [INFO] [Shader driver]: Using GLSL shader backend.
emu-main.js?v=2.3:2035 [WARN] [GL]: Stock GLSL shaders will be used.
emu-main.js?v=2.3:2035 [INFO] [GLSL]: Found GLSL vertex shader.
emu-main.js?v=2.3:2035 [INFO] [GLSL]: Found GLSL fragment shader.
emu-main.js?v=2.3:2035 [INFO] [GLSL]: Linking GLSL program.
emu-main.js?v=2.3:2035 [INFO] [GLSL]: Found GLSL vertex shader.
emu-main.js?v=2.3:2035 [INFO] [GLSL]: Found GLSL fragment shader.
emu-main.js?v=2.3:2035 [INFO] [GLSL]: Linking GLSL program.
emu-main.js?v=2.3:2035 [INFO] [GLSL]: Found GLSL vertex shader.
emu-main.js?v=2.3:2035 [INFO] [GLSL]: Found GLSL fragment shader.
emu-main.js?v=2.3:2035 [INFO] [GLSL]: Linking GLSL program.
emu-main.js?v=2.3:2035 [INFO] [GL]: Using 4 textures.
emu-main.js?v=2.3:2035 [INFO] [GL]: Loaded 1 program(s).
emu-main.js?v=2.3:2035 [INFO] [Video]: Found display server: "null".
emu-main.js?v=2.3:2035 [INFO] [Display]: Found display driver: "gl".
emu-main.js?v=2.3:2035 [INFO] [Config]: Saved new config to "/home/web_user/retroarch/userdata/retroarch.cfg".
*A bunch of Asset Missing stuff from retroarch's OZONE menu*
e saved.
emu-main.js?v=2.3:2035 [INFO] [Playlist]: Loading history file: "/home/web_user/retroarch/userdata/content_history.lpl".
emu-main.js?v=2.3:2035 [INFO] [Playlist]: Loading history file: "/home/web_user/retroarch/userdata/content_music_history.lpl".
emu-main.js?v=2.3:2035 [INFO] [Playlist]: Loading favorites file: "/home/web_user/retroarch/userdata/content_favorites.lpl".
emu-main.js?v=2.3:2030 invalid core option pcsx_rearmed_memcard2

**Comment by ethanaobrien** [comment]
Most likely the bios. I’ll fix this when I can

**Comment by ethanaobrien** [comment]
I fixed the bios, still couldnt get playstation to work, I decided to remove support for the new playstation cores until thats been fixed

**Comment by Ramaerel** [comment]
Unless I'm missing something, the psx core still seems to default to the broken one. 

Out of curiosity, could the breaking have something to do with the last line regarding PCSX_rearmed_memcard2? Or does the Beetle PSX core use the same options as PCSX rearmed?

**Comment by ethanaobrien** [comment]
No that wouldn't affect it.

Clear your cache, make sure v.json is updated. I checked it's set to be unsupported on the new cores
