### ISSUE TITLE
[beta] N64 not working on Android

### ISSUE THREAD

**Issue by Ramaerel** [emulatorjs/emulatorjs#325]
Unfortunately, I can't get you a log for this one sorry.
It would appear that all n64 games seem to not function at all on all Android browsers. This is a new development, as the first update that updated the N64 core was working.

Edit to clarify: It goes past the rom loading and core loading, but once it loads into the emulator it goes to a black screen with the controls. The games work fine on PC, however

**Comment by ethanaobrien** [comment]
This cannot be fixed.

On mobile, I default to the old cores because they have more compatibility, and if even those don't work then there's nothing I can do.

There's nothing I can do because in a situation like this it is because the browser doesn't support the feature

Sorry

**Comment by Ramaerel** [comment]
All good, thought it might be a bug was all. Thank you
