### ISSUE TITLE
Error Missing old Mame2003 core

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#328]
Hi,

When trying to run the Killer instict game (mame2003) i got this error message  (when debug mode is TRUE):
Failed to load resource: the server responded with a status of 404 (Not Found): ..../data/old/mame2003-old-wasm.data?v=3

This file seems to be missing from the old directory.

**Comment by shaylevary** [comment]
After removing this command param "EJS_oldCores" the game is working ok.

**Comment by imneckro** [comment]
> After removing this command param "EJS_oldCores" the game is working ok.

Hello. Can you share your rom structure? Where did you place kinst chd etc?
Thanks in advance

**Comment by imneckro** [comment]
> After removing this command param "EJS_oldCores" the game is working ok.

Hello again. Did you manage to play killer instinct with mame2003?
