### ISSUE TITLE
Some thing is wrong here.

### ISSUE THREAD

**Issue by allancoding** [emulatorjs/emulatorjs#33]
This is the log:
loader.js:52 Path to data is set to https://allancoding.000webhostapp.com/snes-nes/emulator/
loader.js:7 Using emulatorjs version 0.4.23 but the newest version is 0.4.23-05
loader.js:1 Fetch finished loading: GET "https://raw.githack.com/ethanaobrien/emulatorjs/main/data/version.json".
(anonymous) @ loader.js:1
emulator.js?v=0.4.23:882 XHR finished loading: GET "https://allancoding.000webhostapp.com/snes-nes/emulator/v.json?t=1634329589".
(anonymous) @ emulator.js?v=0.4.23:882
_0x361fdc.exports @ emulator.js?v=0.4.23:839
_0x5db8bc.exports @ emulator.js?v=0.4.23:760
Promise.then (async)
_0x37287b.request @ emulator.js?v=0.4.23:684
_0x37287b.<computed> @ emulator.js?v=0.4.23:690
(anonymous) @ emulator.js?v=0.4.23:655
(anonymous) @ emulator.js?v=0.4.23:15457
setInterval (async)
(anonymous) @ emulator.js?v=0.4.23:15396
(anonymous) @ emulator.js?v=0.4.23:15499
_0x5127f4 @ emulator.js?v=0.4.23:13827
emulator.js?v=0.4.23:15046 Uncaught (in promise) ReferenceError: getHeadGameInfo is not defined
    at _0x5048db (emulator.js?v=0.4.23:15046)
    at _0x139f68 (emulator.js?v=0.4.23:15169)
    at _0x452592 (emulator.js?v=0.4.23:15254)
    at _0x10b71a (emulator.js?v=0.4.23:15336)
    at Object._0x4d7024.wasmData.window.Module.monitorRunDependencies (emulator.js?v=0.4.23:15347)
    at removeRunDependency (eval at _0x54d695 (emulator.js?v=0.4.23:15370), <anonymous>:8:15481)
    at receiveInstance (eval at _0x54d695 (emulator.js?v=0.4.23:15370), <anonymous>:8:16978)
    at receiveInstantiatedSource (eval at _0x54d695 (emulator.js?v=0.4.23:15370), <anonymous>:8:17098)
_0x5048db @ emulator.js?v=0.4.23:15046
_0x139f68 @ emulator.js?v=0.4.23:15169
_0x452592 @ emulator.js?v=0.4.23:15254
_0x10b71a @ emulator.js?v=0.4.23:15336
_0x4d7024.wasmData.window.Module.monitorRunDependencies @ emulator.js?v=0.4.23:15347
removeRunDependency @ VM68:8
receiveInstance @ VM68:8
receiveInstantiatedSource @ VM68:8
Promise.then (async)
instantiateArrayBuffer @ VM68:8
instantiateAsync @ VM68:8
createWasm @ VM68:8
Module.asm @ VM68:8
eval @ VM68:8
_0x54d695 @ emulator.js?v=0.4.23:15370
(anonymous) @ emulator.js?v=0.4.23:15374
_0xbae705 @ emulator.js?v=0.4.23:13842
_0x21d6a1 @ emulator.js?v=0.4.23:15378

**Comment by ethanaobrien** [comment]
Can I see your html file?

It seems as if you are clearing the `getHeadGameInfo` function defined in `loader.js` and then called in `emulator.js`

**Comment by alniles** [comment]
<title>Secret of Mana!</title>
<link rel="icon" type="image/png" href="emulator/img/icon.png"/>
<link rel="icon" type="image/png" href="emulator/img/icon.png"/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="main.css">
<script src="main.js"></script>
<div id="preloader"></div>
  <style>
.containerr { 
  top: 0;
  left: 0;
  position: fixed;
  z-index: 99999999;
  opacity: 0;
  transition: opacity .1s ease-in-out;
  -moz-transition: opacity .1s ease-in-out;
  -webkit-transition: opacity .1s ease-in-out;
}

.vertical--center {
  position: fixed;
  top: 0;
  left: 0;
  width: 150px;
  height: 180px;
}
.a{
    left: 60px !important;
    position: fixed;
}
.bot {
  padding: 5px;
  margin: 10px;
  border-radius: 50%;
  background-color: #ff1100;
  border: 2px solid black;
  width: 50px;
  height: 50px;
  font-size: 25px;
  color: white;
  cursor: pointer;
}
.containerr:hover {
  opacity: 1.0;
  transition: opacity .1s ease-in-out;
  -moz-transition: opacity .1s ease-in-out;
  -webkit-transition: opacity .1s ease-in-out;
}
#helppp{
    visibility: hidden;
    transition: opacity .1s ease-in-out;
  -moz-transition: opacity .1s ease-in-out;
  -webkit-transition: opacity .1s ease-in-out;
}
</style>
<div class="containerr">
    <div id="hov" class="vertical--center">
    <button id="helpp" onclick="window.location.href = '/snes-nes/';" class="bot">⬅</button>
    </div>
</div>
<div style="width:100%;hight:100%;">
        <div id="game"></div>
      </div>
<script type="text/javascript">
    EJS_player = '#game';
    EJS_gameUrl = 'SOM/SOM.smc.zip'; // Url to Game rom
    EJS_gameID = 20002; // ID in your website, required for netplay.
    EJS_core = 'snes';
    EJS_mouse = false; // SNES Mouse
    EJS_multitap = false; // SNES Multitap
    EJS_pathtodata = 'emulator/';
</script>
<script src="emulator/loader.js"></script>

**Comment by allancoding** [comment]
```
<title>Secret of Mana!</title>
<link rel="icon" type="image/png" href="emulator/img/icon.png"/>
<link rel="icon" type="image/png" href="emulator/img/icon.png"/>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="main.css">
<script src="main.js"></script>
<div id="preloader"></div>
  <style>
.containerr { 
  top: 0;
  left: 0;
  position: fixed;
  z-index: 99999999;
  opacity: 0;
  transition: opacity .1s ease-in-out;
  -moz-transition: opacity .1s ease-in-out;
  -webkit-transition: opacity .1s ease-in-out;
}

.vertical--center {
  position: fixed;
  top: 0;
  left: 0;
  width: 150px;
  height: 180px;
}
.a{
    left: 60px !important;
    position: fixed;
}
.bot {
  padding: 5px;
  margin: 10px;
  border-radius: 50%;
  background-color: #ff1100;
  border: 2px solid black;
  width: 50px;
  height: 50px;
  font-size: 25px;
  color: white;
  cursor: pointer;
}
.containerr:hover {
  opacity: 1.0;
  transition: opacity .1s ease-in-out;
  -moz-transition: opacity .1s ease-in-out;
  -webkit-transition: opacity .1s ease-in-out;
}
#helppp{
    visibility: hidden;
    transition: opacity .1s ease-in-out;
  -moz-transition: opacity .1s ease-in-out;
  -webkit-transition: opacity .1s ease-in-out;
}
</style>
<div class="containerr">
    <div id="hov" class="vertical--center">
    <button id="helpp" onclick="window.location.href = '/snes-nes/';" class="bot">⬅</button>
    </div>
</div>
<div style="width:100%;hight:100%;">
        <div id="game"></div>
      </div>
<script type="text/javascript">
    EJS_player = '#game';
    EJS_gameUrl = 'SOM/SOM.smc.zip'; // Url to Game rom
    EJS_gameID = 20002; // ID in your website, required for netplay.
    EJS_core = 'snes';
    EJS_mouse = false; // SNES Mouse
    EJS_multitap = false; // SNES Multitap
    EJS_pathtodata = 'emulator/';
</script>
<script src="emulator/loader.js"></script>
```

**Comment by ethanaobrien** [comment]
Try these things: 
1: make sure your emulatorjs version is up to date

2: add this code inside a script tag

```
window.getHeadGameInfo = function(normalFunc, url) {
	if (! url.startsWith('blob:')) {
		return normalFunc(url, {})
	} else {
		return async function() {
			//console.log('blob url')
			var a = await fetch(url)
			var a = await a.blob()
			return {headers:{'content-length': a.size, 'content-type': 'text/plain'}}
		}();
	}
}
```

**Comment by allancoding** [comment]
That fixed it!

**Comment by ethanaobrien** [comment]
Which one?

**Comment by allancoding** [comment]
All the errors!

**Comment by ethanaobrien** [comment]
Which method did you use? Adding the additional code or checking for an update

**Comment by allancoding** [comment]
Both!
