### ISSUE TITLE
"Missing Mame Config" - When trying to play Golden Axe Death Adder (MAME core)

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#331]
Hi,

When i try to play "Golden Axe Death Adder" (MAME), I get an error message: "Missing Mame Config".
EJS_core = 'mame';

Do i need to set the "EJS_mameCore" param? if yes, what do i need to enter?

**Comment by ethanaobrien** [comment]
Yes, you set the name config to `savestates|corenumber`

Save states - whether or not you can save/load states. Must be 0 or 1.

Core number - which core to use. Must be 1, 2, 3, 4, 5, or 6.

Which does what I do not know you'll have to go through and test them all
