### ISSUE TITLE
Shader selection doesn't appear after refresh - SNES CORE

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#333]
Hi,

There is a problem in the latest script version with the Shader settings of the SNES Core.
When I select a certain shader setting (2xsai) and refresh the browser, the selected setting is saved in the settings, but doesn't activate (it appear as "disabled" - check attached screenshot).
In order to solve it, i need to click on Shader->Disabled again and than re-enable the same Shader setting again.
![snes_shader](https://user-images.githubusercontent.com/10597517/185073946-2bd886c3-e3d4-499b-b03e-91a4769cf4bb.jpg)

Thanks in advance.

**Comment by ethanaobrien** [comment]
Fixes
