### ISSUE TITLE
"Arcade Core" - After loading ROM - game doesn't run

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#335]
Hi,

After updating to the latest script files, All my "arcade core" games stopped working.
Here is my "Final Fight" console log:

ErrnoError {node: undefined, errno: 2, message: 'FS error', stack: '<generic error, no stack>', setErrno: ƒ}
emu-main.js?v=23.3:2034 [INFO] RetroArch 1.7.7 (Git e97c35ec2d)
emu-main.js?v=23.3:2034 [INFO] Redirecting save file to "/data/saves/ffight.srm".
emu-main.js?v=23.3:2034 [INFO] Redirecting savestate to "/home/web_user/retroarch/userdata/states/ffight.state".
emu-main.js?v=23.3:2034 [INFO] === Build =======================================
emu-main.js?v=23.3:2034 [INFO] Capabilities: 
emu-main.js?v=23.3:2034 [INFO] Built: Apr 15 2020
emu-main.js?v=23.3:2034 [INFO] Version: 1.7.7
emu-main.js?v=23.3:2034 [INFO] Git: e97c35ec2d
emu-main.js?v=23.3:2034 [INFO] =================================================
emu-main.js?v=23.3:2034 [INFO] [Overrides] no core-specific overrides found at /etc/FB Alpha/FB Alpha.cfg.
emu-main.js?v=23.3:2034 [INFO] [Overrides] no content-dir-specific overrides found at /etc/FB Alpha/F.cfg.
emu-main.js?v=23.3:2034 [INFO] [Overrides] no game-specific overrides found at /etc/FB Alpha/ffight.cfg.
emu-main.js?v=23.3:2034 [INFO] [recording] twitch streaming key empty
emu-main.js?v=23.3:2034 [INFO] Environ SET_VARIABLES.
emu-main.js?v=23.3:2034 [INFO] [Remaps]: remap directory: /home/web_user/retroarch/userdata/config/remaps
emu-main.js?v=23.3:2034 [INFO] [Remaps]: no game-specific remap found at /home/web_user/retroarch/userdata/config/remaps/FB Alpha/ffight.rmp.
emu-main.js?v=23.3:2034 [INFO] [Remaps]: no content-dir-specific remap found at /home/web_user/retroarch/userdata/config/remaps/FB Alpha/F.rmp.
emu-main.js?v=23.3:2034 [INFO] [Remaps]: no core-specific remap found at /home/web_user/retroarch/userdata/config/remaps/FB Alpha/FB Alpha.rmp.
emu-main.js?v=23.3:2034 [INFO] Redirecting save file to "/data/saves/ffight.srm".
emu-main.js?v=23.3:2034 [INFO] Redirecting savestate to "/home/web_user/retroarch/userdata/states/ffight.state".
emu-main.js?v=23.3:2034 [INFO] Environ GET_LOG_INTERFACE.
emu-main.js?v=23.3:2034 [INFO] Content loading skipped. Implementation will load it on its own.
emu-main.js?v=23.3:2034 [libretro INFO] Setting save dir to /data/saves
emu-main.js?v=23.3:2034 [INFO] Environ SYSTEM_DIRECTORY: "/".
emu-main.js?v=23.3:2034 [libretro INFO] Setting system dir to /
emu-main.js?v=23.3:2034 [libretro INFO] set_environment: SYSTEM: 8, DIPSWITCH: 0, MACRO: 0
emu-main.js?v=23.3:2034 [libretro INFO] retro_variable (SYSTEM)    { 'fba-aspect', 'Core-provided aspect ratio; DAR|PAR' }
emu-main.js?v=23.3:2034 [libretro INFO] retro_variable (SYSTEM)    { 'fba-cpu-speed-adjust', 'CPU overclock; 100|110|120|130|140|150|160|170|180|190|200' }
emu-main.js?v=23.3:2034 [libretro INFO] retro_variable (SYSTEM)    { 'fba-controls-p1', 'Control scheme; gamepad|arcade' }
emu-main.js?v=23.3:2034 [libretro INFO] retro_variable (SYSTEM)    { 'fba-controls-p2', 'Control scheme; gamepad|arcade' }
emu-main.js?v=23.3:2034 [libretro INFO] retro_variable (SYSTEM)    { 'fba-sh2-mode', 'Psikyo/Kaneko SH2 mode (need 'hard' restart); accurate|fast' }
emu-main.js?v=23.3:2034 [libretro INFO] retro_variable (SYSTEM)    { 'fba-hiscores', 'Hiscores; enabled|disabled' }
emu-main.js?v=23.3:2034 [libretro INFO] retro_variable (SYSTEM)    { 'fba-lr-controls-p1', 'L/R P1 gamepad scheme; normal|remap to R1/R2' }
emu-main.js?v=23.3:2034 [libretro INFO] retro_variable (SYSTEM)    { 'fba-lr-controls-p2', 'L/R P2 gamepad scheme; normal|remap to R1/R2' }
emu-main.js?v=23.3:2034 [INFO] Environ SET_VARIABLES.
emu-main.js?v=23.3:2034 [INFO] Saved core options file to "/etc/retroarch-core-options.cfg"
emu-main.js?v=23.3:2034 [libretro INFO] [FBA] Archive: ffight
**emu-main.js?v=23.3:2034 [libretro ERROR] [FBA] Failed to find archive: ffight, let's continue with other archives...**
emu-main.js?v=23.3:2034 [libretro ERROR] [FBA] ROM at index 0 with CRC 0xf9a5ce83 is required ...
emu-main.js?v=23.3:2034 [libretro ERROR] [FBA] Cannot find driver.
emu-main.js?v=23.3:2034 [libretro ERROR] [FBA] Cannot load this game.
emu-main.js?v=23.3:2034 [ERROR] Failed to load content
emu-main.js?v=23.3:2034 [INFO] Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
emu-main.js?v=23.3:2034 [INFO] Unloading game..
emu-main.js?v=23.3:2034 [INFO] Unloading core..
emu-main.js?v=23.3:2034 [INFO] Unloading core symbols..
emu-main.js?v=23.3:2034 [INFO] Saved core options file to "/etc/retroarch-core-options.cfg"
emu-main.js?v=23.3:2034 [INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
emu-main.js?v=23.3:2034 [INFO] [recording] twitch streaming key empty
emu-main.js?v=23.3:2034 [INFO] [Overrides] configuration overrides unloaded, original configuration restored.
048518b2:0xc07c47 Uncaught RuntimeError: memory access out of bounds
    at 048518b2:0xc07c47
    at 048518b2:0x6a273
    at 048518b2:0x7a1a5
    at Module._set_variable (eval at _0x54d695 (emu-main.js?v=23.3:1982:44), <anonymous>:8:228938)
    at ccall (eval at _0x54d695 (emu-main.js?v=23.3:1982:44), <anonymous>:8:7767)
    at Object.eval [as setVariable] (eval at _0x54d695 (emu-main.js?v=23.3:1982:44), <anonymous>:8:8117)
    at _0x6954aa.updateCoreOptions (emu-main.js?v=23.3:5162:142)
    at emu-main.js?v=23.3:5305:53
    at Array.forEach (<anonymous>)
    at HTMLDivElement.<anonymous> (emu-main.js?v=23.3:5304:62)
$func45975 @ 048518b2:0xc07c47
$func826 @ 048518b2:0x6a273
$_set_variable @ 048518b2:0x7a1a5
Module._set_variable @ VM1347:8
ccall @ VM1347:8
eval @ VM1347:8
updateCoreOptions @ emu-main.js?v=23.3:5162
(anonymous) @ emu-main.js?v=23.3:5305
(anonymous) @ emu-main.js?v=23.3:5304
_0xbae705 @ emu-main.js?v=23.3:253
start @ emu-main.js?v=23.3:1479
_0x3512e9 @ emu-main.js?v=23.3:1545
(anonymous) @ emu-main.js?v=23.3:1649
_0x2b6d6d.oncomplete @ emulator.js?v=23.3:398
6048518b2:0xc07c47 Uncaught RuntimeError: memory access out of bounds
    at 048518b2:0xc07c47
    at 048518b2:0x6a273
    at 048518b2:0x7a1a5
    at Module._set_variable (eval at _0x54d695 (emu-main.js?v=23.3:1982:44), <anonymous>:8:228938)
    at ccall (eval at _0x54d695 (emu-main.js?v=23.3:1982:44), <anonymous>:8:7767)
    at Object.eval [as setVariable] (eval at _0x54d695 (emu-main.js?v=23.3:1982:44), <anonymous>:8:8117)
    at HTMLDivElement.<anonymous> (emu-main.js?v=23.3:1905:47)
    at _0x6954aa._0xbae705 (emu-main.js?v=23.3:253:23)
    at start (emu-main.js?v=23.3:1479:43)
    at _0x3512e9 (emu-main.js?v=23.3:1545:29)
$func45975 @ 048518b2:0xc07c47
$func826 @ 048518b2:0x6a273
$_set_variable @ 048518b2:0x7a1a5
Module._set_variable @ VM1347:8
ccall @ VM1347:8
eval @ VM1347:8
(anonymous) @ emu-main.js?v=23.3:1905
_0xbae705 @ emu-main.js?v=23.3:253
start @ emu-main.js?v=23.3:1479
_0x3512e9 @ emu-main.js?v=23.3:1545
(anonymous) @ emu-main.js?v=23.3:1649
_0x2b6d6d.oncomplete @ emulator.js?v=23.3:398
emu-main.js?v=23.3:2029 53
emu-main.js?v=23.3:2034 53
VM1347:8 Uncaught abort("53"). Build with -s ASSERTIONS=1 for more info.
runIter @ VM1347:8
Browser_mainLoop_runner @ VM1347:8
requestAnimationFrame (async)
requestAnimationFrame @ VM1347:8
Browser_mainLoop_scheduler_rAF @ VM1347:8
_emscripten_set_main_loop @ VM1347:8
$_main @ 048518b2:0x7aae7
Module._main @ VM1347:8
callMain @ VM1347:8
start @ emu-main.js?v=23.3:1468
_0x3512e9 @ emu-main.js?v=23.3:1545
(anonymous) @ emu-main.js?v=23.3:1649
_0x2b6d6d.oncomplete @ emulator.js?v=23.3:398
emu-main.js?v=23.3:4132 hidden
emu-main.js?v=23.3:4132 active

**Comment by ethanaobrien** [comment]
That's really strange, the rom seems to completely be missing.

Could you type in the console `FS.root.contents`, expand that, and send a screenshot?

Also could you send the html code you have so I could look at that

**Comment by shaylevary** [comment]
On the previous version from 18/08 it's working fine, the problem appears only on latest build.

I've tried to type what you've asked in my console and got this error message:
VM498:1 Uncaught ReferenceError: FS is not defined
    at <anonymous>:1:1

Here is my html:

<div id="playframe" style="width:800px;height:600px;max-width:100%;">
<div id="game"></div>
</div>
<script type="text/javascript">
 EJS_player = '#game';
 EJS_startOnLoaded = false;
 EJS_core = 'arcade';
 EJS_BETA = true;
 EJS_gameUrl = 'ffight.zip';
EJS_gameName = 'final_fight_1';
 EJS_pathtodata = '/data/';
EJS_DEBUG_XX = true;
</script>
<script src="/data/loader.js"></script>


Here is the console log again when running this code:
ErrnoError {node: undefined, errno: 2, message: 'FS error', stack: '<generic error, no stack>', setErrno: ƒ}errno: 2message: "FS error"node: undefinedsetErrno: ƒ (errno)stack: "<generic error, no stack>"[[Prototype]]: Error
    at Object.ensureErrnoError (eval at _0x54d695 (/data/emu-main.js?v=23.3:1982:44), <anonymous>:8:108166)
    at Object.staticInit (eval at _0x54d695 (/data/emu-main.js?v=23.3:1982:44), <anonymous>:8:108385)
    at eval (eval at _0x54d695 (/data/emu-main.js?v=23.3:1982:44), <anonymous>:8:205489)
    at _0x54d695 (/data/emu-main.js?v=23.3:1983:133)
    at HTMLDivElement.<anonymous> (/data/emu-main.js?v=23.3:1994:29)
    at _0x6954aa._0xbae705 (/data/emu-main.js?v=23.3:253:23)
    at Worker._0x21d6a1 (/data/emu-main.js?v=23.3:1998:76)
emu-main.js?v=23.3:2034 [INFO] RetroArch 1.7.7 (Git e97c35ec2d)
emu-main.js?v=23.3:2034 [INFO] Redirecting save file to "/data/saves/ffight.srm".
emu-main.js?v=23.3:2034 [INFO] Redirecting savestate to "/home/web_user/retroarch/userdata/states/ffight.state".
emu-main.js?v=23.3:2034 [INFO] === Build =======================================
emu-main.js?v=23.3:2034 [INFO] Capabilities: 
emu-main.js?v=23.3:2034 [INFO] Built: Apr 15 2020
emu-main.js?v=23.3:2034 [INFO] Version: 1.7.7
emu-main.js?v=23.3:2034 [INFO] Git: e97c35ec2d
emu-main.js?v=23.3:2034 [INFO] =================================================
emu-main.js?v=23.3:2034 [INFO] [Overrides] no core-specific overrides found at /etc/FB Alpha/FB Alpha.cfg.
emu-main.js?v=23.3:2034 [INFO] [Overrides] no content-dir-specific overrides found at /etc/FB Alpha/F.cfg.
emu-main.js?v=23.3:2034 [INFO] [Overrides] no game-specific overrides found at /etc/FB Alpha/ffight.cfg.
emu-main.js?v=23.3:2034 [INFO] [recording] twitch streaming key empty
emu-main.js?v=23.3:2034 [INFO] Environ SET_VARIABLES.
emu-main.js?v=23.3:2034 [INFO] [Remaps]: remap directory: /home/web_user/retroarch/userdata/config/remaps
emu-main.js?v=23.3:2034 [INFO] [Remaps]: no game-specific remap found at /home/web_user/retroarch/userdata/config/remaps/FB Alpha/ffight.rmp.
emu-main.js?v=23.3:2034 [INFO] [Remaps]: no content-dir-specific remap found at /home/web_user/retroarch/userdata/config/remaps/FB Alpha/F.rmp.
emu-main.js?v=23.3:2034 [INFO] [Remaps]: no core-specific remap found at /home/web_user/retroarch/userdata/config/remaps/FB Alpha/FB Alpha.rmp.
emu-main.js?v=23.3:2034 [INFO] Redirecting save file to "/data/saves/ffight.srm".
emu-main.js?v=23.3:2034 [INFO] Redirecting savestate to "/home/web_user/retroarch/userdata/states/ffight.state".
emu-main.js?v=23.3:2034 [INFO] Environ GET_LOG_INTERFACE.
emu-main.js?v=23.3:2034 [INFO] Content loading skipped. Implementation will load it on its own.
emu-main.js?v=23.3:2034 [libretro INFO] Setting save dir to /data/saves
emu-main.js?v=23.3:2034 [INFO] Environ SYSTEM_DIRECTORY: "/".
emu-main.js?v=23.3:2034 [libretro INFO] Setting system dir to /
emu-main.js?v=23.3:2034 [libretro INFO] set_environment: SYSTEM: 8, DIPSWITCH: 0, MACRO: 0
emu-main.js?v=23.3:2034 [libretro INFO] retro_variable (SYSTEM)    { 'fba-aspect', 'Core-provided aspect ratio; DAR|PAR' }
emu-main.js?v=23.3:2034 [libretro INFO] retro_variable (SYSTEM)    { 'fba-cpu-speed-adjust', 'CPU overclock; 100|110|120|130|140|150|160|170|180|190|200' }
emu-main.js?v=23.3:2034 [libretro INFO] retro_variable (SYSTEM)    { 'fba-controls-p1', 'Control scheme; gamepad|arcade' }
emu-main.js?v=23.3:2034 [libretro INFO] retro_variable (SYSTEM)    { 'fba-controls-p2', 'Control scheme; gamepad|arcade' }
emu-main.js?v=23.3:2034 [libretro INFO] retro_variable (SYSTEM)    { 'fba-sh2-mode', 'Psikyo/Kaneko SH2 mode (need 'hard' restart); accurate|fast' }
emu-main.js?v=23.3:2034 [libretro INFO] retro_variable (SYSTEM)    { 'fba-hiscores', 'Hiscores; enabled|disabled' }
emu-main.js?v=23.3:2034 [libretro INFO] retro_variable (SYSTEM)    { 'fba-lr-controls-p1', 'L/R P1 gamepad scheme; normal|remap to R1/R2' }
emu-main.js?v=23.3:2034 [libretro INFO] retro_variable (SYSTEM)    { 'fba-lr-controls-p2', 'L/R P2 gamepad scheme; normal|remap to R1/R2' }
emu-main.js?v=23.3:2034 [INFO] Environ SET_VARIABLES.
emu-main.js?v=23.3:2034 [INFO] Saved core options file to "/etc/retroarch-core-options.cfg"
emu-main.js?v=23.3:2034 [libretro INFO] [FBA] Archive: ffight
**emu-main.js?v=23.3:2034 [libretro ERROR] [FBA] Failed to find archive: ffight, let's continue with other archives...
emu-main.js?v=23.3:2034 [libretro ERROR] [FBA] ROM at index 0 with CRC 0xf9a5ce83 is required ...
emu-main.js?v=23.3:2034 [libretro ERROR] [FBA] Cannot find driver.
emu-main.js?v=23.3:2034 [libretro ERROR] [FBA] Cannot load this game.
emu-main.js?v=23.3:2034 [ERROR] Failed to load content**
emu-main.js?v=23.3:2034 [INFO] Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
emu-main.js?v=23.3:2034 [INFO] Unloading game..
emu-main.js?v=23.3:2034 [INFO] Unloading core..
emu-main.js?v=23.3:2034 [INFO] Unloading core symbols..
emu-main.js?v=23.3:2034 [INFO] Saved core options file to "/etc/retroarch-core-options.cfg"
emu-main.js?v=23.3:2034 [INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
emu-main.js?v=23.3:2034 [INFO] [recording] twitch streaming key empty
emu-main.js?v=23.3:2034 [INFO] [Overrides] configuration overrides unloaded, original configuration restored.
**VM32:8 Uncaught ErrnoError {node: undefined, errno: 2, message: 'FS error', stack: 'Error\n    at new ErrnoError (eval at _0x54d695 (ht…il/engine/console/data/emu-main.js?v=23.3:1627:41', setErrno: ƒ}**
open @ VM32:8
readFile @ VM32:8
setShader @ emu-main.js?v=23.3:3400
(anonymous) @ emu-main.js?v=23.3:5281
_0xbae705 @ emu-main.js?v=23.3:253
start @ emu-main.js?v=23.3:1479
_0x3512e9 @ emu-main.js?v=23.3:1545
(anonymous) @ emu-main.js?v=23.3:1627
Promise.then (async)
_0x43a689 @ emu-main.js?v=23.3:1589
(anonymous) @ emu-main.js?v=23.3:1650
_0x2b6d6d.oncomplete @ emulator.js?v=23.3:398
emu-main.js?v=23.3:2029 53
emu-main.js?v=23.3:2034 53
VM32:8 Uncaught abort("53"). Build with -s ASSERTIONS=1 for more info.
runIter @ VM32:8
Browser_mainLoop_runner @ VM32:8
requestAnimationFrame (async)
requestAnimationFrame @ VM32:8
Browser_mainLoop_scheduler_rAF @ VM32:8
_emscripten_set_main_loop @ VM32:8
$_main @ 048518b2:0x7aae7
Module._main @ VM32:8
callMain @ VM32:8
start @ emu-main.js?v=23.3:1468
_0x3512e9 @ emu-main.js?v=23.3:1545
(anonymous) @ emu-main.js?v=23.3:1627
Promise.then (async)
_0x43a689 @ emu-main.js?v=23.3:1589
(anonymous) @ emu-main.js?v=23.3:1650
_0x2b6d6d.oncomplete @ emulator.js?v=23.3:398
emu-main.js?v=23.3:4132 hidden
emu-main.js?v=23.3:4132 active

**Comment by ethanaobrien** [comment]
Ah yes, there is no new core for the arcade system yet meaning FS is not defined in a global scope. Can you do the same with `EJS_MODULE.FS.root.contents`

**Comment by shaylevary** [comment]
I'm not sure if i understand you, but i've tried to type "Module.FS.root.contents" and got similar error code:
Uncaught TypeError: Cannot read properties of undefined (reading 'FS')

**Comment by ethanaobrien** [comment]
Oh sorry, just edited my comment, try `EJS_MODULE.FS.root.contents`

**Comment by ethanaobrien** [comment]
I just tested on my computer with the exact same config settings and the same game, it worked for me

**Comment by ethanaobrien** [comment]
I'm assuming this is resolved, I tested it myself and it worked fine, I also just compiled arcade to the new cores so that should work now (what're the chances your rom is bad?)

**Comment by shaylevary** [comment]
> Oh sorry, just edited my comment, try `EJS_MODULE.FS.root.contents`

I've uploaded the console log i've got when i've typed this command:
[console.log](https://github.com/ethanaobrien/emulatorjs/files/9394745/console.log)

If you want, i can also send you my rom.

As i've mentioned, when replacing the root js file to the previous version from 18/08 - it works fine.

**Comment by ethanaobrien** [comment]
Try again with the new files. It should work now.

Do you have a game patch file?

**Comment by shaylevary** [comment]
Hi,

I've updated the new files, but there is no change.
When i disable the debug mode, and overwrite only the previous file "emulator.min.js" from 18/08 - it's working fine.
So i guess it's a bug on this specific file.

I don't use separate patch file, here is my rom files list:
buf1
ff_09.12b
ff_18.11c
ff_19.12c
ff_36.11f
ff_37.12f
ff_42.11h
ff-1m.3a
ff-3m.5a
ff-5m.7a
ff-7m.9a
ff-32m.8h
ffe_43.12h
ioa1
iob1.11e
prg1
rom1
s224b.1a
sou1

**Comment by ethanaobrien** [comment]
They should all be zipped together. This works for me so its something youre doing.

**Comment by shaylevary** [comment]
Don't know what to tell you, but from my side, all Arcade ROM doesn't work since latest build.
Let's wait and see if more users will encounter the same issue.

**Comment by shaylevary** [comment]
I got similar problem with psx roms, it suddenly doesn't find the rom in order to load it.

Here is the errors on my console log when running psx game "tekken 3":
ErrnoError {node: undefined, errno: 2, code: 'ENOENT', message: 'No such file or directory', setErrno: ƒ, …}

.
.
.
RetroArch [WARN] :: SYSTEM DIR is empty, assume CONTENT DIR https://localhost/wp-content/uploads/games/console/T/tekken3.pbp
emu-main.js?v=23.4:2037 RetroArch [INFO] :: Environ SYSTEM_DIRECTORY: "https://localhost/wp-content/uploads/games/console/T/".
emu-main.js?v=23.4:2032 no BIOS files found.
emu-main.js?v=23.4:2037 RetroArch [INFO] :: Environ SET_MESSAGE: No PlayStation BIOS file found - add for better compatibility
.
.
.
Could't open 'https://localhost/wp-content/uploads/games/console/T/tekken3.pbp' for reading: No such file or directory
emu-main.js?v=23.4:2032 Error opening CD-ROM plugin!
emu-main.js?v=23.4:2037 RetroArch [libretro INFO] :: failed to open plugins
emu-main.js?v=23.4:2037 RetroArch [ERROR] :: Failed to load content.
emu-main.js?v=23.4:2037 RetroArch [INFO] :: Resetting undo buffers.
emu-main.js?v=23.4:2037 RetroArch [INFO] :: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
VM66:1 Uncaught TypeError: str.charCodeAt is not a function
    at lengthBytesUTF8 (eval at _0x54d695 (emu-main.js?v=23.4:1985:44), <anonymous>:1:16934)
    at Object.writeFile (eval at _0x54d695 (emu-main.js?v=23.4:1985:44), <anonymous>:1:137914)
    at Object.setShader (emu-main.js?v=23.4:3403:34)
    at HTMLDivElement.<anonymous> (emu-main.js?v=23.4:5284:35)
    at _0x6954aa._0xbae705 (emu-main.js?v=23.4:253:23)
    at start (emu-main.js?v=23.4:1482:43)
    at _0x3512e9 (emu-main.js?v=23.4:1548:29)
    at emu-main.js?v=23.4:1630:41
.
.
VM81:1 Uncaught TypeError: str.charCodeAt is not a function
    at lengthBytesUTF8 (eval at _0x54d695 (emu-main.js?v=23.4:1985:44), <anonymous>:1:16934)
    at Object.writeFile (eval at _0x54d695 (emu-main.js?v=23.4:1985:44), <anonymous>:1:137914)
    at Object.setShader (emu-main.js?v=23.4:3403:34)
    at HTMLDivElement.<anonymous> (emu-main.js?v=23.4:5284:35)
    at _0x6954aa._0xbae705 (emu-main.js?v=23.4:253:23)
    at start (emu-main.js?v=23.4:1482:43)
    at _0x3512e9 (emu-main.js?v=23.4:1548:29)
    at emu-main.js?v=23.4:1630:41
lengthBytesUTF8 @ VM81:1
writeFile @ VM81:1
setShader @ emu-main.js?v=23.4:3403
(אנונימי) @ emu-main.js?v=23.4:5284
_0xbae705 @ emu-main.js?v=23.4:253
start @ emu-main.js?v=23.4:1482
_0x3512e9 @ emu-main.js?v=23.4:1548
(אנונימי) @ emu-main.js?v=23.4:1630
Promise.then (אסינכרוני)
_0x43a689 @ emu-main.js?v=23.4:1592
(אנונימי) @ emu-main.js?v=23.4:1653
_0x2b6d6d.oncomplete @ emulator.js?v=23.4:398
emu-main.js?v=23.4:2032 video_context_driver_check_window a
emu-main.js?v=23.4:2032 video_context_driver_check_window 0
emu-main.js?v=23.4:2037 RetroArch [INFO] :: Saving config at path: "/home/web_user/.config/retroarch/retroarch.cfg"
emu-main.js?v=23.4:2037 RetroArch [INFO] :: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
emu-main.js?v=23.4:2032 5
emu-main.js?v=23.4:2037 5
VM81:1 Uncaught abort(5) at Error
    at jsStackTrace (eval at _0x54d695 (https://www.minigames.co.il/engine/console/data/emu-main.js?v=23.4:1985:44), <anonymous>:1:18019)
    at stackTrace (eval at _0x54d695 (https://www.minigames.co.il/engine/console/data/emu-main.js?v=23.4:1985:44), <anonymous>:1:18190)
    at abort (eval at _0x54d695 (https://www.minigames.co.il/engine/console/data/emu-main.js?v=23.4:1985:44), <anonymous>:1:290639)
    at wasm://wasm/00601ec6:wasm-function[3227]:0x13d690
    at wasm://wasm/00601ec6:wasm-function[558]:0x1e299
    at wasm://wasm/00601ec6:wasm-function[395]:0x57af
    at wasm://wasm/00601ec6:wasm-function[439]:0x1753d
    at wasm://wasm/00601ec6:wasm-function[1089]:0x454ac
    at wasm://wasm/00601ec6:wasm-function[3216]:0x13d5ea
    at Object.eval [as dynCall_v] (eval at _0x54d695 (https://www.minigames.co.il/engine/console/data/emu-main.js?v=23.4:1985:44), <anonymous>:1:285875)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
.
.
.
Uncaught Event {isTrusted: true, type: 'abort', target: IDBTransaction, currentTarget: IDBTransaction, eventPhase: 2, …}

**Comment by ethanaobrien** [comment]
This is a bug...  I see what I did wrong, sorry for that. I'll get this fixed

**Comment by ethanaobrien** [comment]
This should be fixed

**Comment by shaylevary** [comment]
Thank you, everything is working great again!
