### ISSUE TITLE
Virtual Gamepad - option to change text size

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#336]
Hi,

When I set the START / SELECT location to the "right" (instead of "center"), the text size get larger (similar to the action buttons fonts).
I think it will be nice if you can add an option to set the font size, and the block / circle radius size - this way I can add text inside the button (for example: kick, jump, ect… )
![Screenshot_20220822-193204_Chrome](https://user-images.githubusercontent.com/10597517/185973615-96cdc8da-afaa-40a8-8a78-67ba717e973e.jpg)

**Comment by ethanaobrien** [comment]
Done

**Comment by shaylevary** [comment]
Thank you, works great!
Keep the good work!
