### ISSUE TITLE
RAM error

### ISSUE THREAD

**Issue by darkworks** [emulatorjs/emulatorjs#339]
Am getting this ram error more like windows blue screen of death lol

![image](https://user-images.githubusercontent.com/12841788/186176133-23492e23-1cdc-40bd-a096-e8a55621d107.png)

**log**
```js
VM309:1 Uncaught ErrnoError {node: undefined, errno: 2, code: 'ENOENT', message: 'No such file or directory', setErrno: ƒ}
open @ VM309:1
readFile @ VM309:1
setShader @ emulator.min.js?v=23.5:1
(anonymous) @ emulator.min.js?v=23.5:1
G @ emulator.min.js?v=23.5:1
n @ emulator.min.js?v=23.5:1
A @ emulator.min.js?v=23.5:1
(anonymous) @ emulator.min.js?v=23.5:1
Promise.then (async)
t @ emulator.min.js?v=23.5:1
(anonymous) @ emulator.min.js?v=23.5:1
i.oncomplete @ emulator.min.js?v=23.5:1

```
have cloned repo and loaded sega saturn metal slug rom : https://coolrom.com.au/roms/saturn/98/Metal_Slug.php

but no success getting Blue screen with ram warning

**Comment by ethanaobrien** [comment]
I can't fix this
