### ISSUE TITLE
/data/saves Browser storage IndexedDB

### ISSUE THREAD

**Issue by thelamer** [emulatorjs/emulatorjs#34]
When launching a game there seems to be logic to store a stateful buffer in browser storage specifically named `/data/saves` which in turn acts like a memory card for the emulated game and stashes saved game data there for whenever it is re-launched. 
For some reason I had it working initially, (have git pulled since then) but when hosting locally those buffers are no longer generated. I have tried walking back in the commit history with no luck.
Can anyone replicate this or am I alone here? (You can check for timestamp entries in the DB from your browser console under application) 

Also side note looks like https://www.emulatorjs.com has been updated pretty extensively also added master system support.

**Comment by ethanaobrien** [comment]
@thelamer Are you testing with a single game. Some systems do not have support for this.

**Comment by thelamer** [comment]
It's across the board, I even rendered in examples pages from emulatorjs.com using their js loader. srm is created on their page but not on a localhost hosting of the identical html. It creates the DB and columns just no srm file there. IE https://www.emulatorjs.com/snes.html . I'm beginning to wonder if it is related to my local hosting setup. 
If no one else has this issue I'll close this out, just wondering before I go further into troubleshooting.

**Comment by ethanaobrien** [comment]
Yeah, from what I've found this feature doesn't work on localhost. I have something in my TODO to change that may fix the problem but I don't really expect it to.

**Comment by thelamer** [comment]
No it is more than that, here check this out: 
https://www.taisun.io/game.html
Start game no SRM created (tag timestamp in the location I referenced above)
https://www.emulatorjs.com/snes.html
Start game SRM created perfectly fine, this html is pretty basic and identical to the example on that page.

**Comment by thelamer** [comment]
Man now after I cleared site data in my console the SRM is no longer created even on emulatorjs.com. There has to be some kind of logic block somewhere that should optimally check for existence and create if not there.

**Comment by ethanaobrien** [comment]
If you want to investigate, search the `emulator.js` file for `/data/saves` and try to learn what it does and how it works

**Comment by thelamer** [comment]
I got it, srm file saving is triggered by the `beforeunload` window event, it spins off an FS sync event and does a dump of the contents. It was simply a problem with my testing procedure I was expecting it to create on load when in fact it creates it on proper window exit. Kind of an FYI though, closing the window might not save the game you should always use back.
