### ISSUE TITLE
The notification for loading a state in an n64 game doesn't get cleared

### ISSUE THREAD

**Issue by Wade7wastaken** [emulatorjs/emulatorjs#343]
[localhost-1661396966296.log](https://github.com/ethanaobrien/emulatorjs/files/9420740/localhost-1661396966296.log)

When loading a state with a hotkey, the notification gets stuck at 97% and is never cleared.

![image](https://user-images.githubusercontent.com/86390605/186558729-ddb840e2-0daa-4d80-b1c7-dbcf5facbb96.png)

I loaded these states at the title screen, and they were still there 30 seconds later.

However, If you load a state that doesn't exist, the notification gets properly cleared.

**Comment by ethanaobrien** [comment]
Fixed
