### ISSUE TITLE
axioserror: Network Error

### ISSUE THREAD

**Issue by Smev1** [emulatorjs/emulatorjs#344]
When you embed it into a website it can sometimes say axioserror: Network Error and I would like to know what is causing that?

Here's the website link it sometime loads the ui but not the game and heres the github

https://hotboi69.github.io/helloworld/

https://github.com/hotboi69/helloworld

**Comment by ethanaobrien** [comment]
I don't use axios anymore. You're using the emulatorjs.com website, not this project, they're very different
