### ISSUE TITLE
Website Problem

### ISSUE THREAD

**Issue by Smev1** [emulatorjs/emulatorjs#346]
when clicking code editor under select a console there are no options just blank.

**Comment by Smev1** [comment]
nvm only happens sometimes

**Comment by ethanaobrien** [comment]
You can comment on closed issues you know

**Comment by Smev1** [comment]
On ds instead of booting up the game it boots up retroarch

**Comment by ethanaobrien** [comment]
Then your rom is invaid

**Comment by Smev1** [comment]
ok thanks do I do the zip file or the nds file

**Comment by ethanaobrien** [comment]
Sorry for the delay, in the code helper I'd recommend turning on the feature to make it work offline. Then you wouldn't need to worry about any other issues (other than githack being blocked). The file can be zipped or not it doesn't matter

**Comment by Smev1** [comment]
ok thank you also you should make a tutorial on how to do this I know it's not that confusing but it might be helpful and how would I unblock githack if possible UPDATE: It worked fine when I opened the Index.html file but when I put it on github the game wasn't working

**Comment by allancoding** [comment]
I fixed to loading issue. I should be fixed
