### ISSUE TITLE
Virtual Gamepad - switch left/right location appearance

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#349]
Hi,
I think it would be nice if you can a feature for the user to select the appearance side of the virtual gamepad  (it can be add under settings -> Virtual Gamepad menu).
For example, the nipple now appears on the left side, and the user prefers, for his convenience, that the nipple will appear on the right side, so by pressing a button from menu, he can switch the the appearance side of the Virtual Gamepad.

Thanks in advance. 

![vpad-switch-nipple-left](https://user-images.githubusercontent.com/10597517/187510904-ad4284d5-a293-4bc4-ad1f-f753818ceb03.jpg)
![vpad-switch-nipple-right](https://user-images.githubusercontent.com/10597517/187510910-5d923cbe-75ac-4bbf-af58-774cd5c86640.jpg)

**Comment by ethanaobrien** [comment]
Just letting you know, I'm putting a temporary hold on all the enhancements. I do plan to do them all, I am working on a very big update and I'm about 1/3 through it. Once I get it in a working condition and I fix all the bugs I can find, if you don't mind, I'd like you to bug test it before I release it, if possible I'd like to transfer it through email (I'm trying to keep it secret, haven't told anyone yet) and id like for you to be the first one to try it (and find any bugs).

Let me know what you think, just letting you know it'll probably by a month (maybe 2) before I finish with this feature. (Although for all I know it may be a week)

I think you'll be very excited about this new feature 😃

**Comment by shay-la** [comment]
This is a great news, it would be a great honor for me to be a beta tester of this amazing project.
You are doing a great job and I would be happy to contribute from my knowledge and experience in what I can.
Here is my contact email: shaylevary@gmail.com

**Comment by ethanaobrien** [comment]
Awesome, thank you, I'll contact you when it's ready to be tested, thank you! (Should be about a month)

**Comment by jeffabner** [comment]
friend shaylevary, could you send me the version that works with netplay, my email jeffhardyabner@hotmail.com

**Comment by ethanaobrien** [comment]
@shaylevary @shay-la Just letting you know, I theoretically sent you an email. If you didn't receive it please let me know. Thanks!

**Comment by ethanaobrien** [comment]
Added
