### ISSUE TITLE
N64 network error

### ISSUE THREAD

**Issue by Avi7x** [emulatorjs/emulatorjs#35]
![00723193-095F-4348-B457-B589A4E2F9B2](https://user-images.githubusercontent.com/18734588/137623637-de41072f-71c3-4363-8d9d-ffe624aac7c9.jpeg)
`<script type="text/javascript">
    EJS_player = '#game';
    EJS_gameUrl = '{$emulatorRom}'; // Url to Game rom
    EJS_core = 'n64';
    EJS_pathtodata = 'assets/data/'; //path to all of the wasm and js files. MUST all be in the same directory!!
</script> `
does anyone knows any solution all paths set right and im using z64 roms.

**Comment by ethanaobrien** [comment]
I've seen this error happen. Only seems to happen on android. I havent looked into this yet

**Comment by burkasaurusrex** [comment]
+1 on this as well - running into it on xbox one

**Comment by ethanaobrien** [comment]
@burkasaurusrex @Avi7x  
Can one of you try to get the path it is trying to fetch?

**Comment by ethanaobrien** [comment]
@burkasaurusrex @Avi7x
I have found a missing n64 core. Could you update and try to load again?

**Comment by ethanaobrien** [comment]
Closed (see #63 )
