### ISSUE TITLE
EJS_color not working

### ISSUE THREAD

**Issue by Bobgills** [emulatorjs/emulatorjs#361]
Whenever I try to load one of the cores on the emulator button it shows a black screen 
[Screen recording 2022-09-03 9.41.51 PM.webm](https://user-images.githubusercontent.com/105334946/188294759-47ec68a3-1145-4f61-899a-d5c20dacced1.webm)

**Comment by ethanaobrien** [comment]
Wrong repository to open this in, also, I'd need a log of the console

**Comment by sDetective** [comment]
This happened to me today

**Comment by sDetective** [comment]
Here's what I have in the console and when I open the Embed and emulator button it shows up black.
![Screenshot 2022-09-06 10 25 09 AM](https://user-images.githubusercontent.com/85586892/188675105-13221868-70b6-4753-aae0-390bb631754b.png)

**Comment by ethanaobrien** [comment]
That's not the console.

**Comment by sDetective** [comment]
oh sorry I didn't know what would be the console?

**Comment by ethanaobrien** [comment]
Right click, click inspect, click the "console" tab at the top

**Comment by sDetective** [comment]
thanks

**Comment by sDetective** [comment]
I have the log is this what you would be looking for?
![image](https://user-images.githubusercontent.com/85586892/191760492-55b64340-b004-4547-9538-dec25adc0cea.png)
This was on emulator button and the 2nd link of the emulator button shows it as 404 on its repo

**Comment by ethanaobrien** [comment]
Yes, but if it's for the emulator button than this is not the correct repository to send it to

**Comment by sDetective** [comment]
Well this happens for EmulatorJS too I'm going to report the bug tomorrow

**Comment by ethanaobrien** [comment]
This has been fixed
