### ISSUE TITLE
Preset Settings

### ISSUE THREAD

**Issue by ShatteredDisk** [emulatorjs/emulatorjs#363]
I may have missed something in the docs, but I don't think I did.
I think it would be great to be able to define settings in the loader js before a user loads a game.

For example:
I would define an object called something like "EJS_Presets" with the setting names and what I want it to start as.
This would be similar to the "EJS_Settings" object but would rather include all of the settings in the GUI.
(such as the choice that changes whether to save games as a download or keep them in the browser)
The user then loads whatever game I've specified and sees the selected option already picked for them in settings.

Definitely not the highest priority but would be greatly appreciated.

~Thanks, ShatteredDisk

**Comment by ethanaobrien** [comment]
This is actually a really good idea! Thanks for opening this, I'll add this to my list for the next update

**Comment by ethanaobrien** [comment]
This has been added!
