### ISSUE TITLE
nintendo switch compatabley

### ISSUE THREAD

**Issue by Smevy** [emulatorjs/emulatorjs#364]
its not what you think because it is possible to get a switch (unmodded) to pull up a web browser with DNS settings and I was wondering if you could get it switch compatible

**Comment by ethanaobrien** [comment]
No, I cannot get this to work the switch. As you said, a web browser is needed.

**Comment by ethanaobrien** [comment]
Although you can pair your pro-controller or something to another device and use the gamepad feature to play with the controller

**Comment by Smevy** [comment]
No go to settings, internet, change settings, manual dns, and type in 045.055.142.122 and then it will act like there is no internet click next and you have a web browser on the Nintendo switch

**Comment by Ramaerel** [comment]
The nintebdo dns browser has nowhere near the features it needs to run this

**Comment by Smevy** [comment]
Ok thanks for your trying tho
