### ISSUE TITLE
Upload files in batches

### ISSUE THREAD

**Issue by Smevy** [emulatorjs/emulatorjs#365]
on the code helper on emulatorjs.ga you should make it so you can upload a batch of roms at once instead of one at a time

**Comment by ethanaobrien** [comment]
Migrated to https://github.com/emulatorjs/emulatorjs/issues/2

**Comment by ethanaobrien** [comment]
Actually - I just transferred the repository

**Comment by ethanaobrien** [comment]
Please move this to this repository: https://github.com/EmulatorJS/emu-site
