### ISSUE TITLE
Hotkey to change savestate location not working

### ISSUE THREAD

**Issue by Wade7wastaken** [emulatorjs/emulatorjs#367]
[127.0.0.1-1663198735950.log](https://github.com/EmulatorJS/EmulatorJS/files/9570413/127.0.0.1-1663198735950.log)

Pressing the hotkey to change the savestate location doesn't work and gives an error in the console. I tested this on nes, n64 and gba roms, and the same thing happened. However, changing the savestate location manually in settings works fine.

**Comment by ethanaobrien** [comment]
Thank you for reporting this, I will fix this in the next release

**Comment by ethanaobrien** [comment]
Fixed!
