### ISSUE TITLE
Adding Amiga

### ISSUE THREAD

**Issue by MrJay84** [emulatorjs/emulatorjs#369]
Will Amiga be supported?

**Comment by ethanaobrien** [comment]
Could you tell me what amiga is?

**Comment by ethanaobrien** [comment]
Closing until more information is given

**Comment by MrJay84** [comment]
> Closing until more information is given

As in the Amiga line of computers introduced by Commodore.

**Comment by ethanaobrien** [comment]
This will possibly be enabled

**Comment by biglad** [comment]
https://retrogames.pro/2022/11/12/amiga-a500-a4000-operating-system-load-your-own-games/

check this, can it be imported?

**Comment by ethanaobrien** [comment]
> check this, can it be imported?

No

**Comment by biglad** [comment]
can this be imported ?
https://www.emulatorjs.com/amiga.html

**Comment by ethanaobrien** [comment]
No, I have a plan in place. Please be patient

**Comment by shaylevary** [comment]
Hi, 
It will be great if you'll be able to add the Amiga core, it got a lot of classic wonderful games.
Currently i'm using the original Emulatorjs script to run Amiga games, but i prefer using your emscripten core that runs much better.
