### ISSUE TITLE
RetroArch

### ISSUE THREAD

**Issue by Smevy** [emulatorjs/emulatorjs#372]
You should try to make your retroarch project available on the web so we can upload any rom on retroarch and just use the interface you made

**Comment by Ramaerel** [comment]
Do you mean like a version of this that you can just upload roms to, instead of hosting it yourself? Because that's a pretty cool idea tbh, I might do that myself 😅

**Comment by ethanaobrien** [comment]
There is the emulator button and several demos. What else are you asking for?

**Comment by Smevy** [comment]
Well hope you like the idea

**Comment by Smevy** [comment]
It's basically exactly like the GitHub respatory(your respatory retroarcch) and just a online version of that because your demo section is good but you can't save your 
 progress(conveniently) and it's not as advanced as the actual retro arch

**Comment by ethanaobrien** [comment]
That would be what the emulator button is for

**Comment by ethanaobrien** [comment]
Closing (thats what the emulator button is for)

**Comment by Smevy** [comment]
Well Just a better save system might be nice I don't exactly think that would be easy but when you load the game up again it will automatically reload into where they are using save states instated of having to go into settings

**Comment by ethanaobrien** [comment]
This will not be done. The save system is done in a way that will provide as much customization as possible.

**Comment by Smevy** [comment]
Well as One more suggestion when doing in browser savs possibly use a keybind and the numbers to switch between different save states instead of having to go through the entire menu

**Comment by ethanaobrien** [comment]
This is already implemented. In the control settings, scroll to the bottom

**Comment by Smevy** [comment]
oh ok
