### ISSUE TITLE
Embed struggles

### ISSUE THREAD

**Issue by Ducci9129** [emulatorjs/emulatorjs#373]
I'm struggling to embed the emulator into a website I've been experimenting with and I was thinking that a template would be pretty helpful. I have no idea what I'm doing so here's the embed code I've been trying to use:

 ```
 <div style="width:640px;height:480px;max-width:100%">
        <div id="game"></div>
      </div>
<script type="text/javascript">
    EJS_player = '#game'; 
    EJS_gameUrl = 'https://drive.google.com/file/d/1bbwnL1mnRLNTX4LYsCE1SQqi1tb5Rzh9/view'; // Url to Game rom
    EJS_core = 'snes';
    EJS_mouse = false; // SNES Mouse
    EJS_multitap = false; // SNES Multitap
</script>
<script src="https://www.emulatorjs.com/loader.js"></script>
```

**Comment by ethanaobrien** [comment]
First, this is not the same thing as emulatorjs.com; second, use this: https://emulatorjs.netlify.app/editor.html

**Comment by Ducci9129** [comment]
Oh, I didn't know. Thank you though.

**Comment by ethanaobrien** [comment]
It's all good! I'm happy to help!
