### ISSUE TITLE
Save, load, and change savestate hotkeys are missing from the controls menu

### ISSUE THREAD

**Issue by Wade7wastaken** [emulatorjs/emulatorjs#374]
[127.0.0.1-1664048673782.log](https://github.com/EmulatorJS/EmulatorJS/files/9639369/127.0.0.1-1664048673782.log)

![image](https://user-images.githubusercontent.com/86390605/192113753-43f65dd3-f8ef-4fbe-8000-5dfa1aec1b6b.png)

In previous versions, the save, load, and change savestate hotkeys used to be directly below the controller button hotkeys, however they aren't there anymore and can't be changed from their previous value

**Comment by ethanaobrien** [comment]
Very sorry about that, this has just been fixed, update your files and it should appear again. Thanks!
