### ISSUE TITLE
[Bug] "Keep in Browser" not working again

### ISSUE THREAD

**Issue by Ramaerel** [emulatorjs/emulatorjs#376]
Tried a hard refresh, clearing my cache and making sure it was updated like you recommend in the other issue.
Doing a save through the buttons while Keep in Browser is enabled downloads the file anyway, and enabling EJS_DEBUG_XX doesn't show anything different to when it's disabled, except the `invalid core option save-state-location` error that shows up when I switch from keep in browser to download. F2/F4 still work the way they should, and I've tested it on all Nintendo based cores.

**Comment by ethanaobrien** [comment]
This does seem to legitimately be bugged this time

**Comment by ethanaobrien** [comment]
I tested after fixing #379 . I dont seem to be able to reproduce anymore. Could you try this again and let me know if it is still broken (please make sure your cache is cleared). If it is still broken, could you provide me with your code. Thanks!

**Comment by Ramaerel** [comment]
Yep, this is working properly again. Thank you!
