### ISSUE TITLE
Using .ss* files

### ISSUE THREAD

**Issue by parknich** [emulatorjs/emulatorjs#377]
"Okay so the gba core uses mGBA however, even though this is the case, for whatever reason, .ssX files do not work. for example, i save a state in mgba desktop. it gives me "Pokemon Emerald Version.ss0" i try to load it in the website, and it doesnt work, it says its loaded but it actually doesnt do anything , so i try changing the file extension to .state but that doesnt work either.
Can you all add support for .ssx? Or atleast add support for using .sav files, as i would like to use my preexisting save.
Also this isn't an issue with my site as i also tried using the demo site, where it does the same thing ive described here. Thanks in advance"

That is my previous post from discussions, moved here per request

I've found a way to get my preexisting save into emujs by putting my sav file into the retroarch mgba core and saving a state.
I still think it's a good idea to add .sav support or .ss* support. I know the latter would require tweaking the core though.

**Comment by ethanaobrien** [comment]
Yes, currently emulatorjs only supports save states, not save files (which are the .ssx files)

**Comment by ethanaobrien** [comment]
I've been looking into this and something really weird is happening here. I have written it to where it *should* auto-save the save files every 30 minutes, and this works fine, but when reloading the page and trying to play the game again, the save file isn't being loaded from, it has no save data (even though it should) Is this just me? Could someone else check this?

**Comment by Smevy** [comment]
Yeah this is happening if you play the game it does not load the previous save file that was auto saved I don't know if this is still a problem but this have happened to me before

**Comment by donmor** [comment]
As for me the support to .sav is even more important 'cause I want to test daily builds of rom hacks, and real-time saves may lead to problems.

**Comment by donmor** [comment]
Actually there's already a issue #24 but is closed. BTW a .sav file stores data that usually written to SRAM on a cartridge, and is also called "battery save" because batteries are soldered on cartridges to keep data stored in SRAM.

**Comment by duanyu5871** [comment]
@ethanaobrien @parknich081 
This new feature has been updated to loader.js, found in [https://www.emulatorjs.com/gba.html](url)
![image](https://github.com/EmulatorJS/EmulatorJS/assets/15108185/a347d5d4-58a5-4676-a167-4d3ee6566f21)
The button has class "ejs--e7e06622e3c04957c2ebb05c5adec0".
But It is too difficult for me  to figure out the true function in obfuscate code.
Hope it will help your progress.

**Comment by ethanaobrien** [comment]
This has been added!
