### ISSUE TITLE
Having to redo all the code for my website

### ISSUE THREAD

**Issue by Smevy** [emulatorjs/emulatorjs#378]
When the new version was released all the games on my website stopped working Idk if there's a way I could fix this but I don't want to redo lots of code

**Comment by ethanaobrien** [comment]
Please provide a log of the console

**Comment by Smevy** [comment]
There was no console log but the error is Invalid System if that helps.

**Comment by Smevy** [comment]
Wait nevermind just got a console log

Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
09:18:38.661

**Comment by ethanaobrien** [comment]
I either need the entire console log or your config

**Comment by Smevy** [comment]
I just got a bit more if this helps I just got Now

[Violation] 'setInterval' handler took 127ms

But then there is also the first log repeating this is the entire console just copied exactly

nchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
09:18:38.661 MarioKartCircut.html:1 Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
09:18:38.661 MarioKartCircut.html:1 Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
09:18:38.661 MarioKartCircut.html:1 Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
09:20:20.375 content-script-start.js:6543 [Violation] 'setInterval' handler took 127ms

**Comment by ethanaobrien** [comment]
I can't debug this or reproduce this. Can I please see your code

**Comment by Smevy** [comment]
ok this is the code



<p id="p1">MarioKart Super Circuit</p>
--
  | <div style="width:640px;height:480px;max-width:100%">
  | <div id="game"></div>
  | </div>
  | <script>
  | EJS_player = "#game";
  | EJS_core = "gba";
  | EJS_gameName = "Mario Kart Super Circuit";
  | EJS_startOnLoaded = true;
  | EJS_pathtodata = "https://rawcdn.githack.com/ethanaobrien/emulatorjs/main/data/";
  | EJS_gameUrl = "Mario Kart Super Circuit (U) [!].zip";
  | </script>
  | <script src="https://rawcdn.githack.com/ethanaobrien/emulatorjs/main/data/loader.js"></script>

**Comment by ethanaobrien** [comment]
This is happening because I moved the repository to an organization. To fix this you either need to re-generate the code using the code helper or replace all `https://rawcdn.githack.com/ethanaobrien/emulatorjs` references with `https://rawcdn.githack.com/EmulatorJS/EmulatorJS`

**Comment by Smevy** [comment]
Oh that would make sense thank you
