### ISSUE TITLE
Catching savestates through js seems to be broken

### ISSUE THREAD

**Issue by Ramaerel** [emulatorjs/emulatorjs#379]
Been a while since I've done anything in regards to the cloud saving you helped me with (#181), but I just tested it out again for a new project and the function `window._0x378b5c.saveState();` seems to not be working. I know I had this working previously with help of the code shown in #52, and using it now seems to throw an error in the console. Specifically, this: 

`Uncaught TypeError: Cannot read properties of undefined (reading 'saveState')`

I thought I'd just check to see if anything has changed in regards to this so I can fix it. If it's a user-end error, I apologize

**Comment by ethanaobrien** [comment]
I'll look at this

**Comment by ethanaobrien** [comment]
I have replaced this with a more permanent solution. `window.EJS_saveState();` will now return the save state.

Note: in update `3.0.5` the save state function was changed to return a promise. `window.EJS_saveState();` will return a promise that resolves with a `Uint8Array`

**Comment by imneckro** [comment]
> I have replaced this with a more permanent solution. `window.EJS_saveState();` will now return the save state.
> 
> Note: in update `3.0.5` the save state function was changed to return a promise. `window.EJS_saveState();` will return a promise that resolves with a `Uint8Array`

@ethanaobrien Ethan when you have time can you help on how to resolve it and convert it to blob?

**Comment by imneckro** [comment]
> I have replaced this with a more permanent solution. `window.EJS_saveState();` will now return the save state.
> 
> Note: in update `3.0.5` the save state function was changed to return a promise. `window.EJS_saveState();` will return a promise that resolves with a `Uint8Array`

@ethanaobrien Ethan when you have time can you help on how to resolve it and convert it to blob?
