### ISSUE TITLE
Find keyboard controls to play in the frontend

### ISSUE THREAD

**Issue by Polarolouis** [emulatorjs/emulatorjs#380]
I'm currently looking for a way of finding the controls for the keyboard when playing from the frontend.

When using the loader script there is a nice button to show and modify the controls, but when using the frontend I can't manage to find them.

Hope I'm not missing a clear path.

If that helps I'm trying to play on NES and NDS.

Thanks

**Comment by ethanaobrien** [comment]
Please see the docs: https://emulatorjs.netlify.app/docs/Control%20Mapping.html

Let me know if you need more than this

**Comment by Polarolouis** [comment]
Thanks for this answer.

I can use this docs to setup an embedded script but what I intended to do was to use the http://emulatorjs.example.com/frontend/#game to play and I can't get the keyboard controls to work as controls for the game as they are mapped to RetroArch.

Am I misunderstanding the usage ?

**Comment by ethanaobrien** [comment]
In that case you need to use the simulate input function. You can search in the emulator main file for simulateInput for how to use it

**Comment by Polarolouis** [comment]
Thank you very much, I'll look for this
