### ISSUE TITLE
Game Not Loading

### ISSUE THREAD

**Issue by Smevy** [emulatorjs/emulatorjs#382]
The problem is the grey box doesnt even appear and I want to know what this error is
Console log

Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'innerHTML')
    at nt.<anonymous> (emulator.min.js?v=30.5:1:459760)
    at new Promise (<anonymous>)
    at new nt (emulator.min.js?v=30.5:1:458373)
    at loader.js:93:33

**Comment by ethanaobrien** [comment]
Please include a log with `EJS_DEBUG_XX` set to true

**Comment by Smevy** [comment]
thanks
