### ISSUE TITLE
Mulit disk support

### ISSUE THREAD

**Issue by sDetective** [emulatorjs/emulatorjs#384]
Would it be possible for both EmulatorJS and Emulator button could the retroarch menu to be accessed to implement more futures in the future?

**Comment by ethanaobrien** [comment]
I really don't want to put the retroarch menu in there, it would kind of take away from the feel of emulatorjs. Why would you want this?

**Comment by sDetective** [comment]
It would bring a lot of features like doesn't the retroarch menu have the option to change disks already or Change video drivers like Vulkan to OpenGL or other. The user could edit the settings to make the game better looking or faster fps.
I just thought this would be a cool idea that would help maybe some issues for other users.
(The menu does show up and works sorta but that's whenever the cores didn't work specifically PlayStation but the old cores option fixes that already)

**Comment by ethanaobrien** [comment]
>the option to change disks 

This is planned

> Change video drivers like Vulkan to OpenGL or other.

OpenGL is the only video driver that is supported on the web

> The user could edit the settings to make the game better looking or faster fps.

All the available settings are located in the setting in the bottom right corner

**Comment by sDetective** [comment]
Now that I think more about it, its all there what I just said in both repos dang

**Comment by sDetective** [comment]
Would Vulkan work using webgpu wait, no that wouldn't work I don't think?

**Comment by ethanaobrien** [comment]
No, vulkan requires it's own drivers, and cannot be run on the web

**Comment by sDetective** [comment]
would a widescreen hack be a good idea or is that a feature that was suggested already?

**Comment by ethanaobrien** [comment]
A widescreen hack would be something you'd suggest in the retroarch core repositories themselves

**Comment by sDetective** [comment]
Oh it wouldn't work for all games then if were to be made as an all games type of deal

**Comment by ethanaobrien** [comment]
This has been added!
