### ISSUE TITLE
[Bug] N64 - Left and Right joystick not working correctly on controller.

### ISSUE THREAD

**Issue by Ramaerel** [emulatorjs/emulatorjs#385]
The left/right joystick don't seem to pick up sensitivity correctly on controllers. Holding the sticks about half way picks up movement, albeit very minimal (tested on Super Mario 64). Pushing it past that point stops movement altogether. Tested on a generic xinput controller as well as a PS4 controller with the same results

**Comment by sDetective** [comment]
have you checked the dead zone option?

**Comment by ethanaobrien** [comment]
This is strange, Could you use [this tool](https://encoderpie.github.io/gamepad-api-test/) to verify it is not your controller

**Comment by ethanaobrien** [comment]
@Ramaerel have you tested with https://encoderpie.github.io/gamepad-api-test/

**Comment by Ramaerel** [comment]
Nope sorry. My email had a meltdown a couple days back, I didn't even see that you responded. I'll get onto that in about an hour

**Comment by Ramaerel** [comment]
Neither gamepad seems to have any issues with that test. Changing the deadzone option also does absolutely nothing in regards to this issue.

**Comment by ethanaobrien** [comment]
Ok, thank you. When I get a chance I'll set up a test for the gamepad api I have. If I can't reproduce this I'll ask you to test it.

**Comment by ethanaobrien** [comment]
@Ramaerel Could you download [this file](https://drive.google.com/file/d/1Ge6M1Mfq4iQdAoNlj6NX-t6dJjkKNzat/view?usp=sharing) and open index.html (in a web server on localhost or on an https page, so we can use the gamepad api) and connect your controller and record a screen recording of the progress bars while moving the joysticks. I tested with a pro controller and could not reproduce this issue. Could you also check this wasn't a one time thing?

**Comment by Ramaerel** [comment]
Yeah, I'm not entirely sure what happened but I can't reproduce the issue anymore. It was still happening yesterday, but this doesn't seem to be the case now

**Comment by ethanaobrien** [comment]
That's weird. Possibly a problem with cache or your controller/computer.

Since this is no longer reproducible could you close this? This way you can re-open this is this occurs again
