### ISSUE TITLE
Help Someone

### ISSUE THREAD

**Issue by Matt3455** [emulatorjs/emulatorjs#386]
Hi My Name Is Matt, Oh And I Like Snowmans, Ok I Think Thats Enough Of An Introduction. Anyways I've Been Trying To Make A Retro Game Website Using The "EmulatorJS" Emulator, And I've Run Across A Problem, I've Been Trying To Make It For Where Instead Of Having To Manually Place The Rom Of The Game You Want To Play Every Time You Want To Play It, You Just Have To Select The Game You Want To Play And Play It. But I Cant Figure Out How To. Please Help It Would Mean The World To Me.

Sincerely-
Mat.

Ok Bye.

Ps: 
Heres The Website That Im Making: 
https://sites.google.com/view/mats-snow-shack/home

Ok Bye Fr

**Comment by Smevy** [comment]
First Download a ROM you should do it off of emulatorgames.net it has to be one of the consles listed in readme downloaded the rom you want and then go to media fire and make a account and upload the rom and click the share option and copy the link then copy this code but swap out the spot that says URL that you copied with the URL that you copied from Mediafire make sure you do not delete the quotation marks " and in between the quotes you will also have to change the "gamecore" to see what to change it to scroll down in the readme and click on the text of the consle you are doing look in the code for EJS_Core and whatever it it says change this code to match that
```
<div style="width:640px;height:480px;max-width:100%">
            <div id="game"></div>
        </div>
        <script>
            EJS_player = "#game";
            EJS_core = "n64";
            EJS_gameName = "Super Smash Bros.";
            EJS_startOnLoaded = true;
            EJS_pathtodata = "https://rawcdn.githack.com/EmulatorJS/EmulatorJS/main/data/";
            EJS_gameUrl = "URL that you copied";
        </script>
        <script src="https://rawcdn.githack.com/EmulatorJS/EmulatorJS/main/data/loader.js"></script>
```
Once you have the code you just changed then click on embed in google sites and paste the code
also change the game name it doesn't have to be exact but you should change it for save states.
If you have questions pls just ask I can respond within a day (Normaly)

**Comment by ethanaobrien** [comment]
First, please note #61, #100, #161, and #203 for information of embedding into google sites.

You can take a look at the [index.html code](https://github.com/EmulatorJS/EmulatorJS/blob/main/index.html). The index.html file does what youre looking for.

Here is the minimal code you'd need:
```
<html>
    <head></head>
    <body>
        <input type="file" id="file">
        <div style="width:640px;height:480px;max-width:100%">
            <div id="game"></div>
        </div>
        <script>
            
            document.getElementById('file').addEventListener('change', async (e) => {
                EJS_player = '#game';
                EJS_pathtodata = 'data/';
                
                EJS_core = 'ENTER GAME CORE HERE';
                EJS_gameUrl = URL.createObjectURL(new Blob([await e.target.files[0].arrayBuffer()]));
                
                const loader = document.createElement('script');
                loader.src = 'data/loader.js';
                document.body.appendChild(loader);
                e.target.remove();
            })
        </script>
    </body>
</html>
```
