### ISSUE TITLE
Update 3do core

### ISSUE THREAD

**Issue by dosboxonline** [emulatorjs/emulatorjs#387]
Hi.
Is it possible to add Core options? - Timing Hack 1 (Crash 'n Burn) [opera_hack_timing_1] (disabled|enabled).
I tried adding this to the html file, but it didn't work.  - EJS_3do_settings = {"core-options": {"opera_hack_timing_1": "enabled"}}

Works if manually add this in Chrome developer tools as shown in the attached file. It also worked in the old version of the emulator by adding to "emulator.js" file.

![core-options](https://user-images.githubusercontent.com/10185752/193406074-4d7d1163-b3cd-4514-b8f4-54d47ae635ff.png)

Thanks.

**Comment by ethanaobrien** [comment]
This isn't supported yet because the 3do core hasnt been upgraded

**Comment by ethanaobrien** [comment]
This has been upgraded!
