### ISSUE TITLE
Not working with all downloaded games

### ISSUE THREAD

**Issue by Noahfoot2** [emulatorjs/emulatorjs#388]
![Screenshot 2022-10-01 11 00 46 AM](https://user-images.githubusercontent.com/114822974/193417911-67b20f16-353e-498d-9057-a626a3c75973.png)
please fix it it wont let me play pokemon roms

**Comment by ethanaobrien** [comment]
A description of the actual problem would be nice

**Comment by Noahfoot2** [comment]
![Screenshot 2022-10-01 11 04 37 AM](https://user-images.githubusercontent.com/114822974/193418090-df8d05ff-5e81-4814-9990-8277d473b5c6.png)
> A description of the actual problem would be nice

Just updated it

**Comment by ethanaobrien** [comment]
How about a log of the console...?

**Comment by Noahfoot2** [comment]
> 

Ok did it

**Comment by Noahfoot2** [comment]
Are you looking at it

**Comment by ethanaobrien** [comment]
I said a log of the console, not a screenshot of the message saying emulatorjs is available. I suggest contacting the owners of that site
