### ISSUE TITLE
Clear cache on fetch

### ISSUE THREAD

**Issue by ethanaobrien** [emulatorjs/emulatorjs#389]
When the url is a `blob:` url, use `revokeObjectURL` on it after it has been fetched (to clear up memory)

**Comment by Smevy** [comment]
Just would like to bring up if you are going to continue working on the emu site github page

**Comment by ethanaobrien** [comment]
Yes, I have been, please just wait

**Comment by Smevy** [comment]
ok thanks

**Comment by ethanaobrien** [comment]
Done!
