### ISSUE TITLE
SEGA Saturn emulator not work

### ISSUE THREAD

**Issue by dosboxonline** [emulatorjs/emulatorjs#39]
![saturn-eml](https://user-images.githubusercontent.com/10185752/140543694-56c091f9-8325-4df5-8a97-457336661598.png)

You can check it yourself - https://play.retrogames.onl/saturn/amok-saturn.html . 
Fully working emulator Sega Saturn in a browser on the same server with the same ZIP files (bios and cue/iso) files - https://play.retrogames.onl/saturn/amok.html . 
If you think that I was mistaken in the HTML code or  paths to the emulator files, then here is the proof of another game on the EmulatorJS on the same server - https://play.retrogames.onl/3do/wolfenstein-3do.html . 

Please do not write comments like "it works for me" without a screenshot of the running Saturn game on your server with EmulatorJS.

At the moment, it doesn't matter what format the game files are in, because the emulatorjs doesn't even download them.

**Comment by ethanaobrien** [comment]
Will you see if the this game runs with the original emulatorjs.com code?

**Comment by dosboxonline** [comment]
Another link to the site with the game Sonic Jam for Sega Saturn - https://www.vizzed.com/play/sonic-jam-ss-online-sega-saturn-69228-playable .  EmulatorJS also won't start.

**Comment by ethanaobrien** [comment]
Add this line of code to your game and then please include a log of the console

```
EJS_DEBUG_XX = true
```

**Comment by dosboxonline** [comment]
Didn't see any changes in the Chrome console after adding - EJS_DEBUG_XX = true;
You can check - https://play.retrogames.onl/saturn/amok-debug-true.html . 
With the original emulatorjs.com code - https://play.retrogames.onl/saturn/amok-original-emulatorjs-debug-true.html

**Comment by xxxnewbiexxx** [comment]
> Didn't see any changes in the Chrome console after adding - EJS_DEBUG_XX = true; You can check - https://play.retrogames.onl/saturn/amok-debug-true.html . With the original emulatorjs.com code - https://play.retrogames.onl/saturn/amok-original-emulatorjs-debug-true.html

Hi dosboxonline, for me the game is working on both links ;-)

**Comment by ethanaobrien** [comment]
https://play.retrogames.onl/saturn/amok-saturn.html
On this link it seemed to load fine. Have you tried another browser/system?
![Screenshot 2021-11-05 10 33 25 PM](https://user-images.githubusercontent.com/77750390/140596636-ebf32f64-d0c2-44bd-a02f-5dc65d52f38f.png)
![Screenshot 2021-11-05 10 32 39 PM](https://user-images.githubusercontent.com/77750390/140596634-69c09480-fb90-4a0a-b19e-d05d318a4190.png)

**Comment by dosboxonline** [comment]
Now it works. For two months I tried to run on three different PС, Win 7 and 10 64/32 bit, Chrome, Firefox, Edge, Android. Obviously, the problem is on the server side of the IIS, since only today I started it on another server bypassing the CDN cache CloudFlare. Many thanks.

**Comment by dosboxonline** [comment]
Close issue. Unfortunately, it works 20% slower than other emulator because it does not wasm.

**Comment by dosboxonline** [comment]
.
