### ISSUE TITLE
melonDS touch doesn't work

### ISSUE THREAD

**Issue by parknich** [emulatorjs/emulatorjs#394]
### Discussed in https://github.com/EmulatorJS/EmulatorJS/discussions/392

<div type='discussions-op-text'>

<sup>Originally posted by **parknich081** October 11, 2022</sup>
for some reason i cant get the touch screen to work on melonDS, it works on desmume but non melonds, and melonds runs better in my experience. any help?</div>

**Comment by parknich** [comment]
would this issue be in the melonds wasm or in one of the js files?

**Comment by ethanaobrien** [comment]
The wasm

**Comment by parknich** [comment]
ah

**Comment by ethanaobrien** [comment]
This has been fixed!
