### ISSUE TITLE
"Network Error"

### ISSUE THREAD

**Issue by DannysGameLab** [emulatorjs/emulatorjs#396]
I'm really new to this, and when I tried building Super Mario 64 it popped up with "Network Error".
![Screenshot 2022-10-18 215818](https://user-images.githubusercontent.com/91354369/196586896-cef22931-e5e1-4f13-bb41-b84e2bbfe25c.png)
This is on my home computer, where nothing is blocked. I'm not really sure what the problem is.

**Comment by tomato8010** [comment]
Yea that happens to me too on the Pokémon emerald

**Comment by ethanaobrien** [comment]
I need a log of the console to actually diagnose the problem. Please send a log of the console and I will re-open.

If you don't know how to get a log, use google to figure out how

**Comment by tomato8010** [comment]
Ok thank you so mich

**Comment by bofanuts** [comment]
idk how to fix network error still
