### ISSUE TITLE
embed?

### ISSUE THREAD

**Issue by 0deez** [emulatorjs/emulatorjs#398]
how do i embed the games on say like a google site?

**Comment by parknich** [comment]
probably an iframe for google sites, but if you're hosting it on something that gives you access to the html then you can just do it like normal

**Comment by ethanaobrien** [comment]
Duplicate of https://github.com/EmulatorJS/EmulatorJS/issues/61, https://github.com/EmulatorJS/EmulatorJS/issues/100, https://github.com/EmulatorJS/EmulatorJS/issues/161, https://github.com/EmulatorJS/EmulatorJS/issues/203, and https://github.com/EmulatorJS/EmulatorJS/issues/386.
