### ISSUE TITLE
DS EmulatorJS sends straight to retro arch/Desume2015 menu and game doesn’t load

### ISSUE THREAD

**Issue by FireVirusMC** [emulatorjs/emulatorjs#399]
![image](https://user-images.githubusercontent.com/79536173/197092074-d7cc451d-3817-4a02-8e86-806165e5e99b.png)

I was trying to set up a ds emulator for pokemon platinum and it does not seem to load the content/game I assigned. Does this have something to do with the game or URLs I'm using or a replit issue? It only redirects to DESUME 2015's retroarch page. Please comment or give a fix for this problem.

**Comment by FireVirusMC** [comment]
I see this my be due in part for the Bios file requirements being different from GBA games and DS games and I am a bit confused on how to input BIOS files for this script.

**Comment by ethanaobrien** [comment]
Can you please include a full log of the console?

**Comment by FireVirusMC** [comment]
What do you mean by log?

**Comment by ethanaobrien** [comment]
Right click > click inspect > click the "console" tab at the top > right click and click the save log to file option

**Comment by FireVirusMC** [comment]
[replit.com-1666321364790.log](https://github.com/EmulatorJS/EmulatorJS/files/9835360/replit.com-1666321364790.log)

**Comment by FireVirusMC** [comment]
Any updates?

**Comment by ethanaobrien** [comment]
The error is that it cannot find the rom file, maybe try renaming it to something smaller?
