### ISSUE TITLE
Error with playstation emulator with ISO, and CUE

### ISSUE THREAD

**Issue by Impre-visible** [emulatorjs/emulatorjs#404]
Hi, I want to emulate playstation games, but when I import an ISO, a .cue with .bin files it don't work, here's the error: 
![image](https://user-images.githubusercontent.com/69050895/198590072-68e99cfe-dbef-4951-aa94-20a388f48bea.png)
and here's my js code :
```js
<script type="text/javascript">
EJS_player = "#game";
EJS_biosUrl = "/bios/PS1";
EJS_gameUrl = "/gameFile/PS1/Ape Escape.iso";
EJS_core = "psx";
</script>
```

at /bios/PS1 I have the bios file returned by my backend
and at /gameFile/PS1/Ape Escape.iso I have the .iso, but I have a black screen and the error as you can see in the image, it's the same for the .cue file :
the js :
```js
<script type="text/javascript">
EJS_player = "#game";
EJS_biosUrl = "/bios/PS1";
EJS_gameUrl = "/PS1GameFile/PS1/Command & Conquer - Alerte Rouge (France) (Disc 1) (Allies).cue";
EJS_core = "psx";
</script>
```
and at PS1GameFile I return the .cue file modified, so in this .cue, all path return to a root, called "/PS1binFile/"
so a .cue is :
```
FILE "/PS1binFile/Command & Conquer - Alerte Rouge (France) (Disc 1) (Allies).bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00
```
and at PS1binFile I return the .bin of the disc1 of the game, so I don't understand why it don't work

**Comment by ethanaobrien** [comment]
You need to zip the cue and bin files together

If you look here (https://github.com/EmulatorJS/EmulatorJS/blob/main/docs/Systems/PlayStation.md) iso files are not supported

**Comment by Impre-visible** [comment]
I need to zip the .cue and.bin ?

**Comment by ethanaobrien** [comment]
Yes, the bin and cue files need to be zipped together

**Comment by Impre-visible** [comment]
> Yes, the bin and cue files need to be zipped together

And for the .iso ?

**Comment by ethanaobrien** [comment]
Look here - https://github.com/EmulatorJS/EmulatorJS/blob/main/docs/Systems/PlayStation.md

Iso files are not supported. If you need iso support then you need to open an issue in the retroarch beetle-psx repository

**Comment by Impre-visible** [comment]
> Look here - https://github.com/EmulatorJS/EmulatorJS/blob/main/docs/Systems/PlayStation.md
> 
> Iso files are not supported. If you need iso support then you need to open an issue in the retroarch beetle-psx repository

My bad, i was thinking that .iso was supported.
