### ISSUE TITLE
axios error?

### ISSUE THREAD

**Issue by Snow-SHACK** [emulatorjs/emulatorjs#406]
i've been trying to put the emulator in google sites but whenever i boot up the emulator it always says "Axios Error" and ive been trying to figure out why, pls help
also heres the code ive been using

<div style="width:640px;height:480px;max-width:100%">
        <div id="game"></div>
      </div>
<script type="text/javascript">
    EJS_player = '#game';
EJS_startOnLoaded = true;
 EJS_gameName = "Sonic 3 & Knuckles.";
EJS_pathtodata = "https://rawcdn.githack.com/EmulatorJS/EmulatorJS/main/data/"
    EJS_gameUrl = 'https://www.mediafire.com/file/n9ttiz2vfdx2i6a/SONIC_3_%2526_KNUCKLES.html/file'; // Url to Game rom
    EJS_core = 'segaMD';
</script>
<script src="https://www.emulatorjs.com/loader.js"></script>

sos

**Comment by ethanaobrien** [comment]
First, I stripped out axios long ago, second, this is because of [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS), third, you are using emulatorjs.com, not this project

**Comment by Snow-SHACK** [comment]
oh ok thanks
