### ISSUE TITLE
Typing

### ISSUE THREAD

**Issue by tomato8010** [emulatorjs/emulatorjs#408]
Hello so when I try to type anything in the hack section,it wouldn’t let me

**Comment by ethanaobrien** [comment]
What hack section? What do you mean "it won't let you" can you provide screen recordings? Screenshots? Logs?

**Comment by ethanaobrien** [comment]
Closing until more details are given

**Comment by tomato8010** [comment]
https://user-images.githubusercontent.com/115638692/200200566-733a5b8d-4e12-4987-8f02-0e33a40a5e96.MOV

**Comment by ethanaobrien** [comment]
Hmm, that is strange. It may be a safari thing

**Comment by tomato8010** [comment]
Oh is there any way I can fix this?

**Comment by ethanaobrien** [comment]
No, this is a bug

**Comment by tomato8010** [comment]
That’s what I thought at first but when I reloaded the game and the tab,it still wouldn’t work

**Comment by tomato8010** [comment]
Do u have any way to fix this bug?

**Comment by ethanaobrien** [comment]
Yeah, Time and patience

**Comment by a789693894** [comment]
This is caused by the css style of the input box (user-select: none). Changing to (user-select: text) can be resolved

**Comment by ethanaobrien** [comment]
@a789693894 

>This is caused by the css style of the input box (user-select: none). Changing to (user-select: text) can be resolved

Would you like to submit a pull request with these changes? If not I can do this myself, but it'd show you as a contributor.

**Comment by ethanaobrien** [comment]
@a789693894 

>This is caused by the css style of the input box (user-select: none). Changing to (user-select: text) can be resolved

Would you like to submit a pull request with these changes? If not I can do this myself, but it'd show you as a contributor.

**Comment by a789693894** [comment]
I have submitted the merge request, please check. thank you @ethanaobrien

**Comment by ethanaobrien** [comment]
Thank you!
