### ISSUE TITLE
Problem with ps1 speed and ios support

### ISSUE THREAD

**Issue by hadoizz** [emulatorjs/emulatorjs#409]
hey there is problem in ps1 games on ios so when i search i found two scrips which could help to make things better and faster can we use it with emualator js https://github.com/dkoluris/pseudo-js 

there is demo for it https://naden.co/pseudo/

its very fast and when you upload game with 700 mgb its works good can you check 

contact me i can give you bounas or donate for this job hadoidxb@gmail.com 

thanks u

**Comment by ethanaobrien** [comment]
See #342

Second, I cannot embed the provided emulator, it must use retroarch. If you'd like you can use the old cores, that may be better for what you're doing, but have major sound bugs. Sorry
