### ISSUE TITLE
How to put games on Wordpress?

### ISSUE THREAD

**Issue by ildomandatore** [emulatorjs/emulatorjs#41]
I am a novice to both Wordpress and Github. After almost a year of work on my website and about 2000 custom CSS lines, it's time to add the games.

I created the FTP folders for the games, the bios and put the unzipped folder of your project.

I put the code you suggest for the Nintendo Gameboy Advance and put the link for bios and game, but it doesn't work. I'm doing something wrong.

`<div style="width:640px;height:480px;max-width:100%">
<div id="game"></div>
</div>
<script type="text/javascript"><br />
    EJS_player = '#game';<br />
    EJS_biosUrl = 'public_html/Bios/Nintendo/Gameboy Advance/gba_bios.bin';<br />
    EJS_gameUrl = 'public_html/Games/Nintendo/Gameboy Advance/dragonball-z-buu-s-fury-usa.zip'; // Url to Game rom<br />
    EJS_core = 'gba';<br />
    EJS_pathtodata = 'data/'; //path to all of the wasm and js files. MUST all be in the same directory!!<br />
</script>
<script src="data/loader.js"></script>`

**Comment by ethanaobrien** [comment]
Do you have this code in your code. It must be before you define the scripts
```
<div style="width:640px;height:480px;max-width:100%">
  <div id="game"></div>
</div>
```

**Comment by ildomandatore** [comment]
An example?

Il giorno mer 10 nov 2021 alle ore 14:20 ethanaobrien <
***@***.***> ha scritto:

**Comment by ethanaobrien** [comment]
Its in the readme

**Comment by ildomandatore** [comment]
I read the redme at least 5 times. I need to understand better, because I
am a beginner. I'm sure it's simple to understand, but I need some help
first. :)

Il giorno mer 10 nov 2021 alle ore 17:52 ethanaobrien <
***@***.***> ha scritto:

**Comment by ethanaobrien** [comment]
The full demo code is
```
<div style="width:640px;height:480px;max-width:100%">
        <div id="game"></div>
      </div>
<script type="text/javascript">
    EJS_player = '#game';
    EJS_biosUrl = '';
    EJS_gameUrl = ''; // Url to Game rom
    EJS_core = 'gba';
    EJS_pathtodata = 'data/'; //path to all of the wasm and js files. MUST all be in the same directory!!
</script>
<script src="data/loader.js"></script>
```

Make sure all this is in your file

**Comment by ildomandatore** [comment]
https://oldfreegame.com/en/uncategorized/elementor-5464/

Il giorno mer 10 nov 2021 alle ore 18:14 ethanaobrien <
***@***.***> ha scritto:

**Comment by ildomandatore** [comment]
The demo code you gave me is the one that doesn't work. How do I fill in
the fields? I guess the code is not to be put all in the HTML. I'm on
Wordpress.org and I use Elementor.

Il giorno mer 10 nov 2021 alle ore 18:14 ethanaobrien <
***@***.***> ha scritto:

**Comment by ildomandatore** [comment]
I found that PHP was old. I updated it and disabled a plugin.

I thought it was all right; The Emulatorjs NES demo works fine. I used your code, the game I entered doesn't load and I have ads!
https://postimg.cc/VrtvHyWN

`<div style="width:640px;height:480px;max-width:100%">
        <div id="game"></div>
      </div>
<script type="text/javascript">
    EJS_player = '#game';
    EJS_biosUrl = '';
    EJS_gameUrl = 'public_html/Games/Nintendo/Gameboy Advance/dragonball-z-buu-s-fury-usa.zip'; // Url to Game rom
    EJS_core = 'gba';
    EJS_pathtodata = 'data/'; //path to all of the wasm and js files. MUST all be in the same directory!!
</script>
<script src="data/loader.js"></script>
`

The Nintendo Gameboy Color emulator is missing. Could you check which emulators are missing from Emulatorjs?

**Comment by ethanaobrien** [comment]
Again, you need to add the following code to your html
```
<div style="width:640px;height:480px;max-width:100%">
        <div id="game"></div>
      </div>
```
This is the code that tells the game where to render. Without it, it cannot load. If there is a problem with a core file missing please include a screenshot of the network log or console so I know where to get it from.

**Comment by ildomandatore** [comment]
I point out that the code you tell me on Github hides it from me. I copied that part too. 

```
<div style="width:640px;height:480px;max-width:100%">
        <div id="game"></div>
      </div>
<div style="width:640px;height:480px;max-width:100%">
        <div id="game"></div>
      </div>
<script type="text/javascript">
    EJS_player = '#game';
    EJS_biosUrl = '';
    EJS_gameUrl = 'public_html/Games/Nintendo/Gameboy Advance/dragonball-z-buu-s-fury-usa.zip'; // Url to Game rom
    EJS_core = 'gba';
    EJS_pathtodata = 'data/'; //path to all of the wasm and js files. MUST all be in the same directory!!
</script>
<script src="data/loader.js"></script>
```

Did I write everything right? Being new to the JS, I don't know where to put the code parts. Ok, the first part, but from the script onwards, where do I put it? With that plugin?

**Comment by ildomandatore** [comment]
Network error. Did I follow everything well? In the meantime, I try to see if there are any plugins that are causing problems.
https://postimg.cc/gallery/ZKc5BmM

Wasn't the emulator supposed to be ad-free?

I'm trying to add the script with Code Snippet and it gives me fatal error even with <script type = "text / javascript">
<script src = "data / loader.js"> </script>.

**Comment by ildomandatore** [comment]
I tried to insert a NES game; Super Mario Bros. NES games are supposed to be the easiest to enter, yet they don't even start out that way.

I tried the Emulatorjs test code on the NES and it works for me. So I'm not wrong where to implement the HTML and the script.

I must have skipped a few steps in your guide. What have I done;
- I downloaded the ZIP https://github.com/ethanaobrien/emulatorjs/archive/refs/heads/main.zip.
- I unzipped it.
- The unzipped file is in the Wordpress public_html folder.
- I downloaded the game and bios.
- I'll put them on my site.
- I put the HTML code and change the ID try.
- I put the script and paste the bios and game paths.
- In the script I put the id try.
- I save everything, I load the page, I delete the cache. Nothing ... The loader does not start either.

What am I missing to do?

**Comment by ildomandatore** [comment]
Error 507 Insufficient Storage.

And

[Json error](https://postimg.cc/9zFXmHsd)

**Comment by ethanaobrien** [comment]
Could this be a problem with the editor you are using to save the page?

**Comment by ildomandatore** [comment]
Gutenberg? I also had problems with Elementor to be honest, even if he
didn't tell me the cause.

Il giorno dom 21 nov 2021 alle ore 20:09 ethanaobrien <
***@***.***> ha scritto:

**Comment by ildomandatore** [comment]
Do I need to download this? https://github.com/linuxserver/emulatorjs

If so, here's what I was missing. Do I upload the file as ZIP or unzipped?

**Comment by ethanaobrien** [comment]
Can you send me the link to the rom or something so I can do some testing

**Comment by ildomandatore** [comment]
Should I put the script code as JS? So far I have mistakenly put it as CSS. The code says javascript. I get an error;

> Fatal error: require_once(): Failed opening required '/home/smlolwcq/public_html/wp-content/themes/astra/inc/compatibility/edd/class-astra-edd.php' (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') in /home/smlolwcq/public_html/wp-content/themes/astra/functions.php on line 140.

```
<script type="text/javascript">
    EJS_player = '#game';
    EJS_biosUrl = 'public_html/Bios/Nintendo/GameboyAdvance/gba_bios907607290.bin';
    EJS_gameUrl = 'public_html/Games/Nintendo/Gameboy Advance/dragonball-z-buu-s-fury-usa.zip'; // Url to Game rom
    EJS_core = 'gba';
    EJS_pathtodata = 'data/'; //path to all of the wasm and js files. MUST all be in the same directory!!
</script>
<script src="data/loader.js"></script>
```

**Comment by ethanaobrien** [comment]
Put it inside an html file. not php or css

**Comment by ildomandatore** [comment]
https://oldfreegame.com/wp-admin/admin.php?page=wp_file_manager#:~:text=public_html/Games/Nintendo/GameboyAdvance/dragonball%2Dz%2Dbuu%2Ds%2Dfury%2Dusa.zip

**Comment by ildomandatore** [comment]
I don't think games are the problem. I don't see the loader. maybe it's the requirements?

**Comment by ildomandatore** [comment]
This is the post where I am trying to insert the game.
https://oldfreegame.com/en/nintendo/gameboy-advance/elementor-5464/

**Comment by ethanaobrien** [comment]
yeah, I see the problem. Nothing I need to fix.

this path: https://oldfreegame.com/en/nintendo/gameboy-advance/elementor-5464/data/loader.js is not found, meaning the EJS_pathToData is set to the incorrect value or that you never placed the data/ directory in the correct place.

tip: If you cant host these files, use githack (uptime is not 100%, but emulator files would always be updated.)
```
<script type="text/javascript">
    EJS_player = '#game';
    EJS_biosUrl = 'public_html/Bios/Nintendo/GameboyAdvance/gba_bios907607290.bin';
    EJS_gameUrl = 'public_html/Games/Nintendo/Gameboy Advance/dragonball-z-buu-s-fury-usa.zip'; // Url to Game rom
    EJS_core = 'gba';
    EJS_pathtodata = 'https://raw.githack.com/ethanaobrien/emulatorjs/main/data/'; //path to all of the wasm and js files. MUST all be in the same directory!!
</script>
<script src="https://raw.githack.com/ethanaobrien/emulatorjs/main/data/loader.js"></script>
```

**Comment by ildomandatore** [comment]
I entered this.

```
<script type="text/javascript">
    EJS_player = '#game';
    EJS_biosUrl = 'public_html/Bios/Nintendo/GameboyAdvance/gba_bios907607290.bin';
    EJS_gameUrl = 'public_html/Games/Nintendo/Gameboy Advance/dragonball-z-buu-s-fury-usa.zip'; // Url to Game rom
    EJS_core = 'gba';
    EJS_pathtodata = 'data/'; //path to all of the wasm and js files. MUST all be in the same directory!!
</script>
<script src="data/loader.js"></script>
```


Where can I find the other 2 paths?

**Comment by ethanaobrien** [comment]
Replace what you have with the code I sent

**Comment by ildomandatore** [comment]
Done but it doesn't work.

```
<script type="text/javascript">
    EJS_player = '#game';
    EJS_biosUrl = 'public_html/Bios/Nintendo/GameboyAdvance/gba_bios907607290.bin';
    EJS_gameUrl = 'public_html/Games/Nintendo/Gameboy Advance/dragonball-z-buu-s-fury-usa.zip'; // Url to Game rom
    EJS_core = 'gba';
    EJS_pathtodata = 'https://raw.githack.com/ethanaobrien/emulatorjs/main/data/'; //path to all of the wasm and js files. MUST all be in the same directory!!
</script>
<script src="https://raw.githack.com/ethanaobrien/emulatorjs/main/data/loader.js"></script>
```

**Comment by ethanaobrien** [comment]
Then  can you please include a log of the console so I can actually see what you're missing

**Comment by ildomandatore** [comment]
Today I have had more problems with the site over a full year .. I put the Emulatorjs code on the site to see if it would load at least the loader. It does, but I don't understand for the first time, the menu is not at the top. In the tests done so far, the menu was always above, even using the Emulatorjs code.

Sorry, which log should I show you? Tell me step by step.

**Comment by ethanaobrien** [comment]
Right click, click 'inspect', click 'console' at the top, right click and click save console logs.

**Comment by ildomandatore** [comment]
[yourjs.log](https://github.com/ethanaobrien/emulatorjs/files/7591480/yourjs.log)
[emulatorjs.log](https://github.com/ethanaobrien/emulatorjs/files/7591481/emulatorjs.log)

**Comment by ethanaobrien** [comment]
I dont know what isn't correct. Can you try using a web server to test and run just the emulator.

**Comment by ildomandatore** [comment]
What is a web server?

I am convinced that I have not followed all the steps. Can you explain them to me step by step?

**Comment by ethanaobrien** [comment]
place the following code into an html file
```
<div style="width:640px;height:480px;max-width:100%">
        <div id="game"></div>
      </div>
<script type="text/javascript">
    EJS_player = '#game';
    EJS_biosUrl = '';
    EJS_gameUrl = ''; // Url to Game rom
    EJS_core = 'gba';
    EJS_pathtodata = 'data/'; //path to all of the wasm and js files. MUST all be in the same directory!!
</script>
<script src="data/loader.js"></script>
```
Download and make sure you have the EJS_pathtodata set to the correct place
Set the game url and bios url to the path of the files

Thats all

**Comment by ildomandatore** [comment]
https://postimg.cc/23HgHf36

**Comment by ethanaobrien** [comment]
The `data/` directory is in the wrong place

**Comment by ildomandatore** [comment]
https://postimg.cc/BtxB65fG

```
<div style="width:640px;height:480px;max-width:100%">
        <div id="gioco"></div>
      </div>
<script type="text/javascript">
    EJS_player = '#gioco';
    EJS_biosUrl = 'public_html/Bios/Nintendo/GameboyAdvance/gba_bios907607290.bin';
    EJS_gameUrl = 'public_html/Games/Nintendo/GameboyAdvance/dragonball-z-buu-s-fury-usa.zip'; // Url to Game rom
    EJS_core = 'gba';
    EJS_pathtodata = 'public_html/emulatorjs-main/data'; //path to all of the wasm and js files. MUST all be in the same directory!!
</script>
<script src="data/loader.js"></script>
```

**Comment by ethanaobrien** [comment]
The data/ directory is still in the wrong place. You should be able to add `public_html/emulatorjs-main/data/loader.js` to the main url and it will load

Also, the div id MUST be game - or the emulator.js file cant find the element

**Comment by ildomandatore** [comment]
```
<div style="width:640px;height:480px;max-width:100%">
        <div id="dragonball-z-buu-s-fury-usa"></div>
      </div>
<script type="text/javascript">
    EJS_player = '#dragonball-z-buu-s-fury-usa';
    EJS_biosUrl = 'public_html/Bios/Nintendo/GameboyAdvance/gba_bios907607290.bin';
    EJS_gameUrl = 'public_html/Games/Nintendo/GameboyAdvance/dragonball-z-buu-s-fury-usa.zip'; // Url to Game rom
    EJS_core = 'gba';
    EJS_pathtodata = 'public_html/emulatorjs-main/data/'; //path to all of the wasm and js files. MUST all be in the same directory!!
</script>
<script src="public_html/emulatorjs-main/data/loader.js"></script>
```

**Comment by ethanaobrien** [comment]
1) Click the "add block" button
2) Search for "custom html"
3) Click the "Custom HTML" block
4) Copy the following lines and paste into the Custom HTML block
```
<div style="width:640px;height:480px;max-width:100%">
        <div id="game"></div>
      </div>
<script type="text/javascript">
    EJS_player = '#game';
    EJS_biosUrl = '';
    EJS_gameUrl = ''; // Url to Game rom
    EJS_core = 'gba';
    EJS_pathtodata = 'https://rawcdn.githack.com/ethanaobrien/emulatorjs/main/data/';
</script>
<script src="https://rawcdn.githack.com/ethanaobrien/emulatorjs/main/data/loader.js"></script>
```
5) From the home page of the website, hover over "media" and click "library"
6) Click Add new (If you already have the file uploaded, click on the file you want the link for and skip to step 9)
7) Upload files (you MUST zip the file)
8) Click the file you just uploaded
9) Click "copy URL to clipboard"
10) Go back to the edit page. If you uploaded the bios paste the URL you copied in the biosUrl field, if you uploaded a game, paste the url into the gameUrl field
11) That's all

result:
```
<div style="width:640px;height:480px;max-width:100%">
        <div id="game"></div>
      </div>
<script type="text/javascript">
    EJS_player = '#game';
    EJS_biosUrl = 'https://staging2.oldfreegame.com/wp-content/uploads/2021/11/gba_bios907607290.zip';
    EJS_gameUrl = 'https://staging2.oldfreegame.com/wp-content/uploads/2021/11/dragonball-z-buu-s-fury-usa.zip'; // Url to Game rom
    EJS_core = 'gba';
    EJS_pathtodata = 'https://rawcdn.githack.com/ethanaobrien/emulatorjs/main/data/';
</script>
<script src="https://rawcdn.githack.com/ethanaobrien/emulatorjs/main/data/loader.js"></script>
```
example page: https://staging2.oldfreegame.com/wp-admin/post.php?post=5&action=edit

Does this solve the problem?

**Comment by ethanaobrien** [comment]
@ildomandatore 
Can I close this?

**Comment by ildomandatore** [comment]
Keep it open until I'm sure I've solved it. I'll tell you to close.

**Comment by allancoding** [comment]
Based on our findings, we cannot verify that you got a copy of emulatorjs from its official source. The cause of this is because of undocumented changes (meaning, there is no documentation on your site stating changes, which is required by license) or changes that have removed a link to source of the software. Stating the changes and linking to the original source is REQUIRED by license and we will refuse to service those who do not follow the license whether it be a requested feature, a possible bug, or a need for information. We have the right by law to refuse to service you. To dismiss this notice and be able to receive help, then add the stated changes to your website, and make sure a link to this page (or the information on the page itself) is clearly visible, and that there is a clear link to the source of the original GitHub project. If you get this message and make the required changes and break the license in this way again, then you will be prevented from opening any issues in the emulatorjs repository. No help will be given to make these changes (you managed to make the changes that break the license, you can fix it). We apologize for any inconvenience.
