### ISSUE TITLE
Missing X,Y,Z,Mode buttons in SegaMD

### ISSUE THREAD

**Issue by sfz3mix** [emulatorjs/emulatorjs#411]
I was not able to use or map the X,Y,Z buttons on the Genesis / SegaMD to touch pad. How do you have the 6 button control?

**Comment by ethanaobrien** [comment]
Please see [this](https://emulatorjs.org/docs4devs/Virutal%20Gamepad%20Settings.html#values-needed-for-button:~:text=input_value%3A%20The%20input%20value.%20Available%20options%20can%20be%20found%20here). The `input_value` option, second from the bottom
