### ISSUE TITLE
N64 Emulator Running too fast

### ISSUE THREAD

**Issue by Spl0osh** [emulatorjs/emulatorjs#412]
When opening an N64 Rom, (ex Banjo Kazooie) It runs way too fast, I recommend creating an option to limit the CPU usage.

**Comment by ethanaobrien** [comment]
This was fixed on the newer version of the cores. If you are using the old cores, or if you are on ios than that is the reason why this happens

**Comment by c22dev** [comment]
what if we have no choice of using old cores for net play ?

**Comment by allancoding** [comment]
we are working on adding netplay for the new cores.
