### ISSUE TITLE
Dpad will not recognize inputs

### ISSUE THREAD

**Issue by josephcooley** [emulatorjs/emulatorjs#413]
I have a 8bitdo SN30 Pro and I am trying to get it to work with my installation of EmulatorJS on Truenas scale.  The controller will register the analog stick and buttons in the settings menu but it wont during the game.  I have tried to manually remap the dpad but with no luck.  The controller buttons all seem like they should be working correctly and the look like they're mapped in the controller settings but no input in game. This behavior is the same when in wireless or wired mode.

**Comment by ethanaobrien** [comment]
This sounds really weird, and I can't directly test since I don't have that type of controller, so could you answer these questions and get back to me when you can?

Are there any errors in the console?

Do regular keyboard inputs work?

And if you are able, could you test with another controller to see if it's the controller or the program?


Thank you!

**Comment by josephcooley** [comment]
I tried with an xbox 360 controller and the usb port and it works fine. 
This is what the configuration for the 8bitdo bluetooth controller looks like.
https://i.imgur.com/Lgqris7.jpg
keyboard keys work
nothing on console that I could see.  (I'm assuming you mean logs?)

The SN30 Pro does all of the correct commands when i test it out in windows bluetooth controller configuration ( Up is up, down is down, etc.) and all the buttons register.

**Comment by ethanaobrien** [comment]
>nothing on console that I could see. (I'm assuming you mean logs?)

Yeah, thats what the console is

Also, you should not be mapping controls in the retroarch menu (not sure how you are even accessing it)

You should be using this button to map the controls
![Screenshot 2022-11-09 10 06 12 PM](https://user-images.githubusercontent.com/77750390/200998230-491230a5-1b10-4489-a637-625c7f04e827.png)

Could you test this on https://demo.emulatorjs.org ?

**Comment by josephcooley** [comment]
Yes and no,  I dont have that button on my screen for some reason.  I was
able to load a rom into the test site and it was able to get all of the
buttons to work but the D Pad like my installation.  The analog
sitck worked for dpad inputs but I want to use the dpad for my games.  For
some reason my installation doesnt have the icons like the test
installation, any idea why my installation wouldnt have those buttons?  I
did a standard installation from the truecharts app site within the truenas
core installation.

**Comment by ethanaobrien** [comment]
From the sounds of it you're using linuxservers emulatorjs. This project is actually completely different. If your controller does not work on this nor that project then chances are it's either a problem with a driver, the browser, or the controller. Sorry for the trouble

**Comment by josephcooley** [comment]
Ok, thanks for the clarification. Is there a way to use your installation
in a docker container on TrueNas Scale?

**Comment by ethanaobrien** [comment]
Not at the moment, sorry

**Comment by ghost** [comment]
I'm actually having the same issue with a "gamesir-T3s", granted I'm using the RomM wrapper but to my best understanding they're just pulling EmulatorJS directly and not modifying how it handles controllers. I noticed that some of my other buttones were messed up, like select and start were lft bottom shoulder and right bottom shouylder and the left trigger is "right stick x+1" and the right joystick cannot be set in the up or down direction and the right trigger cannot be set, is it possible that EmulatorJS simply rejects all controller commands that are outside of an internal list, even if they would end up mapping to a used button?
