### ISSUE TITLE
Feed blob instead of game rom url

### ISSUE THREAD

**Issue by imneckro** [emulatorjs/emulatorjs#419]
Hello everyone
Can you feed blob to EJS_gameUrl variable instead of rom url?

**Comment by ethanaobrien** [comment]
Yes, next time please test this before opening an issue

**Comment by imneckro** [comment]
hello @ethanaobrien ! thanks for your quick reply!Indeed was trying to feed blob and got the below error and thought to ask if possible.
![image](https://user-images.githubusercontent.com/42493772/202532146-873669cf-d44d-4460-a3b1-203747350007.png)

navigating to the error
![image](https://user-images.githubusercontent.com/42493772/202532566-d9586751-26b1-4945-91a0-6be42cef8ebd.png)

**Comment by ethanaobrien** [comment]
Thats something that needs to be fixed

**Comment by ethanaobrien** [comment]
Nevermind, You're core files are outdated. Please update your `data/` directory
![Screenshot 2022-11-17 1 09 46 PM](https://user-images.githubusercontent.com/77750390/202536663-f182e638-8dcc-41ee-9091-2b5a76cf6c4b.png)

**Comment by imneckro** [comment]
sorry @ethanaobrien. as long as netplay isnt supported and ios bugs not fixed update not gonna happen.
thanks anyway

**Comment by ethanaobrien** [comment]
Well iOS bugs are fixed and please don't open issues if you aren't using the newest version of emulatorjs

**Comment by ethanaobrien** [comment]
@imneckro Just letting you know, netplay is now supported!
