### ISSUE TITLE
Open source libs

### ISSUE THREAD

**Issue by thelamer** [emulatorjs/emulatorjs#42]
@ethanaobrien I am in the process of publishing a web based emulator frontend. While building and tying things to emulatorJS I started tinkering with the libretro emscripten cores. I got most of the stuff working pretty much 1:1 compatible with emulatorJS var setting then loader here: 
https://github.com/linuxserver/libretrojs

The frontend will be live soon but it can be tested with the docker image `lsiodev/emulatorjs` : 
```
docker run --rm -it -p 3000:3000 -p 80:80 lsiodev/emulatorjs bash
```

I am consuming your repo for where I still use emulatorJS (32x, psx, saturn, 3do, n64, ds, pce), it would be cool if you could cut a release so I could ingest at latest release vs the the main branch.

**Comment by ethanaobrien** [comment]
Thank you Soooo much!!

I'll look into that

Now that I know where the base code came from, I can add credits

**Comment by thelamer** [comment]
This is all in house, I am a linuxserver team member, I publish all my code under the org.
