### ISSUE TITLE
GB save states not loading

### ISSUE THREAD

**Issue by bmaninbama** [emulatorjs/emulatorjs#421]
While playing Final Fantasy Adventure on GB and reaching near end game, the save states stopped loading.  Every time I start the game and try to load any previous save state on the server at retrogames.cc, the game's opening screen remains instead of loading the save.  I also tried to load an old save state for Final Fantasy II on NES with the same result.  I also tried on multiple browsers with no luck.  Does anybody have any ideas why it would start doing that?

**Comment by FlorianH1989** [comment]
+1 every other Emulator loads save states just fine. But GB and GBC are not loading save state  at all.
What kind of logs can we provide to help you?

**Comment by bmaninbama** [comment]
I honestly don't know.  What kind of logs do you have?

**Comment by ethanaobrien** [comment]
Retrogames.cc does not use this project
