### ISSUE TITLE
Add mame0.243

### ISSUE THREAD

**Issue by biglad** [emulatorjs/emulatorjs#422]
Hi, cam EJS_core = 'mame0.243'; be added please

https://www.emulatorjs.com/arcade.html

Thanks

**Comment by ethanaobrien** [comment]
Mame 0.243 cannot be added, as it is not supported by retroarch.

Here are the supported mame versions:
![image](https://user-images.githubusercontent.com/77750390/202860968-0438e248-c9b6-4df2-a395-79659af68d92.jpeg)
