### ISSUE TITLE
Why  remove 'netplay' feature

### ISSUE THREAD

**Issue by seraph98** [emulatorjs/emulatorjs#426]
Hi, as I have checked with ChangeLog, I find the repo remove netplay feature in v2.2.3 , I want to know why remove it (I think it's a very good feature). And the feaure seems like will be added again in the feature, as V3.1.0  said 'Beta netplay cleanup (not yet working)'.   

This feature is very good, so what's your plan for netplay?

**Comment by ethanaobrien** [comment]
See #362 #329 #326 #403 #418 #425 for mort information

I scrapped out netplay because it didn't work - it shouldn't have even worked in the first place, it wasn't possible. I scrapped out netplay and plan to redo it but that's a huge feature.

I've been working on it, although I've had many many setbacks because of the difficulty of the feature. All I can say is it will come when it comes

**Comment by ethanaobrien** [comment]
Also, see #69 for the entire bug and all details

**Comment by seraph98** [comment]
Hi, very thanks for your reply.  But I notice that , if I imort emulatorjs by "https://www.emulatorjs.com/loader.js", and after I set EJS_netplayurl. (lobby.emulatorjs.com),  it works.

**Comment by seraph98** [comment]
As I checked the code of "https://www.emulatorjs.com/loader.js", it's very different with "https://github.com/EmulatorJS/EmulatorJS/blob/main/data/loader.js"

**Comment by seraph98** [comment]
And this is a website which supports netplay, I think this website should also use emulatorjs https://www.retrogames.cc/arcade-games/marvel-vs-capcom-clash-of-super-heroes-980123-usa.html

**Comment by seraph98** [comment]
So what's the diffrence between https://www.emulatorjs.com/loader.js and https://github.com/EmulatorJS/EmulatorJS/blob/main/data/loader.js

**Comment by ethanaobrien** [comment]
> "https://www.emulatorjs.com/loader.js", and after I set EJS_netplayurl. (lobby.emulatorjs.com), it works.

EJS_netplayurl is specific to this project and shouldn't have any affect there

> So what's the diffrence between https://www.emulatorjs.com/loader.js and https://github.com/EmulatorJS/EmulatorJS/blob/main/data/loader.js

It's a completely different project. Has ads, very suspicious code, several bugs and problems with the audio and performance with no way to report any of these bugs (and ads). If you require netplay, you can use it, but any bugs you encounter I cannot help with. Expect performance and audio issues

**Comment by seraph98** [comment]
Oh, Okay, thanks a lot for your explaintion. Hope emulatorjs can release netplay feature, best wishes ！

**Comment by ethanaobrien** [comment]
No problem. I really wish this feature that would just work

**Comment by ethanaobrien** [comment]
@seraph98 Just letting you know, I have re-added netplay!

**Comment by seraph98** [comment]
> @seraph98 Just letting you know, I have re-added netplay!

Thank you so much, I will update as soon as possible
