### ISSUE TITLE
enable recording

### ISSUE THREAD

**Issue by anthonyscorrea** [emulatorjs/emulatorjs#428]
The recording driver is currently null. I believe this is an issue with how retroarch is built. I think it needs to include ffmepg, then retroarch/libretro has to have some flags set at build time. I've been digging in, but I don't currently have the savvy to figure out how to rebuild RetroArch/libretro/emulatorjs for emscripten with ffmpeg and the record flag set correctly. Then I'm not sure where to put it when I did build it.

- [This is a repo that gets it done for the Retropie, along with some links to tutorials](https://github.com/andybalaam/retropie-recording)
- [This is a repo for a js port of FFMPEG](https://github.com/Kagami/ffmpeg.js)

**Comment by ethanaobrien** [comment]
I already have recording implemented. It should be located on the bar with the rest of the save/load/reset buttons. This part is done in JavaScript since (as you've seen) it doesn't seem to be (easily) possible within the wasm itself. Does the screen recording that is currently implemented not work for you?


Please use https://demo.emulatorjs.org to ensure you're on the correct project, as this project often gets confused with linuxservers emulatorjs

**Comment by anthonyscorrea** [comment]
thank you for such a fast response. i did in fact get the two confused. i stumbled on the other project while searching for a docker container.

let me re-evaluate to see if i can get yours to work and to get it to work for my needs. i was planning on using retroarch's recording capability to stream to twitch. but now that i know about your project, i'll have to see if i can get yours to work the way i need it to.

thanks again.

**Comment by ethanaobrien** [comment]
I recommend using the canvas capture stream api and just capture the canvas that retroarch is drawing to. I couldn't get screen recording to work within retroarch itself

If you do get streaming to twitch to work, I'd happily merge a pull request

**Comment by ethanaobrien** [comment]
Also, here is the exact line number that the screen recording implementation is on, if you need to take a look at it. It is a little messy, but I couldn't find an easier way to do this

https://github.com/EmulatorJS/EmulatorJS/blob/53e6dbc90996b33dd0c8e61c0b4aeaf7c53e9a55/data/emu-main.js#L4387

**Comment by ethanaobrien** [comment]
I'm going to go ahead an close this. Let me know if you have any questions!
