### ISSUE TITLE
[Request] Game search

### ISSUE THREAD

**Issue by Rami-Pastrami** [emulatorjs/emulatorjs#43]
Is it possible to add a search bar per game console to search for a specific game? If you have many roms, scrolling through can take a long while

**Comment by ethanaobrien** [comment]
I don't quite get what you mean. Can you explain?

**Comment by Rami-Pastrami** [comment]
Just realized what I was asking was actually unique to this UI instead:

https://github.com/linuxserver/emulatorjs

Sorry for the confusion!
