### ISSUE TITLE
Netplay "Loading" Stuck on screen

### ISSUE THREAD

**Issue by Cattn** [emulatorjs/emulatorjs#437]
When trying to connect to a server on netplay (Windows, Android - Web (obv)) it will display the list in the background, and a loading message ontop which will stay there seemingly forever

**Comment by Cattn** [comment]
This happens on the demo, haven't tried on webpage I'm hosting although this error did pop up, but that was before the servers worked properly

**Comment by ethanaobrien** [comment]
Strange, could you get me a log of the console?

**Comment by Cattn** [comment]
Will have to do tomorrow, but I will do that

**Comment by Cattn** [comment]
setRemoteDescription failed 
 DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Called in wrong state: stable 
 v=0
o=- 397908837067418834 40 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=extmap-allow-mixed
a=msid-semantic: WMS
m=application 11832 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 54.172.60.94
a=candidate:368215851 1 udp 2113937151 45cce9fc-539b-4af1-856c-b0c1981ce76b.local 36382 typ host generation 1 network-cost 999
a=candidate:320909964 1 udp 16785151 54.172.60.94 11832 typ relay raddr 165.161.23.171 rport 15467 generation 1 network-cost 999
a=ice-ufrag:wn1K
a=ice-pwd:rHFvcloABbeLZUSNZbnwwPp0
a=ice-options:trickle
a=fingerprint:sha-256 95:43:C3:0B:E7:A8:B1:F0:EB:5B:75:2F:89:85:F2:7D:35:04:9E:8A:93:84:E1:30:EE:F8:94:64:7F:55:31:C3
a=setup:active
a=mid:0
a=sctp-port:5000
a=max-message-size:262144

(anonymous) @ emulator.min.js?v=31.5:1
Promise.then (async)
c.addRemoteSdp @ emulator.min.js?v=31.5:1
addNegotiatedMessage @ emulator.min.js?v=31.5:1
e @ emulator.min.js?v=31.5:1
v.emitReserved.v.emit @ emulator.min.js?v=31.5:1
value @ emulator.min.js?v=31.5:1
value @ emulator.min.js?v=31.5:1
value @ emulator.min.js?v=31.5:1
v.emitReserved.v.emit @ emulator.min.js?v=31.5:1
value @ emulator.min.js?v=31.5:1
v.emitReserved.v.emit @ emulator.min.js?v=31.5:1
value @ emulator.min.js?v=31.5:1
value @ emulator.min.js?v=31.5:1
v.emitReserved.v.emit @ emulator.min.js?v=31.5:1
value @ emulator.min.js?v=31.5:1
v.emitReserved.v.emit @ emulator.min.js?v=31.5:1
value @ emulator.min.js?v=31.5:1
value @ emulator.min.js?v=31.5:1
ws.onmessage @ emulator.min.js?v=31.5:1
emulator.min.js?v=31.5:1 Remote peer's sdp: v=0
o=- 397908837067418834 41 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=extmap-allow-mixed
a=msid-semantic: WMS
m=application 11832 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 54.172.60.94
a=candidate:368215851 1 udp 2113937151 45cce9fc-539b-4af1-856c-b0c1981ce76b.local 36382 typ host generation 1 network-cost 999
a=candidate:320909964 1 udp 16785151 54.172.60.94 11832 typ relay raddr 165.161.23.171 rport 15467 generation 1 network-cost 999
a=ice-ufrag:wn1K
a=ice-pwd:rHFvcloABbeLZUSNZbnwwPp0
a=ice-options:trickle
a=fingerprint:sha-256 95:43:C3:0B:E7:A8:B1:F0:EB:5B:75:2F:89:85:F2:7D:35:04:9E:8A:93:84:E1:30:EE:F8:94:64:7F:55:31:C3
a=setup:active
a=mid:0
a=sctp-port:5000
a=max-message-size:262144

**Comment by Cattn** [comment]
So for context, I tried to have my friend make a room 2 player it worked fine, as far as I could tell, so couldn't reproduce the exact issue, but when I made one with 3 people, the second the third person join the room the above message was spammed in my console every time I tried to move, (game didn't freeze but I couldn't make inputs) and third person reported loading message (they are unable to get log unfortunately)

**Comment by ethanaobrien** [comment]
Thank you for this information, so to confirm, this only occurs once someone else joins correct?

**Comment by Cattn** [comment]
Only when a third person joins, correct

**Comment by c22dev** [comment]
it even happen for a room of 2 players if a 2nd play joins on my side.

**Comment by brunosilvagarcia** [comment]
@c22dev me too:
![image](https://github.com/EmulatorJS/EmulatorJS/assets/70672736/f9c2c4dc-141e-4e06-9054-b6f1c7065281)
My server is at this url:
https://brunogarcia.dev/

**Comment by ethanaobrien** [comment]
Closing in favor of #590
