### ISSUE TITLE
Getting an error message when trying to create a netplay room

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#438]
iHi,

When trying to create netplay room - it stucked in "loading"
This is the error i get on console:
Access to XMLHttpRequest at 'https://emuserver.emulatorjs.ga/list?game_id=354&domain=www.miniXXXXX' from origin 'https://www.miniXXXX' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Do i have to add something to my code?
Do i have to download the netplay server in order for this to work?

Thank you.

**Comment by ethanaobrien** [comment]
Yes, it is available to download. 

The issue is you are running an outdated version, you need to upgrade

**Comment by shaylevary** [comment]
I've download now the latest available version, but I will try to clean my cache.
 Thank you for your great and hard work, I was waiting for this netplay feature…  so thank you very much! ❤️
