### ISSUE TITLE
can emulatorjs works  with vue?

### ISSUE THREAD

**Issue by FancyTiger** [emulatorjs/emulatorjs#442]
I try to embed emulatorjs into my website which is writen by Vue3 ;   Vue has it's own rule ,  I try to create player when  mounted() and destory  player when  unmounted(), but there is no information about this,   Anyone who can help would be greatly appreciated!

**Comment by ethanaobrien** [comment]
This isn't technically supported, no. I have a `EJS_terminate` function (only defined once the game starts) but this doesn't always completely kill the emulator. For best results, refresh the page. There's nothing I can do about this.
