### ISSUE TITLE
Game doesn't run on firefox

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#443]
Hi,

When i try to run games on firefox, i get an error message on console after clicking on the "start" button.

Uncaught 
Object { node: undefined, setErrno: setErrno(errno), errno: 2, code: "ENOENT", message: "No such file or directory", stack: "ensureErrnoError@https://xxxx.emu-main.js?v=31.5 line 118 > 
eval:1:140993\nstaticInit@https:///emu-main.js?v=31.5 line 118 >

**Comment by ethanaobrien** [comment]
What system?

What core?

Are you on the latest update?

I need a log of the entire console, not just the first red thing you see.

Does the game start regardless of this error?

**Comment by shaylevary** [comment]
Sorry, was my fault, some cache issue.
I've cleaned all cache and now everything running good.

Thank you.
