### ISSUE TITLE
Sega CD game showing a black screen only.

### ISSUE THREAD

**Issue by Lordpun** [emulatorjs/emulatorjs#449]
![Untitled95](https://user-images.githubusercontent.com/120076268/206354105-cc5e92eb-b52a-4c92-b988-acc7c83e5fb5.png)
I was trying to get Sonic CD to work, but for some reason when it loads it show shows a black screen.

**Comment by ethanaobrien** [comment]
Try using https://rawcdn.githack.com/EmulatorJS/EmulatorJS/main/data/ as your path to data (and https://rawcdn.githack.com/EmulatorJS/EmulatorJS/main/data/loader.js as your loader file) and let me know if that works

**Comment by Lordpun** [comment]
I tried adding the links and it's still the same.

**Comment by ethanaobrien** [comment]
Can you try renaming your rom (and the gameurl) to have no spaces?

**Comment by Lordpun** [comment]
It still shows the black screen even when I remove spaces.

**Comment by ethanaobrien** [comment]
Then there's nothing I can do, it's not a problem with emulatorjs. The file is giving the 404 http error when fetched, meaning the file isn't found. This is likely a replit security feature, it may detect the file is a rom and block it. Please try some other way
