### ISSUE TITLE
where are image assets defined?

### ISSUE THREAD

**Issue by teddblue** [emulatorjs/emulatorjs#45]
hello, im trying to find out where image urls are for things like 'save state', 'load state', and 'fullscreen' buttons so that i can make my own assets. any help would be much apreciated!

**Comment by ethanaobrien** [comment]
Hello @teddblue . Thank you for opening an issue

The images for the menu buttons are located towards the bottom of the emulator.js file. search for `this['icons'] = {` in the emulator.js file. The one result you get is where all the icons are

**Comment by teddblue** [comment]
Ok, thank you!
