### ISSUE TITLE
Profiles... What are they? How to use them?

### ISSUE THREAD

**Issue by LostOnTheLine** [emulatorjs/emulatorjs#451]
There is an option in the settings for `Profile Management` & the ability to create profiles... But I can't find a way to login to those profiles or any information on what they do... Is this a feature that is in development that cannot be used yet or am I just missing it?

**Comment by ethanaobrien** [comment]
Hello, could you please confirm you are using this project and not [this project](https://github.com/linuxserver/emulatorjs). You can view the demo [here](https://demo.emulatorjs.org)
