### ISSUE TITLE
"Click to make keyboard keys  work" overlay stays put after entering "gamepad mode" on Xbox

### ISSUE THREAD

**Issue by astrohart** [emulatorjs/emulatorjs#453]
![image](https://user-images.githubusercontent.com/8261875/209448605-1931415e-b9f4-4c30-aed0-70272355f056.png)
**Figure 1.** The **Click to Make Keyboard Keys Work** overlay.

![image](https://user-images.githubusercontent.com/8261875/209448658-fa1bbb5c-6921-49a6-a316-ede31389fdfc.png)
**Figure 2.** The **Menu** button on my Xbox game controller.

![image](https://user-images.githubusercontent.com/8261875/209448697-0495c948-661d-4ad7-85df-ff43b43e7ee4.png)
**Figure 3.** Pressing and holding the **Menu** button on the Xbox game control to summon the Microsoft Edge context menu makes the **Click to Make Keyboard Keys Work** overlay appear.

Hi,

Wonderful emulator!  It's very cool.

However, I am running into a bit of an issue using it on Xbox One with the built-in Microsoft Edge browser that comes built-in to Xbox One.

The issue is, in order to actually play the built in emulated game with my Xbox controller, I need to press and hold the **Menu** button on the controller, as shown in **Figure 2**, in order to summon the menu that is shown in **Figure 3**, so that I may click its **Use Game Controls** command, in order to actually play the game.  Thsi is known as **Gamepad Mode** on that browser.

However, doing this on Xbox One causes the overlay shown in **Figure 1** to appear and, as can be seen in the same Figure, my gameplay has to take place with this overlay constantly on the screen.  When I am in **Gamepad Mode**, I cannot click the overlay to make it go away so I can see my game.

I recommend still have the overlay appear, but put it on a timeout, so that if it does not get clicked in a given time interval, the dark overlay automatically disappears so I can play my game without having to squint at it through the **Click to Make Keyboard Keys Work** message.

Thank you.

Brian

**Comment by ethanaobrien** [comment]
This happens on emulatorjs.com, which is not this project. Can you try using this project and sending the results

**Comment by astrohart** [comment]
Hi @ethanaobrien I need clarification on what you mean.  I am not a Javascript expert, so I am unsure what you are talking about.  I am using the website gamephd.com as shown in the screenshots.  I also did go to emulatorjs.com and got the same result.

Therefore, I am assuming that the issue lies somewhere in the technology of EmulatorJS, hence my posting to this GitHub, as it appears that this is the "official" GitHub for EmulatorJS and the URL from which the websites that use it points to the deployed version of this project.  If there is a willingness to investigate whether the root cause of the issue is in this code, or if you would be so kind as to refer me to the proper GitHub or project repo so I can contact the correct people to get this issue addressed, thank you.

**NOTE:**  I have attempted to contact the authors of both gamephd.com and emulatorjs.com however it does not appear that either website has a "contact us" link and/or form; therefore, I was unsure of where else to direct my issue.

Thank you again.

Regards,


Brian Hart

**Comment by ethanaobrien** [comment]
Sorry for the lack of detail, so there are 2 different versions of emulatorjs, this one and emulatorjs.com. They are 2 different versions. The website you use seems to use emulatorjs.com, which has ads, and from what I've noticed several bugs, limited button support for gamepads, etc... and there is no way to report these things. This project is open source and many bugs in that version are not in this version. I'm not affiliated with emulatorjs.com. If you can, you can try https://demo.emulatorjs.org which is the demo I have up. I don't know if it will work on Xbox or not. Let me know if you need anything else!

**Comment by astrohart** [comment]
@ethanaobrien Thank you.  I appreciate your clarification.
