### ISSUE TITLE
Game boy advance not loading

### ISSUE THREAD

**Issue by adeniyisikirat3** [emulatorjs/emulatorjs#454]
Earlier versions of the game boy advanced worked but current version is stuck at loading decompress data forever

https://www.emulatorjs.com/gba.html

**Comment by ethanaobrien** [comment]
This project does not contain the code for emulatorjs.com. We are 2 separate projects.

**Comment by adeniyisikirat3** [comment]
Hi Ethana, 
Thank you for responding


How do I embedd the correct project , I may be doing something wrong as I can't seem to get it to even display the emulator on a page

I tried uploading the data files to my web host's file manager , and then following the way to put script as on a page , as you instructed here : 
https://github.com/EmulatorJS/EmulatorJS/blob/main/docs/Systems/Nintendo%20Game%20Boy%20Advance.md


But, it's just blank.. am I doing something wrong ?

Can't you please show me how to embedd  maybe as an iframe ..or script? So I can test with ROMs online.  I've been trying with a ROM from [https://us.archive.org/](https://disq.us/url?url=https%3A%2F%2Fus.archive.org%2F%3ABn8qcS4KJ0AzSmVGqxi8OKTBqSA&cuid=5120234) , but still the page is still black

**Comment by adeniyisikirat3** [comment]
<div style='width:640px;height:480px;max-width:100%'>
    <div id='game'></div>
</div>




<script type='text/javascript'>
    EJS_player = '#game';
    



    // Can also be mgba
    EJS_core = 'gba';
    



    // URL to BIOS file
    EJS_biosUrl = '';
    



    // URL to Game rom
    EJS_gameUrl = 'https: //my-website/gbagames/ROM-file-name.7z';
    



    // Path to the data directory
    EJS_pathtodata = 'data/';
</script>
<script src='data/loader.js'></script>    





The above is what i pasted on a html page on my website - perhaps I missed something ?

**Comment by ethanaobrien** [comment]
Try https://emulatorjs.org/editor.html

**Comment by adeniyisikirat3** [comment]
You're an awesome dude my man ! That did the trick!... Thanks alot ! . I have a small issue with the screen position However I've posted that on the discussion section

Thanks again!!
