### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by mury2121** [emulatorjs/emulatorjs#455]
Hello! I want to pull roms from remote server but it is not working. Roms must be the same domain for them to work.

Example: 
www.example.com/roms/pokemon.zip work!
www.cnd.example.com/roms/pokemon.zip not working!

Console Error:
error { target: XMLHttpRequest, isTrusted: true, lengthComputable: false, loaded: 0, total: 0, srcElement: XMLHttpRequest, currentTarget: XMLHttpRequest, eventPhase: 2, bubbles: false, cancelable: false, … }
emulator.min.js:1:1239

And without forgetting, only roms less than 1 mb are working on the cdn server. 2 or more mb roms don't work. I tried on 3 servers, same problem. Can you find a solution to this?

**Comment by ethanaobrien** [comment]
This is because of [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). Please take a look at the page.

>And without forgetting, only roms less than 1 mb are working on the cdn server. 2 or more mb roms don't work. I tried on 3 servers, same problem. Can you find a solution to this?

This sounds like a problem with your server, I cannot help you there

**Comment by mury2121** [comment]
Yes you're right it's obviously a CORS problem. But I tried all kinds of ways and could not solve the problem.

Is there any way you can suggest me?

**Comment by ethanaobrien** [comment]
Please read [this documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) that I sent you. It contains what you need to do to fix the problem

**Comment by mury2121** [comment]
I read that page and tried its all. It opens games with low MB, but there is a problem with games with high MB. I'm sorry but I think there is a problem with your code.

**Comment by ethanaobrien** [comment]
I 100% promise that it is a problem with something you're doing. You must set the `Access-Control-Allow-Origin` header to `*` for this to work. This is not a problem with my code.

**Comment by mury2121** [comment]
Thank you for your answers and for such a nice emulator. I couldn't solve the cross problem, but I solved the problem with iframe.
