### ISSUE TITLE
Gamepad

### ISSUE THREAD

**Issue by redscorpse** [emulatorjs/emulatorjs#456]
I'm running emulatorjs from my raspberry pi and using my iPad for playing games. I have an 8bitdo Bluetooth gamepad and I don't know how make it work.

**Comment by ethanaobrien** [comment]
Which part are you having trouble with? Are you having trouble pairing it to your iPad? Are you having trouble configuring the controls?

**Comment by redscorpse** [comment]
> Which part are you having trouble with? Are you having trouble pairing it to your iPad? Are you having trouble configuring the controls?

I pair the controller with my iPad successfully (It works with App Store compatible games) but on emulatorjs on Safari I still have the screen buttons and my controller doesn't work (but when I run a rom, on retroarch on the left-bottom corner appears as 8bitdo was detected)

**Comment by redscorpse** [comment]
I pair the controller with my iPad successfully (It works with App Store compatible games) but on emulatorjs on Safari I still have the screen buttons and my controller doesn't work (but when I run a rom, on retroarch on the left-bottom corner appears as 8bitdo was detected)

**Comment by ethanaobrien** [comment]
Can you confirm you are using this project? Please use the https://demo.emulatorjs.org/ demo website to test it. You must go into control settings and map the controller buttons.

**Comment by redscorpse** [comment]
On this demo it still doesn't work:

 ![](https://user-images.githubusercontent.com/73442486/211167458-54ab7fca-91d3-4d7f-898b-fa13f5b3747a.jpeg)

Eventhough, I think that I'm using https://hub.docker.com/r/linuxserver/emulatorjs and you say "This project is not affiliated with [linuxserver/emulatorjs](https://github.com/linuxserver/emulatorjs)".

But it seems I have the same problem on both 🤷🏻‍♀️ 

→ my gamepad https://www.8bitdo.com/zero2/

(Maybe If I had another gamepad I could test if the problem is related with this)

Thanks anyways.

**Comment by ethanaobrien** [comment]
If you have the problem on both, then chances are it is a safari incompatibility

**Comment by redscorpse** [comment]
It isn't, I've just tried brave and chrome, and I still have the same problem.

**Comment by ethanaobrien** [comment]
Then chances are it's a problem with iOS. I know I've had problems like this before, where several features, like controllers, aren't allowed to be accessed in the browser for some reason.
