### ISSUE TITLE
Using turbo buttons on GB/GBC games

### ISSUE THREAD

**Issue by Jerrk** [emulatorjs/emulatorjs#459]
I've been looking for a way to enable use of turbo buttons when using the GB/GBC emulator Gearboy, but this option does not seem to exist.

Playing GBA games using VBA Next has an option to enable turbo buttons which works without issue.
https://i.imgur.com/eiRFSfM.png

But GB/GBC games using Gearboy do not have this option
https://i.imgur.com/VIjHSa5.png

Is this just intrinsic to the Gearboy emulator that it does not accept turbo buttons?

Is there another way to use turbo buttons on GB/GBC games using EmulatorJS?

**Comment by ethanaobrien** [comment]
Can you confirm this is the project you are using by taking a look at https://demo.emulatorjs.org/ I think you may be looking for linuxservers emulatorjs, which is a different project
