### ISSUE TITLE
Virtual controller on/off

### ISSUE THREAD

**Issue by zmarteline** [emulatorjs/emulatorjs#462]
Can you insert a button to enable/disable virtual gamepad inside the control settings(gamepad) menu? This way I can hide the settings button and still be able to manually disable virtual gamepad when using mobile devices....

Thanks!

**Comment by ethanaobrien** [comment]
This is in the settings menu, in the bottom right corner. I'm not adding it to the screen itself to avoid clutter

**Comment by zmarteline** [comment]
I did not ask to add it to the screen, I ask to add it inside gamepad menu, so I can hide the settings menu without lose the ability of switch it on/off when using mobile devices.

**Comment by ethanaobrien** [comment]
I'll look at doing this

**Comment by zmarteline** [comment]
Is there any news about this request?

**Comment by zmarteline** [comment]
Is there any news?

**Comment by zmarteline** [comment]
@n-at , would be possible to you add this switch inside the gamepad menu? This will alow us to hide the settings menu without lose the ability of switch it on/off when using mobile devices.

Hide the settings menu will prevent users messing configurations...

Thanks in advance!

**Comment by ethanaobrien** [comment]
Added
