### ISSUE TITLE
Virtual controller toggle

### ISSUE THREAD

**Issue by zmarteline** [emulatorjs/emulatorjs#463]
Could you please check my request again?  I did not ask to add it to the screen, I mean inside gamepad menu, so I can hide the settings menu without lose the ability of switch it on/off when using mobile devices. Since inside settings menu users can mess with graphics quality (shaders), I prefer to hide it.
Thanks again.

_Originally posted by @zmarteline in https://github.com/EmulatorJS/EmulatorJS/issues/462#issuecomment-1376478025_

**Comment by ethanaobrien** [comment]
Please do not open duplicate issues once one is closed, if I see fit to reopen them then I will.
