### ISSUE TITLE
EJS_oldCores = true; in netplay.html

### ISSUE THREAD

**Issue by wantt** [emulatorjs/emulatorjs#465]
Thanks for your excellent work !!!!

in file netplay.html line 16, there is : EJS_oldCores = true  while  it is said  netplay only surpport new core, is this a conflict?

when I use EJS_oldCores = false, I can not find netplay button in android device(chrome), but the button appear in iphone device.

**Comment by ethanaobrien** [comment]
Netplay only supports the old cores right now. Support for the new cores is being worked on
