### ISSUE TITLE
Add Game Speed Controller Settings to EmulatorJS

### ISSUE THREAD

**Issue by deadman616** [emulatorjs/emulatorjs#466]
Please Add Game Speed Controller Settings to EmulatorJS, it help Players dodge multiple enemy attacks and jump on fast moving platforms without fail.

**Comment by Ducci9129** [comment]
I would also like something like this, games are always stuck at half speed no matter what setting I mess with or what game I play. I'm hoping this would compensate for it.

**Comment by Ducci9129** [comment]
I thought about this for a bit, if EJS uses Retroarch couldn't we just be given access to the speed controller already built into it?

**Comment by ethanaobrien** [comment]
Yes, the issue with this is that from what I found, and depending on the reason your computer is lagging it could make it worse.

A possible cause for your computer lagging is that the monitor refresh rate is only 30Hz. If you can, setting it to 60Hz would fix this. Although if it's already set to 60Hz, then this is a hardware limitation, and there's nothing you can do about that

**Comment by deadman616** [comment]
What are you all talk about??? All I want is a Speed Controller Settings like in Cheat Engine to Slow games down.

**Comment by ethanaobrien** [comment]
Im talking about that it could majorly affect performance and cause an undesirable outcome

**Comment by deadman616** [comment]
oh..ok

**Comment by deadman616** [comment]
By the way I forgot to ask you. will you be adding the Speed Controller Settings to EmulatorJS or not it's too risky?

**Comment by ethanaobrien** [comment]
I haven't been able to check yet. It'll depend on how much this impacts the performance and cpu usage

**Comment by ethanaobrien** [comment]
Added
