### ISSUE TITLE
PS2 Core request

### ISSUE THREAD

**Issue by zmarteline** [emulatorjs/emulatorjs#468]
Is it possible to add playstation 2 core? Maybe using  "Play!.js" (https://playjs.purei.org/), I really would to love play Sega Phantasy star PS2 remakes on EmulatorJS.

https://docs.libretro.com/library/play/

Thanks!

**Comment by YuushaExa** [comment]
Is it even work?

**Comment by Ramaerel** [comment]
Hey, so even if this is possible there wouldn't be much point. Play!.js does not run well- Like, it's unplayable. This probably won't be feasible for years

**Comment by zmarteline** [comment]
Not true, for a few games it works very well, like those Phantasy star remakes I mentioned...

**Comment by Ramaerel** [comment]
@zmarteline is that in the js version specifically? Because that's where it would suffer

**Comment by ethanaobrien** [comment]
No, this cannot currently be done due to browser limitations and webgl limitations
