### ISSUE TITLE
Add audio to record feature

### ISSUE THREAD

**Issue by ethanaobrien** [emulatorjs/emulatorjs#47]
So far, I have found it is in `window.RA`

**Comment by ethanaobrien** [comment]
Seems as if this isn't currently possible: https://stackoverflow.com/questions/14418530/record-sounds-from-audiocontext-web-audio-api

**Comment by allancoding** [comment]
You could try something like this: [https://developers.google.com/web/updates/2012/02/HTML5-audio-and-the-Web-Audio-API-are-BFFs](https://developers.google.com/web/updates/2012/02/HTML5-audio-and-the-Web-Audio-API-are-BFFs)
If you could find the function for the audio output. All though you would have to join the audio and video.

**Comment by ethanaobrien** [comment]
Nope, I'm trying to do the exact opposite that that article shows

The output is an audiocontext

**Comment by allancoding** [comment]
What line of code is the audio?

Edit: And what line is your screen recording code start?

**Comment by ethanaobrien** [comment]
Not in the visible code, `window.RA`

not sure, just search "screen record"

**Comment by allancoding** [comment]
Something like this? https://github.com/arblast/Chrome-Audio-Capturer

**Comment by ethanaobrien** [comment]
Yes, but that uses the `chrome.tabCapture` api which not every browser has

**Comment by allancoding** [comment]
If you did record screen but the just did the audio?

**Comment by ethanaobrien** [comment]
I've tried that

**Comment by allancoding** [comment]
I found this: https://github.com/libretro/RetroArch/blob/master/emscripten/library_rwebaudio.js
Could that help?

**Comment by ethanaobrien** [comment]
With the beta version, Im thinking about using the retroarch recorder.

**Comment by ethanaobrien** [comment]
finally this can be closed
