### ISSUE TITLE
Playstation system content failing to load

### ISSUE THREAD

**Issue by fuugg** [emulatorjs/emulatorjs#473]
I am using the following config for loading playstation content through the browser (using Chrome):

                <script type='text/javascript'>
                        EJS_player = '#sample';
                        EJS_core = 'psx';
                        EJS_biosUrl = '/emu/bios/Playstation/psx.bin';
                        EJS_gameUrl = '/emu/games/Sony Playstation/Castlevania-Symphony of the Night[U] [SLUS-00067]/Castlevania - Symphony of the Night (USA).cue';
                        EJS_pathtodata = 'data/';
                </script>
                <script src='data/loader.js'></script>

As you can see based on the screen cap, both the bios file and .cue file for the game are downloaded with status 200 from the server.
![emujs1](https://user-images.githubusercontent.com/123603144/214720377-30902aae-4087-4a71-88bf-8a5588460298.jpg)

However, instead of booting into the game, emulator instead just boots into the retroarch front end. Console output as seen.

![emujs3](https://user-images.githubusercontent.com/123603144/214721060-f75c04c4-2795-464c-9553-b98d7e431120.jpg)

At first I thought that the uncaught FS error must have something to do with the issue, but as you can see, similar errors appear even when booting content that loads properly (following is an n64 game):
![emujs4](https://user-images.githubusercontent.com/123603144/214721356-4ac075a1-1ce5-498b-88d2-7d4a22175ae9.jpg)

I have tried booting several different playstation titles, all with this exact same result. All of these titles work properly on my locally installed retroarch, which utilizes the same exact bios file. I've also had similar results with the demo page (https://demo.emulatorjs.org/) using the click and drag method, where other systems appear to work as well.

**Comment by Ramaerel** [comment]
Hi, I'm unsure on the specifics but I know loading a CUE file directly has never worked for me- You'll need to load the accompanying BIN file

**Comment by ethanaobrien** [comment]
I think the cue problem is an issue with the backend emulator, not something I can fix. Can you try another rom format?

**Comment by fuugg** [comment]
Thanks for the reply. I just tried this same exact process with three other games, only instead of loading the .cue file, i loaded the .bin like you suggested. Unfortunately, the result was very similar. The only difference is that the 'Downloading game data' step takes significantly longer due to the much larger file size. Also, when the retroarch front end appears, there is now an error message 'Failed to load content' in the lower left hand corner, which did not appear when using the .cue files.

![emujs5](https://user-images.githubusercontent.com/123603144/214765941-83aefcbd-bb61-4e43-b86f-83a7c4a48711.jpg)

As far as Playstation games, the only file type i have (besides the associated .cue files) are .bin. If you'd like me to try another format let me know and I'll seek it out.

**Comment by fuugg** [comment]
I did some experimenting today. I have not had success loading playstation games directly from the .bin files on my locally installed Retroarch with the Mednafen based psx emulator cores. I was only able to do this with the PCSX ReARMed core. 

If the Mednafen cores are unable to 'see' standalone .bin files, then I have a suspicion that the issue with EmulatorJS comes from the embedded Retroarch session being unable to find the .bin files associated with the .cue sheet, since only the Mednafen cores are available. This is also supported because the .bin file never downloads according to the network tab in the Chrome developer tools when the EJS_gameurl is set to a .cue file. 

I'd like to see if I can try to run an image manually from within the Retroarch ui in EmulatorJS. However, I'm not sure where to drop the files so that it will see them. It looks like the default data directory in the ui is /home/web_user/retroarch. Does this map to somewhere on the local machine which runs the browser or is it all just virtual space running for the emulator?

**Comment by ethanaobrien** [comment]
This is correct. The core emulatorjs uses doesn't support cue files, and I haven't looked much on adding the other core. 

What do you mean you're not sure where to drop files to use them? What are these files being used for? What files?

**Comment by fuugg** [comment]
> This is correct. The core emulatorjs uses doesn't support cue files, and I haven't looked much on adding the other core.

I may be misunderstanding how things work, or perhaps just confused in general here. According to the EmulatorJS docs (https://github.com/EmulatorJS/EmulatorJS/blob/main/docs/Systems/PlayStation.md), EmulatorJS utilizes the Mednafen Playstation emulator cores. The Mednafen docs at https://mednafen.github.io/documentation/ state under the section 'CD Emulation' that 'Mednafen can load CD-ROM games from a dumped copy of the disc, such as CUE+BIN'. This is supported by my own experience using my locally installed Retroarch, which always successfully loads .cue files with the Beetle PS core, which I understand is a fork of Mednafen. So from my understanding, .cue files should be supported by the core itself. Please correct me if this assumption is wrong. If it is, your doc (https://github.com/EmulatorJS/EmulatorJS/blob/main/docs/Systems/PlayStation.md) probably should be updated to remove the .cue file type under the section titled 'ROM Type'. 

> What do you mean you're not sure where to drop files to use them? What are these files being used for? What files?

sorry for being vague. I'll wait to hear whether or not i'm off base concerning the .cue files before get too deep into my troubleshooting ideas about this. If i am, it would be a waste of time to elaborate on this. 

Can I ask for an example, or maybe a script sample, of the exact method you have used in testing the PS core on EmulatorJS? Has it been tested successfully before? It just seems strange that several other cores in EmulatorJS work great for me, but I have been unable to get the PS ones to work at all even while using content that I know works in a locally installed instance of Retroarch.

**Comment by woolang501** [comment]
In the previous version, I just choose the .cue or .bin file, then select Playstation system at the combo box and the game (tekken 3) just... load.
In this version, it is stuck at 'Game core ready' screen :( :(

**Comment by ethanaobrien** [comment]
You can set `EJS_oldCores` to true for now

**Comment by ethanaobrien** [comment]
Will be fixed in the next update

**Comment by ethanaobrien** [comment]
Fixed. This was a user configuration error. This is now done by the code automatically
