### ISSUE TITLE
[Feature Request] ROM encryption

### ISSUE THREAD

**Issue by donmor** [emulatorjs/emulatorjs#475]
Can the rom be encrypted? In case we are using a customized rom (e.g. a smw hack under test) and we need to prevent it from being downloaded. Maybe we can use AES for data and RSA for the key.

**Comment by donmor** [comment]
Another solution: compress the rom with password and put rsa-encrypted password file and public key along with the archive.

**Comment by ethanaobrien** [comment]
In any situation, the password and the encrypted data will need to be sent to the client, making it completely useless.

This is very very unlikely to ever be supported
