### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by Snoni** [emulatorjs/emulatorjs#476]
im trying to link to a rom at `files.example.com` from `example.com`
im getting "Network Error" with this in the console log

`example.com/:1 Access to XMLHttpRequest at 'https://files.example.com/rom.bin' from origin 'https://example.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

but i dont know how to add this `Access-Control-Allow-Origin`  to  a header

**Comment by Cattn** [comment]
What are you hosting with?

**Comment by Snoni** [comment]
github pages for the regular domain
and a custom apache server for the subdomain

**Comment by ethanaobrien** [comment]
Please use google next time, it will tell you exactly what you need

Access-Control-Allow-Origin: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin
CORS: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

To fix, you need to set the `Access-Control-Allow-Origin` header to `*` on the `files.example.com` server
