### ISSUE TITLE
Cheats on mobile screen 

### ISSUE THREAD

**Issue by 280b9f9b** [emulatorjs/emulatorjs#481]
Can anyone help me to get cheats icon on mobile screen !!!!!

**Comment by 280b9f9b** [comment]
![Uploading IMG_0347.png…]()

Before You push START GAME you have to set mobile screen in landscape (widescreen) position 

![Uploading IMG_0345.jpeg…]()

**Comment by 280b9f9b** [comment]
Before You push START GAME you have to set mobile screen in landscape (widescreen) position

**Comment by 280b9f9b** [comment]
Solved

Before You push START GAME you have to set mobile screen in landscape (widescreen) position.

**Comment by ethanaobrien** [comment]
Some buttons will be hid on setup if the screen isn't wide enough. Maybe we should change what we hide?
