### ISSUE TITLE
EmulatorJS.org can't package DS games into single files

### ISSUE THREAD

**Issue by choccymalk** [emulatorjs/emulatorjs#487]
Here's the error:
editor.js:157 Uncaught (in promise) RangeError: Invalid array length
    at Function.from (<anonymous>)
    at HTMLAnchorElement.<anonymous> (editor.js:157:38)
(anonymous) @ editor.js:157
It seems to happen here:
var b = JSON.stringify(Array.from(new Uint8Array(await (new Blob([file])).arrayBuffer())));

**Comment by ethanaobrien** [comment]
What is the size of the rom you are trying to package?

**Comment by choccymalk** [comment]
It's about 128 MB. I don't think the uint8 array is large enough for it.

**Comment by ethanaobrien** [comment]
No, the issue is it isn't possible to have that much data in a uint8array, the file is too big. Try zipping the file. I'll add an error message at some point to alert the user that the file was too big
