### ISSUE TITLE
Is it possible to extract multiple files for the ROM?

### ISSUE THREAD

**Issue by Johnjoedean** [emulatorjs/emulatorjs#49]
Under the one of the gameurl scripts was libunrar.js, and that JavaScript was able to extract multiple rar files with them being part1.rar to partN.rar. I was wondering if this was possible under the current ussage of the emulator.

**Comment by ethanaobrien** [comment]
I dont think so, At the moment rar extraction seems to be broken. I plan to fix (see #29 )

**Comment by ethanaobrien** [comment]
@Johnjoedean No, not at the moment. Multiple file extraction would probably be pretty unstable - still possible someday

**Comment by ethanaobrien** [comment]
I've been thinking, this wouldnt be very stable and could easily error with the smallest offset variable. I advise just zipping the rom all into one file
