### ISSUE TITLE
Xbox Analog stick not working on N64

### ISSUE THREAD

**Issue by RDude-RampageTeam** [emulatorjs/emulatorjs#493]
When running mario kart 64 on the demo site with a controller plugged in, i can bind all the buttons to the xbox controller buttons including the left and right sticks, but when it comes to the analog stick on the n64 controller the options are greyed out and i cant set them to any controller buttons making it impossible to play. Is this intentional?

**Comment by RDude-RampageTeam** [comment]
huh weird, just tested it and it works. leaving this up though cause i know d-input controllers still have this issue and controllers the dont have analog sticks dont work for the same reason.

**Comment by ethanaobrien** [comment]
The options on n64 are grayed out because it automatically detects any analog input and maps it automatically. You should be able to map other buttons, or a d-pad to these options. Can you not?

**Comment by RDude-RampageTeam** [comment]
Back when I tried mapping my snes dpad to the stick it didnt work.

**Comment by mwmdragon2** [comment]
My PS4 Controller connected via Bluetooth has issues with the sticks not working in the n64 core as well, but they work in other cores.

**Comment by mwmdragon2** [comment]
I found that if I reset the controls, only mapped the d-pad and buttons.. that the sticks (though left empty) auto mapped properly and worked.

**Comment by ethanaobrien** [comment]
That is how it is supposed to be done, so it can fully use the joystick's sensitivity

**Comment by mwmdragon2** [comment]
> That is how it is supposed to be done, so it can fully use the joystick's sensitivity

I wish I had read that somewhere sooner, thanks for confirming :)

**Comment by ethanaobrien** [comment]
>I wish I had read that somewhere sooner, thanks for confirming :)

I added a tool tip when you hover your mouse on it :)

Closing as completed
