### ISSUE TITLE
[Feature Request] Recursive ROM Directory Search

### ISSUE THREAD

**Issue by charles-spurgeon** [emulatorjs/emulatorjs#494]
Sorry for spamming the bug component, I didn't see a better spot.  I just wanted to quickly request a feature to recursively scan platform/roms subdirectories.

My use case is that I host my ROMs from [RetroNAS](https://github.com/danmons/retronas) so I can load ROMs on multiple platforms from one place.  Given the size of my library, I order titles under alphabetical groupings.

Perhaps there's an upper limit on the number of roms that can be efficiently indexed by the platform but It would be super awesome if emulatorJS could scan directories under platform/roms to add them as playable titles.

This would enable a high level of inter-operability between all the platforms: MiSTer, Batocera, RetroPie, emulatorJS, RetroArch, etc.

Thanks for your time and contributions!

**Comment by ethanaobrien** [comment]
Can you confirm this is the project you are using by taking a look at https://demo.emulatorjs.org/ I think you may be looking for linuxservers emulatorjs, which is a different project

**Comment by TheMrChao** [comment]
I did intentionally post in this project but I re-read the documentation and I see that lsio project would be a more appropriate place to post.

**Comment by ethanaobrien** [comment]
This and that project are 2 completely separate things.
