### ISSUE TITLE
Atari 2600

### ISSUE THREAD

**Issue by dosboxonline** [EmulatorJS/EmulatorJS#5]
https://www.emulatorjs.com/a2600.html

**Comment by dosboxonline** [comment]
https://www.emulatorjs.com/cores/a2600-wasm.data

**Comment by ethanaobrien** [comment]
@dosboxonline Thank you. I should have time to add later today. Thank you for including the links! It is very helpful!

**Comment by ethanaobrien** [comment]
Just pushed changes! Let me know if there is still a problem
