### ISSUE TITLE
Google sites and github errors

### ISSUE THREAD

**Issue by Darandomcoda** [emulatorjs/emulatorjs#501]
When trying to make a ds emulator in my google site I need to get the game rom and emulator I usually use replit however for two games it is not working Pokemon Black and White plus their sequels. 

<div style='width:640px;height:480px;max-width:100%'>
    <div id='game'></div>
</div>

<script type='text/javascript'>
    EJS_player = '#game';
    
    // Can also be desmume2015 or melonds
    EJS_core = 'nds';
    
    // URL to BIOS file
    EJS_biosUrl = '';
    
    // URL to Game rom
    EJS_gameUrl = 'Pokemon_ Black Version (1).zip';
    
    // Path to the data directory
    EJS_pathtodata = 'data/';
</script>
<script src='data/loader.js'></script>

Thats my script

**Comment by Darandomcoda** [comment]
Also the ALAN coding version is giving me 404

**Comment by Darandomcoda** [comment]
When I run the program its stuck on Game core ready Downloading game data , and It never changes.

**Comment by ethanaobrien** [comment]
Include a log of the console and the other required information. They can be found in the issue template

**Comment by Darandomcoda** [comment]
How do we do that???

**Comment by Darandomcoda** [comment]
> Include a log of the console and the other required information. They can be found in the issue template

How do we do that???

**Comment by ethanaobrien** [comment]
They can be found in the template you should've used. Look here: https://github.com/EmulatorJS/EmulatorJS/blob/main/.github/ISSUE_TEMPLATE/bug.md

**Comment by Darandomcoda** [comment]
This is very confusing can you explain?

**Comment by ethanaobrien** [comment]
```
- [ ] I have collected a **FULL** log of the console, with `EJS_DEBUG_XX` set to true, and uploaded it straight to GitHub.
- [ ] I have not made any changes to the EmulatorJS instance I am running into this bug on.
- [ ] I am on the latest version of EmulatorJS
- [ ] I have not attached any images or logs via external sites. I have uploaded them straight to GitHub and acknowledge that external sites may pose a security issue.
- [ ] I have included, **IN DETAIL**, the steps to reproduce the bug.

<!-- 
To collect a log of the console.
1. Add the following line to your code

EJS_DEBUG_XX = true;

2. Right click and click `inspect`.
3. Select the `console` tab at the top.
4. then reload the broken page.
5. Right click on the console and click `Save as...`
6. Upload it to your issue.
 -->
```

**Comment by Darandomcoda** [comment]
HUH?. I am very new to this and am making this for my friend please send a video or explain it to me.

**Comment by Darandomcoda** [comment]
I did a little digging and I found out what to to however I dont know where to input the EJS_DEBUG_XX = true; code

**Comment by Darandomcoda** [comment]
loader.js:52 Path to data is set to https://ds-emu-7.ahmrandomvids.repl.co/data/
loader.js:7 Using emulatorjs version 0.4.24 but the newest version is 31.6

open https://github.com/ethanaobrien/emulatorjs to update
injectable_content.min.js:1 Injectable Content:  Object
DevTools failed to load source map: Could not load content for chrome-extension://gekdekpbfehejjiecgonmgmepbdnaggp/adguard/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://gekdekpbfehejjiecgonmgmepbdnaggp/adguard/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
emulator.js?v=0.4.24:842          HEAD https://ds-emu-7.ahmrandomvids.repl.co/Pokemon_%20Black%20Version%20(1).zip 404
(anonymous) @ emulator.js?v=0.4.24:842
_0x361fdc.exports @ emulator.js?v=0.4.24:799
_0x5db8bc.exports @ emulator.js?v=0.4.24:720
Promise.then (async)
_0x37287b.request @ emulator.js?v=0.4.24:644
_0x37287b.<computed> @ emulator.js?v=0.4.24:650
(anonymous) @ emulator.js?v=0.4.24:615
(anonymous) @ emulator.js?v=0.4.24:15030
_0x5048db @ emulator.js?v=0.4.24:15028
_0x139f68 @ emulator.js?v=0.4.24:15159
_0x452592 @ emulator.js?v=0.4.24:15244
_0x10b71a @ emulator.js?v=0.4.24:15326
_0x4d7024.wasmData.window.Module.monitorRunDependencies @ emulator.js?v=0.4.24:15337
removeRunDependency @ VM31:1
receiveInstance @ VM31:1
receiveInstantiatedSource @ VM31:1
Promise.then (async)
instantiateArrayBuffer @ VM31:1
instantiateAsync @ VM31:1
createWasm @ VM31:1
Module.asm @ VM31:1
eval @ VM31:1
_0x54d695 @ emulator.js?v=0.4.24:15360
(anonymous) @ emulator.js?v=0.4.24:15364
_0xbae705 @ emulator.js?v=0.4.24:13807
_0x21d6a1 @ emulator.js?v=0.4.24:15368
emulator.js?v=0.4.24:856 Uncaught (in promise) Error: Request failed with status code 404
    at _0xec42e9.exports (emulator.js?v=0.4.24:856:37)
    at _0x402e67.exports (emulator.js?v=0.4.24:850:98)
    at _0x58a51b.onreadystatechange (emulator.js?v=0.4.24:820:37)
_0xec42e9.exports @ emulator.js?v=0.4.24:856
_0x402e67.exports @ emulator.js?v=0.4.24:850
_0x58a51b.onreadystatechange @ emulator.js?v=0.4.24:820
await in _0x58a51b.onreadystatechange (async)
_0x5048db @ emulator.js?v=0.4.24:15028
_0x139f68 @ emulator.js?v=0.4.24:15159
_0x452592 @ emulator.js?v=0.4.24:15244
_0x10b71a @ emulator.js?v=0.4.24:15326
_0x4d7024.wasmData.window.Module.monitorRunDependencies @ emulator.js?v=0.4.24:15337
removeRunDependency @ VM31:1
receiveInstance @ VM31:1
receiveInstantiatedSource @ VM31:1
Promise.then (async)
instantiateArrayBuffer @ VM31:1
instantiateAsync @ VM31:1
createWasm @ VM31:1
Module.asm @ VM31:1
eval @ VM31:1
_0x54d695 @ emulator.js?v=0.4.24:15360
(anonymous) @ emulator.js?v=0.4.24:15364
_0xbae705 @ emulator.js?v=0.4.24:13807
_0x21d6a1 @ emulator.js?v=0.4.24:15368
emulator.js?v=0.4.24:17264 hidden
emulator.js?v=0.4.24:17264 active

**Comment by Darandomcoda** [comment]
This is what is popping up

**Comment by Darandomcoda** [comment]
> ```
> - [ ] I have collected a **FULL** log of the console, with `EJS_DEBUG_XX` set to true, and uploaded it straight to GitHub.
> - [ ] I have not made any changes to the EmulatorJS instance I am running into this bug on.
> - [ ] I am on the latest version of EmulatorJS
> - [ ] I have not attached any images or logs via external sites. I have uploaded them straight to GitHub and acknowledge that external sites may pose a security issue.
> - [ ] I have included, **IN DETAIL**, the steps to reproduce the bug.
> 
> 
> ```

please help

**Comment by Darandomcoda** [comment]
`DevTools failed to load source map: Could not load content for chrome-extension://gekdekpbfehejjiecgonmgmepbdnaggp/adguard/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
loader.js:52 Path to data is set to https://ds-emu-7.ahmrandomvids.repl.co/data/
DevTools failed to load source map: Could not load content for chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://gekdekpbfehejjiecgonmgmepbdnaggp/adguard/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
loader.js:7 Using emulatorjs version 0.4.24 but the newest version is 31.6

open https://github.com/ethanaobrien/emulatorjs to update
injectable_content.min.js:1 Injectable Content:  {flash_sale: true, payment_confirmation: true, expired_advertising_trackers: true, generic_benefits: true, expired_popup_blocker_benefits: true, …}
emulator.js?v=0.4.24:842          HEAD https://ds-emu-7.ahmrandomvids.repl.co/Pokemon_%20Black%20Version%20(1).zip 404
(anonymous) @ emulator.js?v=0.4.24:842
_0x361fdc.exports @ emulator.js?v=0.4.24:799
_0x5db8bc.exports @ emulator.js?v=0.4.24:720
Promise.then (async)
_0x37287b.request @ emulator.js?v=0.4.24:644
_0x37287b.<computed> @ emulator.js?v=0.4.24:650
(anonymous) @ emulator.js?v=0.4.24:615
(anonymous) @ emulator.js?v=0.4.24:15030
_0x5048db @ emulator.js?v=0.4.24:15028
_0x139f68 @ emulator.js?v=0.4.24:15159
_0x452592 @ emulator.js?v=0.4.24:15244
_0x10b71a @ emulator.js?v=0.4.24:15326
_0x4d7024.wasmData.window.Module.monitorRunDependencies @ emulator.js?v=0.4.24:15337
removeRunDependency @ VM75:1
receiveInstance @ VM75:1
receiveInstantiatedSource @ VM75:1
Promise.then (async)
instantiateArrayBuffer @ VM75:1
instantiateAsync @ VM75:1
createWasm @ VM75:1
Module.asm @ VM75:1
eval @ VM75:1
_0x54d695 @ emulator.js?v=0.4.24:15360
(anonymous) @ emulator.js?v=0.4.24:15364
_0xbae705 @ emulator.js?v=0.4.24:13807
_0x21d6a1 @ emulator.js?v=0.4.24:15368
emulator.js?v=0.4.24:856 Uncaught (in promise) Error: Request failed with status code 404
    at _0xec42e9.exports (emulator.js?v=0.4.24:856:37)
    at _0x402e67.exports (emulator.js?v=0.4.24:850:98)
    at _0x58a51b.onreadystatechange (emulator.js?v=0.4.24:820:37)
_0xec42e9.exports @ emulator.js?v=0.4.24:856
_0x402e67.exports @ emulator.js?v=0.4.24:850
_0x58a51b.onreadystatechange @ emulator.js?v=0.4.24:820
await in _0x58a51b.onreadystatechange (async)
_0x5048db @ emulator.js?v=0.4.24:15028
_0x139f68 @ emulator.js?v=0.4.24:15159
_0x452592 @ emulator.js?v=0.4.24:15244
_0x10b71a @ emulator.js?v=0.4.24:15326
_0x4d7024.wasmData.window.Module.monitorRunDependencies @ emulator.js?v=0.4.24:15337
removeRunDependency @ VM75:1
receiveInstance @ VM75:1
receiveInstantiatedSource @ VM75:1
Promise.then (async)
instantiateArrayBuffer @ VM75:1
instantiateAsync @ VM75:1
createWasm @ VM75:1
Module.asm @ VM75:1
eval @ VM75:1
_0x54d695 @ emulator.js?v=0.4.24:15360
(anonymous) @ emulator.js?v=0.4.24:15364
_0xbae705 @ emulator.js?v=0.4.24:13807
_0x21d6a1 @ emulator.js?v=0.4.24:15368
`

**Comment by Darandomcoda** [comment]
Path to data is set to https://ds-emu-7.ahmrandomvids.repl.co/data/
loader.js:7 Using emulatorjs version 0.4.24 but the newest version is 31.6

open https://github.com/ethanaobrien/emulatorjs to update
injectable_content.min.js:1 Injectable Content:  Object
DevTools failed to load source map: Could not load content for chrome-extension://gekdekpbfehejjiecgonmgmepbdnaggp/adguard/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://gekdekpbfehejjiecgonmgmepbdnaggp/adguard/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
emulator.js?v=0.4.24:842          HEAD https://ds-emu-7.ahmrandomvids.repl.co/Pokemon_%20Black%20Version%20(1).zip 404
(anonymous) @ emulator.js?v=0.4.24:842
_0x361fdc.exports @ emulator.js?v=0.4.24:799
_0x5db8bc.exports @ emulator.js?v=0.4.24:720
Promise.then (async)
_0x37287b.request @ emulator.js?v=0.4.24:644
_0x37287b.<computed> @ emulator.js?v=0.4.24:650
(anonymous) @ emulator.js?v=0.4.24:615
(anonymous) @ emulator.js?v=0.4.24:15030
_0x5048db @ emulator.js?v=0.4.24:15028
_0x139f68 @ emulator.js?v=0.4.24:15159
_0x452592 @ emulator.js?v=0.4.24:15244
_0x10b71a @ emulator.js?v=0.4.24:15326
_0x4d7024.wasmData.window.Module.monitorRunDependencies @ emulator.js?v=0.4.24:15337
removeRunDependency @ VM147:1
receiveInstance @ VM147:1
receiveInstantiatedSource @ VM147:1
Promise.then (async)
instantiateArrayBuffer @ VM147:1
instantiateAsync @ VM147:1
createWasm @ VM147:1
Module.asm @ VM147:1
eval @ VM147:1
_0x54d695 @ emulator.js?v=0.4.24:15360
(anonymous) @ emulator.js?v=0.4.24:15364
_0xbae705 @ emulator.js?v=0.4.24:13807
_0x21d6a1 @ emulator.js?v=0.4.24:15368
emulator.js?v=0.4.24:856 Uncaught (in promise) Error: Request failed with status code 404
    at _0xec42e9.exports (emulator.js?v=0.4.24:856:37)
    at _0x402e67.exports (emulator.js?v=0.4.24:850:98)
    at _0x58a51b.onreadystatechange (emulator.js?v=0.4.24:820:37)
_0xec42e9.exports @ emulator.js?v=0.4.24:856
_0x402e67.exports @ emulator.js?v=0.4.24:850
_0x58a51b.onreadystatechange @ emulator.js?v=0.4.24:820
await in _0x58a51b.onreadystatechange (async)
_0x5048db @ emulator.js?v=0.4.24:15028
_0x139f68 @ emulator.js?v=0.4.24:15159
_0x452592 @ emulator.js?v=0.4.24:15244
_0x10b71a @ emulator.js?v=0.4.24:15326
_0x4d7024.wasmData.window.Module.monitorRunDependencies @ emulator.js?v=0.4.24:15337
removeRunDependency @ VM147:1
receiveInstance @ VM147:1
receiveInstantiatedSource @ VM147:1
Promise.then (async)
instantiateArrayBuffer @ VM147:1
instantiateAsync @ VM147:1
createWasm @ VM147:1
Module.asm @ VM147:1
eval @ VM147:1
_0x54d695 @ emulator.js?v=0.4.24:15360
(anonymous) @ emulator.js?v=0.4.24:15364
_0xbae705 @ emulator.js?v=0.4.24:13807
_0x21d6a1 @ emulator.js?v=0.4.24:15368

**Comment by Darandomcoda** [comment]
emulator.js?v=0.4.24:842          HEAD https://ds-emu-7.ahmrandomvids.repl.co/Pokemon_%20Black%20Version%20(1).zip 404
(anonymous) @ emulator.js?v=0.4.24:842
_0x361fdc.exports @ emulator.js?v=0.4.24:799
_0x5db8bc.exports @ emulator.js?v=0.4.24:720
Promise.then (async)
_0x37287b.request @ emulator.js?v=0.4.24:644
_0x37287b.<computed> @ emulator.js?v=0.4.24:650
(anonymous) @ emulator.js?v=0.4.24:615
(anonymous) @ emulator.js?v=0.4.24:15030
_0x5048db @ emulator.js?v=0.4.24:15028
_0x139f68 @ emulator.js?v=0.4.24:15159
_0x452592 @ emulator.js?v=0.4.24:15244
_0x10b71a @ emulator.js?v=0.4.24:15326
_0x4d7024.wasmData.window.Module.monitorRunDependencies @ emulator.js?v=0.4.24:15337
removeRunDependency @ VM169:1
receiveInstance @ VM169:1
receiveInstantiatedSource @ VM169:1
Promise.then (async)
instantiateArrayBuffer @ VM169:1
instantiateAsync @ VM169:1
createWasm @ VM169:1
Module.asm @ VM169:1
eval @ VM169:1
_0x54d695 @ emulator.js?v=0.4.24:15360
(anonymous) @ emulator.js?v=0.4.24:15364
_0xbae705 @ emulator.js?v=0.4.24:13807
_0x21d6a1 @ emulator.js?v=0.4.24:15368
emulator.js?v=0.4.24:856 Uncaught (in promise) Error: Request failed with status code 404
    at _0xec42e9.exports (emulator.js?v=0.4.24:856:37)
    at _0x402e67.exports (emulator.js?v=0.4.24:850:98)
    at _0x58a51b.onreadystatechange (emulator.js?v=0.4.24:820:37)

**Comment by Darandomcoda** [comment]
Error copy and paste
