### ISSUE TITLE
Console issue

### ISSUE THREAD

**Issue by Darandomcoda** [emulatorjs/emulatorjs#503]
I did a little digging and I found out what to to however I dont know where to input the EJS_DEBUG_XX = true; code

**Comment by Darandomcoda** [comment]
loader.js:52 Path to data is set to https://ds-emu-7.ahmrandomvids.repl.co/data/
loader.js:7 Using emulatorjs version 0.4.24 but the newest version is 31.6

open https://github.com/ethanaobrien/emulatorjs to update
injectable_content.min.js:1 Injectable Content:  Object
DevTools failed to load source map: Could not load content for chrome-extension://gekdekpbfehejjiecgonmgmepbdnaggp/adguard/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://gekdekpbfehejjiecgonmgmepbdnaggp/adguard/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
emulator.js?v=0.4.24:842          HEAD https://ds-emu-7.ahmrandomvids.repl.co/Pokemon_%20Black%20Version%20(1).zip 404
(anonymous) @ emulator.js?v=0.4.24:842
_0x361fdc.exports @ emulator.js?v=0.4.24:799
_0x5db8bc.exports @ emulator.js?v=0.4.24:720
Promise.then (async)
_0x37287b.request @ emulator.js?v=0.4.24:644
_0x37287b.<computed> @ emulator.js?v=0.4.24:650
(anonymous) @ emulator.js?v=0.4.24:615
(anonymous) @ emulator.js?v=0.4.24:15030
_0x5048db @ emulator.js?v=0.4.24:15028
_0x139f68 @ emulator.js?v=0.4.24:15159
_0x452592 @ emulator.js?v=0.4.24:15244
_0x10b71a @ emulator.js?v=0.4.24:15326
_0x4d7024.wasmData.window.Module.monitorRunDependencies @ emulator.js?v=0.4.24:15337
removeRunDependency @ VM31:1
receiveInstance @ VM31:1
receiveInstantiatedSource @ VM31:1
Promise.then (async)
instantiateArrayBuffer @ VM31:1
instantiateAsync @ VM31:1
createWasm @ VM31:1
Module.asm @ VM31:1
eval @ VM31:1
_0x54d695 @ emulator.js?v=0.4.24:15360
(anonymous) @ emulator.js?v=0.4.24:15364
_0xbae705 @ emulator.js?v=0.4.24:13807
_0x21d6a1 @ emulator.js?v=0.4.24:15368
emulator.js?v=0.4.24:856 Uncaught (in promise) Error: Request failed with status code 404
    at _0xec42e9.exports (emulator.js?v=0.4.24:856:37)
    at _0x402e67.exports (emulator.js?v=0.4.24:850:98)
    at _0x58a51b.onreadystatechange (emulator.js?v=0.4.24:820:37)
_0xec42e9.exports @ emulator.js?v=0.4.24:856
_0x402e67.exports @ emulator.js?v=0.4.24:850
_0x58a51b.onreadystatechange @ emulator.js?v=0.4.24:820
await in _0x58a51b.onreadystatechange (async)
_0x5048db @ emulator.js?v=0.4.24:15028
_0x139f68 @ emulator.js?v=0.4.24:15159
_0x452592 @ emulator.js?v=0.4.24:15244
_0x10b71a @ emulator.js?v=0.4.24:15326
_0x4d7024.wasmData.window.Module.monitorRunDependencies @ emulator.js?v=0.4.24:15337
removeRunDependency @ VM31:1
receiveInstance @ VM31:1
receiveInstantiatedSource @ VM31:1
Promise.then (async)
instantiateArrayBuffer @ VM31:1
instantiateAsync @ VM31:1
createWasm @ VM31:1
Module.asm @ VM31:1
eval @ VM31:1
_0x54d695 @ emulator.js?v=0.4.24:15360
(anonymous) @ emulator.js?v=0.4.24:15364
_0xbae705 @ emulator.js?v=0.4.24:13807
_0x21d6a1 @ emulator.js?v=0.4.24:15368
emulator.js?v=0.4.24:17264 hidden
emulator.js?v=0.4.24:17264 active

**Comment by Darandomcoda** [comment]
This is the code I got from console pls help

**Comment by Darandomcoda** [comment]
emulator.js?v=0.4.24:842          HEAD https://ds-emu-7.ahmrandomvids.repl.co/Pokemon_%20Black%20Version%20(1).zip 404
(anonymous) @ emulator.js?v=0.4.24:842
_0x361fdc.exports @ emulator.js?v=0.4.24:799
_0x5db8bc.exports @ emulator.js?v=0.4.24:720
Promise.then (async)
_0x37287b.request @ emulator.js?v=0.4.24:644
_0x37287b.<computed> @ emulator.js?v=0.4.24:650
(anonymous) @ emulator.js?v=0.4.24:615
(anonymous) @ emulator.js?v=0.4.24:15030
_0x5048db @ emulator.js?v=0.4.24:15028
_0x139f68 @ emulator.js?v=0.4.24:15159
_0x452592 @ emulator.js?v=0.4.24:15244
_0x10b71a @ emulator.js?v=0.4.24:15326
_0x4d7024.wasmData.window.Module.monitorRunDependencies @ emulator.js?v=0.4.24:15337
removeRunDependency @ VM169:1
receiveInstance @ VM169:1
receiveInstantiatedSource @ VM169:1
Promise.then (async)
instantiateArrayBuffer @ VM169:1
instantiateAsync @ VM169:1
createWasm @ VM169:1
Module.asm @ VM169:1
eval @ VM169:1
_0x54d695 @ emulator.js?v=0.4.24:15360
(anonymous) @ emulator.js?v=0.4.24:15364
_0xbae705 @ emulator.js?v=0.4.24:13807
_0x21d6a1 @ emulator.js?v=0.4.24:15368
emulator.js?v=0.4.24:856 Uncaught (in promise) Error: Request failed with status code 404
    at _0xec42e9.exports (emulator.js?v=0.4.24:856:37)
    at _0x402e67.exports (emulator.js?v=0.4.24:850:98)
    at _0x58a51b.onreadystatechange (emulator.js?v=0.4.24:820:37)

**Comment by Darandomcoda** [comment]
Console error

**Comment by Darandomcoda** [comment]
Someone please let me know what is happening?

**Comment by ethanaobrien** [comment]
A closed issue does not mean that comments cannot be added. And if you read, the second thing it says is

```
Using emulatorjs version 0.4.24 but the newest version is 31.6
open https://github.com/ethanaobrien/emulatorjs to update
```

This means the scripts are so outdated I hadnt even created an organization for the project yet.

Just update the `data/` folder and it should work

**Comment by Darandomcoda** [comment]
I updated the file but there is a new problem

**Comment by Darandomcoda** [comment]
emulator.min.js?v=31.6:1 Error Reporting ID: 1680971233019-329
injectable_content.min.js:1 Injectable Content:  Object
DevTools failed to load source map: Could not load content for chrome-extension://gekdekpbfehejjiecgonmgmepbdnaggp/adguard/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://gekdekpbfehejjiecgonmgmepbdnaggp/adguard/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
VM270:1 Uncaught ErrnoError {node: undefined, errno: 44, message: 'FS error', setErrno: ƒ}
open @ VM270:1
readFile @ VM270:1
setShader @ emulator.min.js?v=31.6:1
(anonymous) @ emulator.min.js?v=31.6:1
B @ emulator.min.js?v=31.6:1
n @ emulator.min.js?v=31.6:1
u @ emulator.min.js?v=31.6:1
(anonymous) @ emulator.min.js?v=31.6:1
Promise.then (async)
t @ emulator.min.js?v=31.6:1
(anonymous) @ emulator.min.js?v=31.6:1
a.oncomplete @ emulator.min.js?v=31.6:1
VM270:1 Uncaught ErrnoError {node: undefined, errno: 44, message: 'FS error', setErrno: ƒ}
open @ VM270:1
readFile @ VM270:1
setShader @ emulator.min.js?v=31.6:1
(anonymous) @ emulator.min.js?v=31.6:1
B @ emulator.min.js?v=31.6:1
n @ emulator.min.js?v=31.6:1
u @ emulator.min.js?v=31.6:1
(anonymous) @ emulator.min.js?v=31.6:1
Promise.then (async)
t @ emulator.min.js?v=31.6:1
(anonymous) @ emulator.min.js?v=31.6:1
a.oncomplete @ emulator.min.js?v=31.6:1

**Comment by Darandomcoda** [comment]
This is the console

**Comment by Darandomcoda** [comment]
and its taking me to the retro arch home screen or error area

**Comment by ethanaobrien** [comment]
2 things, Those errors mean nothing, that is why I ask for a complete error of the console, because you do not know what everything means. I was able to find your issue with your error reporting ID. That is because replit seems to be anti-piracy and block any roms. Your file is returning `404` which means not found. I cannot fix this as the way youre doing this isnt legal and replit doesnt like that

**Comment by Darandomcoda** [comment]
This is not the issue other Nintendo DS games are running just pokemon black and white or black and white 2 are not

**Comment by ethanaobrien** [comment]
Not all detection technologies are perfect
