### ISSUE TITLE
[Bug] arcade core

### ISSUE THREAD

**Issue by koraytastan** [emulatorjs/emulatorjs#504]
The old "arcade" core was running Shadow Dancer game. 
But in this version Shadow Dancer and other same games does not load with "Failed Content" error when loading roms. I hope the arcade core rom will be updated.

**Comment by ethanaobrien** [comment]
set `EJS_oldCores` to `true`. This happens because I havent had the time to make it to where the games know what arcade core to use, as the new version has 2.

**Comment by koraytastan** [comment]
I am pleased with your reply. However, I get the same error with the following code. Also the "mame2003" core is not working. Is it possible to check the core (old) files?

`
  <div style='width:640px;height:480px;max-width:100%'>
    <div id='game'></div>
</div>

<script type='text/javascript'>
    EJS_player = '#game';

    EJS_biosURL = 'bios.zip';
    
    // Can also be fbalpha2012_cps1 or fbalpha2012_cps2
    EJS_core = 'arcade';
    
    // URL to Game rom
    EJS_gameUrl = 'shdancer.zip';
    
    // Path to the data directory

    EJS_pathtodata = 'data';

    EJS_oldCore = true;
</script>
<script src='data/loader.js'></script>`

**Comment by ethanaobrien** [comment]
If a game doesnt work, Its not a problem here, its a problem with the retroarch core. I cannot fix this

**Comment by koraytastan** [comment]
It works flawlessly with the following script address. I wonder if this system does not belong to you? 

https://www.emulatorjs.com/loader.js
( FBA v0.2.97.42 ROMs set)

**Comment by ethanaobrien** [comment]
I have not managed to get that core working yet in this project. Sorry

**Comment by koraytastan** [comment]
Thanks for replies. Best.
