### ISSUE TITLE
ask for your suggestions

### ISSUE THREAD

**Issue by shahram7** [emulatorjs/emulatorjs#505]
Hello everyone,
I'm not here to report an issue. I just need to ask for some suggestions.
I installed emulatorjs with docker from linuxserver on my proxmox homeserver.
Now I want to play on my Android TV, but the native web browser installed on my Bravia makes it impossible.
I just wanted to ask if there is an android app that plays the front end roll?
Best Regards

**Comment by ethanaobrien** [comment]
Please see [here](https://github.com/linuxserver/emulatorjs/issues/24) This is not the repository youre looking for. Sorry
