### ISSUE TITLE
[Bug] SVG version of EmulatorJS icon?

### ISSUE THREAD

**Issue by loganmarchione** [emulatorjs/emulatorjs#506]
Hello there! 👋

I'm the maintainer of [homelab-svg-assets](https://github.com/loganmarchione/homelab-svg-assets) and would like to add the [EmulatorJS icon](https://github.com/EmulatorJS/EmulatorJS/blob/main/docs/Logo-light.png) to my project. However, I didn't see any brand guidelines or a vector (SVG) version of the icon. Could you please provide one or both of these?

Thanks, and keep up the good work!

**Comment by ethanaobrien** [comment]
I believe @allancoding has this information

**Comment by allancoding** [comment]
Yes I have it somewhere let me look for it.

**Comment by allancoding** [comment]
If you want a Black and white one tell me but this is the color one:
![Emulatorjs Logo](https://user-images.githubusercontent.com/74841470/236378784-9a1b597e-d5c2-4ae6-bab0-473c0c124367.svg)
