### ISSUE TITLE
Dip Swich Keyboard Shortcut-Bug

### ISSUE THREAD

**Issue by koraytastan** [emulatorjs/emulatorjs#507]
How can we access the "dip switch" mode. 

I didn't see it in the joystick settings. 

Sometimes it appears when i press different keyboard keys.

Is this a bug or is there a way ?

**Comment by ethanaobrien** [comment]
What is this "dip switch" mode? What console? Can you provide screenshots?

**Comment by koraytastan** [comment]
This is the option menu where the game settings (difficult, control, audio, etc.) are edited. You can find more detailed information if you type mame dipswitch. I think when I press the "w" key (in mame or other core) this menu appears. 

https://retropie.org.uk/forum/assets/uploads/files/1618841810264-capture2.png

**Comment by ethanaobrien** [comment]
Can you confirm this on the https://demo.emulatorjs.org website? I don't recognize the menu and think you might have this project confused with [this project](https://github.com/linuxserver/emulatorjs)

**Comment by koraytastan** [comment]
Run the mame2003 core and the shdancer.zip rom. Then press the keyboard key 'W'. It will appear. 

I recently ran the mame2003 kernel with the arcade kernel (https://github.com/EmulatorJS/EmulatorJS/issues/504) which I could not run with the arcade kernel. The application settings do not work 100% correctly without clearing the cache. You need to find the cache folder and clear it.

**Comment by ethanaobrien** [comment]
There is no cache folder. I think you are using the wrong project. This project is 100% in the web browser, there is no cache folder.
