### ISSUE TITLE
cheat is valid in ios device 

### ISSUE THREAD

**Issue by eks5115** [emulatorjs/emulatorjs#509]
I accessed demo.emulatorjs.org from my ios device. 
nes-old-wasm-data version is 25.
nes game snow-brothers-usa set cheat Infinite Lives P1(0076:09).
but lives is only 2.
![IMG_0735](https://user-images.githubusercontent.com/21402882/232235132-d0952816-5fd3-42ed-8b3f-449e330e14e5.PNG)

**Comment by eks5115** [comment]
The nes game used nes-old-wasm.data version 25 in ios. Cheat is invalid.
But the nes game used nes-wasm.data version 23 in ios. Cheat is valid.

**Comment by ethanaobrien** [comment]
I can't maintain the old cores. They support almost nothing and are very slow
