### ISSUE TITLE
Video Pre-roll

### ISSUE THREAD

**Issue by xxxnewbiexxx** [emulatorjs/emulatorjs#51]
Hi all, any idea how to implement the video pre-roll ad tag code below inside emulator.js file?

Ad Tag Code:

```
<script type="text/javascript">
(function(i,w,d,p,c,e,o,a,s,t){

p.poolid = 74997; 
c.background = null;  
c.close = null;    
c.type = 'game';  

t=d.getElementsByTagName('script');if(!w[i]){w[i]={ads:[]};s=d.createElement('script');s.src=(d.location.protocol=='https:'?'//server':'//cdn')+'.cpmstar.com/cached/js/global_v100.pack.js?poolid='+p.poolid;s.type='text/javascript';s.async='';t[0].parentNode.insertBefore(s,t[0]);}w[i].ads.push(a={params:p,config:c,events:e,overlay:o,placeholder:t[t.length-1]});})('cpmstar',window,document,{},{},{},{});
</script>
```

Thanks in advance for your usual support!

**Comment by ethanaobrien** [comment]
Hello, on line 14653 is the code for the adUrl embedding. You might be able to put it in there.
search for the code `if (typeof _0xc6823.adUrl === 'string') {`

To make it to where the user can only click it after the video ends, you can probably edit the setTimeout feature or edit the setTimeout to show the `x` button. search for `adUrl`

**Comment by xxxnewbiexxx** [comment]
Hi @ethanaobrien , thanks for your reply. I will make a few tests and let you know ;-)

**Comment by xxxnewbiexxx** [comment]
> Hello, on line 14653 is the code for the adUrl embedding. You might be able to put it in there. search for the code `if (typeof _0xc6823.adUrl === 'string') {`
> 
> To make it to where the user can only click it after the video ends, you can probably edit the setTimeout feature or edit the setTimeout to show the `x` button. search for `adUrl`

Hi @ethanaobrien , I tried to implement the Ad URL straight into the emulator.js like below:

Line 14653:

`if (typeof _0xc6823.adUrl === 'https://mysite.com/ad.html') {`

and 

Line 14656:

`'src': https://mysite.com/ad.html,`

But it didn't work :-(

It only works if I add this line: 

`EJS_AdUrl = 'https://mysite.com/ad.html'`

Like the code below:

```
<script type="text/javascript">
    EJS_player = '#game';
    EJS_gameUrl = 'files/snes/Donkey-Kong-Country.zip'; // Url to Game rom
    EJS_core = 'snes';
    EJS_mouse = false; // SNES Mouse
    EJS_multitap = false; // SNES Multitap
    EJS_pathtodata = 'data/'; //path to all of the wasm and js files. MUST all be in the same directory!!
    //EJS_AdUrl = 'https://mysite.com/ad.html' //path to AD page
</script>
<script src="data/loader.js"></script>
```

Is it possible to add the Ad URL straight into the emulator.js file?

Thank you!

**Comment by ethanaobrien** [comment]
`if (typeof _0xc6823.adUrl === 'https://mysite.com/ad.html') {` is not proper javascript (unless you have a type named `https://mysite.com/ad.html`) it must be kept as `if (typeof _0xc6823.adUrl === 'string') {`

To specify it in the emulator.js file, search for the code `//_0x2ba0e6.adUrl = 'https://www.youtube.com/embed/8vkh9UO3PnA'`, remove the `//` from the beginning and change the youtube link to the link of your ad page

**Comment by xxxnewbiexxx** [comment]
Thanks for your quick reply @ethanaobrien !

It's not working for me as you can see in the test page below :-(

Test page - https://coolstuffblast.com/games/test.html

Emulator.js file was modified as per your instructions above.

**Comment by ethanaobrien** [comment]
![Screenshot 2021-12-08 8 51 16 PM](https://user-images.githubusercontent.com/77750390/145325695-3eb60393-c3aa-488d-9898-2e3b18a3ae4d.png)
Seems to work fine, just takes a sec to load (as ads always do)

**Comment by xxxnewbiexxx** [comment]
Hi @ethanaobrien , that's really strange ... I have cleared my Google Chrome cache, Cloudflare cache, I even tried anonymous browser and it was not working lol ... I had to flush my DNS via CMD to see it was working :-)

Thank you for your help!

The banner ads was an easy implementation via emulator.js , just trying to figure it out how to implement the video pre-roll now. 

Is there any easy way to call an ad url from emulator.js to load before the emulator loads using the whole game frame 640x480 pixels?

Thanks in advance for all your help and support!

**Comment by ethanaobrien** [comment]
No, this isn't possible in javascript to check if the ad is loaded. Sorry

**Comment by xxxnewbiexxx** [comment]
Hi @ethanaobrien , thanks for your reply.

It doesn´t need to check if the ad is loaded, just need to call and load the ad url in the whole game iframe as soon as it loads the emulator. The video pre-roll script will have the close button and the time set up to work it by itself.

The result would be similar to this one - https://neptunjs.xyz/snes.html

But it would load the video pre-roll ad before ;-)

**Comment by ethanaobrien** [comment]
Sorry for the late reply, got busy then I just kept forgetting to respond.

>It doesn´t need to check if the ad is loaded, just need to call and load the ad url in the whole game iframe as soon as it loads the emulator. The video pre-roll script will have the close button and the time set up to work it by itself.

This is what it does, the moment the emulator loads the iframe is created and starts loading

**Comment by xxxnewbiexxx** [comment]
Hi @ethanaobrien , thanks for your reply.

In the new emulator, I couldn't find the code: `//_0x2ba0e6.adUrl = 'https://www.youtube.com/embed/8vkh9UO3PnA'` in the emulator.js file.

How to implement the Ad URL inside the new emulator.js file?

Thanks in advance for all your help and support!

**Comment by ethanaobrien** [comment]
Bottom of the `emu-main.js` file. Search for `this.adUrl =`

**Comment by ethanaobrien** [comment]
@xxxnewbiexxx Did you ever get this working? Can I close this or?

**Comment by xxxnewbiexxx** [comment]
Hi @ethanaobrien, just the banner is working at the moment, still working on the video pre-roll implementation ...

**Comment by ethanaobrien** [comment]
Im going to assume you've got this under control

I'm closing since this isn't technically an issue, but a question

**Comment by xxxnewbiexxx** [comment]
Hi @ethanaobrien , have you done any change to the code that skip modifications on emu-main.js ?

I tried to implement the ad URL inside emu-main. js file changing this line:

this.adUrl = null;

to this:

this.adUrl = 'https://mysite.com/adurl.html';

but it's not working :-(

Thanks in advance for all your help and support!

**Comment by ethanaobrien** [comment]
It’s defined twice in the file (as shown). It sets the value as null at first than sets it to the value in the config argument. You could define it in the loader.js file

**Comment by xxxnewbiexxx** [comment]
Thanks for your reply @ethanaobrien ! How can I define it in the loader.js file?

I tried this:

'undefined' != typeof EJS_AdUrl && (config.adUrl = 'https://mysite.com/adurl.html');

but it didn't work ...

**Comment by ethanaobrien** [comment]
Set the config ad url to your site instead of the window variable

**Comment by xxxnewbiexxx** [comment]
Thanks for your reply @ethanaobrien !

How can I set this?

**Comment by xxxnewbiexxx** [comment]
> Set the config ad url to your site instead of the window variable

How to set this @ethanaobrien ? Could you please help ?
