### ISSUE TITLE
Can I edit the html created with EmulatorJS codehelper to have my controls mapped already?

### ISSUE THREAD

**Issue by rpdistiso** [emulatorjs/emulatorjs#510]

**Comment by Cattn** [comment]
Yes, this is in the docs you should be able to add the code normally alongside the code

**Comment by rpdistiso** [comment]
Ok, how?

**Comment by Cattn** [comment]
You refer to the [Docs](https://emulatorjs.org/docs4devs/Control%20Mapping.html), and then edit the code as you like, then just paste it in your js config (or likely a script tag in html)
