### ISSUE TITLE
[Bug]3DO Timing Hack and Graphics Step Y Hack

### ISSUE THREAD

**Issue by zmarteline** [emulatorjs/emulatorjs#511]
In order to play certain 3DO games like Crash 'n Burn and Samurai Shodown using libretro cores, we need to switch on these functions: [libreto 3do doc ](https://docs.libretro.com/library/opera/)

timing Hack 1 (Crash 'n Burn) [opera_hack_timing_1] (disabled|enabled)
Graphics Step Y Hack (Samurai Shodown) [opera_hack_graphics_step_y] (disabled|enabled)

Is there a way to parse it using EJS_defaultOptions?  (like we use to set shaders)

Also a way to set opera_cpu_overclock to 25.00Mhz in EJS_defaultOptions would be nice.

**Comment by ethanaobrien** [comment]
If you enable `EJS_DEBUG_XX` and open the console, you will see the core options logged in the console of what you can feed into `EJS_defaultOptions`. You can set the default options for the wanted settings the same way you can set the default shader.

**Comment by zmarteline** [comment]
unfortunately it seems that timing Hack and Graphics Step Y Hack  are not supported.
