### ISSUE TITLE
N64 virtual yoke not working on phone screen

### ISSUE THREAD

**Issue by Untangled5132** [emulatorjs/emulatorjs#514]
First - awesome project, thanks for creating and sharing it.

I'm using the unraid version, have tried running the games on both firefox and edge on my phone, the virtual yoke control on screen works only in the menu but once the game starts up it no longer responds.  Couldn't find anything online about it, unraid logs for the container looks fine, not really sure which log file i should be taking a look at within the container or if I'm missing a setup step somewhere or if it's a known limitation.

**Comment by ethanaobrien** [comment]
>I'm using the unraid version

I think you're in the wrong place. Are you looking for this https://github.com/linuxserver/emulatorjs

(There is no unraid version)
