### ISSUE TITLE
Failed to start game

### ISSUE THREAD

**Issue by Boss8764** [emulatorjs/emulatorjs#519]
Im using the site Replit to try and run an emulator i run the code and it loads all the way but then says Failed to start game how would i fix this
I got no error console code

**Comment by Boss8764** [comment]
![image](https://user-images.githubusercontent.com/132949735/236928138-3c416ff2-d8b7-4974-bf9f-e3d738abed76.png)

**Comment by OceanMan15WasTaken** [comment]
try changing the game file name to something more simple (without weird symbols, try just "Game") , then put that into gameurl, and then try it. this worked for me.

**Comment by AdhmAlateiat** [comment]
I got the same issue let me know if you find a way to fix this.

**Comment by Boss8764** [comment]
> I got the same issue let me know if you find a way to fix this.

i fixed the issue 
The game does not work in the editor but if you go into the site or the cover screen it works Perfectly just the editor causes problems for it

**Comment by AdhmAlateiat** [comment]
So only thing I need to do is embed it in a website and it should work?

**Comment by ethanaobrien** [comment]
Replit very commonly seems to block rom urls to stop kids at school from doing things like that. Just don't use replit

**Comment by Greys2121** [comment]
Can somebody teach me how to use replit?

**Comment by ethanaobrien** [comment]
you dont
