### ISSUE TITLE
Upload save to server, load save from server.

### ISSUE THREAD

**Issue by imneckro** [emulatorjs/emulatorjs#52]
Hello

I was just wondering if we can create a button that, instead of downloading save file locally, it will upload it to server side.
Also it will need a button to load save files from server.
Is it possible?

**Comment by ethanaobrien** [comment]
I could expose the save and load functions to the window. You could then write your own script to get the data and upload it and to get the data and download and load it. Would this help?

**Comment by ethanaobrien** [comment]
I just merged some changes.

To save: 
call the function `window._0x378b5c.saveState()`
This will return a `uint8array` containing the save file

To load:
call the function `window.EJS_loadState(data)`
data: `uint8array` of the file

**Comment by imneckro** [comment]
Just tried `<button onclick="window._0x378b5c.saveState()" style="position:absolute;z-index:999;">SAVE</button>`
and saw nothing in console.

**Comment by ethanaobrien** [comment]
the `window._0x378b5c.saveState()` function returns a uint8array. There is nowhere in your code where you are logging to the console.

**Comment by imneckro** [comment]
whats the way to store this array on a php variable so i can insert it in mysql?

**Comment by ethanaobrien** [comment]
you must have a function that calls this function, gets the data, and sends it to the server

**Comment by imneckro** [comment]
any ideas?

**Comment by ethanaobrien** [comment]
```
var data = window._0x378b5c.saveState()
fetch('storedata.php', {method: "POST", body: data})
```

**Comment by imneckro** [comment]
You are a god!

**Comment by imneckro** [comment]
at first trigger of `window._0x378b5c.saveState()`
console gives me 
```
VM6203:1 Uncaught abort(6) at Error
    at jsStackTrace (eval at _0x54d695 <anonymous>:1:18019)
    at stackTrace (eval at _0x54d695 , <anonymous>:1:18190)
    at abort (eval at _0x54d695 , <anonymous>:1:292973)
    at wasm://wasm/00766922:wasm-function[3997]:0x13172d
    at wasm://wasm/00766922:wasm-function[2990]:0xf06f3
    at wasm://wasm/00766922:wasm-function[2166]:0xbe784
    at wasm://wasm/00766922:wasm-function[385]:0x694a
    at wasm://wasm/00766922:wasm-function[456]:0x1b354
    at wasm://wasm/00766922:wasm-function[460]:0x1b905
    at eval (eval at _0x54d695 , <anonymous>:1:281007)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

at second attempt of `window._0x378b5c.saveState()`
gives me the `uint8array `.


Why is that?

**Comment by ethanaobrien** [comment]
The game has to be running before you call the function. Could this be the case?

**Comment by imneckro** [comment]
I'll check it out today and get back. thanks again

**Comment by imneckro** [comment]
I am trying to convert `unt8array` into base64 so i cant store it in mysql with this code
```
    var data = window._0x378b5c.saveState();
    var ascii = new Uint8Array(data);
   var b64encoded = btoa(String.fromCharCode.apply(null, ascii));
```
Is there any other way to store it in mysql?
What type of column will accept `unit8array`?

**Comment by ethanaobrien** [comment]
It shouldnt be. The most I've seen is 16mb (For the n64). The way I showed
you is the same way the emulator saves

**Comment by imneckro** [comment]
So mysql isnt ideal? Then can we store it as a binary file on server so we can load it from there?

**Comment by ethanaobrien** [comment]
correct

**Comment by imneckro** [comment]
How to store it as a binary file on server?

**Comment by ethanaobrien** [comment]
I dont know. Youll have to figure that part out

**Comment by imneckro** [comment]
I kind of figured it out.

But at this point console throws `window.EJS_loadState()` is not defined.

**Comment by imneckro** [comment]
For anyone interested how to save binary file on server side here is my code:
```
<html>
<button onclick="savestate();" style="position:absolute;z-index:999;">save</button>
</html>
<script>
function savestate(){
var blobData = window._0x378b5c.saveState();
 var data;
  data = new Blob([blobData], {
    type: 'application/octet-stream'
  });   
$.ajax({
  type: 'POST',
  url: 'save.php',
  data: data,
  contentType: 'application/octet-stream', 
  processData: false
});
    
}
</script>

//and for save.php page:
<?php
    $data = file_get_contents('php://input');
    $fp = fopen("/var/www/html/saves/gamesave", "wb");
    fwrite($fp, $data);
    fclose($fp);
?>
```

About loading the save from server side with  `window.EJS_loadState(data)` :
```
<html>
<button onclick="loadstate();" style="position:absolute;z-index:999;">load</button>
</html>
<script>
var arrayBuffer = "";
function loadstate(){
  var oReq = new XMLHttpRequest();
oReq.open("GET", "saves/gamesaver", true);
oReq.responseType = "arraybuffer";
oReq.onload = function(oEvent) {
  var arrayBuffer = oReq.response;
  var byteArray = new Uint8Array(arrayBuffer);

window.EJS_loadState(byteArray);
};
oReq.send(); 
}
</script>
```

Cheers and Ethan thanks for helping out.

**Comment by imneckro** [comment]
Ethan whats the way to  change the behaviour of native save button below 

`<button aria-expanded="false" type="button" class="ejs--8732295ca5c4902a060d34706a8146 ejs--a83b6c705e103e81a7762d0ed5e64b" data-btn="save-state"><svg role="presentation" focusable="false"><svg viewBox="0 0 448 512"><path fill="currentColor" d="M433.941 129.941l-83.882-83.882A48 48 0 0 0 316.118 32H48C21.49 32 0 53.49 0 80v352c0 26.51 21.49 48 48 48h352c26.51 0 48-21.49 48-48V163.882a48 48 0 0 0-14.059-33.941zM224 416c-35.346 0-64-28.654-64-64 0-35.346 28.654-64 64-64s64 28.654 64 64c0 35.346-28.654 64-64 64zm96-304.52V212c0 6.627-5.373 12-12 12H76c-6.627 0-12-5.373-12-12V108c0-6.627 5.373-12 12-12h228.52c3.183 0 6.235 1.264 8.485 3.515l3.48 3.48A11.996 11.996 0 0 1 320 111.48z"></path></svg></svg><span class="ejs--74c6d4176d27e37a19d2e9e61de8f4">Save State (Shift + F2)</span></button>`

and native load button below

`<button aria-haspopup="true" aria-expanded="false" type="button" class="ejs--8732295ca5c4902a060d34706a8146 ejs--a83b6c705e103e81a7762d0ed5e64b" data-btn="load-state"><svg role="presentation" focusable="false"><svg viewBox="0 0 576 512"><path fill="currentColor" d="M572.694 292.093L500.27 416.248A63.997 63.997 0 0 1 444.989 448H45.025c-18.523 0-30.064-20.093-20.731-36.093l72.424-124.155A64 64 0 0 1 152 256h399.964c18.523 0 30.064 20.093 20.73 36.093zM152 224h328v-48c0-26.51-21.49-48-48-48H272l-64-64H48C21.49 64 0 85.49 0 112v278.046l69.077-118.418C86.214 242.25 117.989 224 152 224z"></path></svg></svg><span class="ejs--74c6d4176d27e37a19d2e9e61de8f4">Load State (Shift + F4)</span></button>`


to respond to our functions savestate() and loadstate() accordingly?

**Comment by ethanaobrien** [comment]
Keep in mind, this is not for quick save and load buttons. Only for the save and load button on the menu bar

saveStage on line 17237. You can also search for the code `_0x1093f4.call(_0xa88a13, _0xa88a13.elements.container, 'savestate', function(_0x25b541) {`

loadState is on line 17261. You can also search for the code `_0x1093f4.call(_0xa88a13, _0xa88a13.elements.container, 'loadstate', function(_0x13504c) {`

hope this helps!

**Comment by imneckro** [comment]
Thanks a lot Ethan!

**Comment by imneckro** [comment]
The way to get save state's screenshot below for anyone interested:
```
var blobimgData = window._0x378b5c.getScreenData();
var imgdata;
  imgdata = new Blob([blobimgData], {
    type: 'image/jpeg'
  }); 
```

**Comment by ethanaobrien** [comment]
@imneckro can I close this?

**Comment by imneckro** [comment]
> @imneckro can I close this?

Sure Ethan. Thanks for everything
