### ISSUE TITLE
[Bug] Master System shooting games

### ISSUE THREAD

**Issue by zmarteline** [emulatorjs/emulatorjs#520]
Is there a way to play Master System shooting games? maybe using mouse or controller as lightgun?

**Comment by ethanaobrien** [comment]
You should be able to add `EJS_lightgun = true;`. If that doesn't work use the old cores

**Comment by zmarteline** [comment]
Doesn`t work, even with:   
EJS_lightgun = true;
EJS_oldCore = true;
