### ISSUE TITLE
Bug: After update to v31.6 - Emulatorjs script doesn't load

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#521]
Hi,

After i update the script code to latest v31.6, the emulator stopped to work. and show this error message on console:

caught TypeError: Cannot read properties of null (reading 'call')
    at a (emulator.min.js?v=31.6:1:153)
    at Object.<anonymous> (emulator.min.js?v=31.6:1:200029)
    at a (emulator.min.js?v=31.6:1:153)
    at EJS (emulator.min.js?v=31.6:1:1180)
    at emulator.min.js?v=31.6:1:1191

loader.js:94 Uncaught (in promise) TypeError: EJS is not a constructor
    at loader.js:94:33

This code get's the error under emulator.js:
        return _0x574f5e[_0x289550].call(_0x4f6398.exports, _0x4f6398, _0x4f6398.exports, _0x1d686b),

If you need more debug info, i will send you.

**Comment by ethanaobrien** [comment]
As always, and as stated in the instructions to send a bug report. Send the ENTIRE log. You don't know what parts mean what, so send the entire thing.

**Comment by shaylevary** [comment]
Hi,

Here is the full console error message:

caught TypeError: Cannot read properties of null (reading 'call')
    at a (emulator.min.js?v=31.6:1:153)
    at Object.<anonymous> (emulator.min.js?v=31.6:1:200029)
    at a (emulator.min.js?v=31.6:1:153)
    at EJS (emulator.min.js?v=31.6:1:1180)
    at emulator.min.js?v=31.6:1:1191
a @ emulator.min.js?v=31.6:1
(anonymous) @ emulator.min.js?v=31.6:1
a @ emulator.min.js?v=31.6:1
EJS @ emulator.min.js?v=31.6:1
(anonymous) @ emulator.min.js?v=31.6:1
loader.js?v3:94 Uncaught (in promise) TypeError: EJS is not a constructor
    at loader.js?v3:94:33
(anonymous) @ loader.js?v3:94
await in (anonymous) (async)
(anonymous) @ loader.js?v3:96

I've tried to clear all cache, open under Incognito, and always get the same error when using latest version.
When switch back to previous version, it works fine.

BTW, Does previous version should work with the new Netplay update? because when i've tried to test it, the 2nd player doesn't see anything on screen (blank) after joining a netplay game.

![emulatorjs_error](https://github.com/EmulatorJS/EmulatorJS/assets/10597517/3e80d00e-03c2-4e16-80f7-fba4337f3851)

**Comment by ethanaobrien** [comment]
As stated in the issue template, set `EJS_DEBUG_XX` to true and send the entire log. At the moment the information sent doesn't help at all

**Comment by shaylevary** [comment]
At the start of this message, i've sent you the console log message that i get after i turn on debug mode.
There is nothing on the console except of this, and it appears only when i try to run latest script.

emulator.js?v=31.6:13 Uncaught TypeError: Cannot read properties of null (reading 'call')
    at _0x1d686b (emulator.js?v=31.6:13:37)
    at window.EJS_main (emu-main.js?v=31.6:7:23)
    at _0x1d686b (emulator.js?v=31.6:13:37)
    at EJS (emulator.js?v=31.6:76:12)
    at emulator.js?v=31.6:77:2
_0x1d686b @ emulator.js?v=31.6:13
window.EJS_main @ emu-main.js?v=31.6:7
_0x1d686b @ emulator.js?v=31.6:13
EJS @ emulator.js?v=31.6:76
(anonymous) @ emulator.js?v=31.6:77
loader.js?v3:94 Uncaught (in promise) TypeError: EJS is not a constructor
    at loader.js?v3:94:33
(

this is the "call" error code line under emulator.js:
        return _0x574f5e[_0x289550].call(_0x4f6398.exports, _0x4f6398, _0x4f6398.exports, _0x1d686b),

and this is the error line under loader.js:
    window.EJS_emulator = await new EJS(EJS_player, config);

![debug_bug](https://github.com/EmulatorJS/EmulatorJS/assets/10597517/ea36b16c-91f1-418c-943c-6d47d3031253)

**Comment by shaylevary** [comment]
I would like to say thanks, last update for version 3.1.6, fixed the loading crash problem.
Now everything works great, include the netplay. 

I appreciate all your work and help.
