### ISSUE TITLE
Not load

### ISSUE THREAD

**Issue by Cakricks** [emulatorjs/emulatorjs#528]
![Screenshot_2023-05-12-01-41-43-790_com android chrome-edit](https://github.com/EmulatorJS/EmulatorJS/assets/11593196/b9a5d151-d6e5-4680-9f83-8a4ed5075fd2)

I have this error, it crashes and I have this message:
Saved new config to:

**Comment by ethanaobrien** [comment]
When this happens can you interact with the webpage? Or is everything frozen?

**Comment by Cakricks** [comment]
Yes and it is frozen too

**Comment by ethanaobrien** [comment]
Then this is a duplicate of #416. Are you on ios?

**Comment by Cakricks** [comment]
Look: https://mztcity.com/juegos/contra.html

**Comment by ethanaobrien** [comment]
Thank you. That seems to be 100% reproducible. I'll look at it

**Comment by Cakricks** [comment]
does it work in your browser?  i test my smartphone and laptop and its Frozen :/

**Comment by Cakricks** [comment]
Apparently this version has an error, i tested on the demo page and it remains the same.
https://demo.emulatorjs.org/

**Comment by ethanaobrien** [comment]
This is a known bug, #416.
