### ISSUE TITLE
Game Core Ready  -  Network Error

### ISSUE THREAD

**Issue by ShadDeal** [emulatorjs/emulatorjs#529]
I download the HTML that it gives to me and it opens up in Chrome just fine, but when I click start game loads the core and then states "Network Error"
[Screen recording 2023-05-12 12.21.58 PM.webm](https://github.com/EmulatorJS/EmulatorJS/assets/95373070/2acb6b46-6f18-4e11-9812-855dc561a54c)

**Comment by ethanaobrien** [comment]
You cannot run it from a `file://` url. You need to host it with a web server.
