### ISSUE TITLE
[BUG?] - It takes a lot of time for Player 2 to get an updated screen content

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#532]
Hi,

Since i've updated to the new version of Netplay (which required Twich api), it takes a lot of time for Player 2 to get sync with player 1 the content.

For example, after joining a Netplay game room, when the loading message disappears, player 2's screen remains as if in a stuck state (freeze) with the last content that was displayed on screen before I clicked on joining the room.

Only after about a 1 min or more, the content on player 2's screen is updated and displayed in sync with player 1.

In general, no error message appears on the console, it's only a very slow process for player 2 to join the game and synchronizing with player 1's screen.

Once the sync is done, both players can play, but there is still seems to be some slowness in synchronizing the movements of the 2 players - compared to the old versions of netplay that didn't required to use Twich API.

Is this a problem related to the Twitch server or some bug on the code? Is there anything that can be done about this to improve the performance like it was on the previous version?

Regards,
Shay.

**Comment by ethanaobrien** [comment]
>Since i've updated to the new version of Netplay (which required Twich api), it takes a lot of time for Player 2 to get sync with player 1 the content.

First of all, it required the twilto api. I'm not sure the twitch api would even work. Double check that

>For example, after joining a Netplay game room, when the loading message disappears, player 2's screen remains as if in a stuck state (freeze) with the last content that was displayed on screen before I clicked on joining the room.

I think this is just your internet speed

>Only after about a 1 min or more, the content on player 2's screen is updated and displayed in sync with player 1.

Which is when the data finally loads

>In general, no error message appears on the console, it's only a very slow process for player 2 to join the game and synchronizing with player 1's screen.

Again, probably because of slow internet. There's no error for that.

>Once the sync is done, both players can play, but there is still seems to be some slowness in synchronizing the movements of the 2 players - compared to the old versions of netplay that didn't required to use Twich API.

Again, twilto. And again, the old version of netplay DID require the twilto api. I can just no longer have a server that will distribute the twilto turn urls. The only thing I changed about netplay is you need to do it yourself. If you look in the commit history you'll see, twilto was added long before this last commit.

>Is this a problem related to the Twitch server or some bug on the code? Is there anything that can be done about this to improve the performance like it was on the previous version?

Absolutely no clue. If it's slow, it's a configuration error, and I don't know

**Comment by shaylevary** [comment]
Hi,

hehehe you are right, i meant twilo, not twich. :)
Anyway, if you haven't change anything on code, and as i've mentioned, i don't get any error message in console, it's just takes too long to load content for play 2, i guess it's bandwidth issue on my server side.
I will check this issue with my server admin.

Thank you for your all your help.

**Comment by ethanaobrien** [comment]
It's my pleasure, but yeah, the only think I changed is you have to provide those twilto strings instead of me. None of the netplay code itself was changed
