### ISSUE TITLE
Organization has blocked usage of JavaScript

### ISSUE THREAD

**Issue by rpdistiso** [emulatorjs/emulatorjs#535]
My Organization has blocked the usage of JavaScript any workarounds? They blocked OS settings and chrome://settings
![Screenshot 2023-05-19 08 07 14](https://github.com/EmulatorJS/EmulatorJS/assets/116186005/90c5ea1b-31d5-4137-a25e-f5aaedf81e44)

**Comment by ethanaobrien** [comment]
2 things, I won't help get around organization settings.

1. There is literally a "allow javascript" button in the pop-up you showed me
2. You are trying to run from a `file:` url. You must host using a web server or on another website

**Comment by rpdistiso** [comment]
I doesn't let me select "Always Allow JavaScript"

**Comment by ethanaobrien** [comment]
Well I'm sorry. That's not something I can help with. Play games at home and not at school

**Comment by rpdistiso** [comment]
@ethanaobrien Maybe we could completely rewrite this in C++ or C# maybe CSS

**Comment by ethanaobrien** [comment]
1. Css isn't a programming language
2. Javascript needs to be used to communicate with the webassembly backend
3. It's already written in C https://github.com/EmulatorJS/RetroArch

**Comment by rpdistiso** [comment]
Is Javascript the only language?

**Comment by ethanaobrien** [comment]
On the web, yes
