### ISSUE TITLE
[Bug] When I go to any website that uses EmulatorJs and i click Play Now it doesn't start the game it stays on the same screen.

### ISSUE THREAD

**Issue by NewYorkRailfanner** [emulatorjs/emulatorjs#536]
#### Make sure your issue doesn't get closed! Make sure you have done the following items

- [x] I have collected a **FULL** log of the console, with `EJS_DEBUG_XX` set to true, and uploaded it straight to GitHub.
- [x] I have not made any changes to the EmulatorJS instance I am running into this bug on.
- [x] I am on the latest version of EmulatorJS
- [x] I have not attached any images or logs via external sites. I have uploaded them straight to GitHub and acknowledge that external sites may pose a security issue.
- [x] I have included, **IN DETAIL**, the steps to reproduce the bug.

 
[www.retrogames.cc-1684759932487.log](https://github.com/EmulatorJS/EmulatorJS/files/11524757/www.retrogames.cc-1684759932487.log)

[DOM] Found 2 elements with non-unique id #check1: (More info: https://goo.gl/9p2vKq) <input id=​"check1" type=​"checkbox" name=​"_remember_me" value=​"1">​ <input id=​"check1" type=​"checkbox" name=​"_remember_me" value=​"1">​
jsziptools.js:4 pre-main prep time: 2 ms
Error with Permissions-Policy header: Unrecognized feature: 'ambient-light-sensor'.
ad.html?domain=www.retrogames.cc:6 Uncaught DOMException: Blocked a frame with origin "https://www.emulatorjs.com" from accessing a cross-origin frame.
    at https://www.emulatorjs.com/ad.html?domain=www.retrogames.cc:6:26
    at https://www.emulatorjs.com/ad.html?domain=www.retrogames.cc:55:3
(anonymous) @ ad.html?domain=www.retrogames.cc:6
(anonymous) @ ad.html?domain=www.retrogames.cc:55
DevTools failed to load source map: Could not load content for https://static-int.adsafeprotected.com/visJS.append.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
sca.17.6.2.js:32 a: 0.010009765625 ms
5main.js:534 https://cdn.flashtalking.com/122755/instantAssets/1x1.png
main.js:534 https://cdn.flashtalking.com/122755/instantAssets/Shopper_82022_BG_300x250.jpg
main.js:534 https://cdn.flashtalking.com/122755/instantAssets/OAlenovo_front_center_BL.png
main.js:534 fonts/Gotham-Book.woff
main.js:534 fonts/Gotham-Bold.woff
main.js:534 https://cdn.flashtalking.com/feeds/lenovo/sku_images_09_22/82UD002RUS.png
main.js:534 https://cdn.flashtalking.com/feeds/lenovo/sku_images_09_22/F0GH0000US.png
main.js:534 https://cdn.flashtalking.com/feeds/lenovo/sku_images_09_22/82R70005US.png
main.js:534 https://cdn.flashtalking.com/feeds/lenovo/sku_images_09_22/90Q6000DCM.png
main.js:393 calling pre-animate
main.js:418 calling animateAd
main.js:459 1
onetag-sys.com/:1 Mixed Content: The page at 'https://onetag-sys.com/usync/?pubId=5adb88524e24e50' was loaded over HTTPS, but requested an insecure element 'http://sync.adkernel.com/user-sync?zone=175005&r=_M6WjJBDsAEq6R6Kd2bdWJWJ4g-HSVeWgkWICypmGww'. This request was automatically upgraded to HTTPS, For more information see https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html
sync.adkernel.com/user-sync?zone=181093&r=https%3A%2F%2Fusersync.gumgum.com%2Fusersync%3Fb%3Dmdp%26i%3D%5BUID%5D&gdpr=0&gdpr_consent=&ccpa=1---:1     Failed to load resource: the server responded with a status of 400 (Bad Request)
main.js:459 2
sync:2     GET https://sync.tidaltv.com/genericusersync.ashx?dpid=3157&gdpr=0&gdpr_consent= 404
sync.adkernel.com/user-sync?zone=175005&r=_M6WjJBDsAEq6R6Kd2bdWJWJ4g-HSVeWgkWICypmGww:1     GET https://sync.adkernel.com/user-sync?zone=175005&r=_M6WjJBDsAEq6R6Kd2bdWJWJ4g-HSVeWgkWICypmGww 400 (Bad Request)
Image (async)
(anonymous) @ VM7:48
(anonymous) @ VM7:42
main.js:459 3
cs.iqzone.com/e9d4ff858b5e32317e843f5ed11b2659.gif?puid=u_32313327-9318-4cf6-93eb-7a1a29f0a820&redir=https%3A%2F%2Fusersync.gumgum.com%2Fusersync%3Fb%3Diqz:1     Failed to load resource: the server responded with a status of 404 (Not Found)
main.js:459 carousel
main.js:484 0
main.js:459 carousel
main.js:484 0
main.js:500 1
main.js:500 2
main.js:500 3

**Comment by ethanaobrien** [comment]
I can't help with this. The site retrogames.cc does not use this project, they use emulatorjs.com, and this project and that website are 2 different things. I recommend reaching out to the owners of the site if you are experiencing an error
