### ISSUE TITLE
[Question] How to run on react ?

### ISSUE THREAD

**Issue by Impre-visible** [emulatorjs/emulatorjs#538]
Hi, I have a question, how can I use EmulatorJS on a React App ? Is it possible ?

Thanks

**Comment by Impre-visible** [comment]
I tried something it's not the best but it work :
here's my code :

```js
useEffect(() => {
    const scripts = {
        GB:
        'let EJS_player = "#game";\nlet EJS_biosUrl = "";\nlet EJS_gameUrl = "{slug}";\nlet EJS_core = "gb";',
        GBA:
        'let EJS_player = "#game";\nlet EJS_biosUrl = "";\nlet EJS_gameUrl = "{slug}";\nlet EJS_core = "gba";',
        GBCGB:
        'let EJS_player = "#game";\nlet EJS_biosUrl = "";\nlet EJS_gameUrl = "{slug}";\nlet EJS_core = "gb";',
        N64: 'let EJS_player = "#game";\nlet EJS_gameUrl = "{slug}";\nlet EJS_core = "n64";',
        NES:
        'let EJS_player = "#game";\nlet EJS_biosUrl = "";\nlet EJS_gameUrl = "{slug}";\nlet EJS_core = "nes";\nEJS_lightgun = false;',
        NDS:
        'let EJS_player = "#game";\nlet EJS_biosUrl = "";\nlet EJS_gameUrl = "{slug}";\nlet EJS_core = "nds";',
        SNES:
        'let EJS_player = "#game";\nlet EJS_biosUrl = "";\nlet EJS_gameUrl = "{slug}";\nlet EJS_core = "snes";\nEJS_mouse = false;\nEJS_multitap = false;',
        "Sega Mega Drive": 'let EJS_player = "#game";\nlet EJS_gameUrl = "{slug}";\nlet EJS_core = "segaMD";',
        "Sega Master System": 'let EJS_player = "#game";\nlet EJS_gameUrl = "{slug}";\nlet EJS_core = "segaMS";',
        "Sega Saturn":
        'let EJS_player = "#game";\nlet EJS_biosUrl = "";\nlet EJS_gameUrl = "{slug}";\nlet EJS_core = "segaSaturn";',
        PS1:
        'let EJS_player = "#game";\nlet EJS_biosUrl = "{bios}";\nlet EJS_gameUrl = "{slug}";\nlet EJS_core = "psx";',
    };

    let theConsole = scripts[console].replace("{slug}", gameFile);

    if (theConsole.includes("{bios}")) {
        let bios = `https://chocolateserver.chevrier.cf/bios/${console}`
        theConsole = theConsole.replace("{bios}", bios);
    }

    const theScript = document.createElement("script");
    theScript.innerHTML = theConsole;
    theScript.defer = true;
    theScript.id = "gameScript";
    theScript.type = "text/javascript";

    const root = document.getElementById("root");
    const gameScript = document.getElementById("gameScript");
    const emulatorJSScript = document.createElement("script");
    const emulatorScript = document.getElementById("emulatorScript");
    emulatorJSScript.src = "https://www.emulatorjs.com/loader.js"
    emulatorJSScript.defer = true;
    emulatorJSScript.id = "emulatorScript";

    if (gameScript === null) {
        root.appendChild(theScript);
    }

    if (emulatorScript === null) {
        root.appendChild(emulatorJSScript);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
}, []);
```

**Comment by Impre-visible** [comment]
I reopen cause I have to actualise the page to make the emulator start

**Comment by nezza2005** [comment]
Hi has this been resolved? as I am also trying to integrate this software into React. 

I have managed to create a React Component and render this into the index.html and when inspecting the html page it seems to be rendering correctly as shown in a snipping image below:

![image](https://github.com/EmulatorJS/EmulatorJS/assets/73351888/ba7bb3bc-d6dc-4e02-b44a-999a67285df2)

However the page comes up blank, i am using Pesticide to show the div outlines in beleow image:

![image](https://github.com/EmulatorJS/EmulatorJS/assets/73351888/9ec68ca9-5c4b-47e7-917c-7b65215e4bf2)

I have also tried pointing to:
    `<script src="https://www.emulatorjs.com/loader.js"></script>

But still the same blank Page.

If i use Emulator.js in a node/express application using EJS templating it to inject this into an html file it works, if i produce a static html file and hardcode EMulator.js it works but it does not work if i try to render this in React using a component despite the source code looking correct.`  

Any one figured this out?

**Comment by nezza2005** [comment]
Hi, hi have managed to get this to work but as soon as the game loads i get an uncaught runtime error : 

ERROR
this.localization is not a function
TypeError: this.localization is not a function
    at Object.getCoreOptions (http://localhost:3000/EmulatorJS-main/data/emulator.min.js?v=31.6:1:417917)
    at Object.updateCoreOptions (http://localhost:3000/EmulatorJS-main/data/emulator.min.js?v=31.6:1:427094)
    at http://localhost:3000/EmulatorJS-main/data/emulator.min.js?v=31.6:1:430558
    at Array.forEach (<anonymous>)
    at HTMLDivElement.<anonymous> (http://localhost:3000/EmulatorJS-main/data/emulator.min.js?v=31.6:1:430515)
    at nt.B (http://localhost:3000/EmulatorJS-main/data/emulator.min.js?v=31.6:1:204925)
    at n (http://localhost:3000/EmulatorJS-main/data/emulator.min.js?v=31.6:1:293604)
    at Worker.o (http://localhost:3000/EmulatorJS-main/data/emulator.min.js?v=31.6:1:293976)
ERROR
this.localization is not a function
TypeError: this.localization is not a function
    at Object.getCoreOptions (http://localhost:3000/EmulatorJS-main/data/emulator.min.js?v=31.6:1:417917)
    at Object.updateCoreOptions (http://localhost:3000/EmulatorJS-main/data/emulator.min.js?v=31.6:1:427094)
    at http://localhost:3000/EmulatorJS-main/data/emulator.min.js?v=31.6:1:430558
    at Array.forEach (<anonymous>)
    at HTMLDivElement.<anonymous> (http://localhost:3000/EmulatorJS-main/data/emulator.min.js?v=31.6:1:430515)
    at nt.B (http://localhost:3000/EmulatorJS-main/data/emulator.min.js?v=31.6:1:204925)
    at n (http://localhost:3000/EmulatorJS-main/data/emulator.min.js?v=31.6:1:293604)
    at Worker.o (http://localhost:3000/EmulatorJS-main/data/emulator.min.js?v=31.6:1:293976)

i can close this error and the game runs fine allthough sound is a bit clumsy.

I am running a psx game.

Any idea why i am getting this error please?

**Comment by ethanaobrien** [comment]
On version 4.0, as long as you properly load it in, it should work.

Single page apps are not supported though

**Comment by Impre-visible** [comment]
> 

Can whe have a demo ? What this should look like, cause VanillaJS is way different than ReactJS.
Thanks

**Comment by ethanaobrien** [comment]
Well I'm definetely no react expert, but assuming this is correct it should be pretty simple

```
const injectScripts = () => {
    if (window.EJS_emulator || window.EmulatorJS) return;
    window.EJS_player = '#game';
    window.EJS_core = 'nes';
    window.EJS_gameUrl = 'path_to_rom';
    window.EJS_pathtodata = 'data/';
    
    const script = document.createElement('script');
    script.src = "data/loader.js";
    document.body.appendChild(script);
}

function App() {
  injectScripts();
  return (
    <div style={{width: "640px", height: "480px", maxWidth: "100%"}}>
        <div id='game'></div>
    </div>
  );
}

export default App;
```

**Comment by ethanaobrien** [comment]
@allancoding can you add this to the documentation. Also mention `EJS_DEBUG_XX` will not properly work on react

**Comment by allancoding** [comment]
Ok will do

**Comment by allancoding** [comment]
Add docs in EmulatorJS/emulatorjs.org/pull/27
