### ISSUE TITLE
Local host

### ISSUE THREAD

**Issue by drewlobel** [emulatorjs/emulatorjs#54]
Is there anyway I could host this just from a  micro sd card? with without a webserver?

**Comment by ethanaobrien** [comment]
no. You must use a web server due to the content secutity policy of local files.
If it helps, use this https://raw.githack.com/ethanaobrien/emulator-button/main/index.html

**Comment by drewlobel** [comment]
I was looking at the web server section for this and went to the one you have. was is git? i want to get this working for myself. sorry

**Comment by ethanaobrien** [comment]
https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb?hl=en

This is the web server I use

**Comment by drewlobel** [comment]
I think I had tried that but when ever i went to the link it wasent there. but i will try again

**Comment by drewlobel** [comment]
It works on my computer. Is it supposed to work on other computers on my wifi?

**Comment by ethanaobrien** [comment]
if you enable local network

**Comment by drewlobel** [comment]
Ok i did. Im not home right now, when i get home ill let you know of it worked on a separate computer

**Comment by drewlobel** [comment]
Also, with the web server, can I host multiple at once?

**Comment by ethanaobrien** [comment]
no. If you need to host more than one at once, try this beta web server - https://drive.google.com/drive/folders/1MmJYRceI1g1ZLNvANZ3AlnG9KB8GF3_h?usp=sharing

**Comment by drewlobel** [comment]
ok. thx

**Comment by ethanaobrien** [comment]
@drewlobel Can I close this?

**Comment by drewlobel** [comment]
Yah go ahead! Sorry about that
