### ISSUE TITLE
Zelda 4 Swords anniversary edition for nds

### ISSUE THREAD

**Issue by ShadDeal** [emulatorjs/emulatorjs#543]
Whenever i try to load the ROM, it comes out blank white. Even when loaded in demo.emulatorjs.org

**Comment by Ramaerel** [comment]
4 swords anniversary is a DSi exclusive rom, I don't believe that it's compatible.

**Comment by ethanaobrien** [comment]
First, please follow the bug issue template, as I can't do anything at all with the information I was provided with. A log of the console? Did anything else happen to the page? Is it just this game? Just this rom? This is most likely something that can't be fixed but "it turned white" doesn't tell me the issue. Please answer these questions and I'll reopen the issue, or I'll give you a reason of what's wrong and why I can't fix it, or if this is already part of another issue, which is possible
