### ISSUE TITLE
automatically full screen

### ISSUE THREAD

**Issue by yyj1983** [emulatorjs/emulatorjs#545]
Hello, may I ask how to set the automatic full screen display after entering the game? For example, on the mobile end, when I click to start the game, it will be automatically full screen, or automatically landscape full screen? thanks

**Comment by ghost** [comment]
You can attempt to try this script:
```
 <div style="width:100vw;height:100vh;max-width:100%">
```
It works really well on Chromebook and my pc. It won't do a true full screen unless you click F11.

**Comment by yyj1983** [comment]
> You can attempt to try this script:
> 
> It works really well on Chromebook and my pc. It won't do a true full screen unless you click F11.

Didn't you see the script?

**Comment by ethanaobrien** [comment]
Added new `EJS_fullscreenOnLoaded` option
