### ISSUE TITLE
avoid unzipping / hash checking roms option

### ISSUE THREAD

**Issue by silkyclouds** [emulatorjs/emulatorjs#547]
Hi there,

I store my roms in the cloud, and it makes it almost impossible to import them in emulatorJS, as I have to unzip each of my chd, etc. upfront the hash check at import time.

I trust my roms...so, would it be possible to add an option to skip the hash check at rom import time ? This to simply import the roms based on their name ? 

Would be great ! 

(and byt he way, the discord fails to load...) :( 

THANKS !

**Comment by ethanaobrien** [comment]
Hello!

>I have to unzip each of my chd, etc. upfront the hash check at import time.

You shouldn't have to do anything manually. Can you confirm this is the project you're using? This project doesn't have a docker version and is completely online. Could you upload your rom to https://demo.emulatorjs.org/ and confirm this is the project you're using

>(and byt he way, the discord fails to load...) :(

@allancoding could you check this please

**Comment by silkyclouds** [comment]
Hi Ethan,

Sure, EmulatorJs is what I am referring to, and it runs using a docker container packed by linuxserver.io : 

https://docs.linuxserver.io/images/docker-emulatorjs

Now I'm reading me back and "unzipping" is not wat I meant. EmulatorJS reads the file, and checks its hash, for each file it scans. I understand verifying a file hash is nice, but I'd rather simply feed it with my roms, hosted in the cloud, and mapped through a path variable to the docker container, without the need to wait for each rom to get downloaded, hash verfified... :)

**Comment by ethanaobrien** [comment]
I think you might be looking for this repository: https://github.com/linuxserver/docker-emulatorjs

Our two projects are completely different. Not sure why he chose the same name. I can't help you, sorry about that.  My project has no docker version currently available

**Comment by silkyclouds** [comment]
ok Sorry it's my misunderstanding then ;)

**Comment by ethanaobrien** [comment]
It's all good :)
