### ISSUE TITLE
Haptic vibration feedback problem in mobile browser

### ISSUE THREAD

**Issue by duanyu5871** [emulatorjs/emulatorjs#552]
The problem is that virtual-gamepad in mobile mode will send Haptic vibration feedback when long press.
If you long press (about 1s) the direction pad which used in NES and GBA cores or blank area in screen (div #display), it will send you back a small haptic vibration feedback. This wont be triggered in all other action buttons (likes "ABXY") or setting buttons (likes save load). 

If I stop the eventlistener of div#display with JScode
`$("#display")[0].addEventListener("touchstart",function(e) {e.preventDefault()},true)`
The Haptic vibration feedback will be closed, but setting button won't work anymore.

Is there any methods to turn it off or at least for the direction pad ?
Thanks

**Comment by ethanaobrien** [comment]
Will be fixed in the next update

**Comment by ethanaobrien** [comment]
Fixed
