### ISSUE TITLE
Memory Address locations for psx emulator to identify game progress variables like score or rounds won etc.

### ISSUE THREAD

**Issue by nezza2005** [emulatorjs/emulatorjs#553]
#### Make sure your issue doesn't get closed! Make sure you have done the following items
Hi,

I am looking for a way to detect the memory addresses that hold in game progress variables like player health or rounds won, coins collected etc.

I am using the mednafen_psx_hw emulator and have recorded a memory profile in the chrome dev tools whilst in game to look for these variables. 
But this is proving very difficult.

Do you have any suggestions on how to pin point these variables or do you have any API's that can find variables that change during game play?

Thanks.

**Comment by ethanaobrien** [comment]
I wouldn't know how to do this. I'd recommend looking at the [beetle psx hw](https://docs.libretro.com/library/beetle_psx_hw/) docs, as its the backend for the psx emulator

>Do you have any suggestions on how to pin point these variables or do you have any API's that can find variables that change during game play?

If you'd like to access any frontend specific code. Use `window.EJS_emulator`
