### ISSUE TITLE
I can't load a game...

### ISSUE THREAD

**Issue by L-spec875** [emulatorjs/emulatorjs#554]
Hello, I'm using replit to use EmulatorJS however I don't want advertisements in the game (Like in Emulatorjs.com) but when I use the code editiors code for Index.Html this is the code: 
            EJS_player = "#game";
            EJS_core = "nds";
            EJS_gameName = "Pokemon Soulsilver";
            EJS_color = "#bdbfc2";
            EJS_pathtodata = "https://cdn.jsdelivr.net/gh/ethanaobrien/emulatorjs@main/data/";
            EJS_gameUrl = "Pokemon - SoulSilver Version (USA).nds";
            EJS_biosUrl = "bios9.bin";
        </script>
        <script src="https://cdn.jsdelivr.net/gh/ethanaobrien/emulatorjs@main/data/loader.js"></script>
                   Then everything works perfectly until it goes to "Downloading Game Data" then it states "Failed to start game"
Please fix this "issue" it would be greatly aprreciated

**Comment by L-spec875** [comment]
a

**Comment by ethanaobrien** [comment]
b
