### ISSUE TITLE
Using "SaveAs" function with "EJS_onSaveState"

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#560]
Hi,

I'm trying to add to my "EJS_onSaveState" function this code - in order to open file storage window in order to save state file:
  saveAs(new Blob([state], {type:"application/octet-stream"}), 'game-state-file.save');

When i'm using the encrypted original site code, it works ok.

But when trying to run it under your open source script - i get this error message:
VM186923:163 Uncaught ReferenceError: saveAs is not defined

I've noticed that this "saveAs" function appears under emu-main.js file.

Can you please help me fix it?

Thank you.

**Comment by ethanaobrien** [comment]
Where are you getting this `saveAs` function from?

**Comment by shaylevary** [comment]
When using emulatojs.com script, the SaveAs function is loaded from his emulator js code, and this custom function works (save state folder window opens):
saveAs(new Blob([state], {type:"application/octet-stream"}), 'game-state-file.save');

When using your project script, this function doesn't work (I've noticed that your emulator.js file contain some of this SaveAs function).

Can you help me with a different function maybe that will open the save state file folder selection?

**Comment by ethanaobrien** [comment]
https://stackoverflow.com/a/54626214

You're simply downloading a blob. Google is your friend, remember that

**Comment by ethanaobrien** [comment]
@shaylevary You've been made a beta tester! Check discord when you get the chance
