### ISSUE TITLE
Not Loading

### ISSUE THREAD

**Issue by pizza699** [emulatorjs/emulatorjs#563]
Hey I start the emulator it is stuck on the loading screen (see the video below)
[Screen recording 2023-07-18 9.16.22 PM.webm](https://github.com/EmulatorJS/EmulatorJS/assets/130519782/39caaa73-241c-4f7d-934d-e37fa886d380)

**Comment by L-spec875** [comment]
I have that same issue except it is on a white screen

**Comment by ethanaobrien** [comment]
As the bug template states, I need a log of the console with `EJS_DEBUG_XX` set to true, uploaded to GitHub. I can't do anything without that.

If not supplied within 1 day,  this issue will be closed

**Comment by pizza699** [comment]
so you want the code?

**Comment by pizza699** [comment]
here's the code 
<html>
    <head>
        
    </head>
    <body>
        <div style="width:640px;height:480px;max-width:100%">
            <div id="game"></div>
        </div>
        <script>
            EJS_DEBUG_XX = true
            EJS_player = "#game";
            EJS_core = "nds";
            EJS_color = "#0064ff";
            EJS_pathtodata = "https://rawcdn.githack.com/EmulatorJS/EmulatorJS/main/data/";
            EJS_gameUrl = "Pokemon Renegade Platinum .nds";
        </script>
        <script src="https://rawcdn.githack.com/EmulatorJS/EmulatorJS/main/data/loader.js"></script>
    </body>
</html> 
(sorry I code in replit not GitHub

**Comment by pizza699** [comment]
<html>
    <head>
        
    </head>
    <body>
        <div style="width:640px;height:480px;max-width:100%">
            <div id="game"></div>
        </div>
        <script>
            EJS_DEBUG_XX = true
            EJS_player = "#game";
            EJS_core = "nds";
            EJS_color = "#0064ff";
            EJS_pathtodata = "https://rawcdn.githack.com/EmulatorJS/EmulatorJS/main/data/";
            EJS_gameUrl = "Pokemon Renegade Platinum .nds";
        </script>
        <script src="https://rawcdn.githack.com/EmulatorJS/EmulatorJS/main/data/loader.js"></script>
    </body>
</html>

**Comment by ethanaobrien** [comment]
>I need a log of the console with EJS_DEBUG_XX set to true, uploaded to GitHub

**Comment by pizza699** [comment]
ok

**Comment by L-spec875** [comment]
![Screenshot 2023-07-19 11 04 14 AM](https://github.com/EmulatorJS/EmulatorJS/assets/120753922/19bb3d7d-c379-4b6e-8c1f-1627ec10c798)

**Comment by L-spec875** [comment]
![Screenshot 2023-07-19 11 06 00 AM](https://github.com/EmulatorJS/EmulatorJS/assets/120753922/67ccd664-3cd5-4078-bf51-979c68e0a150)

**Comment by ethanaobrien** [comment]
`Using emulatorjs version 31.6 but the newest version is 40.2`

Update your EmulatorJS instance, clear your cache

**Comment by L-spec875** [comment]
THANKS!!!

**Comment by pizza699** [comment]
thanks I got it work
