### ISSUE TITLE
Support browser with old chrome core

### ISSUE THREAD

**Issue by duanyu5871** [emulatorjs/emulatorjs#564]
Hello
I love your project very much and update to 4.0 vision as soon as quickly. However, I found it will get error in old browser with chrome core (vision 95.0.4638.69) and report in console like follow:

```
Uncaught (in promise) TypeError: i.forEach is not a function
    at GamepadHandler.updateGamepadState (emulator.min.js:1)
    at GamepadHandler.loop (emulator.min.js:1)
    at new GamepadHandler (emulator.min.js:1)
    at EmulatorJS.bindListeners (emulator.min.js:1)
    at new EmulatorJS (emulator.min.js:1)
    at loader.js:90
```

The focus codes were something about gamepad begin with follow :

```
updateGamepadState() {
        const i = this.getGamepads();
        i.forEach((a,e)=>{ 
            if (a) {
                let t = !1;
                this.gamepads.forEach((o,e)=>{
                    if (o.index === a.index) {
                        const s = {
                            axes: [],
                            buttons: {},
                            index: o.index
                        };
... ...

```

This problem will stop emulator start and display nothing but black screen. And this wont be triggered in newer core chrome like 114.0 and so on.
By the way, thank you for your fix about #552 and writing easy api in window.EJS_emulator.gameManager for game save.

**Comment by ethanaobrien** [comment]
Fixed by https://github.com/ethanaobrien/Gamepad/commit/5d90c78486299323bdbe4996580e97eb66daf6bd. Changes just pushed here!
