### ISSUE TITLE
Question: How can I use my old states?

### ISSUE THREAD

**Issue by L-spec875** [emulatorjs/emulatorjs#565]
Hello, I am running Pokemon and when I try to open my save .state file nothing happens

**Comment by ethanaobrien** [comment]
Click the load state button
![image](https://github.com/EmulatorJS/EmulatorJS/assets/77750390/666df973-997e-45f7-b2bd-8ecddcea760b)

and upload the file

**Comment by L-spec875** [comment]
[Screen recording 2023-07-19 11.33.48 AM.webm](https://github.com/EmulatorJS/EmulatorJS/assets/120753922/a457ae77-ee0e-4404-a225-7b6897c86caf)

**Comment by ethanaobrien** [comment]
Don't access it from recent files. Go to the files location. If this is a bug, as I mentioned in that other issue, I need a log of the console with `EJS_DEBUG_XX` set to true

**Comment by L-spec875** [comment]
I fixed it by switching cores

**Comment by Juncx** [comment]
same problem with ios safari
@L-spec875 L-spec875 ，Which core did you use?

**Comment by ethanaobrien** [comment]
@Juncx switch to desmume

**Comment by L-spec875** [comment]
@Juncx I switched to MelonDS then it broke so I switched to desmume

**Comment by michael-j-green** [comment]
I think it’s probably worth noting that when loading a save state that it would require the _both_ the same core, and exactly the same ROM that was used to create it
