### ISSUE TITLE
[Bug] Network Error

### ISSUE THREAD

**Issue by pizza699** [emulatorjs/emulatorjs#566]
``Hi, I keep encountering this bug whenever I start up the emulator it shows a network error  I've also attached the HTML code I used. Yes, I have collected a FULL console `log,` with `EJS_DEBUG_XX` set to true, see images.
![Screenshot 2023-07-19 4 35 42 PM](https://github.com/EmulatorJS/EmulatorJS/assets/130519782/dd8b09c9-a3d7-404a-8949-163dd4c98504)
![Screenshot 2023-07-19 4 36 03 PM](https://github.com/EmulatorJS/EmulatorJS/assets/130519782/795b1622-5b0c-41d8-a95d-bae8e6a0c70c)
![Screenshot 2023-07-19 4 36 12 PM](https://github.com/EmulatorJS/EmulatorJS/assets/130519782/59247337-784e-4473-a542-68bba482f12f)
![Screenshot 2023-07-19 4 40 56 PM](https://github.com/EmulatorJS/EmulatorJS/assets/130519782/0cf3315e-2321-4f38-8877-c08fe5482b74)

`div style='width:100%;height:100%;max-width:100%'>
    <div id='game'></div>
</div>

<script type='text/javascript'>
    EJS_player = '#game';
    
    // Can also be desmume2015 or melonds
    EJS_core = 'nds';
    
    // URL to BIOS file
    EJS_biosUrl = '';
      
    // URL to Game rom
    EJS_gameUrl = 'Pokemon Renegade Platinum v1.3.0 Complete Boosted Shiny 1s8192 shiny rate.nds';
    
    // Path to the data directory
    EJS_pathtodata = 'https://cdn.jsdelivr.net/gh/ethanaobrien/emulatorjs@main/data/';
</script>
<script src='https://cdn.jsdelivr.net/gh/ethanaobrien/emulatorjs@main/data/loader.js'></script>`

**Comment by ethanaobrien** [comment]
The url you are using is crazily outdated.

ethanaobrien/emulatorjs should be EmulatorJS/EmulatorJS

**Comment by pizza699** [comment]
ok thanks

**Comment by pizza699** [comment]
![Screenshot 2023-07-19 6 57 33 PM](https://github.com/EmulatorJS/EmulatorJS/assets/130519782/7122bc3d-dbf9-4db4-9b28-2724402ba033)
@ethanaobrien it still does not work

**Comment by ethanaobrien** [comment]
Send a screenshot of the network tab in the console

Clear your cache

Try another browser

**Comment by pizza699** [comment]
ok here
![Screenshot 2023-07-19 8 19 59 PM](https://github.com/EmulatorJS/EmulatorJS/assets/130519782/e08451d4-d137-4bea-8865-770bf3a0a958)

**Comment by pizza699** [comment]
well clearing my cache did not work

**Comment by pizza699** [comment]
also, a different browser did not work

**Comment by ethanaobrien** [comment]
Are you using replit

**Comment by pizza699** [comment]
yes

**Comment by pizza699** [comment]
@ethanaobrien  so ???

**Comment by ethanaobrien** [comment]
Replit is known to cause these problems. Use something like this - https://github.com/ethanaobrien/worker-server

**Comment by pizza699** [comment]
ok

**Comment by pizza699** [comment]
thanks
