### ISSUE TITLE
Play and Pause function to use on our own.

### ISSUE THREAD

**Issue by imneckro** [emulatorjs/emulatorjs#57]
Can anyone write whats the play and pause functions to use ?

Thanks in advance

**Comment by ethanaobrien** [comment]
I don't quite get what you're asking, can you explain

**Comment by imneckro** [comment]
im trying to use play() and pause() functions on my own buttons and in different situations.
but i dont know whats the according name of these functions

**Comment by ethanaobrien** [comment]
So you would like the ability to call the play/pause function?

**Comment by imneckro** [comment]
yes exactly

**Comment by ethanaobrien** [comment]
okie, Give me some time and I'll get that to you

**Comment by imneckro** [comment]
Any progress on this? Thanks Ethan

**Comment by ethanaobrien** [comment]
Sorry, havent had too much time to look at this. I haven't been able to locate the location of the pause/play functions. sorry. I'll let you know when I find it

**Comment by allancoding** [comment]
You can use [jquery](https://api.jquery.com/) and run `$("[data-btn='play']").trigger("click");`
That will toggle play and pause.

**Comment by imneckro** [comment]
> You can use [jquery](https://api.jquery.com/) and run `$("[data-btn='play']").trigger("click");` That will toggle play and pause.

Thats nice!
Anyway to call netplay join function with parameters from javascript?

**Comment by allancoding** [comment]
You first have to set the players name.
You can do that with `$("[data-btn='netplay']").trigger("click");$(".ejs--158ea9dd34e3e7af2d837f8b05babb").attr("hidden","");$(".ejs--71527b6509aa48afce3ce1a11c02f0").val("players name");setTimeout(function(){$(".ejs--71527b6509aa48afce3ce1a11c02f0").trigger("click");}, 1000);`
There has to be a current room for it to work So would you create a room and then join or what?

**Comment by allancoding** [comment]
Do you what to do if room not found or too many players create new one?

**Comment by imneckro** [comment]
im live fetching rooms as you pointed so i can disable the ones maxed out.

**Comment by imneckro** [comment]
> $(".ejs--158ea9dd34e3e7af2d837f8b05babb").attr("hidden","");

this working but despite filling input with provided players name joins/creates game and players name remains undefined.

**Comment by imneckro** [comment]
click submit playersname was missing 
adding this $('.ejs--319bcec5dee9444e1a2a53d6503b7c').first().trigger("click");
solves the issue.

**Comment by ethanaobrien** [comment]
On the latest version (I just pushed) you can call these functions

play: `window.EJS_MODULE.resumeMainLoop();`
pause: `window.EJS_MODULE.pauseMainLoop();`

The play/pause button in the UI will not change

@imneckro Can I close?

**Comment by imneckro** [comment]
@ethanaobrien Great Ethan thanks a lot. Yes go ahead!
