### ISSUE TITLE
[Bug] SEGA Genesis gamepad directions are missing

### ISSUE THREAD

**Issue by zmarteline** [emulatorjs/emulatorjs#570]
There is no option to set UP, DOWN, LEFT and RIGHT on SEGA Genesis games, after the new releases.

**Comment by ethanaobrien** [comment]
Probably caused by #568. Should all sega systems have these options

**Comment by zmarteline** [comment]
Sorry, I did not understand how I fix it. I followed the link you sent, but there is no instructions there. I also tried use n-at:main's data folder.
Can you please explain what I have to do?
