### ISSUE TITLE
[Bug] STEP BY STEP NETPLAY Server

### ISSUE THREAD

**Issue by zmarteline** [emulatorjs/emulatorjs#573]
Please give me an easy step by step procedures to create a netplay server for your emulator?  I know it's not your business and you probably have a lot other stuff to take care, but I really miss play a few matches with my kids... This was one of the few bond moments we share after they move.

**Comment by ethanaobrien** [comment]
It's all in the documentation:

https://emulatorjs.org/docs4devs/Netplay.html#to-add-to-your-site

**Comment by zmarteline** [comment]
This instructions says it will not work on the current version. Any ETA for a netplay release for 4.x emulator?

**Comment by ethanaobrien** [comment]
Not at the moment, nope
