### ISSUE TITLE
EmulatorJS Error

### ISSUE THREAD

**Issue by FS2B** [EmulatorJS/EmulatorJS#574]
So I Entered The Game And This Error Was That
![363030F6-5FE8-48F7-BFB1-F620C78F3C2A](https://github.com/EmulatorJS/EmulatorJS/assets/126734509/2213f8cb-a750-479b-a464-c7b9a68f7117)

**Comment by ethanaobrien** [comment]
I see no error

**Comment by FS2B** [comment]
RIP N64 Emulatorjs Pls Fix It

**Comment by ethanaobrien** [comment]
I can't fix an error I have no log for
