### ISSUE TITLE
Problems with mobile/touch page scrolling - Since v4.0

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#575]
Hi

In the old version of the emulatorjs script, I could scroll up and down the HTML page that the script was embedded in - by clicking on the script window and scrolling with my finger up and down.

Starting with version 4, the script window goes into some focus mode and I can't scroll up or down the page while clicking on the script window.

For example, if i need to open the settings menu at the top of the script window (when browsing from the mobile phone), in most of the times i need to scroll down a little to reach the bottom menu options, but as I mentioned, scrolling the screen by pressing the script windows isn't not possible since version 4.

**Comment by ethanaobrien** [comment]
This is a hard thing to decide what to do, because some systems that have mouse need this (like nds)...

**Comment by shaylevary** [comment]
Maybe you can add a configurable settings for this feature, so users can decide if to enable/disable this option.
As much as I know, only nes and nds currently support mouse.

**Comment by ethanaobrien** [comment]
Got a solution! I'll get it implemented and out there asap

**Comment by ethanaobrien** [comment]
Fixed in 4.1.1
