### ISSUE TITLE
How to use decrypt tools

### ISSUE THREAD

**Issue by cyrillpetroff** [emulatorjs/emulatorjs#58]
Greetings. I don’t understand in any way how to use decrypt tools. The script is just loaded, there is nothing in the console.

**Comment by ethanaobrien** [comment]
are you trying to use index.html, index2.html, or index3.html?

**Comment by cyrillpetroff** [comment]
> are you trying to use index.html, index2.html, or index3.html?

Oh sure. I open the obfuscated script in them, but nothing happens. The script is simply downloaded under the name emulator. The console logs are also clean.

**Comment by ethanaobrien** [comment]
Ok, the `index.html` file is for replacing all the uses of the encryption variable, the one supported in it is `_0x4e1f`. You must manually update the method in the `decrypt.js` file which contains the first little bit of the obfuscated code.  You upload the file to the page, wait a bit (it may stop responding) and then it will download the unobfuscated code.

The `index2.html` file is for replacing all `this.['asdfdgs']` things with `this.asdfdgs`. It is beta and you may have to go through and undo a few. You upload the file and it will process it and then download it

**Comment by cyrillpetroff** [comment]
It's clear. Now it is clear. Thank you.

**Comment by ethanaobrien** [comment]
cool, can I close this?

**Comment by cyrillpetroff** [comment]
Oh sure. Close.
