### ISSUE TITLE
[Bug]Is Nintendo 64 Still Work

### ISSUE THREAD

**Issue by FS2B** [EmulatorJS/EmulatorJS#584]
#### Make sure your issue doesn't get closed! Make sure you have done the following items

- [x] I have collected a **FULL** log of the console, with `EJS_DEBUG_XX` set to true, and uploaded it straight to GitHub.
- [x] I have not made any changes to the EmulatorJS instance I am running into this bug on.
- [x] I am on the latest version of EmulatorJS
- [x] I have not attached any images or logs via external sites. I have uploaded them straight to GitHub and acknowledge that external sites may pose a security issue.
- [x] I have included, **IN DETAIL**, the steps to reproduce the bug.

**Comment by Ramaerel** [comment]
N64 works fine, I can run multiple different games without any issues

**Comment by ethanaobrien** [comment]
I think its ios safari specific. I'll ask s-coding open a legitimate issue

**Comment by ethanaobrien** [comment]
But otherwise, I got no logs

**Comment by FS2B** [comment]
It’s Stayes As 99%
