### ISSUE TITLE
[Bug] Annoying Shader message at startup...

### ISSUE THREAD

**Issue by zmarteline** [emulatorjs/emulatorjs#585]
Could you please get rid of the annoying retroarch Shader message at startup?
![shader](https://github.com/EmulatorJS/EmulatorJS/assets/101960945/3b1beb53-6d28-44c2-8f81-bcde8222bdf0)

:)

**Comment by ethanaobrien** [comment]
This should be easy

**Comment by allancoding** [comment]
Yes it would be good to remove this, along with the loading of the config file message.

**Comment by ethanaobrien** [comment]
What loading of the config file message @allancoding

**Comment by allancoding** [comment]
I think it already got removed. lol

**Comment by zmarteline** [comment]
Now it is gone! Many thanks for that!
