### ISSUE TITLE
[Feature Request] Play on open - Set `EJS_` args based on URL

### ISSUE THREAD

**Issue by AndrewBudziszek** [emulatorjs/emulatorjs#587]
It would be cool if EmulatorJS had a feature that allowed files to be directly opened via something like URL params.

This would enable applications like [RomM](https://github.com/zurdi15/romm) to send users straight into their games. 

PS: If these two projects worked together, great things could happen.

**Comment by ethanaobrien** [comment]
Basically, adding an html page that you can make an iframe on your site that would set the `EJS_` arguments based on the url params? That makes sense.

**Comment by S-Coding23** [comment]
> It would be cool if EmulatorJS had a feature that allowed files to be directly opened via something like URL params.
> 
> This would enable applications like [RomM](https://github.com/zurdi15/romm) to send users straight into their games.
> 
> PS: If these two projects worked together, great things could happen.

You can use iframe like @ethanaobrien said. Look at https://rec0ded88.com

**Comment by michael-j-green** [comment]
I do this in my project. Build a wrapper page that reads the query strings and then passes them off to an iframe.

I also pass which core to use, and the bios URL to make sure it's configured properly.
