### ISSUE TITLE
[Bug] ATARI 2600 Control Missing a button

### ISSUE THREAD

**Issue by zmarteline** [emulatorjs/emulatorjs#591]
There is a console button missing, that in the old gamepad style was represented by the START  button, it's used to start some atari games. Can you please bring it back?

**Comment by zmarteline** [comment]
This is an example of game that cannot be played because of this issue.

**Comment by ethanaobrien** [comment]
Please dont upload roms

@n-at Could you look at this?

**Comment by n-at** [comment]
Added missing buttons for atari2600. 7800 had similar issue, also updated.

**Comment by ethanaobrien** [comment]
Thanks @n-at!

**Comment by zmarteline** [comment]
Thanks!! 💯
