### ISSUE TITLE
[Bug] Problem with setting 3DO defaultControllers

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#593]
Hi, 

There is problem to set 3DO defaultControllers on v4.05.
When using the previous 3.x version - it works without any problem.

I've encounter this "defaultControllers" issue only with 3DO emulator.

**Comment by ethanaobrien** [comment]
What is expected to happen? What happens differently? Anything in the console?

**Comment by ethanaobrien** [comment]
Oh wait, the way of mapping the default controllers changed in v 4.x. Please see https://emulatorjs.org/docs4devs/Control%20Mapping.html

**Comment by shaylevary** [comment]
I've set it this way, but for example I've set the shift key for the select button, but it always show it as V button (even after I try to click on reset control buttons).
I don't have this issue with other cores, only with 3do.

**Comment by ethanaobrien** [comment]
This seems highly improbable. Can you send your configuration so I can look at it?
