### ISSUE TITLE
NDS - How to Rotate the Game Screen - 90 Degree

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#596]
Hi,

I've got a few NDS games that need to be rotated 90 degree.
<img width="453" alt="nds2" src="https://github.com/EmulatorJS/EmulatorJS/assets/10597517/612a1759-ba51-4432-a355-d7a137decb3a">
![nds](https://github.com/EmulatorJS/EmulatorJS/assets/10597517/c269d760-c414-4f69-a56d-fcbad61fc475)

I didn't find any option to rotate the game screen on the emulator settings.
I will appreciate if you can please help me with this issue.

**Comment by ethanaobrien** [comment]
That's funny. I'll see if I can add this
