### ISSUE TITLE
Can You Fix My N64 Emulatorjs

### ISSUE THREAD

**Issue by FS2B** [EmulatorJS/EmulatorJS#597]
My Nintendo 64 Emulatorjs Stopped Working Can You Fix It

**Comment by ethanaobrien** [comment]
Do I get:
- Logs
- EmulatorJS version
- device
- browser

Have you tried:
- updating
- clearing your cache

**Comment by FS2B** [comment]
No

**Comment by ethanaobrien** [comment]
You can get logs on mobile

**Comment by FS2B** [comment]
How
