### ISSUE TITLE
[Bug] Mobile Settings Menu Location

### ISSUE THREAD

**Issue by S-Coding23** [emulatorjs/emulatorjs#598]
On multiple cores, the setting menu is located too far to the left side of the screen, cutting off some text. I have noticed this with Genesis, DS, and PlayStation on iOS and Android. 

![IMG_4148](https://github.com/EmulatorJS/EmulatorJS/assets/135175291/7ea4ae1b-5b95-43d9-9e51-a9c9d187a25e)
![IMG_4147](https://github.com/EmulatorJS/EmulatorJS/assets/135175291/181e269e-1dc6-499e-8cc0-a209e87347f0)

**Comment by ethanaobrien** [comment]
@S-Coding23 Can you test again

**Comment by S-Coding23** [comment]
> @S-Coding23 Can you test again

I updated, cleared server and browser cache, but the settings menu is still the same.

**Comment by ethanaobrien** [comment]
Oh yeah, I think I forgot something

If you have the settings menu open, rotate your phone landscape and back, does it work?

**Comment by S-Coding23** [comment]
> Oh yeah, I think I forgot something
> 
> If you have the settings menu open, rotate your phone landscape and back, does it work?

When I rotate, the menu shifts to the right side of the screen and is completely visible. When I rotate back, it goes back to being cut off on the left.

**Comment by ethanaobrien** [comment]
Aw, I'll look at this

**Comment by ethanaobrien** [comment]
Alright, This has been fixed
