### ISSUE TITLE
Webpage scrolling up/down during gameplay

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#599]
Hi,

Since v4.xx, when i play a game on my web browser and click on the up/down arrow buttons, the webpage also scroll up/down.
This issue doesn't appear to happened on the previous version v3.xx and original emulatorjs core.

**Comment by ethanaobrien** [comment]
Now this probably won't be changed, because several people use the arrow keys to play the game. If we don't lock this the page will be moving around constantly during gameplay is the issue

**Comment by ethanaobrien** [comment]
Wait, I understood the opposite

**Comment by ethanaobrien** [comment]
Just tested and cannot reproduce this. Please note it will not block any keys until the game is started and that the canvas must be the focused element (the user must click on it)

**Comment by shaylevary** [comment]
For some reason it doesn't lock the game window for me after starting game on v4.xx, so when using the arrows during gameplay, all the page moves constanley.

When switching to previous v3.xx or original emulatorjs script - this issue doesnt appear.

Did anyone else here encouter the same issue?

**Comment by ethanaobrien** [comment]
Can you send a screen recording?

You must click the emulator window before it will lock

**Comment by shaylevary** [comment]
I've dm you on discord.
