### ISSUE TITLE
EJS_core = 'mame';

### ISSUE THREAD

**Issue by dosboxonline** [EmulatorJS/EmulatorJS#6]
please add this file - "mame-3-wasm.data" from www.emulatorjs.com. Its need for some Arcade Machine games.

**Comment by dosboxonline** [comment]
https://www.emulatorjs.com/cores/mame-3-wasm.data

**Comment by dosboxonline** [comment]
https://www.emulatorjs.com/cores/mame-1-wasm.data
https://www.emulatorjs.com/cores/mame-2-wasm.data
https://www.emulatorjs.com/cores/mame-4-wasm.data - Battletoads game and need "bsmt2000.bin" (sound chip bios)
https://www.emulatorjs.com/cores/mame-5-wasm.data
https://www.emulatorjs.com/cores/mame-6-wasm.data

**Comment by ethanaobrien** [comment]
@dosboxonline Thank you. I should have time to add later today. Thank you for including the links! It is very helpful!

**Comment by ethanaobrien** [comment]
Just pushed changes! Let me know if there is still a problem
