### ISSUE TITLE
cheats database

### ISSUE THREAD

**Issue by ethanaobrien** [emulatorjs/emulatorjs#60]
Database to search common cheat codes. This would be cool - it would just take time

**Comment by InTheMidl** [comment]
What kind of cheats work on here?

**Comment by ethanaobrien** [comment]
@InTheMidl

cheats will look like this `8133B176 FFFF`

This site has some https://www.gamegenie.com/cheats/gameshark/n64/super_mario_64.html

**Comment by InTheMidl** [comment]
ok.

**Comment by ethanaobrien** [comment]
This would take wayyy to much memory and would take a lot of time.
