### ISSUE TITLE
[Bug] Keeps loading forever

### ISSUE THREAD

**Issue by deblpr** [emulatorjs/emulatorjs#600]
When i test it on a GitHub pages page it just keeps loading forever and this errors appears on the console:

```
Solicitud desde otro origen bloqueada: la política de mismo origen impide leer el recurso remoto en https://rawcdn.githack.com/EmulatorJS/EmulatorJS/main/data/v.json (razón: falta la cabecera CORS 'Access-Control-Allow-Origin'). Código de estado: 404.

error { target: XMLHttpRequest, isTrusted: true, lengthComputable: false, loaded: 0, total: 0, srcElement: XMLHttpRequest, eventPhase: 0, bubbles: false, cancelable: false, returnValue: true, … }
[emulator.min.js:1:1239](https://rawcdn.githack.com/EmulatorJS/EmulatorJS/main/data/emulator.min.js?v=30.5)
Uncaught (in promise) TypeError: t is undefined
    exports https://rawcdn.githack.com/EmulatorJS/EmulatorJS/main/data/emulator.min.js?v=30.5:1
    z https://rawcdn.githack.com/EmulatorJS/EmulatorJS/main/data/emulator.min.js?v=30.5:1
[emulator.min.js:1:1555](https://rawcdn.githack.com/EmulatorJS/EmulatorJS/main/data/emulator.min.js?v=30.5)

```

To recreate it just go to Code Editor, select the N64 System, then Select Start On page load and upload a rom. Leave blank Ad URL, bios file and SaveState(to be loaded on start). Press Generate Out file, then drop it's content on github as a release. Upload it to github pages and go to the page.

**Comment by ethanaobrien** [comment]
This is a "cors" error. That means the emulator cannot access a resource

https://emulatorjs.org/docs/FAQ.html#q-i-m-getting-network-error-when-trying-to-play-what-do-i-do

**Comment by ethanaobrien** [comment]
(Ps, it looks like you need to update)
