### ISSUE TITLE
[Feature Request] Slowdown

### ISSUE THREAD

**Issue by deadman626** [emulatorjs/emulatorjs#603]
Back when Online Emulators used to run on Adobe Flash Player I could easily use Cheat Engine to slow games down to easily dodge large amounts of enemy bullets or jump on fast-moving platforms or to win in Quick Time Events.

- Please add a Games Speed Sittings that lets me play games at Half or Quarter of game original Speed. it will add more fun to it.

**Comment by ethanaobrien** [comment]
Oh wait, this isnt done yet
