### ISSUE TITLE
[Bug] pause/play crashes the emulator

### ISSUE THREAD

**Issue by n-at** [emulatorjs/emulatorjs#605]
After loading game pressing pause and then play button causes emulator crash with error message:

```
Uncaught RuntimeError: memory access out of bounds
```

Tested with fceumm in chromium based browser (firefox has similar issue with different message).

It looks like problem is here: https://github.com/EmulatorJS/RetroArch/blob/master/gfx/drivers_context/emscriptenegl_ctx.c#L49

Change to

```c
emscripten_set_main_loop_timing(EM_TIMING_RAF, 1);
```

solves this issue but breaks fast forward.

Screenshot from firefox and https://demo.emulatorjs.org/
![image](https://github.com/EmulatorJS/EmulatorJS/assets/2185280/392e86dd-fe06-44db-9f69-313a1401c3fc)

**Comment by ethanaobrien** [comment]
Uh oh, that's an issue. I'm not sure what it would be, but I don't think it's the timing method. Changing to request animation frame would break fast forward and speed on lower fps devices

**Comment by allancoding** [comment]
I just had the same problem. It was with a nes game. The page did not freeze just the game.

**Comment by n-at** [comment]
I tried to build two fceumm core variants on current version of https://github.com/EmulatorJS/RetroArch with EM_TIMING_RAF and with EM_TIMING_SETIMMEDIATE - first works (but fast forward don't), second crashes. EM_TIMING_SETTIMEOUT also crashes.

**Comment by n-at** [comment]
Problem may be with pauseMainLoop/resumeMainLoop of emscripten here: https://github.com/EmulatorJS/EmulatorJS/blob/main/data/GameManager.js#L255
Change this to pause in RetroArch (like here: https://github.com/EmulatorJS/RetroArch/compare/master...n-at:EJS_RetroArch:master#diff-3082ed9563ae0070650b649c04091334e4b144d8af21a52a81c405853ff738f2R6180) resolves this issue but causes another: FPS on pause becomes unstable.

**Comment by ethanaobrien** [comment]
You are completely correct. When `Module.pauseMainLoop` is called while the wasm code is sleeping, it causes the whole program to get wonky. My idea is similar, but instead of using retroarches pausing feature, use emscriptens pause main loop inside of the main loop function. Pause the main loop there so we know we aren't in sleep

**Comment by ethanaobrien** [comment]
@n-at Can you update and try again? I believe I fixed it

**Comment by n-at** [comment]
Yes, now play/pause works (and fast forward too). Thank you.
