### ISSUE TITLE
[Request] N64DD Support

### ISSUE THREAD

**Issue by Norbtails97** [emulatorjs/emulatorjs#606]
It's great that we have a n64 core, but how about adding n64dd support?

**Comment by ethanaobrien** [comment]
It should be supported under the n64 core. Does it not work?

**Comment by Norbtails97** [comment]
still loads, but doesn't launches the n64dd game :(

**Comment by Norbtails97** [comment]
Also it's unresponsive.

**Comment by ethanaobrien** [comment]
That's going to be a core issue. You should check the libretro mupen64 docs for a compatibility list

**Comment by Norbtails97** [comment]
k

**Comment by Norbtails97** [comment]
is there a way you can make a 64dd core?

**Comment by ethanaobrien** [comment]
There should be no separate core... there is no n64dd specific emulator

**Comment by Norbtails97** [comment]
try other n64 cores? mabe setup n64dd settings on mupen64plus core? i know retroarch have mupen64 64dd settings.

**Comment by ethanaobrien** [comment]
Every Nintendo64 core supported in retroarch is supported in emulatorjs

**Comment by ethanaobrien** [comment]
See this @Norbtails97 

https://forums.libretro.com/t/is-there-a-mupen64plus-next-64dd-guide-anywhere/35014

**Comment by Norbtails97** [comment]
Can you add the bios to emulatorjs? will that work?

**Comment by ethanaobrien** [comment]
You must supply the bios itself

**Comment by Norbtails97** [comment]
failed to start game error when i run the 64dd bios

**Comment by ethanaobrien** [comment]
Then do some research and figure it out

**Comment by Norbtails97** [comment]
ok
