### ISSUE TITLE
[Feature request] Override individual options

### ISSUE THREAD

**Issue by zmarteline** [emulatorjs/emulatorjs#613]
So, I have several html files to launch games, as a matter of fact, one for each game, each html contains the start configuration to launch Emulatorjs. The problem is, when a new feature is launched, EJS_fullscreenOnLoaded for example, I have to add it inside of each html file.

With thatim mind, my request is a config file that overide any configuration command set trough html, for example, if I set inside this config file only these 2 lines:

EJS_fullscreenOnLoaded = false;
EJS_DEBUG_XX = true;

The game will not start full screen and the debug will be turned on for every game, no matter what is inside the html used to launch the game.

Is that possible?

**Comment by ethanaobrien** [comment]
Technically you can just modify the `loader.js` file, which would be the most "possible" solution and the only way to guarantee it'd be turned on/off for every game

Does this work for you?

**Comment by zmarteline** [comment]
Sure it does!
Thanks for the tip, Saved me from a lot of work!

**Comment by zmarteline** [comment]
Just a small follow up question and I will close this again (sorry):

Inside loader.js, we have:

config.buttonOpts = window.EJS_Buttons;

How can I set buttons to show/hide bypassing (or replacing) this?

**Comment by zmarteline** [comment]
I found a workaround. Just in case someone also need  it:

You can bypass Show /  hide buttons  inside emulator.js, just look for this.config.buttonOpts.xxx where xxx is the name of the button, im my case this.config.buttonOpts.settings.

After that is just a matter of set what you want.

**Comment by zmarteline** [comment]
Weird. It works, but once I start a game from another core, the settings are back. Probably the option called from html takes place... Any ideas on how to avoid it?

**Comment by zmarteline** [comment]
I got it, just put  

**config.buttonOpts.settings = false;** after  **config.buttonOpts = window.EJS_Buttons;**

on **loader.js**... also works for any other buttons: **config.buttonOpts.xxx**.

Thats it!

**Comment by ethanaobrien** [comment]
That's a smart idea
