### ISSUE TITLE
[Bug] fullscreenOnLoad does not work while startOnLoad is enabled

### ISSUE THREAD

**Issue by zmarteline** [emulatorjs/emulatorjs#614]
Can you guys check if it also happens with you?

**Comment by ethanaobrien** [comment]
That's expected. You must interact with the page within a specific amount of time for fullscreen on loaded to work

**Comment by zmarteline** [comment]
That was quick! lol
Thanks.

**Comment by ethanaobrien** [comment]
Yep, sorry about that.

Safari has a similar issue actually. It may "freeze" on load (until clicked) because safari has more strict permissions
