### ISSUE TITLE
PS2 Core

### ISSUE THREAD

**Issue by zmarteline** [emulatorjs/emulatorjs#616]
There was some developments in retroarch regarding PS2 core (PCSX2)... Is this still not possible?

https://docs.libretro.com/library/pcsx2/

#468

**Comment by ethanaobrien** [comment]
Probably not, especially with the amount of memory the page you sent says is required.

I can try compiling it but it it doesn't work, there's not much I can do

**Comment by ethanaobrien** [comment]
Never mind, it uses cmake

**Comment by zmarteline** [comment]
:(
