### ISSUE TITLE
[Request] When input_value is entered as an array, it only functions in debug mode.

### ISSUE THREAD

**Issue by skyksit** [emulatorjs/emulatorjs#617]
For the Double Dragon game, there are often instances where you need to press the Y + B buttons simultaneously. To address this, I modified the approach by creating an array for input_value and sending the corresponding events based on the length of the array whenever an array is inputted.

The issue is that when EJS_DEBUG_XX = true, this modification works properly. However, when EJS_DEBUG_XX = false, it doesn't function.

I would like to know the reason behind this.

The modified part is as follows:

emulator.js

                let values = [];
                if (typeof info[i].input_value === 'number') {
                    values.push(info[i].input_value);
                } else if (Array.isArray(info[i].input_value)) {
                    values = info[i].input_value;
                }
                this.addEventListener(button, "touchstart touchend touchcancel", (e) => {
                    e.preventDefault();
                    if (e.type === 'touchend' || e.type === 'touchcancel') {
                        e.target.classList.remove("ejs_virtualGamepad_button_down");
                        window.setTimeout(() => {
                            for (const value of values) {
                                this.gameManager.simulateInput(0, value, 0);
                            }
                        });
                    } else {
                        e.target.classList.add("ejs_virtualGamepad_button_down");
                        
                        for (const value of values) {
                            this.gameManager.simulateInput(0, value, 1);
                        }
                    }
                });

index.html
           EJS_DEBUG_XX = true;
           EJS_VirtualGamepadSettings = [
                ...
               { type: "button", text: "Y+B", id: "u", location: "right", top: -45, left: 50, bold: true, input_value: [1, 8] },
               ...
           ];

**Comment by skyksit** [comment]
![Screenshot 2023-08-14 at 1 02 20 PM](https://github.com/EmulatorJS/EmulatorJS/assets/20593462/9e280e8f-e78a-4fc7-8367-f6803c886b0e)

**Comment by ethanaobrien** [comment]
@skyksit 

Did you minify your scripts?

https://emulatorjs.org/docs4devs/Minifying.html

Debug will pull the non minified files

**Comment by skyksit** [comment]
thank you I didn't think it was minified in the test version because I didn't use minify in the service version. problem solved thanks to you
