### ISSUE TITLE
[Bug] Problem with display game screenshot on startup screen when using "EJS_backgroundBlur" option

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#618]
Hi,

I've used the new option for adding game screenshot on the startup screen using this function: "EJS_backgroundImage".
The problem is that when i set "EJS_backgroundImage=true" the screenshot display get messy.

![blur](https://github.com/EmulatorJS/EmulatorJS/assets/10597517/18aef0c8-17ac-4a44-9006-5ebcdf3ab88a)

**Comment by ethanaobrien** [comment]
@allancoding

**Comment by allancoding** [comment]
Looks like I forgot no repeat.

**Comment by allancoding** [comment]
@shaylevary could you send me your html code and the image so I can test?

**Comment by allancoding** [comment]
@shaylevary `EJS_backgroundImage` is supposed to equal a image path like bellow:
![2023-08-14_14-58](https://github.com/EmulatorJS/EmulatorJS/assets/74841470/3b52ecbd-6eca-474d-a429-a4fd6c0e801d)

**Comment by shaylevary** [comment]
@allancoding i'm using relative url, and still get the same duplicate screenshot results when the "Backgroundblur" is set to TRUE on every game i try. if i set the blur to false, it work ok.

Here is my js script settings:

EJS_player = '#game';
EJS_startOnLoaded = false;
EJS_fullscreenOnLoaded = false; 
EJS_core = 'arcade';
EJS_biosUrl = '/engine/console/bios/arcade.7z';
EJS_gameUrl = '/wp-content/uploads/games/console/S/strhoop.zip';
EJS_gameID = 786;
EJS_playerName = 'Guest_981796';
EJS_pathtodata = '/engine/console/core_new_v7/';
EJS_backgroundImage = '/wp-content/uploads/2023/03/street_hoop_1678878409.jpg'; 
EJS_backgroundBlur = true;

**Comment by allancoding** [comment]
@shaylevary What does your html and css look like?

**Comment by shaylevary** [comment]
I will send you later a zip containg a demo html file, as it is already after midnight here.
I just would like to add that my div#game resolution is 800x600, so maybe this is what causing the issue.

**Comment by allancoding** [comment]
are you setting dimensions on the div or the `#game` div?
```html
<div style='width:800px;height:600px;max-width:100%'>
            <div id='game'></div>
        </div>
```
800x600 works fine for me:
![2023-08-14_15-55](https://github.com/EmulatorJS/EmulatorJS/assets/74841470/f1401428-b8b1-4fbe-8390-48288857bee2)

**Comment by shaylevary** [comment]
I'm setting the div that comes before the div#game.
I will check this issue again on morning and send you my html file.

Btw, I think it will be a nice feature to align "start game" button to top/middle/bottom of screen, as I prefer to set it to the middle of screen, it appears immediately to mobile users, while if it appear on bottom, they need to scroll down a bit sometimes to see it.

**Comment by allancoding** [comment]
> Btw, I think it will be a nice feature to align "start game" button to top/middle/bottom of screen, as I prefer to set it to the middle of screen, it appears immediately to mobile users, while if it appear on bottom, they need to scroll down a bit sometimes to see it.

I added this is #620

**Comment by ethanaobrien** [comment]
@allancoding can you at least "fix" this (make it foolproof)

**Comment by allancoding** [comment]
I still don't know how this error came about. I'm waiting for the html and some logs. Cuz it should be fool proof right now.

**Comment by ethanaobrien** [comment]
@shaylevary can you dm @allancoding the website through discord

**Comment by shaylevary** [comment]
Hi,

I found out what CSS code was causing all this trouble.
My WP theme uses this code:
#td-game-wrap {
    text-align: center
}

So in order to solve this problem, i've added this css code:
.ejs_game_background {    text-align: -webkit-auto; }

I think you should also add this code to your original css, in order to solve similar issues.

Anyway, we can close this issue.

**Comment by allancoding** [comment]
Ok I will add that if it doesn't cause any other problems.
Thanks

**Comment by ethanaobrien** [comment]
Wait to close until it's fixed

**Comment by allancoding** [comment]
Well technically it is fixed I just have to add that css if there using other css that has text align center. Lol
