### ISSUE TITLE
Save/Load state slots

### ISSUE THREAD

**Issue by ethanaobrien** [emulatorjs/emulatorjs#62]
Multiple slots to save/load state

**Comment by raulbojalil** [comment]
Is there any progress on this?. I started working on a server-backed save state manager (so I can share states between devices), so I wanted to know if any work on this was already done (to avoid reinventing the wheel). 

If there's nothing done yet, don't worry :). Thanks.

**Comment by ethanaobrien** [comment]
No progress yet, although most of it is going to be copy and paste

**Comment by raulbojalil** [comment]
No problem then. Out of curiosity, will you be implementing this on the client (localstorage, IndexedDB, wasm sqlite, etc.) or server?

**Comment by ethanaobrien** [comment]
I was planning on just implementing this for the quick save state, so on the client

**Comment by raulbojalil** [comment]
It'd be cool to store the states locally and then automatically synchronize with the server when a connection is available, useful for those situations where you lose your connection for whatever reason.

**Comment by ethanaobrien** [comment]
Normally I dont do server side things, I tend to make it simple for a new developer who knows nothing to operate. You could probably implement this pretty easily

**Comment by ethanaobrien** [comment]
implemented
