### ISSUE TITLE
[Bug] Cheat menu broken on v4.xx

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#621]
Hi,

Today I started adding Game Genie Codes to my SNES, SEGA and N64 games.
From my tests, All GG codes doesn't work with the new v4.xx script, only when I switch back to v3.xx all GG codes works fine.

Another problem that i've noticed, when I enter the emulatorjs "Cheat Screen" in the new version, it seems like it keeps all kinds of old GG information from previous games i've entered.

Despite this, I did not encounter any error on console.
![gg-issue](https://github.com/EmulatorJS/EmulatorJS/assets/10597517/427e8a4f-1231-4db2-80e4-72f5dec8793f)

**Comment by pizza699** [comment]
I thought the Emulator uses Action replay codes

**Comment by shaylevary** [comment]
I use gam egenie codes, but maybe action replay codes works too.
Anyway, currently v4.xx has bug with the cheat menu, so only v3.xxx can be used.

**Comment by shaylevary** [comment]
Thank you, works like charm!
