### ISSUE TITLE
cors issue

### ISSUE THREAD

**Issue by genericguy01** [EmulatorJS/EmulatorJS#622]
im pretty new to html and ive been using replit to code my site (i know replit doesn't support this, but im just using replit as a code editor, and exporting the website when im done and host it on a other hoster) and when i put the code helpers folder and click start  game i got this issue:

![image_2023-08-15_155227312](https://github.com/EmulatorJS/EmulatorJS/assets/122393410/c83de3e5-2c5d-49c3-9ab3-e89e5f40b146)

and when i click the domain that it tried to get resources from i got a 404: Not found error, i tried the emulatorjs.com code and  it worked with the rom, so i really dont know anymore

**Comment by ethanaobrien** [comment]
Try clearing your cache/updating your instance.. It looks like your setup is trying to pull 3.x resources, and can't find them because they no longer exist

**Comment by genericguy01** [comment]
how do i update my instance, i really new, also i already cleared
 my cache

**Comment by ethanaobrien** [comment]
You update your data folder.

If you're using a source provider and you've cleared your cache, that's their fault.
