### ISSUE TITLE
Multiple controllers

### ISSUE THREAD

**Issue by Juror2372** [emulatorjs/emulatorjs#625]
Hi thank you so much for making this tool! It feels like if I’m 12 all over again!

I was wondering if it’s possible to have more than one controller of the same type for multiplayer games?

I’m trying to use both my PS4 controllers but they seem to be seen as only one controller in an snes game. I tried the same rom in libretro web to make sure it’s not an issue with the rom and there each of my controllers are assigned correctly. 

Any help would be greatly appreciated.

Best,

**Comment by ethanaobrien** [comment]
This should already be implemented.

In the control settings menu, try switching to player 2 and setup those settings.

And to verify, can you test on the demo website: https://demo.emulatorjs.org

**Comment by Juror2372** [comment]
Thanks for the fast reply!
I tried on the demo and I’m getting the same result. I can map individual controllers, but once in game, both controllers controls each player.

**Comment by ethanaobrien** [comment]
This might be a bug. I'll look at this

**Comment by Juror2372** [comment]
Thanks, let me know if there’s anything I can provide to help.

I’m running iOS 17, beta 3 on an iPad Pro 12,9’ (2021)
Rom is Tetris & Dr Mario for snes (don’t judge :))

**Comment by ethanaobrien** [comment]
@Juror2372 Can you clear your cache and try again? I believe I have fixed this

**Comment by Juror2372** [comment]
Cleared my history (only way I found to delete cache on safari on ipad), even tried a different profile, still each controllers are controlling both players.

**Comment by ethanaobrien** [comment]
Can you test again at [this demo url](https://rawcdn.githack.com/EmulatorJS/EmulatorJS/9e4d52c2907d4bfbd6c75c43c391f78cd8b127df/index.html) (to bypass cache). I fixed a few more things and it should be good now

**Comment by Juror2372** [comment]
YES!!! This works perfectly! Thank you so much!

**Comment by ethanaobrien** [comment]
Good to hear!
