### ISSUE TITLE
N64 Network Error 

### ISSUE THREAD

**Issue by DarkShadow8700** [emulatorjs/emulatorjs#63]
![Screenshot 2021-12-18 2 08 31 PM](https://user-images.githubusercontent.com/96354083/146654370-ca975eb1-81ef-4ae0-a8c4-ec669663b718.png)
)

**Comment by DarkShadow8700** [comment]
Does anyone know how to fix it?

**Comment by ethanaobrien** [comment]
I pushed changes not long ago (2 hours ago). Could you update and tell me if it works?

**Comment by DarkShadow8700** [comment]
Yeah It's working again thank you

**Comment by ethanaobrien** [comment]
No problem

**Comment by megamandev** [comment]
@ethanaobrien 
i have this same problem NETWORK ERROR ON NINTENDO 64, My PC i5, OPENGL v1.0

**Comment by ethanaobrien** [comment]
What version of emulatorjs do you have (load the emulator with a working rom and right click, it will show the version.)
