### ISSUE TITLE
Can't setting joystick controller in playstation

### ISSUE THREAD

**Issue by budi1175** [emulatorjs/emulatorjs#631]
Hi I success upload all file with rom and all work and running well. But there is problem how to set up joystick for Playstation. It doesnt work to for keyboard setting too. It can set by push the button both on joystick push or keyboard push but when you use it in game it doesnt work. Easy sample when you set start button with keyboard by pressing enter yes it set enter but when you press enter to start the game it doesnt work. And same problem problem with joystick you set start button by pressing start button in your joystick yes it listed but when you push start button in joystick there is no respon from the game. My website I installed the script is news7.my.id/game1/we4.html. How to solve this problem please help thank you

**Comment by ethanaobrien** [comment]
This is weird, and seems like a core issue, as no buttons work. Try the other Playstation core (see the docs)

**Comment by budi1175** [comment]
Sorry but can you help me about this problem or still you search solution? why old version work but mine dont work? what different? Can I get old version ver 0.5.13 like on retrogames.cc? Ok I'll comment on closed issue too

**Comment by budi1175** [comment]
My opened issue 
https://github.com/EmulatorJS/EmulatorJS/issues/632 still not find solution
