### ISSUE TITLE
[Bug] Sne9x core breaks the game and erase the data when loading the state

### ISSUE THREAD

**Issue by Norbtails97** [emulatorjs/emulatorjs#634]
Ok i loaded the state and it gave me a blank screen and when I restart it, I lost all of my data.
[Screen recording 2023-08-24 12.15.53 PM.webm](https://github.com/EmulatorJS/EmulatorJS/assets/123211390/2d30d2b4-6dec-4e5e-89ee-b02303288737)

**Comment by ethanaobrien** [comment]
1. Can I get a log?
2. Have you tried any other save states?

Closing until additional information is supplied
