### ISSUE TITLE
Webgl rendering can be used, do not need to activate the page

### ISSUE THREAD

**Issue by kwanboy** [emulatorjs/emulatorjs#636]
At present, through the wasm rendering, need to activate the page to render

**Comment by kwanboy** [comment]
You can refer to https://www.wo1wan.com/

**Comment by ethanaobrien** [comment]
Webgl is used.  Sound is the reason you need to "activate the page"

**Comment by kwanboy** [comment]
canvas.getContext("webgl")、WebAudioContext，use wasm callback Buffer，On the page rendering and play sounds
Suggest using the worker，Better performance

**Comment by ethanaobrien** [comment]
Which is exactly what is done

**Comment by kwanboy** [comment]
http://themaister.net/glslview/ 
RetroArch GLSL shader viewer
web WebGL  shader

**Comment by ethanaobrien** [comment]
Ok...? We use these shaders in this project. Are you looking at the right project. Please look at the demo- https://demo.emulatorjs.org

**Comment by kwanboy** [comment]
I mean, back to buffer by wasm, rendering webgl himself on the page, and sound

**Comment by ethanaobrien** [comment]
That's what is done...
