### ISSUE TITLE
[Bug] Fullscreen Button tooltip position

### ISSUE THREAD

**Issue by zmarteline** [emulatorjs/emulatorjs#638]
Can you fix the fullscreen button tooltip position:

![tooltip](https://github.com/EmulatorJS/EmulatorJS/assets/101960945/89f2817d-2a83-414f-93e9-eb54bf904932)

**Comment by allancoding** [comment]
Yes let me fix this

**Comment by allancoding** [comment]
Should be fixed now.

**Comment by zmarteline** [comment]
Yes, it's perfect now, as usual. Thanks...
