### ISSUE TITLE
Control settings _ Virtual gamepad button position

### ISSUE THREAD

**Issue by zmarteline** [emulatorjs/emulatorjs#639]
Can you please add a little space between Virtual gamepad button and key set buttons?
![space](https://github.com/EmulatorJS/EmulatorJS/assets/101960945/734672b2-132e-4169-be9e-a06011698d06)

Thanks!

**Comment by allancoding** [comment]
Is this on mobile?

**Comment by zmarteline** [comment]
No, this screen is from desktop. But this button is for enable it on mobile devices.

**Comment by allancoding** [comment]
@zmarteline Is this good?
![2023-08-26_17-00](https://github.com/EmulatorJS/EmulatorJS/assets/74841470/1500e9a1-4b10-4266-b7f9-b45c95480bd2)

**Comment by zmarteline** [comment]
Looks great!

**Comment by allancoding** [comment]
Fixed in #641

**Comment by zmarteline** [comment]
Thanks!
