### ISSUE TITLE
Why not use webgl2 to build?

### ISSUE THREAD

**Issue by rexhang** [emulatorjs/emulatorjs#642]
Others' websites use webgl2 for rendering, which has better performance, smoother operation, and lower hardware usage, Also supports high frame rate.

![image](https://github.com/EmulatorJS/EmulatorJS/assets/14832793/7c9bb822-f038-46d7-9cf0-8c1aac66e02d)

And our canvas currently uses webgl to render instead of webgl2.

![image](https://github.com/EmulatorJS/EmulatorJS/assets/14832793/e48f8a53-4318-42bd-aa52-6843dfb2775b)

Here to upgrade the rendering method to webgl2, is it necessary to re-make C language make to wasm files?

Hope to get your reply support.

thanks.

**Comment by ethanaobrien** [comment]
What core are you using? Can you please confirm this is the correct project by loading the game on https://demo.emulatorjs.org

**Comment by rexhang** [comment]
> What core are you using? Can you please confirm this is the correct project by loading the game on https://demo.emulatorjs.org

bios: 'bios/arcade.7z'
game: 'roms/kof97.zip'
core: 'arcade' || 'fbneo'

**Comment by ethanaobrien** [comment]
I doubt using webgl2 would improve anything. (Some 3d cores already use it, because its needed).

>which has better performance, smoother operation, and lower hardware usage

Where are you getting these statistics?

>Also supports high frame rate.

I doubt this. Even then, RetroArch cant truly go higher than 60

**Comment by rexhang** [comment]
> I doubt using webgl2 would improve anything. (Some 3d cores already use it, because its needed).
> 
> > which has better performance, smoother operation, and lower hardware usage
> 
> Where are you getting these statistics?
> 
> > Also supports high frame rate.
> 
> I doubt this. Even then, RetroArch cant truly go higher than 60

webgl2 has been enabled, but the stability needs to be tested.

<img width="1057" alt="eb145b0845c078898682b3fc6ae098c" src="https://github.com/EmulatorJS/EmulatorJS/assets/14832793/a7264867-88be-4694-876e-674732af1198">

**Comment by rexhang** [comment]
> I doubt using webgl2 would improve anything. (Some 3d cores already use it, because its needed).
> 
> > which has better performance, smoother operation, and lower hardware usage
> 
> Where are you getting these statistics?
> 
> > Also supports high frame rate.
> 
> I doubt this. Even then, RetroArch cant truly go higher than 60

Direct use of emulator.js seems to sometimes cause phantoms (I don’t know if the drawing frequency is lost) although the frame number display has been maintained at 60FPS

**Comment by ethanaobrien** [comment]
>webgl2 has been enabled, but the stability needs to be tested.

The issue is both older browsers and even slightly older safari. Webgl2 has no performance increase or decrease on any cores it isnt already enabled in

>Direct use of emulator.js seems to sometimes cause phantoms (I don’t know if the drawing frequency is lost) although the frame number display has been maintained at 60FPS

Correct. We **must** draw at 60fps, regardless of screen fps, to support lower fps screens. This will not change.

**Comment by rexhang** [comment]
> > webgl2 has been enabled, but the stability needs to be tested.
> 
> The issue is both older browsers and even slightly older safari. Webgl2 has no performance increase or decrease on any cores it isnt already enabled in
> 
> > Direct use of emulator.js seems to sometimes cause phantoms (I don’t know if the drawing frequency is lost) although the frame number display has been maintained at 60FPS
> 
> Correct. We **must** draw at 60fps, regardless of screen fps, to support lower fps screens. This will not change.

The shader language of WebGL2 supports the original GLSL 100 of WebGL1, and also supports GLSL 300 es, but if you want to use more advanced features, you must use GLSL 300 es. If you need to support more shaders in the future, you still need to change to webgl2.0 I hope you can modify the code

**Comment by ethanaobrien** [comment]
>The shader language of WebGL2 supports the original GLSL 100 of WebGL1, and also supports GLSL 300 es, but if you want to use more advanced features, you must use GLSL 300 es

We dont need these advanced features... Theres nothing to do with them. None of the cores compiled without webgl2 support gles3.

>If you need to support more shaders in the future, you still need to change to webgl2.0 I hope you can modify the code

Its a matter of changing one line, but we dont really need more shaders nor is it worth it to cut of support for thousands of people for a few shaders.

**Comment by rexhang** [comment]
> 



> > webgl2 has been enabled, but the stability needs to be tested.
> 
> The issue is both older browsers and even slightly older safari. Webgl2 has no performance increase or decrease on any cores it isnt already enabled in
> 
> > Direct use of emulator.js seems to sometimes cause phantoms (I don’t know if the drawing frequency is lost) although the frame number display has been maintained at 60FPS
> 
> Correct. We **must** draw at 60fps, regardless of screen fps, to support lower fps screens. This will not change.

We can use requestAnimationFrame (this can be dynamically adjusted on the browser side according to the hardware screen refresh rate) or dynamically update the drawing time of each frame by setting the project. I don’t know if this is possible.

**Comment by ethanaobrien** [comment]
>We can use requestAnimationFrame

We cant, this will break game speed on lower end devices
