### ISSUE TITLE
[Bug] Problem running psp rom (Console error: SharedArrayBuffer is not defined)

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#644]
Hi,

I've tried to run a psp rom, after loading 99% of the file, this error message appeared on console:
5d79739d-5633-40e1-b11d-c5955121cfce:393 Uncaught ReferenceError: SharedArrayBuffer is not defined

![shared_buffer](https://github.com/EmulatorJS/EmulatorJS/assets/10597517/e0964d17-4f88-44cf-9fd2-67592ce99a5a)

**Comment by ethanaobrien** [comment]
https://emulatorjs.org/docs/FAQ.html#q-i-m-seeing-an-error-that-says-sharedarraybuffer-is-not-defined-how-do-i-fix-this
