### ISSUE TITLE
Is there no method to set the aspect ratio in fbneo_libretro.wasm?

### ISSUE THREAD

**Issue by rexhang** [emulatorjs/emulatorjs#648]
### I would like to know if the game core provides options for rendering ratio or filling the width and height of the canvas container?

![image](https://github.com/EmulatorJS/EmulatorJS/assets/14832793/6c8b6b04-01d6-4620-bd2b-dbf160d6d83a)

As shown in the figure above, the width and height of the canvas are set to 200:120, but the rendered game screen is only 4:3, and the canvas container is not covered. Does the core provide a method to change the rendering ratio?

![image](https://github.com/EmulatorJS/EmulatorJS/assets/14832793/da601733-3e6a-4155-8cb7-6772481a0a8b)

I did not find the corresponding method in the Module object

I hope you can give me an answer, thank you very much.

**Comment by ethanaobrien** [comment]
(Can you confirm this is this project by going to https://demo.emulatorjs.org and confirming it looks the same)

If there is an option in the settings menu, then yes. If not, then no.

**Comment by rexhang** [comment]
> (Can you confirm this is this project by going to https://demo.emulatorjs.org and confirming it looks the same)
> 
> If there is an option in the settings menu, then yes. If not, then no.

The demo page does not yet support arcade platform games

**Comment by ethanaobrien** [comment]
Oh yeah. Can you load some other console and make sure it just looks the same, same right click menu/ buttons at the bottom

**Comment by rexhang** [comment]
![image](https://github.com/EmulatorJS/EmulatorJS/assets/14832793/bd176266-fc20-4a1f-9e12-33d5cad82b28)

This is probably the case. As shown in the above picture, the canvas is not fully used, and there is still a blank area in the non-game content display area. I filled it with red. So my question is, can the emulator game completely fill the canvas and fill the canvas container. Until I can’t see the red color, is there such a method provided? I see that the call stack information has no place to pass in the rendering scale information

**Comment by ethanaobrien** [comment]
Why is the element style height set to 220px

**Comment by rexhang** [comment]
> Why is the element style height set to 220px

I hope it can be rendered in the canvas of the width and height I specified, such as a 1600x900 canvas, and the game screen will fill the 1600x900, instead of maintaining a 4:3 display in this 100x900 canvas, which will leave black margins.

**Comment by ethanaobrien** [comment]
![264326835-bd176266-fc20-4a1f-9e12-33d5cad82b28.png](https://github.com/EmulatorJS/EmulatorJS/assets/77750390/9b01444f-d7ee-452f-988a-8fa0ca8387fe)

**Comment by rexhang** [comment]
<img width="1280" alt="image" src="https://github.com/EmulatorJS/EmulatorJS/assets/14832793/a874d800-896e-4850-a1d1-cbe7264f8135">

Look at this picture, without any modification, the game screen does not fill the entire screen, can it fill the entire screen? what should I do

**Comment by ethanaobrien** [comment]
The settings button, click the settings button. If it is available there will be an option to change the screen size. Otherwise no

**Comment by rexhang** [comment]
However, there is only one full-screen option. After full-screen, the game is still centered in a 4:3 ratio. Full-screen does not mean covering the screen. If you want to achieve unequal proportions covering the screen, this is a bit similar to the setting of stretching the desktop wallpaper of the Windows system to full screen. Certainly

**Comment by rexhang** [comment]
> The settings button, click the settings button. If it is available there will be an option to change the screen size. Otherwise no

What I want to know is, doesn't the core provide an option to set the rendering area

**Comment by ethanaobrien** [comment]
No. 

https://docs.libretro.com/library/fbneo/

**Comment by rexhang** [comment]
> 

ok, thanks.
