### ISSUE TITLE
hey can i hire you to fix thing in my host

### ISSUE THREAD

**Issue by hadoizz** [emulatorjs/emulatorjs#66]
hey can i hire someone to install this script in my host please contact me hadoidxb@gmail.com

i really dont understand i just unzip it in my host and its keep downloading emulator.js

**Comment by allancoding** [comment]
Are you trying to play a rom? Do you have your rom file?

**Comment by hadoizz** [comment]
i am trying to fix the script to add in my host sever everything fine but i want to fix more things like safari controller its kind of in middle of the game is there a chance to put the controller down ?

**Comment by allancoding** [comment]
Yes I can help you, what kind of server is it? Are you using the server for chrome of a terminal like apache? And what do you mean by safari controller?

**Comment by allancoding** [comment]
Can you explain what you are trying to do. Are you making for mobile or desktop?

**Comment by hadoizz** [comment]
i am making it for mobile i have checked your html verison and the controller is cool same as i wanted but need to be fixed since the page show as lose when u try to click sometimes its zoom can we contact somwhere please?

**Comment by hadoizz** [comment]
i am using cpanel

**Comment by ethanaobrien** [comment]
@hadoizz You can use https://emulatorjs.netlify.app/codehelper to help you create what you need
