### ISSUE TITLE
(request core) Wii and GameCube

### ISSUE THREAD

**Issue by jacojanze** [emulatorjs/emulatorjs#660]
Is there going to be a Wii core and a GameCube core in the future? 

Thanks!

**Comment by ethanaobrien** [comment]
Nowhere in the near future.

I recently tried making a PSP core, because that was more likely to work compared to wii/gamecube, and (when it decides to work) it runs  at like 20fps, on high end devices.

So not at the moment, sorry. No wii and gamecube cores are planned

**Comment by jacojanze** [comment]
ok
