### ISSUE TITLE
Add VB core 3d color preset

### ISSUE THREAD

**Issue by Norbtails97** [emulatorjs/emulatorjs#662]
I can do anaglyph but i can't do color preset so I use my 3d glasses for it.

**Comment by ethanaobrien** [comment]
If it's in RetroArch, it's in emulatorjs. If its not in RetroArch, its not in EmulatorJS.

**Comment by Norbtails97** [comment]
one opsion you forgot to add  is the 3d color preset that give you to make it red/blue, red/cyan, etc.

**Comment by Norbtails97** [comment]
hint: there two different color opsion types

**Comment by ethanaobrien** [comment]
I didn't forget to add anything. All the settings are pulled directly from RetroArch

**Comment by Norbtails97** [comment]
check this
![Screenshot 2023-09-07 11 35 33 AM](https://github.com/EmulatorJS/EmulatorJS/assets/123211390/2d559aba-23b3-475d-aca1-d65743d5ca3e)

**Comment by ethanaobrien** [comment]
That doesn't look like this project

**Comment by Norbtails97** [comment]
this is what emulattor js is compare the first and the second image
![Screenshot 2023-09-07 11 36 45 AM](https://github.com/EmulatorJS/EmulatorJS/assets/123211390/1aaaefb7-628c-4f26-a033-483f32a3b1d7)

**Comment by ethanaobrien** [comment]
All settings are pulled directly from RetroArch - https://github.com/EmulatorJS/RetroArch/blob/f111451b5b9a126a1759c87bfdaf727be737a820/runloop.c#L8296

**Comment by Norbtails97** [comment]
doesn't have red and blue, etc. on color mode then
