### ISSUE TITLE
[Bug] blank screen after you update

### ISSUE THREAD

**Issue by Norbtails97** [emulatorjs/emulatorjs#666]
not loading game
![image](https://github.com/EmulatorJS/EmulatorJS/assets/123211390/db302978-b0e9-4477-97d3-1274590b5af5)

**Comment by ethanaobrien** [comment]
Logs? Core? System? Browser? OS?

**Comment by Norbtails97** [comment]
y? it was working yesterday it just you update the "data" folder and every time I load a ROM, it does not load.
Google Chrome: Version 116.0.5845.168 (Official Build)  (32-bit)
Platform: 15509.72.0 (Official Build) stable-channel jacuzzi
Channel: stable-channel
Firmware Version: Google_Burnet.12573.342.0
ARC Enabled: false
ARC: 10634276
Enterprise Enrolled: true
Developer Mode: false

**Comment by ethanaobrien** [comment]
>y? it was working yesterday it just you update the "data" folder and every time I load a ROM, it does not load.

Because logs tell me what's wrong

>Enterprise Enrolled: true

With no additional information, my conclusion is because your admin is blocking something

**Comment by allancoding** [comment]
This was just fixed[ in this commit](https://github.com/EmulatorJS/EmulatorJS/commit/e151a9b1d5ef224eb01f694f74a88d1e1c26e2f8)
Sorry

**Comment by Norbtails97** [comment]
tanx for helping allacoding

**Comment by allancoding** [comment]
The website takes a minute for it to update

**Comment by Norbtails97** [comment]
still not working.

**Comment by allancoding** [comment]
clear the website cache

**Comment by Norbtails97** [comment]
works thank u
