### ISSUE TITLE
v3.xx mame core 6 console error

### ISSUE THREAD

**Issue by discordfar** [emulatorjs/emulatorjs#673]
today i tested mame core 6 but console say this error

![mame core 6 bug](https://github.com/EmulatorJS/EmulatorJS/assets/142048925/2aa753d8-381f-4849-8ea3-3dcf4f50657a)

any can help to solve this, i try searching solutions but not sucess

bests

**Comment by ethanaobrien** [comment]
https://emulatorjs.org/docs/FAQ.html#q-i-m-seeing-an-error-that-says-sharedarraybuffer-is-not-defined-how-do-i-fix-this

**Comment by discordfar** [comment]
@ethanaobrien

thank you for help men, but this method not work more, maybe browsers disable this function
i put this code on server and say same error.
have one local specific for insert this codes?
bests men

**Comment by ethanaobrien** [comment]
Can you not use version 4.0? (mame2003 core, should work)

anyways, if you must use 3.0, open the console, go to the networking tab, find the first request the page made when reloaded, and send a screenshot of the headers

**Comment by discordfar** [comment]
@ethanaobrien

response headers

![log rede](https://github.com/EmulatorJS/EmulatorJS/assets/142048925/1e9ba21d-d77b-4e1d-9373-2c1e457eed52)

**Comment by ethanaobrien** [comment]
The following headers need to be set
```
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
```

**Comment by discordfar** [comment]
@ethanaobrien

please men
how do i set it correctly, i use nginx

**Comment by ethanaobrien** [comment]
I dont know, refer to the nginx documentation on how to set custom response headers

**Comment by discordfar** [comment]
@ethanaobrien

apache you know ?

**Comment by ethanaobrien** [comment]
nope, I dont know how. Id say refer to the apache documentation on setting custom response headers

**Comment by discordfar** [comment]
@ethanaobrien

Do you know somewhere where I can insert the code?

**Comment by ethanaobrien** [comment]
https://httpd.apache.org/docs/current/mod/mod_headers.html
