### ISSUE TITLE
Legacy opengl support?

### ISSUE THREAD

**Issue by discordfar** [emulatorjs/emulatorjs#678]
@ethanaobrien

Demo Emulator v4, N64 not work Why?
mario 64 failed to start game.
i need update to v4, but n64 work or no?
Bests brothers

**Comment by ethanaobrien** [comment]
Logs? Operating system? Device? Did you try the other Nintendo 64 core?

Closing until additional information is given

**Comment by discordfar** [comment]
@ethanaobrien

say mensage failed to start game, and i print log

![n64 v4 failed to start](https://github.com/EmulatorJS/EmulatorJS/assets/142048925/50275b9d-e8da-46ac-af0c-45880d88a6c0)

**Comment by ethanaobrien** [comment]
The entire log

**Comment by discordfar** [comment]
@ethanaobrien

ok, entire logo

![entire log n64](https://github.com/EmulatorJS/EmulatorJS/assets/142048925/d1b4915e-0291-4aa7-abf3-a17413e4c8b7)

**Comment by ethanaobrien** [comment]
With EJS_DEBUG_XX enabled

**Comment by discordfar** [comment]
yes debug enable

**Comment by ethanaobrien** [comment]
If debug was enabled I wouldn't have asked for it to be enabled

**Comment by discordfar** [comment]
i tested with debug true and without debug and same error in n64 core
default n64 core
mupen64plus_next
core "n64"

**Comment by discordfar** [comment]
@ethanaobrien

i try in other pc with same windows 10 and work n64
but in my pc say this error in emulator.min.js

other pc opengl v2
my pc opengl v1

maybe cause error with opengl v1 or no ?

**Comment by ethanaobrien** [comment]
I need a full log of the console, with EJS_DEBUG_XX set to true. If I do not have this log, nothing will happen

**Comment by discordfar** [comment]
@ethanaobrien

full log pc win 10 opengl v1

in log say gl version 1.4 bad match

click image link 2x for view better img

![full log pc win 10 opengl v1](https://github.com/EmulatorJS/EmulatorJS/assets/142048925/bccbe086-4743-42a9-95d9-55769cdf29e8)

**Comment by ethanaobrien** [comment]
Try using the `parallel_n64` core

**Comment by discordfar** [comment]
@ethanaobrien 

same error, with other n64 core

same error too with PS1

other consoles work

**Comment by ethanaobrien** [comment]
Check for Google Chrome updates and for any graphics card updates.

**Comment by discordfar** [comment]
@ethanaobrien

browser updated and video is old only support opengl v1,
emulator v3 work all
emulator v4 not work n64 and ps1

**Comment by ethanaobrien** [comment]
I'll see if anything can be done. This is not likely to be fixed

**Comment by discordfar** [comment]
@ethanaobrien

I'm willing to help, in the v3 emulator when I use the new cores it gives me the same error as in the v4 emulator.
but when I use the old cores everything works fine

It is very likely that the new cores of n64 and ps1 are incompatible with opengl v1, because the other consoles work

**Comment by ethanaobrien** [comment]
Would you mind sending me a screenshot of the "Network" tab in the console on v3 with the old cores enabled? (Open the console before the game is loaded, then load the game and take the screenshot)

**Comment by discordfar** [comment]
@ethanaobrien

emulator v3 old cores true

network

![network emu v3 old](https://github.com/EmulatorJS/EmulatorJS/assets/142048925/ba53e213-121b-43c7-a67a-44f34442a0ca)

console the log is very very big i send in txt format

[console emulator v3 n64 old.txt](https://github.com/EmulatorJS/EmulatorJS/files/12717523/console.emulator.v3.n64.old.txt)

**Comment by ethanaobrien** [comment]
Thank you. I will see if I can do anything about this

**Comment by discordfar** [comment]
@ethanaobrien

Detected problem: "intel HD Graphics and windows 10"

"Intel HD Graphics" is not compatible with Windows 10, with the updated driver is giving this error
With the cores of Nintendo 64 and PlayStation.
I removed the driver and installed an earlier version.
The Nintendo 64 and PlayStation started to work, however very slow.
Already with updated driver does not work N64 and PS1 but the other consoles work without lag.

**Comment by discordfar** [comment]
@ethanaobrien

emulatorjs original same error with mupen64plus
but today this error fixed, release mupenplus2 for emulatorjs original

**Comment by discordfar** [comment]
@ethanaobrien

I played on a website with the original emulatorjs version 0.5
same error on n64 and psx core
but yesterday this error was corrected
I can play n64 and psx

I saw that core changed to mupen64plus2 but that's not all
the script in emulator.js was certainly changed

**Comment by discordfar** [comment]
@ethanaobrien

segacd core genesis_plus_gx error incompatible with opengl v1, same n64 error, failed to start

**Comment by shaylevary** [comment]
@discordfar can you please tell me how do I set an opengl v1 core for psx/n64? Do I need to recompile each core to make it work?
Or can you send me your opengl cores for tests?

**Comment by ethanaobrien** [comment]
You don't. The cores don't support gles2 (opengl 1)

This is going to take quite a bit of time and effort on my part

**Comment by ethanaobrien** [comment]
>segacd core genesis_plus_gx error incompatible with opengl v1, same n64 error, failed to start

`genesis_plus_gx` doesn't use gles3... if it doesn't work then I cannot possibly make it work.

**Comment by discordfar** [comment]
@ethanaobrien 

OpenGL comes with the motherboard or video card and cannot be updated to the latest version. Just buy a latest generation video card and you will have opengl updated, if I'm not mistaken, it's already on version 4

The only way to test OpenGL V1 is to have a motherboard or video card with OpenGL V1, in this case an old computer like mine between 2009 and 2013. My 2011 Intel i5 computer with OpenGL V1 on the motherboard.

The cores that work with opengl v1 are the cores from version 3 of the emulator, if you want I can send them to you

**Comment by ethanaobrien** [comment]
I already have the cores, and I'm aware on how opengl works.

To be able to add "legacy" n64 support, I'm going to need to use an outdated version of the emulator


Adding opengl 1 support is not as easy as it may seem

**Comment by discordfar** [comment]
@ethanaobrien

To do the tests you need a computer with OpenGL v1, I'm here to help you

**Comment by ethanaobrien** [comment]
Alright, thanks

**Comment by discordfar** [comment]
i found possible solution for this opengl v1 error
if you have time i send

**Comment by ethanaobrien** [comment]
sure

**Comment by discordfar** [comment]
log error

[INFO] [Video]: Set video size to: 1440x1080.
emulator.js:1036 [INFO] [Video]: Using HW render, OpenGL driver forced.
emulator.js:1036 [INFO] [Video]: Using configured "gl" driver for GL HW render.
emulator.js:1036 [INFO] [EGL] Falling back to eglGetDisplay
emulator.js:1036 [INFO] [EGL]: EGL version: 1.4
emulator.js:1036 [ERROR] [EGL]: #0x3009, EGL_BAD_MATCH
emulator.js:1036 [INFO] [GL]: Found GL context: "null".
emulator.js:1036 [INFO] [GL]: Detecting screen resolution: 320x240.

possible solution

https://stackoverflow.com/questions/33006774/how-to-fix-the-0x3009-egl-bad-match-issue-while-invoking-eglcreatepbuffersurfa

**Comment by ethanaobrien** [comment]
The issue is your gpu doesnt support gles3, not the way the context is being created

**Comment by discordfar** [comment]
I understood

**Comment by discordfar** [comment]
There are two versions of mupen64plus

Mupen64Plus-Next GLES2
Mupen64Plus-Next GLES3

info: https://github.com/libretro/libretro-super/blob/master/dist/info/mupen64plus_next_gles2_libretro.info

**Comment by ethanaobrien** [comment]
I am aware, and have already mentioned the solution I have. Please be patient

**Comment by discordfar** [comment]
I'm not appreciating you, just trying to be helpful
see the link with the list of cores: https://docs.libretro.com/meta/core-list/
There's even a neocd and dreamcast that I made a request for

bests man.

**Comment by ethanaobrien** [comment]
A legacy n64 core has been added.
