### ISSUE TITLE
[Bug] Network error when loading rom in Chrome/iPhone on iOS17

### ISSUE THREAD

**Issue by alberto666** [emulatorjs/emulatorjs#679]
I can't get log without having a mac, but in Safari on iOS 17 the emulator (all systems) runs without problem. The problem only is in Chrome. In Chrome on iOS 16 there was no problem.

**Comment by ethanaobrien** [comment]
This sounds like a google chrome issue. Let me explain:

On iOS 16 down, every browser (chrome, firefox) were all just an apple webkit wrapper (safari). iOS 17 unlocked other browsers to be able to use their own web engine, and Chrome did this. This is likely some sort of chrome bug, but I could be wrong

Assuming I am correct about ios17 having added this feature, could you see if you can debug from windows chrome?

**Comment by alberto666** [comment]
Through Windows it is not possible to debug on iOS, I am going to look for a Mac and comment on what I have seen in the console log.Thank you very much.

**Comment by S-Coding23** [comment]
@alberto666 
I have an iPhone 13 that I just updated to 17.0.1 and installed Chrome. Everything is working for me still. Want to share your source code?

**Comment by alberto666** [comment]
To avoid implementation problems, I have been testing from the demo page: https://demo.emulatorjs.org 

Now it works randomly for me both with my code and in the demo.

I don't know if there has been any automatic Chrome update. When it fails, it tells me network error. 

What I do see from Chrome and not from Safari is that, when it works, I have to click twice on the menu icon. Until the menu is opened and closed, the screen remains black. This does not happen in Safari.

**Comment by alberto666** [comment]
I close the issue because I think it must be a problem in my Chrome for iOS profile. In my profile, just reinstalled Chrome, it works the first few times, but ends up not working, also in incognito mode.
With a new profile, this does not happen. I thought these things only happened in desktop browsers.
