### ISSUE TITLE
[Question] v3 old and new cores

### ISSUE THREAD

**Issue by discordfar** [emulatorjs/emulatorjs#681]
@ethanaobrien

It is possible to use at the same time, old and new cores? 
example: snes with old core and n64 with new core
i need use different cores
you have any code for this?

**Comment by allancoding** [comment]
You could just use the older version of the project just on the page your using.

**Comment by discordfar** [comment]
if i set oldcores true the system limit to run only oldcores
possible use newcores with oldcores true ?

**Comment by ethanaobrien** [comment]
No. Old cores are not supported. If you use them you're on your own
