### ISSUE TITLE
Keyboard key W causing problems with A/B inputs

### ISSUE THREAD

**Issue by CycloKid** [emulatorjs/emulatorjs#682]
When holding the W KEY on a keyboard, pressing any other keys mapped to the A/B buttons/input to do C-Pad Down & C-Pad Left.

W + (A) = C-Pad Down
W + (B) = C-Pad Left

**Comment by ethanaobrien** [comment]
@allancoding

**Comment by CycloKid** [comment]
For clarification, V3 doesnt do this, this behavior seems to have appeared from V4.

**Comment by ethanaobrien** [comment]
@CycloKid Does the issue occur on this demo:

https://raw.githack.com/EmulatorJS/EmulatorJS/c1999074511e87bef046745cb1764fa3ff2817ae/index.html

**Comment by allancoding** [comment]
What core are you using? n64?

**Comment by CycloKid** [comment]
> What core are you using? n64?

Yes, I am using the N64 core.

> @CycloKid Does the issue occur on this demo:
> 
> https://raw.githack.com/EmulatorJS/EmulatorJS/c1999074511e87bef046745cb1764fa3ff2817ae/index.html

Just realized that it wasnt the input at all. I think its an issue with setting controls. If I attempt to set the "Stick" controls to WASD, and A&B to K&L, it causes this.
If it makes it easier, I double-checked this problem with the controls with [this rom](https://github.com/Ryzee119/n64_controller_test/releases/download/build-202008190836/main.z64)

**Comment by allancoding** [comment]
Looks like the controls are overlapping

**Comment by CycloKid** [comment]
If you need any extra info about my browser, OS, etc., ill be glad to provide if needed.

**Comment by allancoding** [comment]
I think I found the issue.
Would you mind testing here: https://allancoding-emulatorjs.netlify.app/

**Comment by CycloKid** [comment]
Super sorry for the late reply, but ive been playing games on the n64 core and the controls seem to work perfectly now!
