### ISSUE TITLE
[Bug] n64 C-Buttons not work on USB gamepad

### ISSUE THREAD

**Issue by discordfar** [emulatorjs/emulatorjs#685]
with keyboard all work nice
with usb gamepad:
cross and analog not remap
c-buttons not work

![n64 cross-analog-c buttons bug](https://github.com/EmulatorJS/EmulatorJS/assets/142048925/5eafc958-82fd-4b85-b517-4a5ea9fa71cc)

**Comment by ethanaobrien** [comment]
This is a limitation of 3.0, update to 4.0 for this ability

**Comment by discordfar** [comment]
@ethanaobrien

right,

very thank you and cheers men

**Comment by JScripto** [comment]
With GoldenEye 007 when the C-PAD Down is paired with Right Stick down (RIGHT_STICK_Y:+1) it functions as C-Stick up. So basically whether I move the Right Stick Up or the Right Stick Down, it looks up. Also, I wanted to switch Left Stick Right/Left with Right Stick Right/Left and it doesn't pair at all. I'm using v4.0.8. Same results with both mupen64plus_next & parallel_n64.

![goldeneye](https://github.com/EmulatorJS/EmulatorJS/assets/150749376/7c5495c0-a615-4737-9923-8a029963689f)
