### ISSUE TITLE
[enhancement] Change Start Button Text

### ISSUE THREAD

**Issue by S-Coding23** [emulatorjs/emulatorjs#686]
Similar to EJS_alignStartButton, would it be possible to have something like EJS_StartButtonName so that we can change the start button from "Start Game" to a variable of the actual Game Name? Example: "Start Mario Kart".
 Im currently using startOnLoaded so that I can have my own Start button that does this, but since startOnLoaded requires some interaction from the user's part anyway, its not really starting on load.

**Comment by S-Coding23** [comment]
You can close this. With the EJS_onGameLoad workaround, I'm back to not using the built-in start game button.

**Comment by ethanaobrien** [comment]
Eh, I think we should keep it open. Having a custom title like "start mario kart" sounds nice and would take about 5 minutes of effort to do
