### ISSUE TITLE
Nintendo DS emulation lag

### ISSUE THREAD

**Issue by RandomUser423423** [emulatorjs/emulatorjs#687]
On multiple computers, the lag on DS games have made them run at anywhere from 0-20 fps, making the games unplayable as well as making the audio crackling sounding.

**Comment by ethanaobrien** [comment]
Send console log.

What ds core?

**Comment by RandomUser423423** [comment]
MelonDS.

**Comment by ethanaobrien** [comment]
Send console log.

**Comment by RandomUser423423** [comment]
Where do you find that

**Comment by ethanaobrien** [comment]
To collect a log of the console.
1. Add the following line to your code
```
EJS_DEBUG_XX = true;
```
2. Right click and click `inspect`.
3. Select the `console` tab at the top.
4. then reload the broken page.
5. Right click on the console and click `Save as...`
6. Upload it to your issue.

**Comment by ethanaobrien** [comment]
1. I can't do anything without a console log
2. Try another ds core
3. This is likely your computer being too slow
