### ISSUE TITLE
[Arcade] FBneo only support .zip files

### ISSUE THREAD

**Issue by discordfar** [emulatorjs/emulatorjs#689]
old emulator v3 arcade core support .zip and .7z
all my file in .7z because .7z reduces file sizes much more

I'm solving it by changing to .zip

appear this error

![fbneo only zip](https://github.com/EmulatorJS/EmulatorJS/assets/142048925/d3ff19da-dd6d-4d1c-9d8e-93793a3be8e4)

**Comment by ethanaobrien** [comment]
>7zip files are not supported for your platform
