### ISSUE TITLE
Netplay is broken between some devices

### ISSUE THREAD

**Issue by imneckro** [emulatorjs/emulatorjs#69]
Anyone tried Netplay through a mobile device?
Apparently it doesn't work..

**Comment by ethanaobrien** [comment]
What do you mean "it doesnt work"

This provides no detail. Please explain. What doesnt work. Is it giving you an error, is there no netplay button?

**Comment by imneckro** [comment]
Hitting join closes the modal as if connected but It doesn't connect at all. It doesn't output any error.
Try from your phone to connect to your pc's hosted game and you will understand.

**Comment by ethanaobrien** [comment]
>Try from your phone to connect to your pc's hosted game and you will understand.

I cant do this, I dont need to explain why I just cant.

Could you upload a screen recording

**Comment by imneckro** [comment]
There is nothing to record. Hitting join from phone displays loading as if it will connect, then modal goes away and nothing happens.

**Comment by ethanaobrien** [comment]
@imneckro
>There is nothing to record. Hitting join from phone displays loading as if it will connect, then modal goes away and nothing happens.

Its really hard to fix a bug I cant reproduce. I've used android emulators and it seems to work fine.

You aren't using my beta [emuserver](https://github.com/ethanaobrien/emuserver) are you? It currently doesn't work at all yet.

**Comment by imneckro** [comment]
@ethanaobrien through emulators problem doesnt exist. through real  android or ios devices exists.

**Comment by ethanaobrien** [comment]
Can you give me some sort of data that I can use to fix this?

**Comment by imneckro** [comment]
@ethanaobrien i cannot debug log ios or android phones. certanly needs someone more experienced than me.

**Comment by ethanaobrien** [comment]
@imneckro I just tested it using an android phone. Netplay connected and worked fine. Can you try again? If you could, could you use my netplay server (mentioned in the readme)

**Comment by imneckro** [comment]
@ethanaobrien shall we chat on discord so we can arange an online test?

**Comment by ethanaobrien** [comment]
I'm not going to be able to do that

**Comment by ethanaobrien** [comment]
@imneckro Could you simply try again?

**Comment by imneckro** [comment]
@ethanaobrien same result also with android emulator (bluestacks).
Only pc vs pc netplay works

**Comment by ethanaobrien** [comment]
I tested and got it working. Can you try updating the `data/` directory and try using [this](https://github.com/ethanaobrien/emuserver/releases) server

**Comment by imneckro** [comment]
npm i and then npm run start
✔ Checking your system
✔ Locating Application
✔ Preparing native dependencies
✔ Launching Application
and then nothing..

**Comment by ethanaobrien** [comment]
Can you download the pre-packaged application from under the releases tab?

**Comment by imneckro** [comment]
prepackaged is for windows only?

**Comment by imneckro** [comment]
@ethanaobrien can you try on my website?

**Comment by ethanaobrien** [comment]
I can if you send it to me

**Comment by imneckro** [comment]
https://retrothess.ddns.net/
credentials user01///user01

**Comment by imneckro** [comment]
@ethanaobrien 
https://retrothess.ddns.net/
credentials user01///user01

**Comment by ethanaobrien** [comment]
Thank you, Ill test when I get the chance

**Comment by imneckro** [comment]
@ethanaobrien  thanks.. you got it probably on your email so im deleting comment with credentials

**Comment by ethanaobrien** [comment]
Cool, just letting you know it may be a while before I can check it out.
I've been really busy

**Comment by ethanaobrien** [comment]
I have come to this conclusion.

Some devices dont support the netplay streams used. This may be the computer or the phone but it could be either. I can't do anything to fix this at the moment

**Comment by allancoding** [comment]
It is with the servers websockets. So try to start it on the phone and then join from computer. Because if you start it on a computer the phone can't process a desktop environment but a computer can process a phone's environment with websockets.

**Comment by imneckro** [comment]
@allancoding i have tried all posibilities including vise versa host/join game with no success. Netplay succesfully achieved only between pc.

**Comment by Ramaerel** [comment]
As an addition to this, I used to have this issue too but PC to Mobile works now. However, joining a server hosted on mobile no longer shows up anywhere, making Mobile to PC and Mobile to Mobile impossible. I can try to get logs or help with debugging where needed

**Comment by ethanaobrien** [comment]
Im not sure at all. It seems to be completely random from my point of view. Ive looked and done some debugging and I truly dont know what might be wrong.

I use PC to mobile all the time - it works for me and mobile to pc works for me too. it just doesnt seem to work between all devices and Im not sure why. You can try to look at this but I really have no clue whats wrong

**Comment by allancoding** [comment]
I found out a possible problem. What browsers where you using on mobile. Because chrome and Firefox are the only ones with the websocket connections of the type we used with nodejs.

**Comment by imneckro** [comment]
@allancoding i tried safari and chrome on iOS device. Also tried chrome and native browser on blue stacks android emulated device.

**Comment by Ramaerel** [comment]
I too have tried most browser combos both on my phone (android) and on pc. I'll try with Firefox though

**Comment by ethanaobrien** [comment]
I plan to strip out netplay for the moment. It’s causing bugs even unrelated to netplay. I will eventually build from the ground up but for the moment I’m discontinuing netplay

**Comment by ethanaobrien** [comment]
I have stripped out netplay, at least for the moment
