### ISSUE TITLE
[Bug] USB gamepad 3DO

### ISSUE THREAD

**Issue by discordfar** [emulatorjs/emulatorjs#690]
USB gamepad 3DO

i remap B button to X button in my usb joystick

and B button have 2 function: B and Start

see in the image i press X in my usb joystick and character strikes and pause at the same time

![3do control bug](https://github.com/EmulatorJS/EmulatorJS/assets/142048925/201c53b2-5579-4041-9ae6-d87aae5cd64e)

![3do control bug_](https://github.com/EmulatorJS/EmulatorJS/assets/142048925/4f497ecc-ac3b-4bdc-9bef-ff61a22b2c2b)

**Comment by ethanaobrien** [comment]
This should be fixed
