### ISSUE TITLE
[Enhancement] Start Button

### ISSUE THREAD

**Issue by discordfar** [emulatorjs/emulatorjs#696]
is possible add more commads?

EJS_startButtonColor

for change start button color

EJS_startButtonNameColor

for change name color

Start Button custom is nice
bests and ty all

**Comment by ethanaobrien** [comment]
This is not something that is going to be done. Custom color for one button is going to lead for custom color for every button, and that's wayyyy too many ejs variables.

I recommend you just edit the css files if you want this (or use the EJS_color option)

**Comment by michael-j-green** [comment]
CSS is definitely the best solution to this (since we're playing in a browser).

I don't know if it's done already - but would it be possible for some quick and dirty docs around this? For example element class names, id's, etc so that they can be targeted with CSS?

**Comment by ethanaobrien** [comment]
That's probably a good idea, documenting element css classes and the EJS_emulator "api"

Maybe open an issue in the docs repo?

**Comment by michael-j-green** [comment]
I'll leave that as an exercise for OP. I'm more than happy with the design and layout :D

**Comment by discordfar** [comment]
ty all

start button in css file

i founf variable for change text color
but not found variable for change button color

**Comment by allancoding** [comment]
The `background_color` will be the color of the button. The normal css attribute `color` is the text color of the button.

**Comment by discordfar** [comment]
@allancoding

thank you
ty all
