### ISSUE TITLE
Adverts

### ISSUE THREAD

**Issue by Scoffins** [EmulatorJS/EmulatorJS#7]
How would one add their own adverts into this? The same way EmulatorJS.com did it.

**Comment by Scoffins** [comment]
I did it my own way. Wrap the whole thing in a DIV with relative position then overlay a centered div with absolute position and a 50% transform with an X that has onclick remove tied to the parent DIV. ten stick your adsense in there and away ya go.

Still, if there's a more elegant in-house way of doing this, I'd like to know. My method is a little hacky and really quite generic so can be used for anything you want ads to be displayed over.

**Comment by Scoffins** [comment]
Ended up writing my own script which overlays a div in the center of the emulator container until the user closes it.

**Comment by ethanaobrien** [comment]
Cool, this is basically what emulatorjs does. When I get time to update it. I will create a branch that has you just put the URL to the ad.html

**Comment by Scoffins** [comment]
Okay that'd be great :)
IMO you've got a very good project going here, there's not much else to compare. It's simple, elegant and just works without any hassle. I really hope all the legalities are covered because I want to see this project succeed long-term. I believe it's a valuable set of tools which will prove very useful for developers in the future. Don't let it go stale, keep up with it :) I also think it might be worth uploading the unobfuscated code. There are many online tools to help here, the best I've found is this one: https://codeamaze.com/code-beautifier/javascript-deobfuscator

Thank you for all your work, it's very much appreciated!

**Comment by Scoffins** [comment]
> Ended up writing my own script which overlays a div in the center of the emulator container until the user closes it.

```
<div style="width:640px;height:480px;max-width:100%;margin:0 auto;position:relative;">
    
<div style="width:300px;height:300px;position:absolute;top:50%;left:50%;transform:translate(-50%, -50%);background:#FFFFFF;z-index:999;" id="gameadvert">
<a onclick="document.getElementById('gameadvert').remove();" style="float:right;font-size:18px;font-weight:bold;cursor:pointer;padding:5px;" title="Close Advert">❌</a>
<!-- INSERT AD CODE HERE !-->
</div>

<div id="game"></div>
</div>
```

**Comment by ethanaobrien** [comment]
Thank you! This is a project I like working on. And as for legalities, on the emulatorjs website, I've looked and looked and found absolutely no terms of service. I would upload a unobfuscated version of the code but when I run it through that it just comes through scrambled and the client can't run it. I do use unobfuscaters to decrypt enough of the code to know what I'm working for. Thank you for your encouragement in working on this project!

**Comment by ethanaobrien** [comment]
@Scoffins 

I unobfuscated the `emulator.js` file. It is now human readable and human editable!

**Comment by xxxnewbiexxx** [comment]
Hi @ethanaobrien, could you please share with us the ads code you removed from the script?

Thank you!

**Comment by xxxnewbiexxx** [comment]
> Cool, this is basically what emulatorjs does. When I get time to update it. I will create a branch that has you just put the URL to the ad.html

This would be great!

**Comment by ethanaobrien** [comment]
@Scoffins @xxxnewbiexxx 

Feature implemented
add the following line to the example code
```
EJS_AdUrl = '' //path to AD page
```

**Comment by xxxnewbiexxx** [comment]
Thanks @ethanaobrien !

**Comment by ethanaobrien** [comment]
No problem!
