### ISSUE TITLE
playstaion not working

### ISSUE THREAD

**Issue by tweakdoor** [emulatorjs/emulatorjs#70]
i am trying to play playstaion emulator but when its complete its restart why?

https://tweakdoor.com/game/test2.0/ps.html

only mobile view google view working

**Comment by ethanaobrien** [comment]
I tried it on desktop - it seems to work fine

**Comment by ethanaobrien** [comment]
Please share console log and a screenshot of the network log

**Comment by tweakdoor** [comment]
Hello bro i had friend and i asked him about the elmutor he said it’s
dangerous and his friend get a case in court because of this is this true ?
Is it dangerous?

**Comment by DarkShadow8700** [comment]
If you read what he said in the home page he says the emulator is not illegal and that only the ROMs are so it might be a from or something

**Comment by tweakdoor** [comment]
umm so this might be dangerous

**Comment by ethanaobrien** [comment]
>umm so this might be dangerous

If you are using a copyrighted rom (Not a homebrew game) then yes, this is dangerous

**Comment by ethanaobrien** [comment]
Assuming this is resolved, because I have received no additional info
