### ISSUE TITLE
[BUG] Gba main menu buttons not appear

### ISSUE THREAD

**Issue by discordfar** [emulatorjs/emulatorjs#700]
NOTE: i go investigate, all system same problem.
I'll see what I did wrong in the frontend.
many sorry teambest.

solved, many sorry teambest.
the cause of this bug was a css code that conflicted with emulatorjs.

main menu buttons not appear but when you put mouse
individual button appear
less gamepad control set button

only appear volume button, button settings side volume not appear too

![gba bug](https://github.com/EmulatorJS/EmulatorJS/assets/142048925/3543f21c-2955-4a9a-ab2f-09733533d8df)

![gba bug_](https://github.com/EmulatorJS/EmulatorJS/assets/142048925/0de1a5c9-2f81-4432-8688-3c9799f674de)

LOG

[INFO] RetroArch 1.16.0 (Git a6bd6ff8a6)
emulator.js:1047 [INFO] === Build =======================================
emulator.js:1047 [INFO] Capabilities: 
emulator.js:1047 [INFO] Version: 1.16.0
emulator.js:1047 [INFO] Git: a6bd6ff8a6
emulator.js:1047 [INFO] Built: Oct  2 2023
emulator.js:1047 [INFO] =================================================
emulator.js:1047 [INFO] [Input]: Found input driver: "emulatorjs".
emulator.js:1047 [INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
emulator.js:1047 [INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2_INTL.
emulator.js:1047 [INFO] [Overrides]: Redirecting save file to "/data/saves/mGBA/Sonic Advance (USA) (En,Ja).srm".
emulator.js:1047 [INFO] [Overrides]: Redirecting save state to "/home/web_user/retroarch/userdata/states/mGBA/Sonic Advance (USA) (En,Ja).state".
emulator.js:1047 [INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
emulator.js:1047 [INFO] [Environ]: SET_INPUT_DESCRIPTORS:
emulator.js:1047 [INFO] [Environ]: GET_LOG_INTERFACE.
emulator.js:1047 [INFO] [Content]: Loading content file: "/Sonic Advance (USA) (En,Ja).gba".
emulator.js:1047 [INFO] [Environ]: SET_AUDIO_BUFFER_STATUS_CALLBACK.
emulator.js:1047 [WARN] [Environ]: SYSTEM DIR is empty, assume CONTENT DIR /Sonic Advance (USA) (En,Ja).gba
emulator.js:1047 [INFO] [Environ]: SYSTEM_DIRECTORY: "".
emulator.js:1047 [INFO] [Environ]: SET_MEMORY_MAPS.
emulator.js:1047 [INFO] [Replay]: Found last replay slot: #0
emulator.js:1047 [INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
emulator.js:1047 [INFO] [Core]: Geometry: 240x160, Aspect: 1.500, FPS: 59.73, Sample rate: 32768.00 Hz.
emulator.js:1047 [INFO] [Audio]: Set audio input rate to: 32917.50 Hz.
emulator.js:1047 [INFO] [Video]: Set video size to: 720x480.
emulator.js:1047 [INFO] [EGL] Falling back to eglGetDisplay
emulator.js:1047 [INFO] [EGL]: EGL version: 1.4
emulator.js:1047 [INFO] [EGL]: Current context: 0xf234.
emulator.js:1047 [INFO] [EMSCRIPTEN/EGL]: Dimensions: 300x150
emulator.js:1047 [INFO] [GL]: Found GL context: "egl_emscripten".
emulator.js:1047 [INFO] [GL]: Detecting screen resolution: 300x150.
emulator.js:1047 [INFO] [GL]: Vendor: WebKit, Renderer: WebKit WebGL.
emulator.js:1047 [INFO] [GL]: Version: OpenGL ES 2.0 (WebGL 1.0 (OpenGL ES 2.0 Chromium)).
emulator.js:1047 [WARN] [GL]: GLES implementation does not have BGRA8888 extension.
emulator.js:1047 [GL]: 32-bit path will require conversion.
emulator.js:1047 [INFO] [GL]: Using resolution 300x150.
emulator.js:1047 [INFO] [GL]: Default shader backend found: glsl.
emulator.js:1047 [INFO] [Shader driver]: Using GLSL shader backend.
emulator.js:1047 [WARN] [GL]: Stock GLSL shaders will be used.
emulator.js:1047 [INFO] [GLSL]: Found GLSL vertex shader.
emulator.js:1047 [INFO] [GLSL]: Found GLSL fragment shader.
emulator.js:1047 [INFO] [GLSL]: Linking GLSL program.
emulator.js:1047 [INFO] [GLSL]: Found GLSL vertex shader.
emulator.js:1047 [INFO] [GLSL]: Found GLSL fragment shader.
emulator.js:1047 [INFO] [GLSL]: Linking GLSL program.
emulator.js:1047 [INFO] [GLSL]: Found GLSL vertex shader.
emulator.js:1047 [INFO] [GLSL]: Found GLSL fragment shader.
emulator.js:1047 [INFO] [GLSL]: Linking GLSL program.
emulator.js:1047 [INFO] [GL]: Using 4 textures.
emulator.js:1047 [INFO] [GL]: Loaded 1 program(s).
emulator.js:1047 [INFO] [Video]: Found display server: "null".
emulator.js:1047 [INFO] [OpenAL]: Using 11 buffers of 1024 bytes.
emulator.js:1047 [INFO] [Audio]: Started synchronous audio driver.
emulator.js:1047 [INFO] [Display]: Found display driver: "gl".
emulator.js:1047 [INFO] [Config]: Saved new config to "/home/web_user/retroarch/userdata/retroarch.cfg".
emulator.js:1047 [INFO] [Playlist]: Loading history file: "/home/web_user/retroarch/userdata/content_history.lpl".
emulator.js:1047 [INFO] [Playlist]: Loading history file: "/home/web_user/retroarch/userdata/content_music_history.lpl".
emulator.js:1047 [INFO] [Playlist]: Loading favorites file: "/home/web_user/retroarch/userdata/content_favorites.lpl".
emulator.js:1047 [ERROR] Cannot push NULL or empty core path into the playlist.
emulator.js:3680 shader disabled
emulator.js:1047 [ERROR] [GL]: none shader not supported, falling back to stock GLSL
emulator.js:1047 [INFO] [Shader driver]: Using GLSL shader backend.
emulator.js:1047 [WARN] [GL]: Stock GLSL shaders will be used.
emulator.js:1047 [INFO] [GLSL]: Found GLSL vertex shader.
emulator.js:1047 [INFO] [GLSL]: Found GLSL fragment shader.
emulator.js:1047 [INFO] [GLSL]: Linking GLSL program.
emulator.js:1047 [INFO] [GLSL]: Found GLSL vertex shader.
emulator.js:1047 [INFO] [GLSL]: Found GLSL fragment shader.
emulator.js:1047 [INFO] [GLSL]: Linking GLSL program.
emulator.js:1047 [INFO] [GLSL]: Found GLSL vertex shader.
emulator.js:1047 [INFO] [GLSL]: Found GLSL fragment shader.
emulator.js:1047 [INFO] [GLSL]: Linking GLSL program.
emulator.js:1047 [INFO] [Shaders]: Applying shader: "".
emulator.js:3680 fps hide
emulator.js:3680 ff-ratio 3.0
emulator.js:1042 invalid core option ff-ratio. This is not an error.
emulator.js:3680 sm-ratio 3.0
emulator.js:1042 invalid core option sm-ratio. This is not an error.
emulator.js:3680 fastForward disabled
emulator.js:1042 invalid core option fastForward. This is not an error.
emulator.js:3680 slowMotion disabled
emulator.js:1042 invalid core option slowMotion. This is not an error.
emulator.js:3680 rewindEnabled disabled
emulator.js:1042 invalid core option rewindEnabled. This is not an error.
emulator.js:3680 rewind-granularity 6
emulator.js:1042 invalid core option rewind-granularity. This is not an error.
emulator.js:3680 save-state-slot 1
emulator.js:1042 invalid core option save-state-slot. This is not an error.
emulator.js:3680 save-state-location download
emulator.js:1042 invalid core option save-state-location. This is not an error.
emulator.js:3680 virtual-gamepad disabled
emulator.js:1042 invalid core option virtual-gamepad. This is not an error.
emulator.js:3680 virtual-gamepad-left-handed-mode disabled
emulator.js:1042 invalid core option virtual-gamepad-left-handed-mode. This is not an error.
emulator.js:3680 mgba_gb_model Autodetect
emulator.js:3680 mgba_use_bios ON
emulator.js:3680 mgba_skip_bios OFF
emulator.js:3680 mgba_gb_colors Grayscale
emulator.js:3680 mgba_sgb_borders ON
emulator.js:3680 mgba_color_correction OFF
emulator.js:3680 mgba_solar_sensor_level 0
emulator.js:3680 mgba_force_gbp OFF
emulator.js:3680 mgba_idle_optimization Remove Known
emulator.js:3680 mgba_frameskip_threshold 33
emulator.js:3680 mgba_frameskip_interval 0
emulator.js:3993 Available core options {shader: {…}, fps: {…}, ff-ratio: {…}, sm-ratio: {…}, fastForward: {…}, …}
emulator.js:1047 [INFO] [Environ]: RETRO_ENVIRONMENT_SET_MINIMUM_AUDIO_LATENCY.
emulator.js:1047 [libretro INFO] GBA Memory: Detected Flash savegame

**Comment by ethanaobrien** [comment]
What css conflicted with the file? I'd like to fix this for the future

**Comment by discordfar** [comment]
the buttons of emulatorjs use svg
the background of my site too use svg

I had to change the id of the svg at the background of the site to fix this problem

**Comment by discordfar** [comment]
@ethanaobrien

for you fix this in emulatorjs
you need add svg#id for buttons
