### ISSUE TITLE
Stuck when downloading fileset | Downloading: /data/main/videos/nds.mp4

### ISSUE THREAD

**Issue by Gitonthegrid** [emulatorjs/emulatorjs#708]
Dear all, 

I just wanted to checkout the emulator at my Synology NAS in docker, but for some reason It gets stuck when I am downloading the fileset. 

Ik only gives these 2 lines:
_Downloading: /data/main/videos/nds.mp4
Downloading: /data/main/videos/nds.mp4_

I don`t see any strange errors in the log of the container though.

**Comment by ethanaobrien** [comment]
Wrong project, see the FAQ

https://emulatorjs.org/docs/FAQ.html

Note that if you are using linuxserver's emulatorjs docker, I don't personally recommend it since the project has been unmaintained for months
