### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by DP5PNG** [emulatorjs/emulatorjs#709]
Ok, I'll preface this by saying I'm stupid, so if this is super obvious sorry in advance.
So basically, I'm using replit to get the emulator working, but whenever I hit play on the actual website (not the webview, because that never works) it hits me with a network error, any ideas? Here's the code I have:
```
<div style='width:fill;height:fill;max-width:100%'>
  <div id='game'></div>
</div>

<script type='text/javascript'>
  EJS_player = '#game';

  EJS_DEBUG_XX = true;
  // Can also be pcsx_rearmed or mednafen_psx_hw
  EJS_core = 'psx';

  // URL to BIOS file
  EJS_biosUrl = '';

  // URL to Game rom
  EJS_gameUrl = 'x5.bin';

  // Path to the data directory
  EJS_pathtodata = 'https://cdn.jsdelivr.net/gh/ethanaobrien/emulatorjs@main/data/';
</script>
<script src='https://cdn.jsdelivr.net/gh/ethanaobrien/emulatorjs@main/data/loader.js'></script>
```

**Comment by ethanaobrien** [comment]
2 things.

1. [See the faq](https://emulatorjs.org/docs/FAQ.html), Replit is known to have problems
2. `https://cdn.jsdelivr.net/gh/ethanaobrien/emulatorjs@main/data/` is a very outdated url. It should be `https://cdn.jsdelivr.net/gh/EmulatorJS/EmulatorJS@main/data/`

**Comment by HunterBoy344** [comment]
Try editing EmulatorJS's index.html to load a ROM with a fetch request rather than from the file input. This is how I made it automatically load a file named "data.z64," and yes, it works on Replit:
```
(starting after the script tag)
            window.onload = async () => {
                const response = await fetch("data.z64")
                const url = await response.blob()
                const parts = ["data", "z64"]
(continue with "const core..." like original version)
```
