### ISSUE TITLE
Playstation Network Error 

### ISSUE THREAD

**Issue by DarkShadow8700** [emulatorjs/emulatorjs#71]
![Screenshot 2021-12-29 1 38 09 AM](https://user-images.githubusercontent.com/96354083/147638406-961439a5-ef65-4014-8898-8e7c5ca66a7f.png)
Whenever I try to play a ps1 game it shows a network error and I've tried multiple games but none of them seem to be working Update N64 is starting to work again

**Comment by tweakdoor** [comment]
can you sure your code of ps html or console log

**Comment by ethanaobrien** [comment]
Duplicate of #70
