### ISSUE TITLE
 I can't leave the emulator with the screen full when loading the rom

### ISSUE THREAD

**Issue by ge39** [emulatorjs/emulatorjs#710]
link : https://gegames.com.br/play_game.php?id=1
![fullscreenonload](https://github.com/EmulatorJS/EmulatorJS/assets/29778498/7c074ada-d037-4a0d-94c0-6ab5ae2c73c4)
[](url)

**Comment by ge39** [comment]
sorry, I left the wrong link, https://gegames.com.br/play_game.php?id_game=1

**Comment by ethanaobrien** [comment]
There was a typo in the documentation. It  should be `EJS_fullscreenOnLoaded = true`, sorry about that!
