### ISSUE TITLE
[Request] Add M3U support for the Amiga (and probably other platforms too)

### ISSUE THREAD

**Issue by michael-j-green** [emulatorjs/emulatorjs#713]
M3U support appears to be missing from the Amiga core, but is working fine in the C64 core (I've only tested these two).

When I use the same M3U archive in RetroArch it works properly.

**Comment by Flyingfufu** [comment]
Hi Guys,
Many thanks for all the noce work done, allowing many of us to have good time !
Any chance to see some progress/fix for this one ? Have quite a bunch of Amiga rom, thus missing this feature to enjoy fully Gaseous !

**Comment by michael-j-green** [comment]
Looks like it was just missing the extensions from the emulator.js file.
