### ISSUE TITLE
[Request] Legacy MAME Core - Remove Nag Warnings

### ISSUE THREAD

**Issue by AeonixAeon** [emulatorjs/emulatorjs#717]
MAME2003 Plus is a newer core and is usually more compatible, however, older legacy games more often than not trigger the MAME Nag screen for Copyright Warnings. These are not part of the game itself but part of MAME. I humbly request a Legacy MAME Core option that has this disabled by default as the newer MAME versions do not have this as an option. This is more of a QoL improvement that would open up a larger list of games to be used without the nag warnings.

Preferably this would specifically be: mame0.243-wasm.data as the core.

**Comment by ethanaobrien** [comment]
Added in 4.0.10
