### ISSUE TITLE
[Request] Samples Folder/URL Documented Support

### ISSUE THREAD

**Issue by AeonixAeon** [emulatorjs/emulatorjs#718]
Many of the older arcade games, whether run through MAME or FBNeo rely on external sounds not included in the rom. Zaxxon, Journey, Berserk are just a few.

While games will still play, they do so silently or missing sounds. MAME and FBNeo handles this by having a folder called Samples where you would put the ZIP files that correspond to the games, usually named the same. 

This proposal requests support and documentation for the Samples folder (or direct URL to samples file) so these external sounds can be loaded along with the corresponding ROM files, much like how EJS_loadStateURL works. Being able to define the URL of the additional samples file to load.

In this case something like EJS_loadSamplesURL to handle supplementary files needed to play the game.

An example list of games that can use Samples can be found here: https://samples.mameworld.info/

While some games are merely enhanced by the samples, others completely rely on them to operate properly. There is no special emulator formats for these files, as they should work with MAME and FBNeo respectively.

**Comment by ethanaobrien** [comment]
```
EJS_externalFiles = {
    "/mame2003/samples/<game name>/": "sample.zip",
    "/mame2003-plus/samples/<game name>/": "sample.zip"
}
```

This can be accomplished using the new `EJS_externalFiles` in 4.0.10
