### ISSUE TITLE
 has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by tweakdoor** [emulatorjs/emulatorjs#72]
i am getting this error when i try to install my rom from another website 

Access to XMLHttpRequest at 'https://usaupload.com/5C3I/Super_Mario_Advance_2_-_Super_Mario_World_(USA,_Australia).gba' from origin 'https://tweakdoor.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

is there anyway to fix that ?

**Comment by allancoding** [comment]
You have to have the rom on your server not on another. So in other words download it and put it on your own server and link it to it that way.

**Comment by ethanaobrien** [comment]
More info: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

This must be fixed server side

I am closing this - not a problem with emulatorjs
