### ISSUE TITLE
Remapping Default Controller Buttons

### ISSUE THREAD

**Issue by JScripto** [emulatorjs/emulatorjs#725]
I understand that there is information on how to change the default controller buttons located [here](https://emulatorjs.org/docs4devs/Control%20Mapping.html#control-mapping), however I am having difficulty setting it up. May I have an example of what it looks like within an html file? I would like to change the default NES buttons. Thank you.

**Comment by ethanaobrien** [comment]
Did you try clicking the reset button in the control menu

**Comment by JScripto** [comment]
I just don't quite understand the code.

**Comment by ethanaobrien** [comment]
It's just a variable you set.... the same way you initialize everything else....

Closing because there is no issue

**Comment by JScripto** [comment]
Gosh, I just now realized there is a discussion tab.
