### ISSUE TITLE
Feature: Automatic Cloud Saves

### ISSUE THREAD

**Issue by gorfreed** [emulatorjs/emulatorjs#729]
I know I am a little bit late to the party, as this has been discussed before in previous issues - but I couldn't make much sense of it (or get it to work of course), so here is me hoping for some Github magic:

EmulatorJS works perfect technically, but for me to really enjoy a game on it I need to be able to "pick it up and play" wherever I am and without losing any progress - just as I would with my NDS console. That means, I want to be able to return to a URL and the game would automatically load the latest save state to put me right where I left off. 

I have used the Wizard to set up the game itself and tried to customize the code so it would load the .state file from the root directory of the index.html - but couldn't really make that work. I also was unsuccessful in trying to implement an auto-save function and have it continuously overwrite the .state file in the root directory. 

Compared with the tech marvel that this emulation script is to me, my automatic "cloud save" function shouldn't really present that much of a challenge, right? I hope somebody can help me out :)

**Comment by michael-j-green** [comment]
I've just implemented manual cloud saving in my project (https://github.com/gaseous-project/gaseous-server), and I've found that on some cores, cloud saving is so fast that you don't notice it... however, on some cores - especially the more resource heavy ones (like the N64) - there is a significant pause when grabbing the save state, to the point where if you were doing it automatically would render the game unplayable.

I'm also not sure that implementing cloud saving in EJS itself is the appropriate place - this should be left to the platforms that use EJS.

**Comment by ethanaobrien** [comment]
Closing as not planned, this isnt something that emulatorjs is aimed to do
