### ISSUE TITLE
[Bug] the decompress progress always 97% in android chrome

### ISSUE THREAD

**Issue by ajccom** [emulatorjs/emulatorjs#730]
I was uploaded a rom named '2020 Nen Super Baseball (Japan).md.zip' at demo page: 'https://demo.emulatorjs.org/' in android chrome.

Then I selected game core 'Sega Mega Drive' and click load game button.

After download core, there is a tip at page bottom, "Decompress Game Core 97%".
My problem is the decompress progress always 97% as I tried many times.

I tried in mac chrome, it's ok. But in android chrome, it's not ok.

**Comment by ethanaobrien** [comment]
First and foremost, never ever upload roms. Can I get a log of the console, I can do nothing without this.

Please use the github "bug" issue template

**Comment by ajccom** [comment]
It was happened on the 'https://demo.emulatorjs.org/'
Could I set the debug mode true anywhere on this demo site?

**Comment by ethanaobrien** [comment]
1. It's always best to setup a local instance to test things like this
2. You can execute `EJS_DEBUG_XX = true` in the console before selecting a rom file

**Comment by ajccom** [comment]
Translation not found for 'Start screen recording'. Language set to 'zh-CN'
recorder-v2.js?v=1.95.0:18 Translation not found for 'Stop screen recording'. Language set to 'zh-CN'
recorder-v2.js?v=1.95.0:18 {cheat: false, cacheManager: false, settings: false, gamepad: false}
recorder-v2.js?v=1.95.0:18 Translation not found for 'D-PAD UP'. Language set to 'zh-CN'
recorder-v2.js?v=1.95.0:18 Translation not found for 'D-PAD DOWN'. Language set to 'zh-CN'
recorder-v2.js?v=1.95.0:18 Translation not found for 'D-PAD LEFT'. Language set to 'zh-CN'
recorder-v2.js?v=1.95.0:18 Translation not found for 'D-PAD RIGHT'. Language set to 'zh-CN'
recorder-v2.js?v=1.95.0:18 Translation not found for 'BUTTON_2'. Language set to 'zh-CN'
recorder-v2.js?v=1.95.0:18 Translation not found for 'BUTTON_4'. Language set to 'zh-CN'
recorder-v2.js?v=1.95.0:18 Translation not found for 'up arrow'. Language set to 'zh-CN'
recorder-v2.js?v=1.95.0:18 Translation not found for 'down arrow'. Language set to 'zh-CN'
recorder-v2.js?v=1.95.0:18 Translation not found for 'left arrow'. Language set to 'zh-CN'
recorder-v2.js?v=1.95.0:18 Translation not found for 'right arrow'. Language set to 'zh-CN'
recorder-v2.js?v=1.95.0:18 Translation not found for 'LEFT_TOP_SHOULDER'. Language set to 'zh-CN'
recorder-v2.js?v=1.95.0:18 Translation not found for 'RIGHT_TOP_SHOULDER'. Language set to 'zh-CN'
recorder-v2.js?v=1.95.0:18 Translation not found for 'LEFT_BOTTOM_SHOULDER'. Language set to 'zh-CN'
recorder-v2.js?v=1.95.0:18 Translation not found for '-1'. Language set to 'zh-CN'
recorder-v2.js?v=1.95.0:18 Translation not found for '+1'. Language set to 'zh-CN'
recorder-v2.js?v=1.95.0:18 Translation not found for '-1'. Language set to 'zh-CN'
recorder-v2.js?v=1.95.0:18 Translation not found for '+1'. Language set to 'zh-CN'
recorder-v2.js?v=1.95.0:18 Translation not found for '-1'. Language set to 'zh-CN'
recorder-v2.js?v=1.95.0:18 Translation not found for '+1'. Language set to 'zh-CN'
recorder-v2.js?v=1.95.0:18 Translation not found for '-1'. Language set to 'zh-CN'
recorder-v2.js?v=1.95.0:18 Translation not found for '+1'. Language set to 'zh-CN'
recorder-v2.js?v=1.95.0:18 Translation not found for 'CU'. Language set to 'zh-CN'
recorder-v2.js?v=1.95.0:18 Translation not found for 'CD'. Language set to 'zh-CN'
recorder-v2.js?v=1.95.0:18 Translation not found for 'CL'. Language set to 'zh-CN'
recorder-v2.js?v=1.95.0:18 Translation not found for 'CR'. Language set to 'zh-CN'
recorder-v2.js?v=1.95.0:18 Translation not found for ''. Language set to 'zh-CN'
recorder-v2.js?v=1.95.0:18 wasm streaming compile failed: CompileError: WebAssembly.instantiateStreaming(): Compiling function #527 failed: Invalid opcode (enable with --experimental-wasm-simd) @+291861
recorder-v2.js?v=1.95.0:18 falling back to ArrayBuffer instantiation
recorder-v2.js?v=1.95.0:18 failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): Compiling function #527 failed: Invalid opcode (enable with --experimental-wasm-simd) @+291861
recorder-v2.js?v=1.95.0:18 Aborted(CompileError: WebAssembly.instantiate(): Compiling function #527 failed: Invalid opcode (enable with --experimental-wasm-simd) @+291861)
e98d3fd3-a460-4d82-8102-2a717d02315c:1 Uncaught (in promise) RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): Compiling function #527 failed: Invalid opcode (enable with --experimental-wasm-simd) @+291861). Build with -sASSERTIONS for more info.
    at abort (blob:http://172.16.17.78:9000/e98d3fd3-a460-4d82-8102-2a717d02315c:1:5591)
    at blob:http://172.16.17.78:9000/e98d3fd3-a460-4d82-8102-2a717d02315c:1:6985


![image](https://github.com/EmulatorJS/EmulatorJS/assets/2509085/b40bb3bf-1efe-4ca0-abff-667606872b25)

I use chrome inspect in my local web server, and get the log.

**Comment by ethanaobrien** [comment]
This shouldn't be possible. Can you check and make sure your browser is the newest version?

**Comment by ajccom** [comment]
I can reproduce this problem on the online demo website 'https://demo.emulatorjs.org/'.

In my local site, I was found `{ "current_version": 40.8 }` in `/data/version.json` file.

**Comment by ethanaobrien** [comment]
I mean the web browser, check thr web browser for updates

**Comment by ajccom** [comment]
My chrome version is 76.0.3809.132, I think its need to be upgraded, thank you very much.
