### ISSUE TITLE
Context menu button small issues

### ISSUE THREAD

**Issue by zmarteline** [emulatorjs/emulatorjs#731]
Please change the tooltip balloon from context menu button to align left, like the one from full screen button, otherwise the text will be cut off when hiding the configuration button:
![context](https://github.com/EmulatorJS/EmulatorJS/assets/101960945/95ea260c-db13-46e8-85a1-f91681a562bb)

Also, how can I hide this button? because adding    "config.contextMenuButton = false;" inside loader.js like I did to "config.buttonOpts.settings" doesn't work.

**Comment by ethanaobrien** [comment]
This has been fixed, thank you for the report.

You can now disable this button by adding `config.contextMenuButton = false`.
