### ISSUE TITLE
memory usage

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [emulatorjs/emulatorjs#732]
so i tried this with pokemon stadium2... on edge 64bit... it works, but the tab it's using 1.3gb of ram, why?
also it fails with out of memory when trying to load the rom in 32bit chrome/edge... even that my computer have 8gb of ram, it could be an address space issue? i could try rebooting with /3g to have more address space, but this would only happend if you were allocating a full huge 1gb block.... which would lead me back to why?

Also is there a prefered format to use? that would be faster to load or require less memory, like not needing to decompress and use double memory (even if temporary), or not needing to swap bytes due to endian or something?

also i checked "window.performance.memory.jsHeapSizeLimit" is 1098907648 on chrome 32bit... and a smaller game that works like wave race... is using 1074535811... while stadium2 is using 1247781422...

**Comment by MyTDT-Mysoft** [comment]
i could workaround it on 32bit chrome/edge by adding `--js-flags="--max_old_space_size=128 --max_semi_space_size=768"`
and yes that jsHeapSizeLimit on 64gb was 2gb... but on 32gb is 1gb... but is still 1gb when a native version wouldnt require 128mb... so... is there something that can be done?

i want to try to recompile and modify it slight so i can make my "Stadium 2 Fusion" (N64 + GBC emulators both working at same time) to have the battles happening on N64 while running the GBC game... so reducing this memory usage would surely help.

**Comment by MyTDT-Mysoft** [comment]
maybe split some memory usage in separate workers?

**Comment by ethanaobrien** [comment]
>so i tried this with pokemon stadium2... on edge 64bit... it works, but the tab it's using 1.3gb of ram, why?

We're running an entire emulator, along with storing any data in memory

>also it fails with out of memory when trying to load the rom in 32bit chrome/edge... even that my computer have 8gb of ram, it could be an address space issue? i could try rebooting with /3g to have more address space, but this would only happend if you were allocating a full huge 1gb block.... which would lead me back to why?

32 bit application can only access 4gb of memory *max*. So even if you have more, it's not going to matter. Memory limits per tab are more sensitive on 32 bit for this reason

>Also is there a prefered format to use? that would be faster to load or require less memory, like not needing to decompress and use double memory (even if temporary), or not needing to swap bytes due to endian or something?

Only real thing you can do it not use compression

> also i checked "window.performance.memory.jsHeapSizeLimit" is 1098907648 on chrome 32bit... and a smaller game that works like wave race... is using 1074535811... while stadium2 is using 1247781422...

Thats expected 

> and yes that jsHeapSizeLimit on 64gb was 2gb... but on 32gb is 1gb... i think that aligns accurately with the biggest address space avaliable... 

I highly doubt this

>on the other hand... is still 1gb when a native version wouldnt require 128mb... so... is there something that can be done?

*all* the storage is kept in memory

>maybe split some memory usage in separate workers?

Not how it works

**Comment by MyTDT-Mysoft** [comment]
well according to other things i found... it actually works... because multiple workers use separate tabs, which would use separate address spaces, and it's possible to copy from one worker to another... (but yes that is not the appropriate solution, just an workaround to make up for the waste)  so it does not matter that's an entire emulator its still 1gb of ram used for it... while the native version would use <256mb 

do you guys not care about making it good? lol

**Comment by ethanaobrien** [comment]
>well according to other things i found... it actually works... because multiple workers use separate tabs, which would use separate address spaces, and it's possible to copy from one worker to another... (but yes that is not the appropriate solution, just an workaround to make up for the waste) so it does not matter that's an entire emulator its still 1gb of ram used for it... 

Correct, separate workers use separate heaps, but this does absolutely nothing for us. Even using the threaded cores, which uses multiple workers, requires using a `SharedArrayBuffer` which would still result with everything in one heap. You cannot break up the memory across threads.

>while the native version would use <256mb

Someone forgot we're keeping more than just the emulator ram in memory...

>do you guys not care about making it good? lol

Do you not care about even trying to contribute? lol

What you want is simply not possible

**Comment by MyTDT-Mysoft** [comment]
well, well... that i dont know about, but yes, i will have to recompile this to get it working the way i want anyway, so i will see about improving its memory usage and then report back... but for the premiliminary tests with /3gb and maxheap=1500 it's enough... (totally not for my phone but ok xD), also i know that you keep everything in memory... but it's basically the same thing for regular native emulators... 64mb for the ROM, plus just a few mb for the code... 8...16mb for the caches (texture/shader/config) , and for "browsers" it does not inclue GPU memory, as that is on a separate process...  if it was about "garbage collection" it would be fine to temporally require that... but it's clearly failing, so something is not being freed... i want to investigate the real numbers on that :)
