### ISSUE TITLE
[Bug] Some TV Web-Browsers don't support EmulatorJS - Why ? 

### ISSUE THREAD

**Issue by unclehowell** [emulatorjs/emulatorjs#733]
Sraf is the name of the Web Browser App on my JVC TV. 
It doesn't display EmulatorJS - Meanwhile every other device on my network displays it fine. 

I'm wondering if there's a fix and what other TV web-browser apps have issues displaying EmulatorJS. And why? If anyone else wants to get into this, I'm willing to work on it. See attached some PDF's about this Sraf TV Browser I'm talking about. 
[SERAPHIC_TVPortal_datasheet.pdf](https://github.com/EmulatorJS/EmulatorJS/files/13710346/SERAPHIC_TVPortal_datasheet.pdf)
[SERAPHIC_PremiumWebApp_datasheet.pdf](https://github.com/EmulatorJS/EmulatorJS/files/13710351/SERAPHIC_PremiumWebApp_datasheet.pdf)
[SERAPHIC+Third-party+Web+UI+and+Application+Framework_datasheet.pdf](https://github.com/EmulatorJS/EmulatorJS/files/13710352/SERAPHIC%2BThird-party%2BWeb%2BUI%2Band%2BApplication%2BFramework_datasheet.pdf)

I got Apache Guacamole to display Gnome Cinnamon desktop (GDM3) / Ubuntu 23.04 from my laptop in my TV Browser, albeit very slow to mirror VNC and XRDP, so the web-browser may not even be the issue. It's maybe a possibility there's maybe some room for improvement in EmulatorJS.   

If it's any help to more skilled programmers than me, the top left corner of EmulatorJS doesn't display, but the TV's mouse cursor changes from an arrow to a hand to indicate I can select it. When I select it and filebrowser.html opens the "filebrowser" div (in the filebrowser.html source) doesn't load at all e.g. the table with the uploaded files, but everything else on the filebrowser.html page appears to.

**Comment by ethanaobrien** [comment]
This is strange, not sure why it wouldnt just not be displayed. Can you check what version of webgl your browser supports?

Oh - and is it the entire "play now" that doesnt load or the game itself?

**Comment by unclehowell** [comment]
Hey, appreciate the reply. 
I Just see a black screen, the 'play now' nor games (nothing at all) loads.
I did a few WebGL benchmark tests and tried the demos and did version checks. 
The demo's like the fish tank work, but not perfectly. 
The WebGL report says it supports WebGL 1 (GLSL ES, inc. antialiasing). 
No WebGL 2 or ANGLE or Major Performance Caveat. 
Vector Shader (max vertex attributes (16), uniform vectors (256), Texture Image Units (0), Varying vectors (12) & Best Float Precision (-2 "127", 2 "127") (23). 
There's more specs for Rasterizer, Fragment Shader, Framebuffer, Textures, but it says no Vertex Textures Available.  
Supported Extensions list is as follows (EXT_blend_minmax, EXT_shader_texture_lod, OES_standard_derivatives, OES_vertex_array_object, WEBGL (copressed_texture_etcl/ debug_renderer_info/ debug_shaders/depth_texture/lose_context) and WEBKIT_WEBGL (depth_texture & lose_contex). 
I also tried luic.github.io/WebGL-Performance-Benchmark/
The Pixel Fill Benchmark (z-buffering enabled or disabled its about the same).
It renders 90 frames (99 in final frame) in 66.69* ms. 
Min Render Time is 16.7ms, max 100ms, avg is 42.31ms. 
The cubes test works, shows a load of cubes  up to 55FPS (some glitchy). 

Couldn't we just add another button in the top left corner (next to the full screen option) to switch this emulator to an RTSP video feed, with the overlay gamepad controllers disabled. Not just to solve this issue, but to have a single game session display on multiple devices simultaneously.  Then introduce a virtual gamepad on another port e.g. https://github.com/jehervy/node-virtual-gamepads 

If you watch 8 minutes into this video you'll see what I'm working on https://wayback.datro.xyz/2020-08-01_hbnb-intro.webm   - I was using UV4L with Emulationstation  but I'm thinking to introduce your EmulatorJS solution and the RTSP & separate virtual gamepad solution I suggested.

**Comment by ethanaobrien** [comment]
>I Just see a black screen, the 'play now' nor games (nothing at all) loads.

This sounds like it might just not like some Javascript syntax we're using. What're the possibilities you can get a console opened?

No webgl2 *might* be an issue

>Couldn't we just add another button in the top left corner (next to the full screen option) to switch this emulator to an RTSP video feed, with the overlay gamepad controllers disabled

I'm not quite sure what you mean by this

**Comment by unclehowell** [comment]
A console opened ? like ssh into the TV ?
Perhaps. 

What I'm suggesting is to put a RTSP webapp inside the docker container too. So that a single emulatorJS session can be cast to multiple screens. Then add a button in the top right corner of the frontend to allow users to join that shared session. Maybe load a page first to ask if they want to load a virtual gamepad controller or the RTSP feed. 

For example: 

Step 1: User joins/starts a multi-user local network session             |  Step 2: User launches a Controller (or shared-session game as a Video Stream)
:-------------------------:|:-------------------------:
![Screenshot from 2023-12-24 10-46-44](https://github.com/EmulatorJS/EmulatorJS/assets/10119070/af94d8ba-e9ae-44b4-92a0-73a5728d4ee4) | ![selectone](https://github.com/EmulatorJS/EmulatorJS/assets/10119070/da563416-38dd-4ae2-bc75-9b2a53e8b236)


Introducing this solution would make multi-player across multi-devices possible. I was doing it using UV4L but that project is outdated now. 

The virtual gamepad controller automatically determined the player number. 
The rtsp video stream should be low enough latency and can be made to scale to fit devices screen sizes ok too. We just make the stream prioritise low-latency above video quality, not that either should suffer much over a local network.

**Comment by ethanaobrien** [comment]
>What I'm suggesting is to put a RTSP webapp inside the docker container too.

Oh wait. This application isn't a docker container. Can you try loading via https://demo.emulatorjs.org/ and both see if it works and if it's the project you're currently using

**Comment by unclehowell** [comment]
It just says drag rom, and while there's an option for a USB Dongle, when I tried to upload a rom the browser doesn't allow file upload. So I can't really test that. I also can't get my hands on a copy of Sraf web-browser to install on my linux machines.

**Comment by ethanaobrien** [comment]
Ah I see, could you setup a local instance (downloaded from releases) and try that?

**Comment by unclehowell** [comment]
Sure. I also tried cloudretro.io and that failed too if that's any help - it half loaded then the browser just refreshed to a 404. So I presume the cache or something on the TV has a low limit set. But I can't see any way to know this for sure without gaining shell access to the TV's OS. 

I'll do what you said and get a local instance of EmulatorJS running on my homeserver later today and try that, but to understand you correctly, are you suggesting running EmulatorJS outside the docker container (bare-metal) to eliminate docker as the issue? I am doubtful that Docker itself or running EmulatorJS from docker-composer.yaml is the issue because like I said, I have EmulatorJS appearing on all other devices on my network without issues. 

The only solution I can suggest to this issue of outdated and/or incompatible web-browsers is to introduce an option to bring up EmulatorJS as a full screen RTSP video feed (and use a mobile gamepad controller webapp from another device to control the gaming session being broadcasted). The images I posted above suggest a simple way of adding this feature to enable users to also enjoy multi-player and multi-device gaming too. 

You'd still have separate gaming sessions with the gamepad controllers overlayed too, as EmulatorJS was intended, except with my feature request users would have the added addition of multi-device, multi-player too (by introducing the RTSP and the mobile gamepad feature I'm suggesting). How hard can it honestly be ?

**Comment by unclehowell** [comment]
I did what you suggested. Ran EmulatorJS bare-metal, outside a docker container. My OS is Ubuntu 23.04. 
Same deal as EmulatorJS inside a docker container, just a black screen. I don't even see the two icons in the top left corner.  So full circle we're back to the beginning of this thread. 
I can implement my feature request on a fork and do a pull request if there's interested in what I'm suggesting.

**Comment by ethanaobrien** [comment]
I'm slightly confused by what you're seeing, since this project does not have a docker version, unless you wrote it yourself. Can you open https://demo.emulatorjs.org/ on another device and verify its what you want shown. I think you might be looking for linuxservers emulatorjs docker project

**Comment by unclehowell** [comment]
Hey. I shouldn't have said outside docker, that was with Linuxservers EmulatorJS in mind, you're right. But it doesn't matter if I run this repo locally or if I run Linuxservers EmulatorJS (with docker) on my homeserver, I still get a black screen on the TV's web browser.  I've run https://demo.emulatorjs.org (and Linuxservers EmulatorJS) on other devices and other devices run it ok. Like I said before, the TV web browser also doesn't permit me to launch a prompt to upload a ROM game, even though I can put the ROM's on a USB Dongle for the TV.

**Comment by ethanaobrien** [comment]
Can you try loading https://ethanthesleepy.one/ejs/ and let me know what shows on the screen?

**Comment by unclehowell** [comment]
Works on everything except my TV web-browser. On the TV browser its just a white page with the word "undefined" showing in the top left corner.

**Comment by ethanaobrien** [comment]
Not entirely what I expected to happen, either way that's good news. Could you reload the page on your TV until it shows something different on the screen?

**Comment by unclehowell** [comment]
Now it's "Uncaught SyntaxError: Unexpected token function"

**Comment by ethanaobrien** [comment]
Now that's not fun.

Is there a way you could open the Javascript console on that TV? If not, there's likely nothing I can do to attempt to fix this

**Comment by unclehowell** [comment]
All I can see is that Sraf TV Browser is chromium based. And when I go to some websites, I think the chrome app store for example, it'll say the exact version of chromium this browser is based on, will stop being supported in January.  Never mind, thanks for trying. Sorry about the confusion caused mixing up Linuxservers Docker-based EmulatorJS with your project. In any case, your support today was appreciated.

**Comment by ethanaobrien** [comment]
It's all good, just wondering, what version is it based on?

**Comment by unclehowell** [comment]
According to whatismybrowser.com it's "Chrome 47 on Linux" , javascript is not enabled.
According to whatismybrowser.org javascript is enabled but under version it says "not installed" too. 
It says WebGL supported. Screen and colour is 1265,720 (screen size is 1280x720) and colour depth is 24 bit.

**Comment by ethanaobrien** [comment]
Ah, that makes sense. Javascript es6 syntax/classes weren't added until 49 I believe. Sorry about that

**Comment by unclehowell** [comment]
I'll fork EmulatorJS from Linuxserver and just add an RTSP webapp to the docker container. 
That'll solve it for me and anyone else who encounters this issue. 
I am just baffled why nobody's done this already.

**Comment by ethanaobrien** [comment]
My guess is because less than 2% of users worldwide are on a browser that doesn't even support es6 syntax

**Comment by ethanaobrien** [comment]
@unclehowell [browservice](https://github.com/ttalvitie/browservice) might be what you need

**Comment by unclehowell** [comment]
2% of chrome users alone would be 46 million users. I'll check out browservice - cheers

**Comment by ethanaobrien** [comment]
I actually meant 2% of all browsers. See this page

https://caniuse.com/?search=es6

But yeah, browservice should suffice. I'm not going to support an ancient browser


Though, when you set the "% of tracked users" option (meaning % of recorded users worldwide that have support), the support number goes up to 99.84%
