### ISSUE TITLE
[Bug] The Settings Menu Moves Off Screen

### ISSUE THREAD

**Issue by S-Coding23** [emulatorjs/emulatorjs#734]
When trying to select a sub menu item from the settings menu, the settings menu will shift to the right and completely off the screen. If you remove any other button from loading, the issue does not happen. 

https://github.com/EmulatorJS/EmulatorJS/assets/135175291/b5279386-ea34-4421-99a4-465a31173034

**Comment by ethanaobrien** [comment]
Fixed in 4.0.10
