### ISSUE TITLE
[Feature request] Login page

### ISSUE THREAD

**Issue by update-freak** [emulatorjs/emulatorjs#736]
Hi,

it would be good to have an login Page when using the Internal Reverse Proxy in Synology DSM. There is no possibility to use basic authentication with username and passwort in the internal Reverse Proxy Manager.

To replace the intern Reverse Proxy (and then use Authelia or Authentik or SWAG) is very hard and complicated: https://www.reddit.com/r/synology/comments/18prdlc/replacing_the_default_reverse_proxy_on_synology/
-> Option A: macvlan but then Problems with Firewall: https://www.synology-forum.de/threads/authelia-mit-internem-nginx-reverse-proxy-von-synology.130960/
-> Option B: additional VM with Linux

This brings me to the conclusion that adding a login page would be better for the Synology Users. Would be really cool if this could be implemented in future releases.

Linked to
https://github.com/linuxserver/emulatorjs/issues/114
https://github.com/linuxserver/emulatorjs/issues/41
https://github.com/linuxserver/docker-emulatorjs/issues/37

**Comment by ethanaobrien** [comment]
This project is actually completely unaffiliated with linuxservers EmulatorJS. I recommend you give their readme a read.

I do believe [gaseous](https://github.com/gaseous-project/gaseous-server) has this feature
