### ISSUE TITLE
The online game stopped working

### ISSUE THREAD

**Issue by Sonix-Corporation** [emulatorjs/emulatorjs#738]
I follow the instructions https://emulatorjs.org/docs4devs/netplay.html
The instructions work well for version 31.6.
However, the instructions do not work for version 40.8.
The network game icon does not appear in the emulator panel.
Please tell me how can I play a network game on version 40.8?

**Comment by ethanaobrien** [comment]
As shown on that page

>Please Note: Netplay is currently being worked on, to make it better and more reliable. If you follow these instructions you need a version of EmulatorJS before 4.0.


#590

**Comment by Sonix-Corporation** [comment]
I apologize for my carelessness. After your answer, having translated the entire page into my language through Google translator, I noticed this inscription)
