### ISSUE TITLE
Update documentation with all currently supported systems

### ISSUE THREAD

**Issue by michael-j-green** [emulatorjs/emulatorjs#740]
Would you be able to update the documentation to include all currently supported systems.

Systems such as Amiga, C64, Colecovision, etc are not listed in the docs.

Thanks!

**Comment by teddblue** [comment]
In addition, it seems that documentation for all consoles is missing

**Comment by ethanaobrien** [comment]
https://emulatorjs.org/docs4devs/Cores.html ?

**Comment by teddblue** [comment]
> https://emulatorjs.org/docs4devs/Cores.html ?

That shows a list of cores, when you click to get more info on a specific core it gives a 404 error

**Comment by ethanaobrien** [comment]
Oh whoops, thanks for pointing that out

**Comment by allancoding** [comment]
Just fixed: https://github.com/EmulatorJS/emulatorjs.org/commit/a991108675b4d91e5be5ae8bddd8a74e453b653d
