### ISSUE TITLE
[Bug] Browser tab freezes when attempting to save state in N64

### ISSUE THREAD

**Issue by michael-j-green** [emulatorjs/emulatorjs#742]
#### Make sure your issue doesn't get closed! Make sure you have done the following items

- [x] I have collected a **FULL** log of the console, with `EJS_DEBUG_XX` set to true, and uploaded it straight to GitHub.
- [x] I have not made any changes to the EmulatorJS instance I am running into this bug on.
- [x] I am on the latest version of EmulatorJS (commit: c1a9d9b2)
- [x] I have not attached any images or logs via external sites. I have uploaded them straight to GitHub and acknowledge that external sites may pose a security issue.
- [x] I have included, **IN DETAIL**, the steps to reproduce the bug.

When clicking the "Save State" button in the emulator while running the N64 core, the browser tab freezes. This happens in both Safari and Edge on macOS (I don't have a Windows device available to test).

I did manage to capture an error in Edge which implied there is an out of memory error:
![Screenshot_2024-01-13_at_8 48 59_am](https://github.com/EmulatorJS/EmulatorJS/assets/84688932/1adf0606-2b5d-4f99-8d36-eb4ec622c133)

I've tested the C64, Amiga, NES, and SNES cores, and they don't seem to have this issue. I'd imagine the issue is probably present on other high memory usage cores like PS1.

If it can't be resolved due to memory limitations, then can onSaveState provide a flag to turn off screenshot capturing, as capturing the state is probably the most important function.

[localhost-1705100548616.log](https://github.com/EmulatorJS/EmulatorJS/files/13924853/localhost-1705100548616.log)

**Comment by michael-j-green** [comment]
Thought I'd have another crack at it. This is being loaded inside Gaseous, and so is capturing the screenshot and the save state:
1. I loaded "Shadows of the Empire" for N64
2. Clicked the Save State button
3. The browser froze for about a minute and then started working again
4. The save state did not download

I checked the console, and got the attached WebGL error. This is from Safari on macOS Sonoma.
[N64Console.txt](https://github.com/EmulatorJS/EmulatorJS/files/14003335/N64Console.txt)

Same test in Edge froze the tab completely.

Checked it against the stable release on demo.emulator.js using Edge with the same N64 core, and the same N64 ROM. I was able to get a save state file, without the browser freezing. I believe it's to do with the screenshot that's provided when using the onSaveState function, as I still got similar errors as the embedded version. Here's the console output:
[demo.emulatorjs.org-1705883835769.log](https://github.com/EmulatorJS/EmulatorJS/files/14003370/demo.emulatorjs.org-1705883835769.log)

I just tried it a second time using the Nightly build, and the browser froze completely.

**Comment by ethanaobrien** [comment]
@michael-j-green 

Sorry for the delay - I've been a little busy.

Could you try to directly trigger a screen shot/save state from the `window.EJS_emulator.gameManager` api directly to see if the freeze is because of save state or the screenshot? Depending on if it's screenshot or save state ill give instructions to dig deeper

I don't believe that webgl error is tied to this issue (though I do believe it is an issue, it shouldn't be causing the page freeze)

**Comment by michael-j-green** [comment]
All good :)

I think this is what you mean:
<img width="1728" alt="Screenshot 2024-01-22 at 12 16 43 pm" src="https://github.com/EmulatorJS/EmulatorJS/assets/84688932/65476c2d-9b06-451c-a170-cf1d3f023b10">

No freeze occurred.

**Comment by ethanaobrien** [comment]
Those are functions. :)

`window.EJS_emulator.gameManager.screenshot()` and `window.EJS_emulator.gameManager.getState()`

**Comment by michael-j-green** [comment]
I should have known I'd goof it up :D

Anyways, the screenshot command worked properly, but getState froze the browser.
<img width="1728" alt="Screenshot 2024-01-22 at 12 36 11 pm" src="https://github.com/EmulatorJS/EmulatorJS/assets/84688932/739845a9-e3dc-4ec4-876d-0d3d44afb999">

**Comment by ethanaobrien** [comment]
That's what I expected. Let's start with this (I'm not 100% sure if this feature is available in safari, I know it's available with edge)

Could you first, freeze the page (by running that in the console). Then with the page frozen, go to the sources tab and click the pause button. This should open exactly where the current execution is frozen.

**Comment by michael-j-green** [comment]
Safari didn't respond, so from here on I'll do all my testing in Edge.

Edge gave me this:
<img width="1630" alt="Screenshot 2024-01-22 at 1 12 28 pm" src="https://github.com/EmulatorJS/EmulatorJS/assets/84688932/f721830b-684a-4144-84d8-5c585e87881c">

**Comment by michael-j-green** [comment]
Also got these:
<img width="1630" alt="Screenshot 2024-01-22 at 1 18 17 pm" src="https://github.com/EmulatorJS/EmulatorJS/assets/84688932/036638c6-bcc4-4bcb-936d-7de45d61cacd">
<img width="1630" alt="Screenshot 2024-01-22 at 1 18 08 pm" src="https://github.com/EmulatorJS/EmulatorJS/assets/84688932/97fc99e4-9faa-4eac-9d66-cd4d12fd8225">

**Comment by ethanaobrien** [comment]
I think I know where that is? Can you click that right arrow thing (to the right of the play/pause button) until it goes to something more readable (if it does)

**Comment by ethanaobrien** [comment]
Oh hmm, could be an issue with asyncify? Wouldn't be *too hard* to work around. If you click the button I mentioned in my last message can you get anything from the GameManager.js file?

**Comment by michael-j-green** [comment]
Seems to be hitting this alot:
<img width="1630" alt="Screenshot 2024-01-22 at 2 42 43 pm" src="https://github.com/EmulatorJS/EmulatorJS/assets/84688932/dae712be-8988-4b7e-8908-bcac3d2de0d1">

Also here:
<img width="1630" alt="Screenshot 2024-01-22 at 2 46 22 pm" src="https://github.com/EmulatorJS/EmulatorJS/assets/84688932/d1782d11-b894-4ec0-9ad1-0e3d7bfeae45">

Can't seem to stop in GameManager.js

**Comment by ethanaobrien** [comment]
I've attempted to make a fix in the RetroArch branch. Pull the nightly cores and try with those in a few hours. (They start building in about an hour)

**Comment by ethanaobrien** [comment]
I was wrong, 2 hours :)

**Comment by michael-j-green** [comment]
haha... all good. I'll check it out tonight.

Will those nightly cores be available on demo.emulator.js?

**Comment by ethanaobrien** [comment]
https://ethanthesleepy.one/public/EmulatorJS/

**Comment by michael-j-green** [comment]
Apologies for taking awhile to get back to you about this.

So, I did some testing.

I grabbed a zip of the latest main branch, and the cores from your link above.

All testing was done in Edge on macOS Sonoma.

Running the downloaded EJS demo site with the new cores allowed Save State, ``window.EJS_emulator.gameManager.screenshot()`` and ``window.EJS_emulator.gameManager.getState()`` to run without issue (small pause of the emulator, but it resumes after about 2 seconds). I also tested this using the same URL path that Gaseous would use (``/emulators/EmulatorJS``).

So I copied the EJS package (new cores and all) over the top of the one I use in the Gaseous package, cleared browser cache and restarted the browser, and ran the same tests with the same freezing results.

It should be noted that I embed EJS into the page with just a div rather than an iframe. I'll check behaviour once I move the emulator to an iframe later today.

Hope this helps!

**Comment by ethanaobrien** [comment]
>small pause of the emulator, but it resumes after about 2 seconds

Thats expected.

Strange, iframe/div shouldnt make a difference. 

To make sure youre actually running the nightly cores you replaced them with, could you try checking the "built on" message retroarch prints on boot? Should be one of the first logs in the console

**Comment by michael-j-green** [comment]
Cores I'm using were built on 2024-01-23 (according to the debug messages).

And now I'm thinking I had a caching issue (despite wiping the cache multiple times. I no longer get a freeze when I click the save button on the version built into Gaseous (different error this time - on my side so I need to check that).

**Comment by ethanaobrien** [comment]
So I did fix the issue? Nice. I do still need to do a bit of cleanup with the fix but good to know its fixed.

**Comment by michael-j-green** [comment]
FYI: I am getting an error in the browser console: WebGL: INVALID_OPERATION: readPixels: buffer is not large enough for dimensions

Not sure if that's an issue or not :)

**Comment by michael-j-green** [comment]
> So I did fix the issue? Nice. I do still need to do a bit of cleanup with the fix but good to know its fixed.

I think we can say it's fixed :)

**Comment by ethanaobrien** [comment]
> FYI: I am getting an error in the browser console: WebGL: INVALID_OPERATION: readPixels: buffer is not large enough for dimensions

That shouldnt have an affect on anything

>I think we can say it's fixed :)

Awesome!

**Comment by michael-j-green** [comment]
Quick question: do you know how big a Save State can get?

My db code is complaining that the combined size of the screenshot and state is 31MB (which is larger than MariaDB typically allows).

I'm guessing the state is only the VM state and any memory right? So theoretically it could get up to 4GB (assuming all emulator memory is used)?

**Comment by ethanaobrien** [comment]
>Quick question: do you know how big a Save State can get?

Nintendo 64 should have the biggest save state, 16mb per save I believe, may be 32?. 

All save state file sizes are static in a sense. A specific core will **always** have a specific save size (since I dont compress them)

**Comment by michael-j-green** [comment]
> > Quick question: do you know how big a Save State can get?
> 
> Nintendo 64 should have the biggest save state, 16mb per save I believe, may be 32?.
> 
> All save state file sizes are static in a sense. A specific core will **always** have a specific save size (since I dont compress them)

Ok, thanks for that. I'll have to do some thinking.

Thankyou again for solving the saving issue!

**Comment by michael-j-green** [comment]
I've resolved the issue on my end by zipping the state before storing it in the db.

But there's now a new issue: the screenshot is just black with some corrupted graphics:
![image-5](https://github.com/EmulatorJS/EmulatorJS/assets/84688932/357f93b6-581d-4bf0-9c65-8e061c11b158)

The resolution of the image is also quite high for what I would expect from a console from the 90's :D
<img width="366" alt="Screenshot 2024-01-24 at 9 55 44 am" src="https://github.com/EmulatorJS/EmulatorJS/assets/84688932/06191f01-eda5-47a5-a77e-a043427a8084">

Is this related to the clean up you said you needed to do? If so, just ignore this :)

**Comment by ethanaobrien** [comment]
Technically, I just need to do the same thing I did to screenshot that I did to save state to fix it

**Comment by michael-j-green** [comment]
Ah sweet... in that case, I'll leave it in your capable hands :)

**Comment by ethanaobrien** [comment]
Fixed in 4.0.10
