### ISSUE TITLE
[Bug] PS1 No Longer Working

### ISSUE THREAD

**Issue by S-Coding23** [emulatorjs/emulatorjs#743]
I was using the cores from the 1st of January and just tried the cores from this morning. I just get a solid black screen when loading a game, no audio. Happens on mobile and desktop. Here is a screenshot of the console log:

![image](https://github.com/EmulatorJS/EmulatorJS/assets/135175291/d5b23b40-a901-4ed1-8bd4-5b005fa5d4ba)

**Comment by ethanaobrien** [comment]
This is using the beta cores or the production cores in this repo? Or both

**Comment by S-Coding23** [comment]
Only the beta cores. The production cores work. Sorry about that.

**Comment by ethanaobrien** [comment]
Fixed: https://github.com/libretro/pcsx_rearmed/pull/819

**Comment by ethanaobrien** [comment]
Fixed in 4.0.10
