### ISSUE TITLE
emulator freezes by 99%

### ISSUE THREAD

**Issue by pavelbv2** [emulatorjs/emulatorjs#744]
Hello.
When loading the core, the emulator freezes by 99% (during the process of unpacking the core).
I've only used the nintendo 64 and ds.

the console log writes an error -
```
wasm streaming compile failed: CompileError: WebAssembly.instantiateStreaming(): Compiling function #495 failed: Wasm SIMD unsupported @+306328
emulator.js:1044 falling back to ArrayBuffer instantiation
emulator.js:1044 failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): Compiling function #495 failed: Wasm SIMD unsupported @+306328
emulator.js:1044 Aborted(CompileError: WebAssembly.instantiate(): Compiling function #495 failed: Wasm SIMD unsupported @+306328)
d876832c-aaeb-4f8c-a5b2-d3c7ad866674:1 Uncaught (in promise) RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): Compiling function #495 failed: Wasm SIMD unsupported @+306328). Build with -sASSERTIONS for more info.
    at abort (d876832c-aaeb-4f8c-a5b2-d3c7ad866674:1:5591)
    at d876832c-aaeb-4f8c-a5b2-d3c7ad866674:1:6976
abort @ d876832c-aaeb-4f8c-a5b2-d3c7ad866674:1
(anonymous) @ d876832c-aaeb-4f8c-a5b2-d3c7ad866674:1
```

What could this be related to?
Thank you.

**Comment by ethanaobrien** [comment]
What device is this on?

(Examples: windows, macos, android, iphone)

What browser are you using?

**Comment by pavelbv2** [comment]
> What device is this on?
> 
> (Examples: windows, macos, android, iphone)
> 
> What browser are you using?

windows 10
chrome and opera

The nes,sega MD,mame are working fine, but the Nintendo DS and 64 are not loading.

**Comment by ethanaobrien** [comment]
What version of opengl does your gpu support?

**Comment by pavelbv2** [comment]
You're right, that's exactly the point!
The laptop has an old version of OpenGL 1.1.0

But before, everything worked fine on the old version of the emulator.
Is there any way to fix this so that it works on OpenGL 1.1.0 as well?

**Comment by ethanaobrien** [comment]
Not likely, See #678

**Comment by ethanaobrien** [comment]
With DS it is not possible - Nintendo 64 is

**Comment by ethanaobrien** [comment]
A legacy n64 core has been added
