### ISSUE TITLE
[Bug] Issues with Sega Mega Drive game not starting.

### ISSUE THREAD

**Issue by no-usernamefr** [emulatorjs/emulatorjs#747]
I am having an issue with using the Sega Mega Drive (Sega Genesis). When using the editor on the emulatorjs.org website. When opening the html file it gives, it works perfectly locally. Editor settings are to make a file that does not rely on a web server. When putting the html file it gave me onto my website, when going to the website, it just shows a black square. I have tried visiting the link on Chrome, Firefox, Microsoft Edge, Pale Moon, Safari, and Opera, for the same result. But if I open it locally on Firefox (Doesn't work on other browsers), it works perfectly, once I put it on my website it stops working. The weird thing is, once I added the EJS_DEBUG_XX = true; to the file, it attempts to load, but it gets stuck on "Download Game Data". The rom works perfectly fine on the demo on emulatorjs.org on all browsers. The game I have been testing is Sonic Spinball, it did work fine in the past. Something might have changed to cause this.

![Screenshot 2024-01-18 5 15 11 PM](https://github.com/EmulatorJS/EmulatorJS/assets/141795010/91a3dc7b-1299-4f4d-bc31-df10010c2d39)
![Screenrecording2024-01-185 10 34PM-ezgif com-video-to-gif-converter](https://github.com/EmulatorJS/EmulatorJS/assets/141795010/8bebd9a7-841a-4f64-b91f-44785509a3c2)
[errorlogs.log](https://github.com/EmulatorJS/EmulatorJS/files/13983113/errorlogs.log)

**Comment by ethanaobrien** [comment]
Uh oh that's a bug, let me get that fixed

**Comment by ethanaobrien** [comment]
I take that back. Looks like something is being cached? Does this work on the demo site? https://demo.emulatorjs.org/?

**Comment by no-usernamefr** [comment]
> I take that back. Looks like something is being cached? Does this work on the demo site? https://demo.emulatorjs.org/?

Yes that is the only place where it works at.

**Comment by no-usernamefr** [comment]
> I take that back. Looks like something is being cached? Does this work on the demo site? https://demo.emulatorjs.org/?

If I use the code editor, that is where the issues happen.

**Comment by ethanaobrien** [comment]
Update the path to data in your code to point to whatever version you'd like located at https://cdn.emulatorjs.org. The code editor likely broke with one of the recent commits in this repo

**Comment by no-usernamefr** [comment]
> Update the path to data in your code to point to whatever version you'd like located at https://cdn.emulatorjs.org. The code editor likely broke with one of the recent commits in this repo

What commit do you suggest I use?

**Comment by ethanaobrien** [comment]
stable, https://cdn.emulatorjs.org/stable/

**Comment by no-usernamefr** [comment]
Thanks, I will check it out now, I will be back in a few minutes with an update.

**Comment by no-usernamefr** [comment]
Which one do I change the EJS_pathtodata or the javascript source at the bottom?

**Comment by ethanaobrien** [comment]
both

**Comment by no-usernamefr** [comment]
Testing it now

**Comment by no-usernamefr** [comment]
Thank you, it is working good now, the game loads and is now playable. Will there be an automatic fix for this when using the code editor?

**Comment by ethanaobrien** [comment]
Once I get the time, the code editor will be updated

**Comment by no-usernamefr** [comment]
Can I now mark this issue as closed?

**Comment by ethanaobrien** [comment]
I'll do it
