### ISSUE TITLE
[Bug] A key and S key override custom bindings on GBA

### ISSUE THREAD

**Issue by crashy102** [emulatorjs/emulatorjs#750]
Currently using the demo provided on the EmulatorJS site to play games, but I keep noticing this bug with every GBA game on every channel (stable, latest, nightly, 4.0.8). I tested 5 roms and they all had the same issue. The "A" key is set to the A button and the "S" key is set to the B button regardless of button mappings. I have my dpad as wasd, and when I try to move left or down I keep pressing A and B.

I've been playing with WASD as a joystick for a while on N64 and encountered no issues, so i'm assuming this is just on the GBA version.

Am I just stupid or is this a weird bug? Screenshot of my bindings:
![Screenshot 2024-01-22 2 38 51 PM](https://github.com/EmulatorJS/EmulatorJS/assets/83352326/ce83f37a-0463-4d98-a273-f918c9974510)

**Comment by ethanaobrien** [comment]
@allancoding

**Comment by allancoding** [comment]
What device are you using? I see that the virtual gamepad is enabled. Can you try with it disabled? Are you using a keyboard? Also what is your system language set to? And what OS if applicable.

**Comment by crashy102** [comment]
I'm using a Chromebook, and the issue persists with virtual gamepad disabled. I am using a keyboard, and my system language is English. OS is Chrome OS

**Comment by allancoding** [comment]
Thanks for the info.

Can you clear your cache: https://support.google.com/accounts/answer/32050?hl=en&co=GENIE.Platform%3DDesktop
and then rebind the keys.
Do you have access to dev tools?

**Comment by crashy102** [comment]
I do not have access to dev tools, I did clear my cache and rebind and the issue persists. I also tried a friend's device and it has the same issue.

**Comment by allancoding** [comment]
Are you using chrome that came with chrome os or something else like firefox or chrome for android?

**Comment by ethanaobrien** [comment]
I can confirm this issue. Switch to the mappings shown in the screenshot and use this test rom 

https://github.com/heroldev/AGB-buttontest/blob/master/BtnTest.gba

**Comment by allancoding** [comment]
why would just GBA have issues?

**Comment by crashy102** [comment]
It's not an issue on the other things i tested like snes and n64.

**Comment by crashy102** [comment]
> Are you using chrome that came with chrome os or something else like firefox or chrome for android?

also i'm using stock os. Stable channel dedede 114.0.5735.343 (Official Build) (64-bit)

**Comment by ethanaobrien** [comment]
This issue has been fixed. Use the "latest" option in the demo until a new release is out. Be sure to clear your cache. If the issue still persists let me know because that's likely the cdn not updating

**Comment by crashy102** [comment]
Yeah I still have the issue. I used the latest and nightly channel. The way it rapidly fires the A button reminds me of turbo buttons. Cleared my cache, cookies, browsing data twice

**Comment by ethanaobrien** [comment]
@allancoding I don't believe the minified files are being updated...

**Comment by allancoding** [comment]
Im looking into it rn

**Comment by allancoding** [comment]
Ok the minified files should be updated.

**Comment by crashy102** [comment]
Is it working for you? I cleared my cache again and still have issues in latest and nightly

**Comment by allancoding** [comment]
I think I fixed the issue.

**Comment by crashy102** [comment]
Yes, you did! Tried it in skiovox (just look it up if you don't know what it is) and it worked fine, so i cleared everything on my entire browser, restarted, and now it works. Thanks
