### ISSUE TITLE
[Enhancement] Enable/Disable Outdated Graphics Driver autocheck function

### ISSUE THREAD

**Issue by discordfar** [emulatorjs/emulatorjs#753]
the new version 4.0.9

It has a function that automatically checks the video card driver. In my case, I have an old computer, this error appears for me.

Outdated Graphics Driver.

![outdated graphics driver](https://github.com/EmulatorJS/EmulatorJS/assets/142048925/5cbbd086-09ed-413a-a84a-3b37752eeec4)

In the console log, the emulator searches for legacy cores. As it is not found, this error appears.
I managed to solve this, with the console log I renamed the core to legacy.
when free time add EJS_checkgraphics = true/false

**Comment by ethanaobrien** [comment]
Not how that feature is supposed to work. I made a logical error before pushing. To fix this until I release the next emulatorjs release use these minified files

https://cdn.emulatorjs.org/latest/data/emulator.min.zip

**Comment by discordfar** [comment]
continue same error, Outdated Graphics Driver.
The emulator ever search for legacy cores
because my pc is legacy 2013 core i3 with video intel HD Graphics

i only fix it rename all cores for legacy and works

**Comment by discordfar** [comment]
When i set
EJS_core = 'psx'

in old computer

by default the emulator load 'pcsx_rearmed-legacy-wasm'
by default the emulator load only legacy cores all systems

in computer high

by default the emulator load updated cores.

in release 4.0.9 only have nintendo 64 legacy cores, others systems no have.
the solution for me is rename cores to legacy to works in my old computer.

**Comment by ethanaobrien** [comment]
Reread my comment....


Clear cache/do what you need to do to use the latest code instead of the last release

**Comment by discordfar** [comment]
version 4.0.9 + replace with code files = working now.

Mupen64 legacy games who need expansion pak not work and others game like pilot wings, top gear have graphic bug. in paralel64 legacy work games who need expansion, but paralel64 core some games like mario kart run slow, in mupen64 run normal.

many thanks
if you need test or other thing
i can help.

**Comment by ethanaobrien** [comment]
There's nothing more I can do, wouldn't be a bad idea to use parallel as the default n64 legacy core.

Thank you!
