### ISSUE TITLE
Create NPM release

### ISSUE THREAD

**Issue by cohenerickson** [emulatorjs/emulatorjs#755]
I am working on a rewrite of my [website](https://github.com/Radon-Games/Radon-Games) and am looking to continue using EmulatorJS without having to include the source or use git submodules by installing via NPM. I think doing so brings an even larger user-base to the project as well as allows for an easier way of self-hosting the project for developers. Ideally it would do something very similar to `@ruffle-rs/ruffle`, by simply publishing all the files after being built including emulator cores. If this isn't something that this project is looking to do, I am happy to maintain a fork which releases to NPM.

**Comment by ethanaobrien** [comment]
As long as it's nothing too big, we could push It to upstream. My main question is how are you looking to interact with the emulator? Would you just like an easier way to include files?

**Comment by cohenerickson** [comment]
> My main question is how are you looking to interact with the emulator?

What I hope to do, is configure my server to statically serve files from `node_modules/@emulatorjs/emulatorjs` (or whatever the package name would be) that way I can simply include a script tag pointing to `/emulatorjs/data/loader.js`. From there I can interact with it as normal using the global configuration variables.

> Would you just like an easier way to include files?

Yes, I'm not looking for any sort of API layer on top that can be imported, just an easier way to include the files through NPM.

**Comment by ethanaobrien** [comment]
Should be easy enough, I can look at creating an emulatorjs npm package
