### ISSUE TITLE
[Bug] Can't Find The Keybinds To Eject And Swap Side Of FDS Disk.

### ISSUE THREAD

**Issue by EricWilliamYT** [emulatorjs/emulatorjs#756]
When I Was Using EmulatorJS 4.0.8, I Could Use Q And E To Eject And Swap Sides Of The Disk. But Now It Doesn't Seem To Work At All. Have You Changed The Keybinds, Or Am I Just Being Dumb?

**Comment by ethanaobrien** [comment]
Can you map the controls from the control settings menu? Or are they not there.

**Comment by EricWilliamYT** [comment]
No, can't use control menu to change them.

**Comment by ethanaobrien** [comment]
I'll add those to the control menu, that should fix the issue.

**Comment by EricWilliamYT** [comment]
alright thanks

**Comment by EricWilliamYT** [comment]
alright thanks

**Comment by ethanaobrien** [comment]
Keep this open till then

**Comment by ethanaobrien** [comment]
Fixed in 4.0.10
