### ISSUE TITLE
I Can't Get Arcade Games To Work

### ISSUE THREAD

**Issue by TrapjawwS** [emulatorjs/emulatorjs#757]
I can't get arcade games to work. I have tried multiple arcade cores, some don't work, but when it does, it loads Retroarcch for some reason. Here is my code:
```
<html>
    <head>
        <style>
            body {
                background-color: black;
                color: white;;
            }
        </style>
    </head>
    <body>
        <div style="width:100%;height:100%;max-width:100%">
            <div id="game"></div>
        </div>
        <script>
            EJS_player = "#game";
            EJS_core = "mame2003";
            EJS_color = "#000000";
            EJS_startOnLoaded = true;
            EJS_pathtodata = "../../storage/emulatorjs/data/";
            EJS_gameUrl = "https://archive.org/download/2020_01_06_fbn/roms/arcade.zip/arcade%2Fsfiii.zip";
        </script>
        <script src="../../storage/emulatorjs/data/loader.js"></script>
    </body>
</html>
```
The reason I have it loading the game from archive.org is because I'm broke and I use Cloudflare Pages for site hosting and it has a 25 mb limit for individual files :(

I have also seen multiple sites online running Street Fighter 3: 3rd Stike with emulatorjs, so I know it's possible. I have tried to inspect element and do the 'view-source' thing, but I can't find the code in the site where they actually run the game, so I'm kind of stuck.

This is what it loads every time.
![Screenshot 2024-01-29 8 37 14 AM](https://github.com/EmulatorJS/EmulatorJS/assets/145371179/c150d397-ca80-4cdd-acc5-1d698bfaa781)

Thanks for the help!

**Comment by TrapjawwS** [comment]
Oh, I just realized that the code gets all compressed. Whoopsie. (I'm a beginner programmer and I'm pretty sure the code needs to be formatted properly, so I'll just provide a screenshot of the code.
![Uploading Screenshot 2024-01-29 8.40.43 AM.png…]()

**Comment by ethanaobrien** [comment]
Whats in the console?

**Comment by TrapjawwS** [comment]
I'm sorry. I'm going to be honest with you, I'm using my school chromebook right now, and they disabled inspect element. :( When I get home I can check, and I'll send a screenshot.

**Comment by TrapjawwS** [comment]
Ok..ummm I solved it somehow. I used githack instead for the file and used the default arcade core. Yippee!

**Comment by ethanaobrien** [comment]
Oh, well that works I guess
