### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by Norbtails97** [emulatorjs/emulatorjs#759]
Playing N64, PSX, etc. is sooooo slow on my school chromebook, how do I speed it up? 
Specs:
Platform: Linux x86-64
CPU: MediaTek mt8183 (8 threads, 1.99GHz) (aarch64)
RAM: 4GB (3.794 Useable)

Google Chrome	120.0.6099.272 (Official Build) (32-bit) 
Revision	888dc4b15753efa1218bde8b900f3571b888e441-refs/branch-heads/6099@{#1876}
Platform	15662.88.0 (Official Build) stable-channel jacuzzi
Firmware Version	Google_Burnet.12573.380.0
Customization ID	esche
ARC	11319972 SDK Version: 30
JavaScript	V8 12.0.267.19
User Agent	Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

i want it to go from 30FPS--->60FPS pls.

**Comment by ethanaobrien** [comment]
Answer: get a new laptop. Literally not possible to just make low end hardware better
