### ISSUE TITLE
N64 Bizzare Polygon Bug.

### ISSUE THREAD

**Issue by manimanotaman** [emulatorjs/emulatorjs#760]
I have nothing really here, i have no idea how its happening. I cant open the error since inspect element is disabled on my device.
I dont think this will be fixed but this is the link is was using it on. https://statistics.profotoart.ch (press any of the buttons to get in)

**Comment by ethanaobrien** [comment]
Thats probably because the website you linked is several major versions behind. Maybe try contacting the owner
