### ISSUE TITLE
[Bug] Not working folowing the get started

### ISSUE THREAD

**Issue by suchorski** [emulatorjs/emulatorjs#779]
Just following this tutorial: https://emulatorjs.org/docs/Getting%20Started.html got this error

```
Uncaught (in promise) ReferenceError: GamepadHandler is not defined
    bindListeners emulator.js:1257
    EmulatorJS emulator.js:300
    <anonymous> loader.js:130
    async* loader.js:144
```

Am I missing something? Thanks

**Comment by ethanaobrien** [comment]
Looks like you have some files missing, what's the path to data set to?

**Comment by suchorski** [comment]
Using this one: https://cdn.jsdelivr.net/gh/EmulatorJS/EmulatorJS@latest/data/

**Comment by ethanaobrien** [comment]
Ah that would make sense. It should point to https://cdn.emulatorjs.org/stable/data/ now that the cores and minified files aren't in the repo, the docs are probably outdated

**Comment by suchorski** [comment]
In the docs have this link you showed me. I'll check later and get back to close the issue.

Thanks

**Comment by suchorski** [comment]
Working now... thanks
