### ISSUE TITLE
Menu button for mobile devices

### ISSUE THREAD

**Issue by imneckro** [emulatorjs/emulatorjs#78]
It would be great to add at virtual gamepad a menu button to open the menu on mobile devices by clicking it.
As it is now whenever you touch the screen to press a button the menu pops up and is kind of annoying.
Ruins game experience imho.

**Comment by ethanaobrien** [comment]
@imneckro I just pushed changes. Does this look good?

**Comment by imneckro** [comment]
@ethanaobrien i downloaded new emulator.js but now console throughs error This request has been blocked; the content must be served over HTTPS.

**Comment by imneckro** [comment]
Ethan did you remove  window.EJS_loadState and EJS_loadStateURL ?

**Comment by ethanaobrien** [comment]
> i downloaded new emulator.js but now console throughs error This request has been blocked; the content must be served over HTTPS.

Can you send a picture? I never touched these things with this update

>Ethan did you remove window.EJS_loadState and EJS_loadStateURL ?

No, I did not touch these files at all

**Comment by ethanaobrien** [comment]
@imneckro 

Can you go to [the github.io demo](https://ethanaobrien.github.io/emulatorjs/) on your phone and see if the menu button works?

**Comment by imneckro** [comment]
@ethanaobrien confirm button menu works

**Comment by ethanaobrien** [comment]
@imneckro Cool, so I can close this?

**Comment by imneckro** [comment]
Sure



Sent from myMail for iOS


Saturday, 8 January 2022, 22:23 +0200 from ***@***.***  ***@***.***>:
***@***.*** Cool, so I can close this?
