### ISSUE TITLE
[Bug] Saves are broken for code editor

### ISSUE THREAD

**Issue by Earth231** [emulatorjs/emulatorjs#781]
I play the game Pokemon Platinum for the DS, and it has worked in the past. Suddenly, the game will not save states for me. I have tried to download different .html files, but nothing fixes it. Also, trying to load saves has crashed the game a few times. 

I also played the SNES game Earthbound, and it took a while before the game would save its first state file.

Finally, the import and export save buttons don't work at all. Only the save and load state buttons work.

**Comment by Earth231** [comment]
Now,  Pokemon Platinum just crashes, even if the game is paused. 

[Screen recording 2024-02-21 6.11.13 AM.webm](https://github.com/EmulatorJS/EmulatorJS/assets/148776234/3851443a-7d65-4e96-979e-2f2ff4b734a5)

**Comment by ethanaobrien** [comment]
They arent broken, clear **all** data for that website. You can do so in settings
