### ISSUE TITLE
[Question] license of the file in the data folder

### ISSUE THREAD

**Issue by soimkim** [emulatorjs/emulatorjs#791]
What is the license of the file in the data folder (https://github.com/EmulatorJS/EmulatorJS/tree/v4.0.8/data/cores)?
Are those files also GPL-3.0?

**Comment by ethanaobrien** [comment]
Not all of them

RetroArch is also licensed under gpl 3 https://github.com/libretro/RetroArch/blob/master/COPYING

but all cores are licensed under different licenses, you can check the RetroArch docs for the corresponding core to get that informaiton.

Adding the core specific licenses to the right click menu has been on my list for a long time

**Comment by soimkim** [comment]
There is no information about the source of each data file in the docs. 
Which file in the repository can I check the download location or license of each data file?

**Comment by ethanaobrien** [comment]
The libretro docs: https://docs.libretro.com/meta/core-list/

**Comment by soimkim** [comment]
Thank you for your quick reply.
