### ISSUE TITLE
[Bug] Accessing the emulator state

### ISSUE THREAD

**Issue by MorenoIgor** [emulatorjs/emulatorjs#793]
I'm working on a project with the Master System core, with a routine that uses EJS_emulator.gameManager.getState() to periodically check the virtual RAM.

However the emulator now throws an uncaught error (#44, FS error) when calling this function. Tracing the source, it appears to come from the fact that the getState function somehow uses the file system to get the state file, which I believe was not the case before.

Is this the current intended behavior? If so, is there another way of reading the virtual machine's RAM?

Data used: _https://cdn.emulatorjs.org/stable/data/_
Loaders used: both _https://cdn.jsdelivr.net/gh/EmulatorJS/EmulatorJS@latest/data/loader.js_ and _https://cdn.emulatorjs.org/stable/data/loader.js_

**Comment by ethanaobrien** [comment]
Clear the sites data, the core version number wasn't bumped for the last update which has resulted in older cores being cached. A long term solution will come in the next update

**Comment by MorenoIgor** [comment]
Thanks, that did fix it! =)

**Comment by MorenoIgor** [comment]
Thanks, that did fix it! =)
