### ISSUE TITLE
supports openGL 1.0

### ISSUE THREAD

**Issue by climst** [emulatorjs/emulatorjs#795]
Hello.

I can't figure out if nintendo 64 supports openGL 1.0?
At startup, core mupen64plus_next-legacy-wasm is downloaded, but hangs at 99% when unpacking.

error - 
`Uncaught (in promise) RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): Compiling function #505 failed: Wasm SIMD unsupported @+292363). Build with -sASSERTIONS for more info.`

EmulatorJS v.4.0.11

**Comment by ethanaobrien** [comment]
I cant support any further back then what is already supported
