### ISSUE TITLE
[Bug]In some browsers on Android phones, games cannot save progress, such as Microsoft browser

### ISSUE THREAD

**Issue by yyj1983** [emulatorjs/emulatorjs#796]
In some browsers on Android phones, games cannot save progress, such as Microsoft browser

**Comment by ethanaobrien** [comment]
What progress? Do I get logs? I can do absolutely nothing without information that tells me what's wrong

Closing until required information is given

**Comment by yyj1983** [comment]
Uncaught TypeError: Cannot read properties of undefined (reading 'apply')
    at ccall (f9223a84-cdc4-44fe-9fc4-36a319e1754a:1:233082)
    at Object.getStateInfo (f9223a84-cdc4-44fe-9fc4-36a319e1754a:1:233650)
    at emulator.min.js:1:79482

**Comment by ethanaobrien** [comment]
Debug needs to be enabled

**Comment by yyj1983** [comment]
![QQ截图20240308123007](https://github.com/EmulatorJS/EmulatorJS/assets/57654301/03d1b812-eb6c-4a7c-beb4-9359d20f13dd)

**Comment by ethanaobrien** [comment]
https://emulatorjs.org/docs/Options.html#ejs-debug-xx

**Comment by yyj1983** [comment]
> https://emulatorjs.org/docs/Options.html#ejs-debug-xx

According to the settings you provided, EJS.DEBUG_XX=true
Prompt for this error

failed to start game TypeError: this.functions.setVSync is not a function
    at EJS_GameManager.setVSync (GameManager.js:310:24)
    at EmulatorJS.menuOptionChanged (emulator.js:3936:30)
    at addToMenu (emulator.js:4257:26)
    at EmulatorJS.setupSettingsMenu (emulator.js:4290:9)
    at EmulatorJS.startGame (emulator.js:1132:18)
    at emulator.js:1079:18

**Comment by ethanaobrien** [comment]
It appears you are using either the latest code or nightly code, which breaks at times because of changes being made that do not align with other commits. Please use the stable version

**Comment by yyj1983** [comment]
> It appears you are using either the latest code or nightly code, which breaks at times because of changes being made that do not align with other commits. Please use the stable version

good thanks

**Comment by yyj1983** [comment]
> It appears you are using either the latest code or nightly code, which breaks at times because of changes being made that do not align with other commits. Please use the stable version

I tried several versions just now but none of them worked. Which version works properly? For example, saving game progress

**Comment by yyj1983** [comment]
Or tell me. Which version can be used without any issues? thanks

**Comment by ethanaobrien** [comment]
I would need logs from the stable version...
