### ISSUE TITLE
[REQUEST] Add VSync option?

### ISSUE THREAD

**Issue by Norbtails97** [emulatorjs/emulatorjs#797]
Did you turn off sync by default for performance improvement? Can you add VSync support so I can play the games smoothly?

**Comment by RobLoach** [comment]
I'm getting the following when running locally...
```
failed to start game TypeError: this.functions.setVSync is not a function
```
This is after having re-built the minified files, and installing the cores.

**Comment by ethanaobrien** [comment]
@RobLoach use stable...

**Comment by RobLoach** [comment]
Stable does it. Nice work. :rocket:

**Comment by Norbtails97** [comment]
but how do you turn it on then?

**Comment by ethanaobrien** [comment]
You use nightly

**Comment by Norbtails97** [comment]
ty :D
