### ISSUE TITLE
Failed to start game

### ISSUE THREAD

**Issue by Norbtails97** [emulatorjs/emulatorjs#798]
since the update 20 hours ago, when I load a ROM, it "fails to start game"

**Comment by ethanaobrien** [comment]
Either

- Use stable
- Use nightly

**Comment by Norbtails97** [comment]
ty

**Comment by L-spec875** [comment]
I'm using the demo and neither works for me. And I can't get logs because I am on a managed Chromebook, sorry.

**Comment by L-spec875** [comment]
nvm stable works
