### ISSUE TITLE
[Bug] Saves still broken

### ISSUE THREAD

**Issue by zmarteline** [emulatorjs/emulatorjs#799]
I tested on Sega Genesis and loading saved game using the menu button still doesn't work.

  Quick save/load works normally.
(I cleared the browser to test).

**Comment by ethanaobrien** [comment]
Logs please! This tells me nothing

Closing until needed information is given




You could also use incognito mode to ensure 100% not a single thing is being cached

**Comment by zmarteline** [comment]
`emulator.js:1115 (2) ['-v', '/Altered Beast (BR).smd']
emulator.js:1089 Built for EmulatorJS Version 4.0.6
emulator.js:1089 Download a copy from https://github.com/EmulatorJS/EmulatorJS
emulator.js:1089 View the licence here: https://github.com/EmulatorJS/EmulatorJS/blob/main/LICENSE
emulator.js:1094 [INFO] RetroArch 1.17.0 (Git 730160afcc)
emulator.js:1094 [INFO] === Build =======================================
emulator.js:1094 [INFO] Capabilities: 
emulator.js:1094 [INFO] Version: 1.17.0
emulator.js:1094 [INFO] Git: 730160afcc
emulator.js:1094 [INFO] Built: Feb  6 2024
emulator.js:1094 [INFO] =================================================
emulator.js:1094 [INFO] [Input]: Found input driver: "emulatorjs".
emulator.js:1094 [INFO] [Overrides]: Redirecting save file to "/data/saves/Genesis Plus GX/Altered Beast (BR).srm".
emulator.js:1094 [INFO] [Overrides]: Redirecting save state to "/home/web_user/retroarch/userdata/states/Genesis Plus GX/Altered Beast (BR).state".
emulator.js:1094 [INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
emulator.js:1094 [INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_V2_INTL.
emulator.js:1094 [INFO] [Environ]: SET_CONTROLLER_INFO.
emulator.js:1094 [INFO] [Environ]: SET_INPUT_DESCRIPTORS:
emulator.js:1094 [INFO] [Environ]: RETRO_ENVIRONMENT_SET_CONTENT_INFO_OVERRIDE.
emulator.js:1094 [INFO] [Content Override]: File Extension: 'mdx' - need_fullpath: FALSE, persistent_data: FALSE
emulator.js:1094 [INFO] [Content Override]: File Extension: ' md' - need_fullpath: FALSE, persistent_data: FALSE
emulator.js:1094 [INFO] [Content Override]: File Extension: 'bin' - need_fullpath: FALSE, persistent_data: FALSE
emulator.js:1094 [INFO] [Content Override]: File Extension: 'smd' - need_fullpath: FALSE, persistent_data: FALSE
emulator.js:1094 [INFO] [Content Override]: File Extension: 'gen' - need_fullpath: FALSE, persistent_data: FALSE
emulator.js:1094 [INFO] [Content Override]: File Extension: 'bms' - need_fullpath: FALSE, persistent_data: FALSE
emulator.js:1094 [INFO] [Content Override]: File Extension: 'sms' - need_fullpath: FALSE, persistent_data: FALSE
emulator.js:1094 [INFO] [Content Override]: File Extension: ' gg' - need_fullpath: FALSE, persistent_data: FALSE
emulator.js:1094 [INFO] [Content Override]: File Extension: ' sg' - need_fullpath: FALSE, persistent_data: FALSE
emulator.js:1094 [INFO] [Content Override]: File Extension: '68k' - need_fullpath: FALSE, persistent_data: FALSE
emulator.js:1094 [INFO] [Content Override]: File Extension: 'sgd' - need_fullpath: FALSE, persistent_data: FALSE
emulator.js:1094 [INFO] [Environ]: GET_VFS_INTERFACE. Core requested version >= V2, providing V3.
emulator.js:1094 [INFO] [Environ]: GET_LED_INTERFACE.
emulator.js:1094 [INFO] [Environ]: PERFORMANCE_LEVEL: 1.
emulator.js:1094 [INFO] [Environ]: GET_LOG_INTERFACE.
emulator.js:1094 [INFO] [Environ]: PERFORMANCE_LEVEL: 7.
emulator.js:1094 [INFO] [Environ]: SET_SERIALIZATION_QUIRKS.
emulator.js:1094 [INFO] [Environ]: SET_DISK_CONTROL_INTERFACE.
emulator.js:1094 [INFO] [Content]: Loading content file: "/Altered Beast (BR).smd".
emulator.js:1094 [INFO] [Environ]: RETRO_ENVIRONMENT_GET_GAME_INFO_EXT.
emulator.js:1094 [INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
emulator.js:1094 [libretro INFO] Frontend supports RGB565 - will use that instead of XRGB1555.
emulator.js:1094 [WARN] [Environ]: SYSTEM DIR is empty, assume CONTENT DIR /Altered Beast (BR).smd
emulator.js:1094 [INFO] [Environ]: SYSTEM_DIRECTORY: "/".
emulator.js:1094 [INFO] [Environ]: SAVE_DIRECTORY: "/data/saves/Genesis Plus GX".
emulator.js:1094 [INFO] [Environ]: SET_AUDIO_BUFFER_STATUS_CALLBACK.
emulator.js:1094 [INFO] [Replay]: Found last replay slot: #0
emulator.js:1094 [INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
emulator.js:1094 [INFO] [Core]: Geometry: 256x192, Aspect: 1.524, FPS: 59.92, Sample rate: 44100.00 Hz.
emulator.js:1094 [INFO] [Audio]: Set audio input rate to: 44156.86 Hz.
emulator.js:1094 [INFO] [Video]: Set video size to: 879x576.
emulator.js:1094 [INFO] [EGL] Falling back to eglGetDisplay
emulator.js:1094 [INFO] [EGL]: EGL version: 1.4
emulator.js:1094 [INFO] [EGL]: Current context: 0xf234.
emulator.js:1094 [INFO] [EMSCRIPTEN/EGL]: Dimensions: 300x150
emulator.js:1094 [INFO] [GL]: Found GL context: "egl_emscripten".
emulator.js:1094 [INFO] [GL]: Detecting screen resolution: 300x150.
emulator.js:1094 [INFO] [GL]: Vendor: WebKit, Renderer: WebKit WebGL.
emulator.js:1094 [INFO] [GL]: Version: OpenGL ES 3.0 (WebGL 2.0 (OpenGL ES 3.0 Chromium)).
emulator.js:1094 [WARN] [GL]: GLES implementation does not have BGRA8888 extension.
emulator.js:1094 [GL]: 32-bit path will require conversion.
emulator.js:1094 [INFO] [GL]: Using resolution 300x150.
emulator.js:1094 [INFO] [GL]: Default shader backend found: glsl.
emulator.js:1094 [INFO] [Shader driver]: Using GLSL shader backend.
emulator.js:1094 [WARN] [GL]: Stock GLSL shaders will be used.
emulator.js:1094 [INFO] [GLSL]: Found GLSL vertex shader.
emulator.js:1094 [INFO] Shader log: WARNING: 0:3: 'GL_OES_standard_derivatives' : extension is not supported
emulator.js:1094 
emulator.js:1094 [INFO] [GLSL]: Found GLSL fragment shader.
emulator.js:1094 [INFO] Shader log: WARNING: 0:3: 'GL_OES_standard_derivatives' : extension is not supported
emulator.js:1094 
emulator.js:1094 [INFO] [GLSL]: Linking GLSL program.
emulator.js:1094 [INFO] [GLSL]: Found GLSL vertex shader.
emulator.js:1094 [INFO] Shader log: WARNING: 0:3: 'GL_OES_standard_derivatives' : extension is not supported
emulator.js:1094 
emulator.js:1094 [INFO] [GLSL]: Found GLSL fragment shader.
emulator.js:1094 [INFO] Shader log: WARNING: 0:3: 'GL_OES_standard_derivatives' : extension is not supported
emulator.js:1094 
emulator.js:1094 [INFO] [GLSL]: Linking GLSL program.
emulator.js:1094 [INFO] [GLSL]: Found GLSL vertex shader.
emulator.js:1094 [INFO] Shader log: WARNING: 0:3: 'GL_OES_standard_derivatives' : extension is not supported
emulator.js:1094 
emulator.js:1094 [INFO] [GLSL]: Found GLSL fragment shader.
emulator.js:1094 [INFO] Shader log: WARNING: 0:3: 'GL_OES_standard_derivatives' : extension is not supported
emulator.js:1094 
emulator.js:1094 [INFO] [GLSL]: Linking GLSL program.
emulator.js:1094 [INFO] [GL]: Using 4 textures.
emulator.js:1094 [INFO] [GL]: Loaded 1 program(s).
emulator.js:1094 [INFO] [Video]: Found display server: "null".
emulator.js:1094 [INFO] [OpenAL]: Using 10 buffers of 1024 bytes.
emulator.js:1094 [INFO] [Audio]: Started synchronous audio driver.
emulator.js:1094 [INFO] [Display]: Found display driver: "gl".
emulator.js:1094 [INFO] [Config]: Saved new config to "/home/web_user/retroarch/userdata/retroarch.cfg".
emulator.js:1094 [INFO] [Playlist]: Loading history file: "/home/web_user/retroarch/userdata/content_history.lpl".
emulator.js:1094 [INFO] [Playlist]: Loading history file: "/home/web_user/retroarch/userdata/content_music_history.lpl".
emulator.js:1094 [INFO] [Playlist]: Loading favorites file: "/home/web_user/retroarch/userdata/content_favorites.lpl".
emulator.js:1094 [ERROR] Cannot push NULL or empty core path into the playlist.
emulator.js:3825 shader disabled
emulator.js:1094 [ERROR] [GL]: none shader not supported, falling back to stock GLSL
emulator.js:1094 [INFO] [Shader driver]: Using GLSL shader backend.
emulator.js:1094 [WARN] [GL]: Stock GLSL shaders will be used.
emulator.js:1094 [INFO] [GLSL]: Found GLSL vertex shader.
emulator.js:1094 [INFO] Shader log: WARNING: 0:3: 'GL_OES_standard_derivatives' : extension is not supported
emulator.js:1094 
emulator.js:1094 [INFO] [GLSL]: Found GLSL fragment shader.
emulator.js:1094 [INFO] Shader log: WARNING: 0:3: 'GL_OES_standard_derivatives' : extension is not supported
emulator.js:1094 
emulator.js:1094 [INFO] [GLSL]: Linking GLSL program.
emulator.js:1094 [INFO] [GLSL]: Found GLSL vertex shader.
emulator.js:1094 [INFO] Shader log: WARNING: 0:3: 'GL_OES_standard_derivatives' : extension is not supported
emulator.js:1094 
emulator.js:1094 [INFO] [GLSL]: Found GLSL fragment shader.
emulator.js:1094 [INFO] Shader log: WARNING: 0:3: 'GL_OES_standard_derivatives' : extension is not supported
emulator.js:1094 
emulator.js:1094 [INFO] [GLSL]: Linking GLSL program.
emulator.js:1094 [INFO] [GLSL]: Found GLSL vertex shader.
emulator.js:1094 [INFO] Shader log: WARNING: 0:3: 'GL_OES_standard_derivatives' : extension is not supported
emulator.js:1094 
emulator.js:1094 [INFO] [GLSL]: Found GLSL fragment shader.
emulator.js:1094 [INFO] Shader log: WARNING: 0:3: 'GL_OES_standard_derivatives' : extension is not supported
emulator.js:1094 
emulator.js:1094 [INFO] [GLSL]: Linking GLSL program.
emulator.js:1094 [INFO] [Shaders]: Applying shader: "".
emulator.js:3825 fps hide
emulator.js:3825 ff-ratio 3.0
emulator.js:1089 invalid core option ff-ratio. This is not an error.
emulator.js:3825 sm-ratio 3.0
emulator.js:1089 invalid core option sm-ratio. This is not an error.
emulator.js:3825 fastForward disabled
emulator.js:1089 invalid core option fastForward. This is not an error.
emulator.js:3825 slowMotion disabled
emulator.js:1089 invalid core option slowMotion. This is not an error.
emulator.js:3825 rewindEnabled disabled
emulator.js:1089 invalid core option rewindEnabled. This is not an error.
emulator.js:3825 rewind-granularity 6
emulator.js:1089 invalid core option rewind-granularity. This is not an error.
emulator.js:3825 save-state-slot 1
emulator.js:1089 invalid core option save-state-slot. This is not an error.
emulator.js:3825 save-state-location download
emulator.js:1089 invalid core option save-state-location. This is not an error.
emulator.js:3825 virtual-gamepad disabled
emulator.js:1089 invalid core option virtual-gamepad. This is not an error.
emulator.js:3825 virtual-gamepad-left-handed-mode disabled
emulator.js:1089 invalid core option virtual-gamepad-left-handed-mode. This is not an error.
emulator.js:3825 genesis_plus_gx_frameskip_threshold 33
emulator.js:3825 genesis_plus_gx_lowpass_range 60
emulator.js:3825 genesis_plus_gx_psg_preamp 150
emulator.js:3825 genesis_plus_gx_fm_preamp 100
emulator.js:3825 genesis_plus_gx_cdda_volume 100
emulator.js:3825 genesis_plus_gx_pcm_volume 100
emulator.js:3825 genesis_plus_gx_audio_eq_low 100
emulator.js:3825 genesis_plus_gx_audio_eq_mid 100
emulator.js:3825 genesis_plus_gx_audio_eq_high 100
emulator.js:3825 genesis_plus_gx_enhanced_vscroll_limit 8
emulator.js:3825 genesis_plus_gx_psg_channel_0_volume 100
emulator.js:3825 genesis_plus_gx_psg_channel_1_volume 100
emulator.js:3825 genesis_plus_gx_psg_channel_2_volume 100
emulator.js:3825 genesis_plus_gx_psg_channel_3_volume 100
emulator.js:3825 genesis_plus_gx_md_channel_0_volume 100
emulator.js:3825 genesis_plus_gx_md_channel_1_volume 100
emulator.js:3825 genesis_plus_gx_md_channel_2_volume 100
emulator.js:3825 genesis_plus_gx_md_channel_3_volume 100
emulator.js:3825 genesis_plus_gx_md_channel_4_volume 100
emulator.js:3825 genesis_plus_gx_md_channel_5_volume 100
emulator.js:3825 genesis_plus_gx_sms_fm_channel_0_volume 100
emulator.js:3825 genesis_plus_gx_sms_fm_channel_1_volume 100
emulator.js:3825 genesis_plus_gx_sms_fm_channel_2_volume 100
emulator.js:3825 genesis_plus_gx_sms_fm_channel_3_volume 100
emulator.js:3825 genesis_plus_gx_sms_fm_channel_4_volume 100
emulator.js:3825 genesis_plus_gx_sms_fm_channel_5_volume 100
emulator.js:3825 genesis_plus_gx_sms_fm_channel_6_volume 100
emulator.js:3825 genesis_plus_gx_sms_fm_channel_7_volume 100
emulator.js:3825 genesis_plus_gx_sms_fm_channel_8_volume 100
emulator.js:4140 Available core options {shader: {…}, fps: {…}, ff-ratio: {…}, sm-ratio: {…}, fastForward: {…}, …}
emulator.js:3825 shader 4xScaleHQ.glslp
emulator.js:1094 [INFO] [Shader driver]: Using GLSL shader backend.
emulator.js:1094 [INFO] [GLSL]: Found GLSL vertex shader.
emulator.js:1094 [INFO] Shader log: WARNING: 0:3: 'GL_OES_standard_derivatives' : extension is not supported
emulator.js:1094 
emulator.js:1094 [INFO] [GLSL]: Found GLSL fragment shader.
emulator.js:1094 [INFO] Shader log: WARNING: 0:3: 'GL_OES_standard_derivatives' : extension is not supported
emulator.js:1094 
emulator.js:1094 [INFO] [GLSL]: Linking GLSL program.
emulator.js:1094 [INFO] [GLSL]: Found GLSL vertex shader.
emulator.js:1094 [INFO] [GLSL]: Found GLSL fragment shader.
emulator.js:1094 [INFO] [GLSL]: Linking GLSL program.
emulator.js:1094 [INFO] [GLSL]: Found GLSL vertex shader.
emulator.js:1094 [INFO] Shader log: WARNING: 0:3: 'GL_OES_standard_derivatives' : extension is not supported
emulator.js:1094 
emulator.js:1094 [INFO] [GLSL]: Found GLSL fragment shader.
emulator.js:1094 [INFO] Shader log: WARNING: 0:3: 'GL_OES_standard_derivatives' : extension is not supported
emulator.js:1094 
emulator.js:1094 [INFO] [GLSL]: Linking GLSL program.
emulator.js:1094 [INFO] [Shaders]: Menu shader set to: "/shader/shader.glslp".
emulator.js:1094 [INFO] [Shaders]: Applying shader: "/shader/shader.glslp".
emulator.js:516 Translation not found for 'BUTTON_4'. Language set to 'pt-BR'
emulator.js:516 Translation not found for 'BUTTON_2'. Language set to 'pt-BR'
emulator.js:516 Translation not found for 'BUTTON_1'. Language set to 'pt-BR'
emulator.js:516 Translation not found for 'LEFT_TOP_SHOULDER'. Language set to 'pt-BR'
emulator.js:516 Translation not found for 'BUTTON_3'. Language set to 'pt-BR'
emulator.js:516 Translation not found for 'RIGHT_TOP_SHOULDER'. Language set to 'pt-BR'
emulator.js:516 Translation not found for 'up arrow'. Language set to 'pt-BR'
emulator.js:516 Translation not found for 'down arrow'. Language set to 'pt-BR'
emulator.js:516 Translation not found for 'left arrow'. Language set to 'pt-BR'
emulator.js:516 Translation not found for 'right arrow'. Language set to 'pt-BR'
emulator.js:516 Translation not found for ''. Language set to 'pt-BR'
emulator.js:516 Translation not found for ''. Language set to 'pt-BR'
emulator.js:516 Translation not found for ''. Language set to 'pt-BR'
emulator.js:3825 shader 4xScaleHQ.glslp
emulator.js:1094 [INFO] [Shader driver]: Using GLSL shader backend.
emulator.js:1094 [INFO] [GLSL]: Found GLSL vertex shader.
emulator.js:1094 [INFO] Shader log: WARNING: 0:3: 'GL_OES_standard_derivatives' : extension is not supported
emulator.js:1094 
emulator.js:1094 [INFO] [GLSL]: Found GLSL fragment shader.
emulator.js:1094 [INFO] Shader log: WARNING: 0:3: 'GL_OES_standard_derivatives' : extension is not supported
emulator.js:1094 
emulator.js:1094 [INFO] [GLSL]: Linking GLSL program.
emulator.js:1094 [INFO] [GLSL]: Found GLSL vertex shader.
emulator.js:1094 [INFO] [GLSL]: Found GLSL fragment shader.
emulator.js:1094 [INFO] [GLSL]: Linking GLSL program.
emulator.js:1094 [INFO] [GLSL]: Found GLSL vertex shader.
emulator.js:1094 [INFO] Shader log: WARNING: 0:3: 'GL_OES_standard_derivatives' : extension is not supported
emulator.js:1094 
emulator.js:1094 [INFO] [GLSL]: Found GLSL fragment shader.
emulator.js:1094 [INFO] Shader log: WARNING: 0:3: 'GL_OES_standard_derivatives' : extension is not supported
emulator.js:1094 
emulator.js:1094 [INFO] [GLSL]: Linking GLSL program.
emulator.js:1094 [INFO] [Shaders]: Menu shader set to: "/shader/shader.glslp".
emulator.js:1094 [INFO] [Shaders]: Applying shader: "/shader/shader.glslp".
emulator.js:1094 [INFO] [Environ]: RETRO_ENVIRONMENT_SET_MINIMUM_AUDIO_LATENCY.
emulator.js:1094 [INFO] [Environ]: SET_GEOMETRY: 320x224, Aspect: 1.306.
emulator.js:1094 [INFO] [State]: Loading state "game.state", 4 bytes.
emulator.js:1094 [ERROR] [State]: Failed to load state from "game.state".
`

**Comment by ethanaobrien** [comment]
Can you please share the save state you're uploading

**Comment by zmarteline** [comment]
They are empty...
[saves.zip](https://github.com/EmulatorJS/EmulatorJS/files/14603953/saves.zip)

**Comment by ethanaobrien** [comment]
There are save files, not save states…..
