### ISSUE TITLE
Save state on iOS browser and/or override UI logic

### ISSUE THREAD

**Issue by birdinforest** [EmulatorJS/EmulatorJS#8]
Hi there, thanks for your work on this.
I found that the Save State button doesn't work on iOS. I guess it is because that the save file dialog doesn't work iOS browser. 

Do you know that if it is possible to save state on iOS browser without any hack?

Any chance that we could override UI logic to save data into indexDB of browser? Any advice will be appreciated.

Thanks again.

**Comment by ethanaobrien** [comment]
@birdinforest Are you using safari or have you tried chrome or firefox or other web browsers?

**Comment by birdinforest** [comment]
Hi @ethanaobrien Thanks for your reminder. I only tested Chrome this morning. The state save and state load work well on Safari. They don't work on Chrome. I haven't test on Firefox.

I'm still interested to know if there is any way to override state save&load. Any advice?

**Comment by ethanaobrien** [comment]
Awesome, if you get a chance, test Firefox and let me know. I don't really think there is anything I can do about this. iOS is known to have very little compatibility with everything. As for the indexed db option, it may be possible but the code is too scrambled to be able to do something like that. I'm very sorry, would you mind testing if the official emulatorjs.com works. Also, you are hosting it on a web server correct? Some JavaScript will not fun on a local file and blobs are part of that JavaScript

**Comment by birdinforest** [comment]
Yes I host it on a web server.  I will close this issue for now and update to you after I test offical emulatorjs and/or on the firefox.

Thanks for your time @ethanaobrien .
