### ISSUE TITLE
Nintendo DS Cursor is not accurate.

### ISSUE THREAD

**Issue by InTheMidl** [emulatorjs/emulatorjs#80]
Nintendo DS touchscreen cursor is not accurate. On mobile devices, the DS touch screen does not work.

**Comment by ethanaobrien** [comment]
There is a little crosshair that you must move around (by dragging) and then click the screen. Are you doing this?

**Comment by InTheMidl** [comment]
@ethanaobrien Yes, I am doing that but it's not that accurate.

**Comment by ethanaobrien** [comment]
Can you post a video?

**Comment by InTheMidl** [comment]
Video:
https://user-images.githubusercontent.com/91590573/148444741-477209b5-d68e-46fb-8073-7a4e955ef09a.mp4

**Comment by ethanaobrien** [comment]
Hmm, I'll take a look

**Comment by ethanaobrien** [comment]
Todo: implement mouse lock

**Comment by ethanaobrien** [comment]
Just pushed changes!
