### ISSUE TITLE
[Bug]error when set EJS_DEBUG_XX = true

### ISSUE THREAD

**Issue by zmarteline** [emulatorjs/emulatorjs#800]
I get this error when set EJS_DEBUG_XX = true;

![falha](https://github.com/EmulatorJS/EmulatorJS/assets/101960945/2e22961d-82c6-48e9-876f-9559a1573329)

screen keeps blank but game sound works.

PS: Please don't rush close the issues I open, I am trying to help leting you know about bugs... If you need further information just ask...

**Comment by ethanaobrien** [comment]
> I get this error when set EJS_DEBUG_XX = true;

Use stable or nightly 

> PS: Please don't rush close the issues I open, I am trying to help leting you know about bugs... If you need further information just ask...

I can re open a closed issue if there is a problem
