### ISSUE TITLE
[Request] Add option to add your own BIOS in demo

### ISSUE THREAD

**Issue by Norbtails97** [emulatorjs/emulatorjs#804]
On the demo, is there a workaround to install bios on the demo? for example, you wnt to play sonic cd. but you need a sega cd bios to run with it. can you make it possible to ADD the bios first, then the ROM?

**Comment by ethanaobrien** [comment]
Duplicate of #249. 

It's a **demo**, it is not meant to play every game, and will stay that way.

**Comment by ethanaobrien** [comment]
Though to answer your question just zip it with the rom

**Comment by Norbtails97** [comment]
really? ok. ty!
