### ISSUE TITLE
[Request] Make canvas the exact size of the native resolution, and let us size it ourselves using css transforms.

### ISSUE THREAD

**Issue by cpgb85** [emulatorjs/emulatorjs#808]
I need to do so custom styling because the portrait view on smaller devices is not very good.  The buttons overlay the screen causing issues.  Would be nice to have a feature where for example, if we load an nes game, the canvas size would load up as 256x240, and we can use CSS transforms or object-fit CSS property to scale it up. Would probably be better for performance also.

**Comment by ethanaobrien** [comment]
Sizing up an image often results in blur. In version 3.0 the canvas was always sized at 800x600 (or somewhere around there), this was changed in 4.0 and the image was noticeably clearer, even with nes. I don't think this is something that will be implemented

**Comment by michael-j-green** [comment]
One problem with this is that some systems used an interlaced video mode (looking at you Amiga and some Arcade systems), which would make the canvas half the height that it should be since interlacing only drew half the scan lines per field.

**Comment by ethanaobrien** [comment]
Closing as not planned
