### ISSUE TITLE
[Bug] All NDS roms freeze after rom load

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#809]
Hi,

Since updating to the latest version of EmulatorJS, all my NDS games freeze after load.
It shows this rectangle white screen on the center of the screen: 
![nds_bug](https://github.com/EmulatorJS/EmulatorJS/assets/10597517/979e4746-70ff-4eba-97df-d8e567ebb061)

This error message appears few times on the console:
735489de-bea8-48ce-873b-c91390d778d9:1 WebGL: INVALID_VALUE: texImage2D: invalid internalformat

I think the new shaders is what causing the problem.

Thank you

**Comment by ethanaobrien** [comment]
@n-at could this be related to your shader pr?

**Comment by S-Coding23** [comment]
I’m not having any issues. Have you tried it from the demo page? 

![IMG_5439](https://github.com/EmulatorJS/EmulatorJS/assets/135175291/59255ec1-138c-4e75-8c0f-2f609a616b4b)

**Comment by n-at** [comment]
> @n-at could this be related to your shader pr?

When shader is failed to load, RetroArch will disable it, game should not be affected.

@shaylevary Can you provide full console output?

**Comment by shaylevary** [comment]
No problem, attached. 
Thank you for the fast response regarding this issue.

[console_nds.txt](https://github.com/EmulatorJS/EmulatorJS/files/14854167/console_nds.txt)

**Comment by n-at** [comment]
I also can't reproduce this issue. I have message about texImage2D in console, but everything works.

Will disabling shader 2xScaleHQ.glslp (or choosing other one) work?

**Comment by shaylevary** [comment]
After a few tests I've found out that the problem appears when I pre-set the display to hybrid-top (bottom screen appears in small size on bottom right).
When I disable this pre-set on my code, it start the emulator with top-bottom display and everything worked fine.

This issue started to appear only since latest version.

**Comment by n-at** [comment]
I've reproduced this issue with settings like this:
![image](https://github.com/EmulatorJS/EmulatorJS/assets/2185280/849d4b74-2011-4dea-8dbe-454fd770c2f3)
and shader 2xScaleHQ or 4xScaleHQ. 
It works without shader or with CRT shaders.

**Comment by n-at** [comment]
Found the cause: I've copied 2xScaleHQ and 4xScaleHQ from the retroarch repository; they're slightly different there. Restored the original version in PR.
