### ISSUE TITLE
[Bug] emulator does not work with controllers that use axis for direction.

### ISSUE THREAD

**Issue by cpgb85** [emulatorjs/emulatorjs#812]
It doesn't do anything.  i tried this with 2 hyperkin controllers.

**Comment by ethanaobrien** [comment]
Map them in controller settings

**Comment by cpgb85** [comment]
> Map them in controller settings

Does not work.  It won't take the input.  This should not be closed.

**Comment by ethanaobrien** [comment]
> This should not be closed.

I got no logs, no "I tried x, x, and x", no "it works with other browser based controller games". So yes, it should be. I don't have any information on the actual issue

**Comment by cpgb85** [comment]
> > This should not be closed.
> 
> I got no logs, no "I tried x, x, and x", no "it works with other browser based controller games". So yes, it should be. I don't have any information on the actual issue

so? this is why github sucks. Something doesn't work.  I'm asking if anyone else if having issues.  oh well.

**Comment by ethanaobrien** [comment]
> I'm asking if anyone else if having issues.

This is not what GitHub issues are for
