### ISSUE TITLE
[Bug] version 4.0.10 after, the NDS console pointer cannot be moved. (mobile)

### ISSUE THREAD

**Issue by skyksit** [emulatorjs/emulatorjs#814]
https://demo.emulatorjs.org/

When you select NDS in mobile mode on the demo page, the pointer moves well up to version 4.0.9, but the pointer does not move after version 4.0.10.

The problem occurs starting with melonds-wasm.data version 11.

Android (chrome) Emulatorjs 4.0.10 ~
Mac (chrome) Emulatorjs 4.0.10 ~
Windows 11 (chome) Emulatorjs 4.0.10 ~
It seems that touch events in the mobile environment are the problem.

**Comment by ethanaobrien** [comment]
iOS or Android please

**Comment by skyksit** [comment]
Android (chrome)
Mac (chrome)
It seems that touch events in the mobile environment are the problem.

**Comment by ethanaobrien** [comment]
Fixed in 4.1.1
