### ISSUE TITLE
[Bug] Degraded performance on mobile browsers since version 4.0.10

### ISSUE THREAD

**Issue by birdinforest** [emulatorjs/emulatorjs#823]
#### Make sure your issue doesn't get closed! Make sure you have done the following items

- [ ] I have collected a **FULL** log of the console, with `EJS_DEBUG_XX` set to true, and uploaded it straight to GitHub.
- [x] I have not made any changes to the EmulatorJS instance I am running into this bug on.
- [x] I am on the latest version of EmulatorJS
- [x] I have not attached any images or logs via external sites. I have uploaded them straight to GitHub and acknowledge that external sites may pose a security issue.
- [ ] I have included, **IN DETAIL**, the steps to reproduce the bug.

**Affected Platforms:**

iOS 16.3.1 on iPhone
iPadOS 16.7.7 on iPad
Android 12 (SP1A.210812.016) - minor performance degrade

**Symptoms:**
Lower FPS and break audio. 
Performance issues are consistent across all platforms and all tested roms. For example, when running a NES rom on iPhone 13 the  FPS is cappted at 30 with broken audio playback.
Performance drops a little on Android. FPS remains on 60 while playing with notable FPS drops when the setting UI is toggle on.

**Comment by ethanaobrien** [comment]
Likely the vsync option, try turning it off. 

Core/RetroArch related code has was not updated with 4.0.10

**Comment by ethanaobrien** [comment]
Oh wait, I was incorrect on that. This might be because webgl2 is used by default on systems that support it. We should be able to add an option to force webgl (not webgl2) for users with devices that run webgl2 slower

**Comment by ethanaobrien** [comment]
This will be fixed in the next release
