### ISSUE TITLE
EmulatorJS V3

### ISSUE THREAD

**Issue by TrapjawwS** [emulatorjs/emulatorjs#826]
Hello! I'm trying to get netplay working. Is there somewhere I can download V3 or earlier of EmulatorJS? Thanks!

Edit: Quick question, can netplay emulate a GBA link cable?

**Comment by ethanaobrien** [comment]
> Hello! I'm trying to get netplay working. Is there somewhere I can download V3 or earlier of EmulatorJS? Thanks!

All versions of EmulatorJS can be found on [the cdn](https://cdn.emulatorjs.org/releases/) [v3.1.5](https://cdn.emulatorjs.org/releases/3.1.5.7z)

> Edit: Quick question, can netplay emulate a GBA link cable?

It cannot, and will likely not ever be able to

Also note [this page](https://emulatorjs.org/docs4devs/netplay), support for figuring out issues with netplay isnt currently supported (it doesnt really work)

**Comment by TrapjawwS** [comment]
Thank you!
