### ISSUE TITLE
Beginners guide to Enable Netplay

### ISSUE THREAD

**Issue by th3th3rmal7** [emulatorjs/emulatorjs#83]
Hello, i have the emulatorjs docker running within an Unraid server. I want to enable the Netplay feature but i'm not understanding, where and how do it apply this code..

Thank you for your help!

**Comment by ethanaobrien** [comment]
@th3th3rmal7 Could you send me the code you currently have?

**Comment by th3th3rmal7** [comment]
![image](https://user-images.githubusercontent.com/95710437/148671342-78c960d8-e5f4-4f2c-baf3-f0f478b8567e.png)

I'm sorry but I'm not sure where to obtain that, is currently a docker in unpaid, these are the images

in here?
![image](https://user-images.githubusercontent.com/95710437/148671422-3197782c-4cfb-40cb-9545-bad94666b2c0.png)

**Comment by ethanaobrien** [comment]
Like, whats the html code. All you need to do is add the line 

```
EJS_gameID = 1; // ID in your website, required for netplay.
```

when sending to the client

**Comment by ildomandatore** [comment]
I would also like to implement Netplay. Should I open a new post to avoid confusion?

**Comment by ethanaobrien** [comment]
If you'd like to create your own netplay server, use #59

**Comment by ildomandatore** [comment]
I think I understand that you are working on Netplay. I would like to host it directly on my website. I have 2tb of bandwidth and I have recently opened the website. That should be enough.

**Comment by ethanaobrien** [comment]
>I would like to host it directly on my website.

I would like to do that too, although I haven't really even scratched the surface

**Comment by ildomandatore** [comment]
No problem, I think it will take me at least a year before I need Netplay. I can wait for the development.

**Comment by ethanaobrien** [comment]
@ildomandatore

just realized, you're using https://github.com/linuxserver/emulatorjs 

You might want to open this issue there

**Comment by ethanaobrien** [comment]
@th3th3rmal7 

you're using https://github.com/linuxserver/emulatorjs not this repository

I've looked into https://github.com/linuxserver/emulatorjs and it doesnt use the same frontend (or backend) that I use. Just a similar project. Doesn't look like most of the UI features are implemented in the linuxserver version.

If you plan to use netplay you're probably going to need to use this repository

You might also want to open an issue [here](https://github.com/linuxserver/emulatorjs/issues)

**Comment by ildomandatore** [comment]
@ethanaobrien I guess you mentioned me by mistake.

**Comment by ethanaobrien** [comment]
@ildomandatore Yeah sorry.

Also, @ildomandatore I just completed the first working version of the working netplay server. If you look in the readme I have added instructions on how to use it! So you can self host your netplay server. Please report bugs you find!!

**Comment by ildomandatore** [comment]
Sure! I have 1GB of ram available, I'm afraid it's not enough for Netplay. I will try Netplay when I have a good income. In the meantime I wait for the video recording to have the audio and the implementation of the photos at the size of our screen and not the emulated device. If you will. I can wait. :)

**Comment by ethanaobrien** [comment]
@ildomandatore 
>video recording to have the audio

If you look at #47, it isn't currently possible because it isn't supported by browsers, so this will be a while.

>photos at the size of our screen

I'm not doing this, seems completely pointless to include extra data. Even if I wanted to. screenshots are taken using the emulator code, not javascript. What you want to do isn't possible

>I have 1GB of ram available

This should be plenty as long as you are running an os that has nodejs. It should take mayybe around 100mb when there are LOTS of users connected.
