### ISSUE TITLE
Bug in smsplus emulator - genesis_plus_gx worked fine

### ISSUE THREAD

**Issue by SelvinPL** [emulatorjs/emulatorjs#834]
This bug is not in emulator itself but in SMS emulation implementation

[changing emulator from genesis_plus_gx to smsplus for segaMS](https://github.com/EmulatorJS/EmulatorJS/commit/0dd28d6d57adf67faadbaa21a8f445f73c9519f5) introduce a bug

compare this two(take a look at the status bar in this example): 

- [4.0.11](https://selvin.pl/retro/large_map-sms.htm)
![image](https://github.com/EmulatorJS/EmulatorJS/assets/1252468/140de1c4-2d4c-49af-bbd3-3edfb6ba419f)

vs

- [4.0.12](https://selvin.pl/retro/large_map-sms-latest.htm)
![image](https://github.com/EmulatorJS/EmulatorJS/assets/1252468/8ed28e48-ef9c-436e-95be-87036c0ef9e9)

on real device(SMS 2 PAL) it works as in 4.0.11 version

can we choose between emulator implementation in this case? (fx by addin "segaMSGX" with "genesis_plus_gx")

**Comment by ethanaobrien** [comment]
Just set the core to `genesis_plus_gx`

**Comment by SelvinPL** [comment]
That was quick :D ... [and it's working](https://selvin.pl/retro/large_map-sms-gx.htm) ...

Closing

**Comment by SelvinPL** [comment]
@ethanaobrien btw where I can find source of smsplus so I could make an issue there

**Comment by ethanaobrien** [comment]
That would be here https://github.com/libretro/smsplus-gx
