### ISSUE TITLE
[Bug] Threads Not Working

### ISSUE THREAD

**Issue by Norbtails97** [emulatorjs/emulatorjs#836]
I have done with experimenting with my school chromebook to improve performance on beefy cores like DSemuME, Mupen64plus, PCSX_reARMed, etc. but I found one thing that could solve the lag issue...Threads!

I set EJS_threads to true; even I use supported cores like Mupen64plus, it give me that ¨Error for site owner check console¨ Error. DevTools is blocked by admin though, so i don't know what is going on then. Is there is anyway to solve this? Please?

P.S. I set the Pathtodata to the CDN and works fine while threads is off.

**Comment by ethanaobrien** [comment]
Use a non-school device to view the console log. 
That’s very obviously an error for the site owner and not an issue with this project so it makes no sense why you opened an issue here. 

I could always just say “it’s probably something the Chromebook admin is blocking” if you’re having issues on a school device

**Comment by Norbtails97** [comment]
console says:
Threads is set to true, but the SharedArrayBuffer function is not exposed. Threads requires 2 headers to be set when sending you html page. See https://stackoverflow.com/a/68630724 
what does this means?

**Comment by ethanaobrien** [comment]
That error literally tells you the fix...

**Comment by Norbtails97** [comment]
ok.  but how do I set headers to 2? i'm kinda noob about this.

**Comment by ethanaobrien** [comment]
google. I'm not here to guide you though setting up a server properly

**Comment by Norbtails97** [comment]
ok.
