### ISSUE TITLE
[Bug] FBNeo core not working???

### ISSUE THREAD

**Issue by Norbtails97** [emulatorjs/emulatorjs#838]
I'm Confused:
"This game is known but one of your romsets is missing files for THIS VERSION of FBNeo"
![Screenshot 2024-05-17 2 00 00 PM](https://github.com/EmulatorJS/EmulatorJS/assets/123211390/a7e192be-dd7b-470b-b7de-0082a2e60c3d)
Is it the ROM is missing files or the core? Or is it an invalid rom?

**Comment by ethanaobrien** [comment]
> THIS IS NOT A BUG! If you don't understand what this message means, then you need to read the arcade and FBNeo documentations at https://docs.libretro.com
