### ISSUE TITLE
Help Wanted

### ISSUE THREAD

**Issue by jalsarraf0** [emulatorjs/emulatorjs#846]
Hello,

I tried loading in two PSX roms which scanned and downloaded all the art fine. However, when launched it will load and kick me back into the RetroArch screen. I have both the roms and cue files in the same directories just in case. Below is the logs I found and a screenshot of the menu it takes my back to. Any help would be appreciated!

![image](https://github.com/EmulatorJS/EmulatorJS/assets/19882582/c3170a50-e3dc-4e61-8bba-97fd6d1ddd45)

[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

generating ED25519 keypair...done
peer identity: 12D3KooWBa22RUxivxve1pnEa4XvmuPEYPMxP4yGv2cpFXLnopX3
initializing IPFS node at /data/.ipfs
[custom-init] No custom files found, skipping...
Connection to localhost (127.0.0.1) 80 port [tcp/http] succeeded!
Initializing daemon...
Kubo version: 0.24.0
Repo version: 15
System version: amd64/linux
Golang version: go1.21.10
2024/06/20 00:02:36 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/127.0.0.1/udp/4001/quic-v1
Swarm listening on /ip4/127.0.0.1/udp/4001/quic-v1/webtransport/certhash/uEiB7ml0gmNHgkEJURiYphW1dsEzAQ-ZBub_IjRB3rAN0ow/certhash/uEiCl5z1jc72pcIx-LzbF5rLO5jOfuT53vq72XRYmAKe7Sg
Swarm listening on /ip4/172.21.0.4/tcp/4001
Swarm listening on /ip4/172.21.0.4/udp/4001/quic-v1
Swarm listening on /ip4/172.21.0.4/udp/4001/quic-v1/webtransport/certhash/uEiB7ml0gmNHgkEJURiYphW1dsEzAQ-ZBub_IjRB3rAN0ow/certhash/uEiCl5z1jc72pcIx-LzbF5rLO5jOfuT53vq72XRYmAKe7Sg
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /ip6/::1/udp/4001/quic-v1
Swarm listening on /ip6/::1/udp/4001/quic-v1/webtransport/certhash/uEiB7ml0gmNHgkEJURiYphW1dsEzAQ-ZBub_IjRB3rAN0ow/certhash/uEiCl5z1jc72pcIx-LzbF5rLO5jOfuT53vq72XRYmAKe7Sg
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/127.0.0.1/udp/4001/quic-v1
Swarm announcing /ip4/127.0.0.1/udp/4001/quic-v1/webtransport/certhash/uEiB7ml0gmNHgkEJURiYphW1dsEzAQ-ZBub_IjRB3rAN0ow/certhash/uEiCl5z1jc72pcIx-LzbF5rLO5jOfuT53vq72XRYmAKe7Sg
Swarm announcing /ip4/172.21.0.4/tcp/4001
Swarm announcing /ip4/172.21.0.4/udp/4001/quic-v1
Swarm announcing /ip4/172.21.0.4/udp/4001/quic-v1/webtransport/certhash/uEiB7ml0gmNHgkEJURiYphW1dsEzAQ-ZBub_IjRB3rAN0ow/certhash/uEiCl5z1jc72pcIx-LzbF5rLO5jOfuT53vq72XRYmAKe7Sg
Swarm announcing /ip4/216.97.243.91/udp/4001/quic-v1
Swarm announcing /ip4/216.97.243.91/udp/4001/quic-v1/webtransport/certhash/uEiB7ml0gmNHgkEJURiYphW1dsEzAQ-ZBub_IjRB3rAN0ow/certhash/uEiCl5z1jc72pcIx-LzbF5rLO5jOfuT53vq72XRYmAKe7Sg
Swarm announcing /ip6/::1/tcp/4001
Swarm announcing /ip6/::1/udp/4001/quic-v1
Swarm announcing /ip6/::1/udp/4001/quic-v1/webtransport/certhash/uEiB7ml0gmNHgkEJURiYphW1dsEzAQ-ZBub_IjRB3rAN0ow/certhash/uEiCl5z1jc72pcIx-LzbF5rLO5jOfuT53vq72XRYmAKe7Sg
RPC API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
Gateway server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
Connection to localhostConnection to localhost (::1) (::1) 4001 port [tcp/*] succeeded!
 3001 port [tcp/*] succeeded!
Connection to localhost (::1) 3000 port [tcp/*] succeeded!
[ls.io-init] done.
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, scandir '/data/config/'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: '/data/config/'
}
Connection to localhost (::1) 3000 port [tcp/*] succeeded!
2024-06-20T01:28:40.374Z        ERROR   core:constructor        node/provider.go:88
🔔🔔🔔 YOU ARE FALLING BEHIND DHT REPROVIDES! 🔔🔔🔔

⚠️ Your system is struggling to keep up with DHT reprovides!
This means your content could partially or completely inaccessible on the network.
We observed that you recently provided 157 keys at an average rate of 29.612157277s per key.

💾 Your total CID count is ~1328 which would total at 10h55m24.944863856s reprovide process.

⏰ The total provide time needs to stay under your reprovide interval (0s) to prevent falling behind!

💡 Consider enabling the Accelerated DHT to enhance your reprovide throughput. See:
https://github.com/ipfs/kubo/blob/master/docs/config.md#routingaccelerateddhtclient

Received interrupt signal, shutting down...
(Hit ctrl-c again to force-shutdown the daemon.)
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

[ipfs-upgrade] Checking if fs-repo needs to be upgraded (this may take some time)
ipfs migration: already at version 15
[custom-init] No custom files found, skipping...
Connection to localhost (127.0.0.1) 80 port [tcp/http] succeeded!
Initializing daemon...
Kubo version: 0.24.0
Repo version: 15
System version: amd64/linux
Golang version: go1.21.10
2024/06/20 02:09:58 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/127.0.0.1/udp/4001/quic-v1
Swarm listening on /ip4/127.0.0.1/udp/4001/quic-v1/webtransport/certhash/uEiB7ml0gmNHgkEJURiYphW1dsEzAQ-ZBub_IjRB3rAN0ow/certhash/uEiCl5z1jc72pcIx-LzbF5rLO5jOfuT53vq72XRYmAKe7Sg
Swarm listening on /ip4/172.21.0.4/tcp/4001
Swarm listening on /ip4/172.21.0.4/udp/4001/quic-v1
Swarm listening on /ip4/172.21.0.4/udp/4001/quic-v1/webtransport/certhash/uEiB7ml0gmNHgkEJURiYphW1dsEzAQ-ZBub_IjRB3rAN0ow/certhash/uEiCl5z1jc72pcIx-LzbF5rLO5jOfuT53vq72XRYmAKe7Sg
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /ip6/::1/udp/4001/quic-v1
Swarm listening on /ip6/::1/udp/4001/quic-v1/webtransport/certhash/uEiB7ml0gmNHgkEJURiYphW1dsEzAQ-ZBub_IjRB3rAN0ow/certhash/uEiCl5z1jc72pcIx-LzbF5rLO5jOfuT53vq72XRYmAKe7Sg
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/127.0.0.1/udp/4001/quic-v1
Swarm announcing /ip4/127.0.0.1/udp/4001/quic-v1/webtransport/certhash/uEiB7ml0gmNHgkEJURiYphW1dsEzAQ-ZBub_IjRB3rAN0ow/certhash/uEiCl5z1jc72pcIx-LzbF5rLO5jOfuT53vq72XRYmAKe7Sg
Swarm announcing /ip4/172.21.0.4/tcp/4001
Swarm announcing /ip4/172.21.0.4/udp/4001/quic-v1
Swarm announcing /ip4/172.21.0.4/udp/4001/quic-v1/webtransport/certhash/uEiB7ml0gmNHgkEJURiYphW1dsEzAQ-ZBub_IjRB3rAN0ow/certhash/uEiCl5z1jc72pcIx-LzbF5rLO5jOfuT53vq72XRYmAKe7Sg
Swarm announcing /ip4/216.97.243.91/udp/4001/quic-v1
Swarm announcing /ip4/216.97.243.91/udp/4001/quic-v1/webtransport/certhash/uEiB7ml0gmNHgkEJURiYphW1dsEzAQ-ZBub_IjRB3rAN0ow/certhash/uEiCl5z1jc72pcIx-LzbF5rLO5jOfuT53vq72XRYmAKe7Sg
Swarm announcing /ip6/::1/tcp/4001
Swarm announcing /ip6/::1/udp/4001/quic-v1
Swarm announcing /ip6/::1/udp/4001/quic-v1/webtransport/certhash/uEiB7ml0gmNHgkEJURiYphW1dsEzAQ-ZBub_IjRB3rAN0ow/certhash/uEiCl5z1jc72pcIx-LzbF5rLO5jOfuT53vq72XRYmAKe7Sg
RPC API server listening on /ip4/127.0.0.1/tcp/5001
WebUI: http://127.0.0.1:5001/webui
Gateway server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
Connection to localhost (::1) 3000 port [tcp/*] succeeded!
Connection to localhost (::1) 3001 port [tcp/*] succeeded!
Connection to localhost (::1) 4001 port [tcp/*] succeeded!
[ls.io-init] done.
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: EISDIR: illegal operation on a directory, read] {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}
Connection to localhost (::1) 3000 port [tcp/*] succeeded!
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: EISDIR: illegal operation on a directory, read] {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}
Connection to localhost (::1) 3000 port [tcp/*] succeeded!

**Comment by ethanaobrien** [comment]
This is not linuxservers docker. Do note that project is no longer actively maintained, and has had nothing but bot “updates” for like 5 months now. 

You are looking for https://github.com/linuxserver/docker-emulatorjs please give their readme a read
