### ISSUE TITLE
problem running large archives on ps1

### ISSUE THREAD

**Issue by climst** [emulatorjs/emulatorjs#848]
hello.
When running games on ps1 there was a problem.
Games are packaged in 7z, if the archive size is more than 300-350mb, the game is not launched. 
In the process of loading the emulator, the core is downloaded first, then download the archive with the game, but unpacking the archive with the game does not start, and the download process immediately jumps to download the BIOS.

What can be the problem?
There is no such problem with archives less than 200mb.

**Comment by ethanaobrien** [comment]
Correct, this is a browser limitation, not an emulatorjs limitation.

the emulator will attempt to download and load any file you throw at it, whether or not your computer can actually handle it is up to the browser
