### ISSUE TITLE
emulators

### ISSUE THREAD

**Issue by 2pro12342** [emulatorjs/emulatorjs#849]
I'm trying to add Forza Horizon Moto sport on Xbox and Super Smash Bros Ultimate on Nintendo Switch on to my website, but I cannot find any of those emulators. can you add the emulators or not?

**Comment by ethanaobrien** [comment]
Neither Xbox nor Nintendo switch is supported, and will not be for a very, very long time

**Comment by 2pro12342** [comment]
how about the Wii, GameCube, or the Nintendo 3DS?

Edited by admin to remove link

**Comment by ethanaobrien** [comment]
Also no, youre expecting quite a bit from a web browser here arent you...

https://emulatorjs.org/docs4devs/cores#unavailable-cores-that-reasons-are-known
