### ISSUE TITLE
Defining EJS_loadStateURL ='gamesave.state' doesnt work

### ISSUE THREAD

**Issue by imneckro** [emulatorjs/emulatorjs#85]
It appears in network logging that EJS_loadStateURL ='gamesave.state' gets gamesave.state and downloads it but never loads it on emulator.
Also i cannot find EJS_loadStateFromURL(); mention in emulator.js as it was before.

**Comment by nenge123** [comment]
```javascript
EJS_onGameStart = e=>{
   console.log(e);
},
// in game do!
EJS_onLoadState = fn=>{
//fn = ejs class
//fn.defaultControllers.loadState(buf);
console.log(fn);
openUI(fn);

}
EJS_onSaveState = data=>console.log(data);

```

**Comment by ethanaobrien** [comment]
>Also i cannot find EJS_loadStateFromURL(); mention in emulator.js as it was before.

I removed this, embeded it directly in the `emulator.js` file

`EJS_loadStateURL` should still work, I'll look at this

**Comment by ethanaobrien** [comment]
@imneckro Turns out I had a typo when converting to a uint8array. Can you pull updates and try again?

**Comment by imneckro** [comment]
@ethanaobrien yes it works. nice!
Ethan is it possible to predefine roomname like EJS_PlayerName?

**Comment by ethanaobrien** [comment]
>Ethan is it possible to predefine roomname like EJS_PlayerName?

nope, The netplay form seems really advanced so I havent really messed with it

I am going to go ahead and close this

**Comment by imneckro** [comment]
@ethanaobrien ok thanks.
i messed with netplay form.. im already predifining roomname inside emulator.js.
I just wondering if i can predefine it outside emulator.js with loader.js.
you can check out here my progress (make sure to turn english translate on, cause im designing it in greek)
https://retrothess.ddns.net
user01////user01
