### ISSUE TITLE
Selecting disk number when running games on ps1

### ISSUE THREAD

**Issue by climst** [emulatorjs/emulatorjs#850]
Hello.
PS1 has games on multiple disks. I have seen on several sites when loading the emulator you can select which disk to load. 
Example on the screenshot.
Is such a function realized? If not, I hope you will add it.
Thank you. 
![1](https://github.com/EmulatorJS/EmulatorJS/assets/162485909/63755032-db88-4ca4-b845-986ca75d187c)

**Comment by michael-j-green** [comment]
EJS supports multiple disks using M3U files. As EJS is a wrapper for RetroArch and Libretro, you can use the guides on Libretro's site to setup multi-disks: https://docs.libretro.com/library/pcsx_rearmed/#multiple-disk-games

When you run EJS using an M3U file, you'll get a floppy disk icon in the bottom right of the screen that you can click to select the disk.
