### ISSUE TITLE
[Bug] desmume2015 nds game touch don't work

### ISSUE THREAD

**Issue by Axlerx** [emulatorjs/emulatorjs#852]
#### Make sure your issue doesn't get closed! Make sure you have done the following items

- [x] I have collected a **FULL** log of the console, with `EJS_DEBUG_XX` set to true, and uploaded it straight to GitHub.
- [x] I have not made any changes to the EmulatorJS instance I am running into this bug on.
- [x] I am on the latest version of EmulatorJS
- [x] I have not attached any images or logs via external sites. I have uploaded them straight to GitHub and acknowledge that external sites may pose a security issue.
- [x] I have included, **IN DETAIL**, the steps to reproduce the bug.

When I use EmuJS to play NES games, I found that touch events don't work, even though JavaScript does respond to touch events. Additionally, in iOS Safari and Chrome, when using DeSmuME to play NES games, the game fails to start. It finishes loading the core and then crashes.

[Log] [bindlisten] touchstart (2) (emulator.js, line 1261)
MouseEvent {isTrusted: true, screenX: 263, screenY: 231, clientX: 263, clientY: 231, …}
function focus() { [native code] }

**Comment by Axlerx** [comment]
DeSmuME works fine on Android and Mac, but encounters issues on iPhone's Safari.

**Comment by ethanaobrien** [comment]
This is a duplicate of #814

**Comment by ethanaobrien** [comment]
Closing as duplicate

**Comment by Axlerx** [comment]
melonds could not running in safari, when loading game core 100% will crash @ethanaobrien

**Comment by ethanaobrien** [comment]
Please provide logs

**Comment by Axlerx** [comment]
> Please provide logs

There is no log. When the core is loaded and unpacked, the page returns to the game selection page.

**Comment by ethanaobrien** [comment]
There are always logs. You need to connect the iPhone to a macOS device and enable developer tools. 

While yes I have an iPhone, I have no crashing issues with melonds
