### ISSUE TITLE
Cloudflare Pages only supports files up to 25 MiB in size

### ISSUE THREAD

**Issue by aidscooler** [emulatorjs/emulatorjs#854]
Hello there.I'm looking for some help.
Here is my problem:  The game ROM file "Metal Slug7.nds" is 64 MiB in size , but Cloudflare Pages only supports files up to 25 Mib in size. If there is any way to solve the problem except changing another static website hosting platform?

**Comment by ethanaobrien** [comment]
I missed how this is an issue with EmulatorJS. That would be an issue you open with cloudflare.
