### ISSUE TITLE
game control

### ISSUE THREAD

**Issue by zhangmenglong-github** [emulatorjs/emulatorjs#857]
Please tell me how to control the triggering of buttons through js code, such as starting, ending the game and moving the character.

**Comment by ethanaobrien** [comment]
You can call the [simulateInput](https://github.com/EmulatorJS/EmulatorJS/blob/611a8c26d61152decb6b0522786338d8eda2ef7e/data/GameManager.js#L189) function

`window.EJS_emulator.gameManager.simulateInput(player, button, value)`

See https://github.com/EmulatorJS/EmulatorJS/blob/611a8c26d61152decb6b0522786338d8eda2ef7e/data/emulator.js#L3024
