### ISSUE TITLE
replaceAll() function not supported in Chrome 84 or lower

### ISSUE THREAD

**Issue by IvanStoilov86** [emulatorjs/emulatorjs#861]
Running EmulatorJS in Chrome 84 or lower shows a black screen and throws the following error in the console, as the replaceAll() function isn't supported until Chrome 85:
![console](https://github.com/user-attachments/assets/faa7bde0-6165-456d-8410-d3b78105178d)
Tested on Chrome 83.0.4103.106

**Comment by ethanaobrien** [comment]
This has been fixed in https://github.com/EmulatorJS/EmulatorJS/commit/f7fa56757b41da8ec1ac947f60b474ad135b80f5. Keeping this issue open until the next stable release

**Comment by ethanaobrien** [comment]
Fixed in 4.1.1
