### ISSUE TITLE
Quit Game?

### ISSUE THREAD

**Issue by brunotrevisan** [emulatorjs/emulatorjs#864]
Is there any routine that closes EJS? something like quitgame exitgame

**Comment by ethanaobrien** [comment]
Currently there is not, you just close the tab page.

Though that does make me think. That’s probably why this one feature doesn’t work properly. Adding a “shutdown EJS” button would give the emulator the time to properly shutdown. Great idea

**Comment by brunotrevisan** [comment]
the idea would be to close without closing the page, the colors themselves have the retro_unload function

**Comment by ethanaobrien** [comment]
Correct

though I should note - if you’re looking to load the emulator again, that won’t work, because of how many properties get defined on the window object

**Comment by brunotrevisan** [comment]
delete window.EJS_DUMMYSTORAGE;
delete window.EJS_GameManager;
delete window.EJS_SHADERS;
delete window.EJS_STORAGE;
delete window...... .

maybe it would be a solution?

**Comment by ethanaobrien** [comment]
> maybe it would be a solution?

those are just static class definitions… deleting them would do nothing

The issue is not EmulatorJS - there is no way to free up used webassembly memory without reloading the page. I wouldn’t even say this is a design flaw, it’s made to be a virtual machine, and acts exactly how a virtual machine would. (As I’ve had to explain in issues, message threads, etc over and over again. Nobody seems to understand  you can’t just do that)

EmulatorJS will likely never be able to discard and load a new context itself. Use an iframe.

**Comment by brunotrevisan** [comment]
I was studying here and saw that the memory is actually overloaded with emscripten, in addition to bringing several files that are from RA and are not used, it is even possible to reset the memory in parts, in this case the modules should be loaded beforehand and only some settings should be relaunched but it seems like a huge effort for little result, the iframe becomes more attractive, however creating a function to Unload the game, you could create an event like EJS_onGameUnload, triggering this event for the user, that would be really COOL :D

**Comment by ethanaobrien** [comment]
> memory is actually overloaded with emscripten

Not true, emscripten itself does a decent job with memory freeing/allocating. Webassembly is the "issue".

Think of a virtual machine, how can the host truly know when the guest operating system is done with the memory its allocated? Even if the guest was to write zeros when a free call is called, how does the host know we dont need these zeros? Once allocated, it will not consume less memory, its not an emscripten issue, its a webassembly "issue"

> in addition to bringing several files that are from RA and are not used

if they're not used, why would memory then be an issue? This would affect binary size, but long term memory usage would be static.

> it is even possible to reset the memory in parts

I don't understand what you're trying to say here, or how this would help solve the issue.

> and only some settings should be relaunched

The emscripten RetroArch build target does not have working dynamic linking, and its not worth the effort to do. In theory it would be possible to re-use the context for another game of the same system, but its really not worth it.

**Comment by michael-j-green** [comment]
I assume you're wanting to run code when the emulator closes down, like save state or something similar?

With ``window.onbeforeunload`` you do have some (limited) opportunity to execute some code.

An alternative is to run a timer in the background on the hosting page that regularly grabs the state of EJS and saves that somewhere.

**Comment by ethanaobrien** [comment]
here are some sources showing it’s not possible to “unload” a webassembly instance, and your concern about memory

https://github.com/emscripten-core/emscripten/issues/19470#issuecomment-1568439870

https://github.com/WebAssembly/design/issues/1397

https://github.com/emscripten-core/emscripten/issues/18080

(Note to self: add links to docs)
