### ISSUE TITLE
[Bug] WHLoader file package doesn't support by the current Amiga core

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#867]
Hi,

I would like to know please if you were able to achieve any progress in adding support for loading WHLoader format files for the Amiga Core?

Currently a normal adf format file  takes a long time to load until you can start playing, while whloader files loads much faster as it emulate hdd loading instead of diskette loading.

Thank you.

**Comment by ethanaobrien** [comment]
Please don’t open new issues when there are issues already open for a topic, just comment on that one

**Comment by shaylevary** [comment]
Sorry, you are right.

Btw, There is a decoded version of emulatorjs 0.5.8 on the net, among its core files you can also find the Amiga emulation core file that supports loading of WHLoader files.
Perhaps the code that appears there can be used to fix here the support of WHLoader file format.
Here is the github project:
https://github.com/nenge123/emulatorjs/tree/0.5.8

**Comment by ethanaobrien** [comment]
Fixed in 4.1.1
