### ISSUE TITLE
Unsuccessful download of game core

### ISSUE THREAD

**Issue by IvanStoilov86** [emulatorjs/emulatorjs#869]
When running the emulator on the Latest channel, it hangs on "Download Game Core" and throws the following error:
![image](https://github.com/user-attachments/assets/80367870-ebf3-4732-895d-8c20a9d2a393)
Tested:
Core: Gambatte, OS: Windows 10, Browser: Chrome.
This doesn't happen when using the Stable channel.

**Comment by ethanaobrien** [comment]
Use stable, or use nightly. “Latest” breaks the most out of any of the options, since the code is up to date, but the cores are held back
