### ISSUE TITLE
Unable to use virtual game pad on IOS.

### ISSUE THREAD

**Issue by bu2d** [emulatorjs/emulatorjs#87]
The demo pages allow the use of a virtual game pad on IOS. However, I am unable to use this feature on my own installation and have found no documentation on activating this function.

**Comment by ethanaobrien** [comment]
You have request desktop site turned off, correct?

**Comment by bu2d** [comment]
Correct it is set to mobile. I tried switching from mobile to desktop and back but nothing changed.

**Comment by bu2d** [comment]
Turns out I’m using this docker https://github.com/linuxserver/emulatorjs on my unraid server.

Not an issue with your build. Probably just something they changed.

Is there a docker template for your build?

**Comment by ethanaobrien** [comment]
>Is there a docker template for your build?

No sorry. I'm not familiar with docker. You might want to open an issue on that repository

**Comment by bu2d** [comment]
Can confirm they removed touchscreen controls on their build.

**Comment by ethanaobrien** [comment]
>Can confirm they removed touchscreen controls on their build.

Ok, thank you. Can I close this?

**Comment by bu2d** [comment]
Yes
