### ISSUE TITLE
Adding PrBoom

### ISSUE THREAD

**Issue by pastisme** [emulatorjs/emulatorjs#873]
Hello,

I tried to add [PrBoom](https://docs.libretro.com/library/prboom/) core to emulatorjs, it compiles and runs fine
![image](https://github.com/user-attachments/assets/35f549cf-19cc-4a72-b5aa-d3d82654d378)

But I came across one problem:
When I upload doom.wad to the index.html page it eventually calls the core with "doom" as first argument (the extension is dropped).
(This does not occur if I zip doom.wad and upload doom.zip).
I tried to read the code in EmulatorJS::downloadRom(), it seems that this is all done on purpose but I am having hard time figuring out whether it's a bug or a feature ?

Any insight ?
Thanks

**Comment by ethanaobrien** [comment]
> When I upload doom.wad to the index.html page it eventually calls the core with "doom" as first argument (the extension is dropped).
(This does not occur if I zip doom.wad and upload doom.zip).

This is neither a bug, nor a feature. More a limitation

When you just upload the rom, all that’s given to EmulatorJS is a blob of data, and the file name before the last dot (as the “name” of the game). EmulatorJS will default to using this “name” if it cannot find the original file name

**Comment by pastisme** [comment]
Ah, I see, the Blob object is constructed in index.html.
However it is constructed out of the first file from the input field:
```javascript
const url = new Blob([input.files[0]])
```
But the files property from input is of type File[] and File inherits from Blob.
So it should be possible to directly use input.files[0] which retains the file name inside its name property.

I will check that option.

**Comment by ethanaobrien** [comment]
You’re right, it should be possible to do it that way, though EmulatorJS itself will need to have added support for the file object first

**Comment by ethanaobrien** [comment]
https://github.com/EmulatorJS/build/commit/b1df9e6115af07e9132693bba5dd8ba46bd7efb1

**Comment by ethanaobrien** [comment]
Added in 4.1.1
