### ISSUE TITLE
How to parse game state

### ISSUE THREAD

**Issue by Johnly1986** [emulatorjs/emulatorjs#874]
How is the state data returned in the getState function mapped to the RAM memory block ?

**Comment by ethanaobrien** [comment]
getState returns current memory at a specific address. What are you trying to do?

**Comment by Johnly1986** [comment]
I want to analyze the game memory to obtain runtime status data, such as level name, character health, ability, etc.

**Comment by ethanaobrien** [comment]
Good luck with that - it's not something I myself know how to do or support. It's very dependent on game and in my opinion not worth it.

I believe the webassembly memory object is also somewhere inside `EJS_emulator.gameManager.Module`
