### ISSUE TITLE
[Bug] Volume Slider Doesnt Change Volume

### ISSUE THREAD

**Issue by S-Coding23** [emulatorjs/emulatorjs#879]
In 4.1.1, the volume slider doesnt actually change the volume level. There is nothing output in the console logs. I have tested on Firefox and Chrome from Windows and Safari in iOS.

**Comment by daxinhub** [comment]
Yes, I am the same

**Comment by ethanaobrien** [comment]
It was caused by this commit https://github.com/EmulatorJS/RetroArch/commit/c8bab6b3908d1106e73e64a442ff7ec39c833fae. 

It should be a simple fix
