### ISSUE TITLE
mame help needed

### ISSUE THREAD

**Issue by ethanaobrien** [emulatorjs/emulatorjs#88]
Does anyone here use mame? If so could you send me the title of the game that works with the emulator?

`core | stateSupported`

`005`: `4|0`
`1941`: `2|0`
`1942`: `2|0`
`1943`: `2|0`
`1944`: `2|0`
`mk`: `3|0`

**Comment by ethanaobrien** [comment]
TODO: implement `EJS_mameCore` which you set to the `4|0` or `3|0` string

**Comment by megamandev** [comment]
mame roms working

mk > mortal kombat
mk2 > mortal kombat 2
mk3 > mortal kombat 3
umk3 > mortal kombat 3 ultimate
batman > batman
cstlevna > vs castlevania
hcastle > haunted castle

mame roms not working

kinst > killer instinct
kinst2 > killer instinct 2
matrimnd > Power Instinct Matrimelee
tekken > tekken
tekken2 > tekken2
mk4 > mortal kombat 4

**Comment by imneckro** [comment]
> 

@ethanaobrien  is it possible to support chd along side arcade rom zips?

**Comment by ethanaobrien** [comment]
No it is not possible
