### ISSUE TITLE
Add cores of J2ME

### ISSUE THREAD

**Issue by duanyu5871** [emulatorjs/emulatorjs#889]
Hello, 
I have stumbled across a core named FreeJ2ME to emulator some java games in earlier phone, which can be found in libretro website (https://docs.libretro.com/guides/core-list/)
![image](https://github.com/user-attachments/assets/b4a01391-d796-44b0-95fe-389af15f5987)
The resource can be found in (https://github.com/hex007/freej2me).  It seems have to work with JavaSE. Im not sure is there any possible to load this core in emulatorjs project. Will you watch on it if possible?
Thank you

**Comment by ethanaobrien** [comment]
Sadly, this isn't possible, it appears to still rely on the java runtime which we do not have:

![image](https://github.com/user-attachments/assets/b805f109-94cd-43df-82dc-52681e078429)
