### ISSUE TITLE
Ds Slowdown

### ISSUE THREAD

**Issue by DarkShadow8700** [emulatorjs/emulatorjs#89]
I don't know if it's the rom I'm using but whenever I try to play a game on the DS emulator I experience slowdown could it be that the  DS might be too powerful to run  or something

**Comment by ethanaobrien** [comment]
@DarkShadow8700 
You're correct, It's because the ds is pretty powerful. Turn on frameskip (settings in bottom right corner). This helps it run a bit faster

**Comment by thisismyaltaccountt** [comment]
Sorry, I know that this is an old post, but is there frameskip in the newer versions of EmulatorJS?
