### ISSUE TITLE
Feature Request: MAME/Arcade Cheat codes support

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#892]
Hi,

I would appreciate if it would be possible to add support for loading up a Mame Cheat db file when loading a mame rom, So  Emulatorjs will know how to automatically route to the corresponding XML file of the game cheat data in orsder to display the cheat rrelevant cheat options.
.
I've tried to add some cheat hex codes manually from the information that appears on the cheat data file, but it didn't work
If adding support for the enite cheat db is a bit compilcated, I would appreciate it if you could at least consider supporting adding hex cheat codes manually.

Here where you can find all the cheats db files:
https://www.mamecheat.co.uk/mame_downloads.htm

Thank you

**Comment by michael-j-green** [comment]
If you need to provide files to MAME, then perhaps the EJS_externalFiles option will suit your needs?

See: https://emulatorjs.org/docs/options#ejs_externalfiles

**Comment by shaylevary** [comment]
First of all, thanks for the help.

I tried to load the file through the External Files option as you suggested.

The file was indeed loaded while loading the game, but I ran into two problems:
1. Although the file is only 3.8 megabytes in size, it contains alot of files, so the decompress process takes time.
2. To activate the cheats, I need to open Mame's options menu which is usually opened by pressing the TAB key. On EJS clicking on the TAB button does nothing. Is there a way to open Mame's options menu inside EJS?

In the other version of EJS, he embedded the cheat file inside the EJS internal cheat system, so when a Mame/Arcade ROM is loaded - it specifically loads its cheat data in XML and then displays it when clicking the Cheat button on the EJS menu.

For example, in the game GoldenAxe, it makes a request to an XML file using this routing which is the name of the game ROM.
https://www.emulatorjs.com/api/fba?name=goldnaxe.zip (click on this url will load the specific game cheat data)

Then, when i click the cheat button on the EJS menu, it will appear like this:
<img width="610" alt="Goldenaxe_cheat_menu" src="https://github.com/user-attachments/assets/4a484c1a-dc95-4af4-8e42-4a18d67a18f1">

It would be nice if a similar option could be implemented in this awesome version of the script as well.

Thank you.

**Comment by michael-j-green** [comment]
Ok, I think I understand now. https://emulatorjs.org/docs/options#ejs_cheats is what you want.

When you load a ROM, the page you've embedded EJS into can supply a JSON array of cheats to load into the native EJS cheats window using the above `EJS_cheats` option.

How you do this is up to you. EJS can't supply all the cheats for all possible ROMs.

**Comment by shaylevary** [comment]
I have no problem adding these codes manually, I did it on all my console games, such as SNES, GENSIS' PSX and more...

The problem is that the format of this Hex codes appears to be different from the codes that usually appear in the other console games.

For example, Here is the game-genie codes for the game Lion King for SNES:
["Infinite lives","CE6E-8464"],["Don't lose roar power when you get hit","C293-E703"],["Infinite Health","7E200404"],["Infinite Energy Bar","7E200210"]

And this is pro action codes for the game Tekken for PSX:
["Arcade ModeP1 Infinite Energy","300AAAB6 008C"],["Arcade ModeP2 Infinite Energy","300AC342 008C"]

However, when I try to enter these codes as they appear in the link that generates cheat codes for a specific MAME game, none of the cheat codes works.

Here is for example codes for Golden Axe as generated by the url:
["Infinite Lives PL1","0, 0xFFE018, 0x05"],["Infinite Energy PL1","0, 0xFFC070, 0x30"]

It is possible that this is a different format of codes that is not supported by your EJS script?

**Comment by ethanaobrien** [comment]
First, its likely you need to remove the commas

Second, 

>It is possible that this is a different format of codes that is not supported by your EJS script?

All the "ejs script" does is feed values into retroarch, just as if you were placing these in the retroarch gui. Test in RetroArch locally if needed, and then move them to EmulatorJS. Though there is no difference in the end.
