### ISSUE TITLE
Toggle On Screen Buttons

### ISSUE THREAD

**Issue by jakesk43** [emulatorjs/emulatorjs#894]
You need to add an option to toggle the on screen buttons on and off in each emulator. Thank you.

**Comment by ethanaobrien** [comment]
First, I don't "need" to do anything.

Please expand on what that feature request is

**Comment by michael-j-green** [comment]
@jakesk43; are you looking to turn the existing buttons on or off? If so; check the documentation: https://emulatorjs.org/docs/options#ejs_buttons

**Comment by jakesk43** [comment]
I don't mean hide or show the buttons, I mean toggle them like pressing them on and off. I don't see it in the code.

**Comment by michael-j-green** [comment]
What are you trying to accomplish? Pretty much all of the buttons in the toolbar don't work as toggles, but as single press.

For example; you can't turn "on" a save.

Toggle-able options are under the cog menu.

Perhaps if you explain in detail what you're trying to accomplish we can help?

**Comment by ethanaobrien** [comment]
Until the OP can get their point across, I'm going to be closing this issue.
