### ISSUE TITLE
Save State Function

### ISSUE THREAD

**Issue by thisismyaltaccountt** [emulatorjs/emulatorjs#898]
Hi! I'm trying to code a little something up, and I was wondering if there was a function or something for the save states. I'm just trying to make something to automatically save state. So if there is one, please let me know. Thanks!

**Comment by duanyu5871** [comment]
You can type `window.EJS_emulator` in console, and you will find some parameters you need, like `gameManager.getState()`, `gameManager.getState()`. You can call these functions to do anything as you like.

**Comment by thisismyaltaccountt** [comment]
Ok, thank you!

**Comment by thisismyaltaccountt** [comment]
This is odd. I am unable to get any of it to work. Any guesses?

![image](https://github.com/user-attachments/assets/df47b760-3fdd-47a4-8868-f25fd200a38e)

**Comment by ethanaobrien** [comment]
Since they are properties of the `window.EJS_emulator` object, you must reference the parent object.  `window.EJS_emulator.gameManager.getState()`

**Comment by thisismyaltaccountt** [comment]
I'm sorry if I'm making any silly mistakes. I'm new to programming.

Any idea why its not loading the state?

![image](https://github.com/user-attachments/assets/e182ef3b-af31-4cbb-83a1-33b748b5b6d2)

Thanks!

**Comment by duanyu5871** [comment]
Because it's a function, and it needs parameters.
It seems you not familiar with javascript, you would better to learn some knowledge about this before change your code.

**Comment by ethanaobrien** [comment]
>Because it's a function, and it needs parameters.

The `loadSaveFiles` function takes no parameters, its only purpose is to tell retroarch to reload the sav files on the disk

>Any idea why its not loading the state?

You are looking for the `loadState` function

**Comment by duanyu5871** [comment]
That's my fault, I means `getState()` and `loadState()`. Sorry, I mixed up the function names.

**Comment by thisismyaltaccountt** [comment]
OK. Thank you. I will look into it tomorrow.

**Comment by ethanaobrien** [comment]
Closing, since this is not an issue
