### ISSUE TITLE
enter fullscreen button doesnt show up

### ISSUE THREAD

**Issue by imneckro** [EmulatorJS/EmulatorJS#9]
![image](https://user-images.githubusercontent.com/42493772/130669753-1d5f0078-1896-4707-ab28-46cbef0c8fc8.png)

**Comment by Scoffins** [comment]
I notice this happens mostly on Mobile browsers, but from the screenshot it looks like you're on something larger. Are you using a tablet, by any chance?

**Comment by imneckro** [comment]
It is from desktop on chrome

**Comment by Scoffins** [comment]
Could you try on another browser? I'm no expert on this script, but after digging around emulator.js I noticed something which seems to check if your have webkit fullscreen enabled on your browser before displaying the icon. I can't think of any reason why or how this would be disabled, but if you can see the Full Screen icon in a different web browser, it might help to narrow down the possible problems to your specific Chrome installation.

**Comment by Scoffins** [comment]
I am running this emulator on one of my websites. You can check if you see the Full Screen icon here:
https://coldcast.org/games/1/Super-Mario-Bros

If you can, maybe it's a problem with the emulator script you're using. Just another way to help narrow down the possible problems.

If you give me a link I can see if I see the icon on your website and we will know if it's a script problem or browser problem.

**Comment by imneckro** [comment]
http://kolonis.ddns.net/test

**Comment by imneckro** [comment]
![image](https://user-images.githubusercontent.com/42493772/130813224-9a221f10-c8dc-4dd3-8e09-8837d8f1d5fb.png)
same browser(chrome) yours display correctly

**Comment by Scoffins** [comment]
I'm not sure why your script is behaving this way, I've tested a few things such as SSL and iframes, etc. Even tried using your files on my server, but mine still shows fine. I can get it to display the button using CSS, but it doesn't activate the fullscreen when it's clicked.
`<style>button[data-btn=fullscreen] {display:block !important;}</style>`

Strange. Maybe you could try redownloading the whole emulatorjs zip from github and starting afresh?

**Comment by imneckro** [comment]
Tried redownloading yesterday but no success. Still same behavior. It is really strange..

**Comment by imneckro** [comment]
I'll see in Apache side settings..

**Comment by Scoffins** [comment]
Okay. I'm sorry I couldn't be of more help. But if you do figure it out, post a comment with details because I'm curious :)

**Comment by imneckro** [comment]
The below header I have in Apache set was interfering 
Header always set Feature-Policy "fullscreen 'none'; microphone 'none'"

thanks a lot for your help!

**Comment by Scoffins** [comment]
Ah, glad you found it :) no problem!

**Comment by imneckro** [comment]
can i ask you what api you re using to get archive org rom urls in your website?

**Comment by ethanaobrien** [comment]
@Scoffins Yes please. I always run into cors problems

Also, would you mind if I included the website you mentioned (https://coldcast.org/games/1/Super-Mario-Bros) in the readme as an example?

**Comment by Scoffins** [comment]
@imneckro it's not an API, I curated the archive myself on their servers. As they have a DMCA exemption, it seems to be the only legit place to host ROM files.

@ethanaobrien Sure, no problem!

**Comment by ethanaobrien** [comment]
@imneckro 

https://ia801902.us.archive.org/cors_get.php?path=/some/path

There are other archive servers, this is one of them, allows cors

**Comment by imneckro** [comment]
got it :)

**Comment by ethanaobrien** [comment]
@imneckro Are you still having problems with this?
