### ISSUE TITLE
PWA on iOS

### ISSUE THREAD

**Issue by basvroegop** [emulatorjs/emulatorjs#90]
Hi,

Incredible to see all of this run! I was wondering if it's possible to turn the frontend into a Progressive Web App, so it's able to run full-screen and with sound on iOS. Right now the sound seems to be muted and the browser bar pops into screen.

**Comment by ethanaobrien** [comment]
>I was wondering if it's possible to turn the frontend into a Progressive Web App, so it's able to run full-screen and with sound on iOS.

You probably could. I did something similar so I have something to do at school ([here](https://github.com/ethanaobrien/emulator-button/)). Sorry I don't know much about progressive web apps or iOS web development do I probably cant help much

>Right now the sound seems to be muted

Is this only on iOS?

> and the browser bar pops into screen.

Which bar?

**Comment by raulbojalil** [comment]
@basvroegop you can try my frontend here: https://github.com/raulbojalil/flemu. It's made with Flutter Web so it's a PWA out of the box, just add it to your home screen from the settings. I also added a button to show it in fullscreen.

Note that you need Flutter to compile the application, I'll add release packages later.

**Comment by basvroegop** [comment]
> Which bar?

The url bar at the top! It just shows as a regular browser on iOS using Safari. It wasn't muted on my Mac using Chrome. 

And that looks great @raulbojalil! I've only been using emulatorjs through the linuxserver Docker so far, so not sure how easily I could swap to your frontend myself.

**Comment by ethanaobrien** [comment]
>The url bar at the top! It just shows as a regular browser on iOS using Safari. It wasn't muted on my Mac using Chrome.

So, just to clarify, sorry, this is not a website opened in safari or anything?

**Comment by basvroegop** [comment]
Bit confused at the question, haha. But I’m running the emulator in my safari web browser. I’ve attached some screenshots to clarify what it looks like on my phone. 
![8B0723BC-133F-47C3-A9D6-697050931B37](https://user-images.githubusercontent.com/7536487/149461800-8451b098-7959-4057-a9cc-394e7af66a67.png)
![6D0CD8FD-EE61-4B26-9A9C-6F10FC0E1682](https://user-images.githubusercontent.com/7536487/149461807-a7aee66f-a4f2-4450-839c-317d2f86521f.png)

**Comment by ethanaobrien** [comment]
Oh ok I see what you mean. Do you think the sound thing could be a bug?

**Comment by ethanaobrien** [comment]
Hey @basvroegop, could I go ahead and close this or is there anything else you need?

**Comment by ethanaobrien** [comment]
I am assuming issue is resolved due to inactivity
