### ISSUE TITLE
[Info] Picodrive core (Sega 32x) Still Black Screen?

### ISSUE THREAD

**Issue by pokemonsilvergoldred** [EmulatorJS/EmulatorJS#900]
Picodrive core (Sega 32x) Still Black Screen?
Any other core to play Sega 32x?
thanks!

**Comment by pokemonsilvergoldred** [comment]
other question
the game Bass Landing 2 for playstation psx
the game work but the usb controller not work in this game, all other games the usb controller work nice

**Comment by ethanaobrien** [comment]
#579 

> the game work but the usb controller not work in this game, all other games the usb controller work nice

Sounds like a browser issue. If it works with one game it will work with all
