### ISSUE TITLE
3 Problems / SNES / ARCADE / NINTENDO 64

### ISSUE THREAD

**Issue by megamandev** [emulatorjs/emulatorjs#91]
hi thank you so much for sharing.
i have 3 problems

1 > I tested more than 10 dragon ball z hyper dimension roms on SUPER NINTENDO and it doesn't work.

2 > I tried to run mortal kombat 1 rom in ARCADE and it doesn't work, you can add MAME to ARCADE Script to run Mortal Kombat 1 from Arcade.

3 > My PC i5 with old motherboard and OPENGL v1.0, does not work Nintendo 64, say message: NETWORK Error.
But the same emulatorjs with ADS this one works NINTENDO 64 on my old PC.

very thank you and cheers!

**Comment by ethanaobrien** [comment]
@megamandev 

Do items 1 and 2 work with the original emulatorjs? ( the one with ads?)

Would you mind sending me a screenshot for the third one? To screenshot
1. Right click (anywhere on the screen)
2. Click inspect element
3. At the top of this frame, click "network"
4. Reload the page
5. Press "play now"
6. once it says "network error" send me a screenshot of the "network" tab you have opened

**Comment by megamandev** [comment]
examples Mortal kombat 1 #ARCADE and NINTENDO 64 working with emulatorjs with ads in PC old and new

https://pastebin.com/5gSVS8Xk
password pastebin > cP7LBM6iH7

very thank you for help i go check beter with your instructions.

**Comment by megamandev** [comment]
Nintendo 64 #Networl error

print screen
https://ibb.co/wBjgVvQ

**Comment by ethanaobrien** [comment]
Solution to Second problem: 

Solution to Third problem: download [this](https://github.com/ethanaobrien/emulatorjs/blob/main/data/n64-legacy-asmjs.data) file into your `data/` directory (you might just want to update the entire `data/` directory, seems like you're a few versions behind)

**Comment by ethanaobrien** [comment]
First problem: strange, what error does it give you?

Solution to Second problem: name your file `mk.zip`

Solution to Third problem: download this file into your data/ directory (you might just want to update the entire data/ directory, seems like you're a few versions behind)

**Comment by megamandev** [comment]
i go try fix with your solutions.
first problem the game dragon ball z hyper dimension not work with this emulator
i play this game with other emulatorjs, in pastebin examples.

second problem the game mortal kombat 1 not have for FBA and not go work with this emu
mk.zip is only MAME.
but i play mortal kombat 1 with same emulatorjs with ads but is different script, not load arcade bios, load MAME api.
i play this game in pastebin examples

**Comment by megamandev** [comment]
@ethanaobrien

i fixed Nintendo 64 network error very thank you brother!

to many nintendo 64 games that don't work perfect, follow the list

used roms

jet-force-gemini-usa #image very buged
perfect-dark-usa #no work
007-the-world-is-not-enough-usa #image buged not appear weapon
indiana-jones-and-the-infernal-machine-usa #no work
pilotwings-64-usa # image buged
vigilante-8-usa #very buged clash emulator
vigilante-8-2nd-offense-usa #very buged clash emulator
kirby-64-the-crystal-shards-usa #buged
top-gear-rally-sua #image buged
top-gear-rally2-usa #image buged
top-gear-bike-usa # black screen when star game
cruisn-exotica-usa #no work
donald-duck-goin-usa #no work
south-park-rally-usa #no work
starcraft-64-usa #image buged
ogre-battle-64-person-of-lordly-caliber-usa #image buged
mario-golf-usa #image buged
mario-tennis-usa #image buged
in-fisherman-bass-hunter-64-usa #image buged
erofighter-assault-usa #buged image
bomberman-64-usa #buged black screen
excitebike-64-usa #no work
world-driver-championship-usa #no work
international-superstar-soccer-64-usa #character with big shadow
jikkyou-j.league-perfect-striker-japan  #character with big shadow
gauntlet-legends-usa #no work
tiggers-honey-hunt-usa #buged sound
yoshis-story-usa #buged screen black only appear characters

**Comment by ethanaobrien** [comment]
I cant really fix any of this, I mainly just maintain the frontend or the whole project. The wasm files is still being decoded. 

Can I close this?

**Comment by megamandev** [comment]
@ethanaobrien 

yes brother save in your notpad the list nintendo 64 games not work
in the future maybe fix it.
very thank you brother.

you have solution to run mortal kombat 1 ARCADE?

**Comment by ethanaobrien** [comment]
>yes brother save in your notpad the list nintendo 64 games not work
in the future maybe fix it.
very thank you brother.

I will, in time.

>you have solution to run mortal kombat 1 ARCADE?

Yes, name the file `mk.zip` and set system to `mame`

**Comment by megamandev** [comment]
@ethanaobrien 

the system he means is the Core?

JS_Core?

**Comment by ethanaobrien** [comment]
>the system he means is the Core?

Correct, set `EJS_core = 'mame'`

**Comment by megamandev** [comment]
@ethanaobrien 

hi brother

i set the system to 'mame' and not work
you can make tutorial with details.
nice day.

**Comment by ethanaobrien** [comment]
@megamandev Did you also name the file `mk.zip` this is also required

**Comment by megamandev** [comment]
@ethanaobrien 

i forget, now work very very thank you and good night brother

**Comment by ethanaobrien** [comment]
Thank you too. Once we get the core files decompiled, we will use this as a source of things to fix. Thank you.
