### ISSUE TITLE
Latest cores update

### ISSUE THREAD

**Issue by mikhailv** [emulatorjs/emulatorjs#916]
Hi, first of all, thank you for this project, it is really impressive.

I faced with the same issue as [this one](https://github.com/EmulatorJS/EmulatorJS/issues/879) not working volume slider, I even prepared some monkey patch to make it work. But later I noticed this closed issue and [fix](https://github.com/EmulatorJS/RetroArch/pull/23) in RetroArch component. So to make this fix work I need updated cores, but latest cores do not include this fix from RetroArch.

I'm confused with versioning and core collection updates. In [versioning](https://github.com/EmulatorJS/EmulatorJS?tab=readme-ov-file#versioning) there is such description for **latest**  version:
> latest - This will contain the latest code but use the stable cores. This will be updated every time the main branch is updated.
But looks like **latest** related to last release same as **stable**, and do not contain latest code as stated.

I found this directory https://cdn.emulatorjs.org/nightly/data/cores/ with **nightly** versions of cores and probably it will work in my case, but not sure why it is really slow for me. The stable directory https://cdn.emulatorjs.org/stable/data/cores/ works much faster.

So my question is, should I download https://cdn.emulatorjs.org/nightly/data/cores/cores.zip for latest RetroArch code and stable cores (probably not because this is alpha), or there is some mistake and such cores should be in **latest** ?

**Comment by mikhailv** [comment]
btw, this is my "monkey patch" workaround to fix volume slider:
```js
(function() {
  let initialized = false;
  const origCreateGain = AudioContext.prototype.createGain;
  AudioContext.prototype.createGain = function() {
    const gain = origCreateGain.apply(this, arguments);
    try {
      const Module = window.EJS_emulator.Module;
      if (!initialized) {
        if (window.AL || Module.AL) { // AL system present, no need to spoof
          AudioContext.prototype.createGain = origCreateGain;
          return gain;
        }
        window.AL = Module.AL = { currentCtx: { sources: [] } };
        initialized = true;
      }
      Module.AL.currentCtx.sources.push({ gain });
    } catch (e) {
      console.error('Failed to spoof AL system', e);
    }
    return gain;
  };
})();
```
Should be executed before loader.

**Comment by ethanaobrien** [comment]
You should use the nightly cores. Latest only updates the code and is most likely the one that will break. Nightly updates the code and cores

>probably not because this is alpha

As long as the code compiles, nightly will very unlikely be broken, but it is still possible

**Comment by mikhailv** [comment]
@ethanaobrien what about latest version description, this is not correct then:
> latest - This will contain the latest code but use the stable cores. This will be updated every time the main branch is updated.
But looks like latest related to last release same as stable, and do not contain latest code as stated.

The `main` branch is updated in both repos (`EmulatorJS/EmulatorJS/main` and `EmulatorJS/RetroArch/master`) but latest cores build since August release.

**Comment by ethanaobrien** [comment]
No @mikhailv,

Cores = RetroArch wasm blobs
Code = EmulatorJS frontend code

stable = cores + code from latest release
latest = cores from the latest release + code from this repository (update as pushed)
nightly = cores built nightly + code from this repository
