### ISSUE TITLE
mupen64plus_next core defaults to WebGL1 when it is set to WebGL2 in cores.json

### ISSUE THREAD

**Issue by flyingtruce** [emulatorjs/emulatorjs#920]
![image](https://github.com/user-attachments/assets/05e43b75-36db-4e73-87a5-2db8b32427ab)

Despite the fact that "defaultWebGL2": true, the default setting for n64 games using this core is as below, which causes visual glitches in mk64, this is fixed when I use WebGL2 so I know that this definitely isn't using that.

![image](https://github.com/user-attachments/assets/64591395-77b1-4cf1-9737-defe155a5292)

**Comment by ethanaobrien** [comment]
This was fixed in https://github.com/EmulatorJS/EmulatorJS/commit/c0ae2e2cafefac53b10a0898a6f021479c77b536. Are you using nightly?

**Comment by flyingtruce** [comment]
I was, however I can't be bothered to update, so I came up with a quick fix if anyone wants it

change the lines:
`(this.supportsWebgl2 = !!document.createElement("canvas").getContext("webgl2") && !0 !== this.config.forceLegacyCores),
(this.webgl2Enabled = !("disabled" === (t = this.preGetSetting("webgl2Enabled")) || !this.supportsWebgl2) && ("enabled" === t || null)),`

to:
`(this.supportsWebgl2 = true),
(this.webgl2Enabled = true),`

and then hide the menu option for it

Thanks for the help!

**Comment by ethanaobrien** [comment]
Fixed in latest release
