### ISSUE TITLE
[Info] emulatorjs

### ISSUE THREAD

**Issue by misoguchiwin** [EmulatorJS/EmulatorJS#925]
support dreamcast and neogeo cd ?
sega 32x not working ?
netplay ?
many thanks all

**Comment by michael-j-green** [comment]
See https://emulatorjs.org/docs/systems for a list of supported systems.

sega32x has a known issue with it's emulation core which results in a black screen. Netplay is not available due to how the emulator works in the browser.

**Comment by misoguchiwin** [comment]
thanks all again
cheers
