### ISSUE TITLE
UI for mobile

### ISSUE THREAD

**Issue by n00b12345** [emulatorjs/emulatorjs#926]
Would it be possible to shift the Select, Start, Fast, Rewind and Slow menus so that it's not hindering the playing area in mobile UI? Maybe by moving it to the right or the left?

It's not a problem in portrait mode, but only in landscape. Please see the screenshot.

(Thank you for everything that this project does 🙏)

![Screenshot_20241223_150800_Firefox.jpg](https://github.com/user-attachments/assets/dff3a028-8b2e-4a74-af10-078dfeeeab9c)

**Comment by ethanaobrien** [comment]
This can be changed by manually defining the virtual gamepad settings for your website:

https://emulatorjs.org/docs4devs/virtual-gamepad-settings

A PR is always welcome to improve the current virtual gamepad settings!
