### ISSUE TITLE
Controller does not recognize all buttons

### ISSUE THREAD

**Issue by ethanaobrien** [emulatorjs/emulatorjs#93]
For example, nintendo switch pro controller, not all buttons work because it goes over the limit.

Todo: fix

**Comment by megamandev** [comment]
@ethanaobrien

the controller nintendo 64, the analog stick and C Buttons work only with keyboard buttons?
i have one simple usb controller without analog, and i try set new config for me use my simple controller but the analog stick nintendo 64 not work, with keyboard work!
analog stick nintendo 64 work only with keyboard not with controller usb?

very ty sorry bad usa.

**Comment by megamandev** [comment]
@ethanaobrien

the controller settings of 'mame' is nintendo 64 controller.
how i can change for controller arcade settings?

**Comment by ethanaobrien** [comment]
This can possibly be fixed with #223

**Comment by ethanaobrien** [comment]
This cannot be fixed as far as I can tell
