### ISSUE TITLE
Player Broken on live website with the new release? 

### ISSUE THREAD

**Issue by muditjuneja** [emulatorjs/emulatorjs#930]
I am on v4.1.1
Game is being downloaded but I get the below error and it happened automatically on my live website. I am updating the version but what went wrong here that it broke the existing build?

![Screenshot 2024-12-25 041914](https://github.com/user-attachments/assets/30b27e2a-08f4-4315-88e7-f03467487272)
![Screenshot 2024-12-25 042048](https://github.com/user-attachments/assets/cafff89f-8195-4233-aed6-a417cf9fdb2d)

**Comment by ethanaobrien** [comment]
It sounds like you do not have the cores downloaded in your data/cores folder. If you don't have the cores and only clone this repo you depend on a failsafe I have in place (that's logged in the console every time you start a game...). If you want to use 4.1.1, you should download and deploy the release on your website: https://github.com/EmulatorJS/EmulatorJS/releases/download/v4.1.1/4.1.1.7z
