### ISSUE TITLE
Update to retroarch cores

### ISSUE THREAD

**Issue by ethanaobrien** [emulatorjs/emulatorjs#94]
Upgrade to retroarch cores.

- [ ] input keymap
- [ ] pause/play - possible cmd solution, `CMD_EVENT_PAUSE_TOGGLE`
- [ ] no UI messages
- [ ] shaders - possible cmd solution, `RA_OPT_SET_SHADER` (possible later implementation)
- [ ] netplay (possible later implementation)
- [ ] cheats (possible later implementation)
- [x] Get it to (somewhat) load
- [x] Cleanup loading
- [x] reset button
- [x] save/load state
- [x] quick save/load state
- [x] screenshot
- [x] on load, `printf` to cite source and to state official version.

Important: this update will change the save/load state method. old saves will not work!
Save state file is also much smaller

I will officially release the next version once all of these features are implemented

I am not currently planning to make the retroarch frontend open source because of what annoying people tend to do.

**Comment by megamandev** [comment]
congratulations brother!

**Comment by nenge123** [comment]
you can edit the "retroarch cores wasm-data"?

**Comment by ethanaobrien** [comment]
yes

**Comment by nenge123** [comment]
> yes

about the "key bursts"
only "ps n64" can use
can you  make the "arcade nes mame" support ?

**Comment by ethanaobrien** [comment]
What does that even mean

**Comment by nenge123** [comment]
> What does that even mean

https://twitter.com/nenge123/status/1492147335568117765?s=21

**Comment by ethanaobrien** [comment]
I'll look into it. Just wondering, are you using the beta code from #109? if so could you share your localization file to make this project more available

**Comment by nenge123** [comment]
It's different. How to refer to it? You need to replace a specific name, because I have replaced a lot. In order to look good.

git /nenge123/emulatorjs

http://emulatorjs.nenge.net

or

if you download test open

localhost/test.html

first link will save js cache
