### ISSUE TITLE
decrypt emulator.js file tool can you decrypt suppor  ？

### ISSUE THREAD

**Issue by wye-sir** [emulatorjs/emulatorjs#96]
I see your emulator.js  file is encrypted ,whether can suppor decrypt tool?

**Comment by ethanaobrien** [comment]
The emulator.js file is decrypted as much as the tool supports.

It isnt encrypted, the variables just arent relevant to what they do

This is it encrypted: https://github.com/ethanaobrien/emulatorjs/blob/9f4d291e2d8fc8e821442692679a91c640c55f02/data/emulator.js
