### ISSUE TITLE
what hardware and software requirements to run with the perfect sound, n64 and ps1

### ISSUE THREAD

**Issue by megamandev** [emulatorjs/emulatorjs#97]
what hardware and software requirements to run with the perfect sound, n64 and ps1

my computer has 8 gigs of ram memory and amd dual core processor. n64 and ps1 works with lag in the game and mostly in sound.
my os is windows 10.

**Comment by ethanaobrien** [comment]
I don't think the emulator has the capability to run with perfect sound on those two systems at the moment. They are extremely beta (not technically supported).

Sorry, I cant do anything about this.
